### ISSUE TITLE
-latomic not present on x86 platforms

### ISSUE THREAD

**Issue by Plantain** [google/highway#1003]
Since #889, the build seems to no longer work on x86 GCC10, where it previously did build just fine.

/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: cannot find -latomic

**Comment by jan-wassenberg** [comment]
For background, please see https://github.com/google/highway/issues/887.
Is it possible you do not have the libatomic package installed? It might be called devtoolset-10-libatomic-devel in your environment. I believe that would solve this.

**Comment by malaterre** [comment]
If this issue keeps on coming, I can provide a proper fix to only include latomic when needed. @jan-wassenberg ?

**Comment by jan-wassenberg** [comment]
@malaterre thanks, sounds potentially useful to only pull in libatomic where required. What would you propose?

**Comment by jan-wassenberg** [comment]
Congrats and thank you for your patience in making this work despite all the CMake and Github Actions roadblocks :)
