### ISSUE TITLE
fatal error: riscv_vector.h: No such file or directory

### ISSUE THREAD

**Issue by davidlt** [google/highway#1017]
I have noticed that 1.0.1 version does not compile on riscv64 using the latest stable GCC and binutils. 

```
In file included from /builddir/build/BUILD/highway-1.0.1/hwy/highway.h:367,
                 from /builddir/build/BUILD/highway-1.0.1/hwy/per_target.cc:21:
/builddir/build/BUILD/highway-1.0.1/hwy/ops/rvv-inl.h:19:10: fatal error: riscv_vector.h: No such file or directory
   19 | #include <riscv_vector.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/hwy.dir/build.make:107: CMakeFiles/hwy.dir/hwy/per_target.cc.o] Error 1
```
`riscv_vector.h` will be available in GCC 13 (2023 April-May time frame). It will take even more time for it to land in Linux distributions.

**Comment by davidlt** [comment]
I did pull in `96d1d5f788703eb3dd3a0f62d36a410f92d22666` to fix `-march` value for GCC builds. I also passed `-DHWY_COMPILE_ONLY_EMU128 -DHWY_DISABLED_TARGETS=HWY_RVV` to `CFLAGS` and `CXXFLAGS`, but now I am getting illegal instructions in tests:
```
  Error running test executable.
    Path: '/builddir/build/BUILD/highway-1.0.1/redhat-linux-build/tests/aligned_allocator_test'
    Result: Illegal instruction
    Output:
  Error running test executable.
    Path: '/builddir/build/BUILD/highway-1.0.1/redhat-linux-build/tests/transform_test'
    Result: Illegal instruction
    Output:
  Error running test executable.
    Path: '/builddir/build/BUILD/highway-1.0.1/redhat-linux-build/tests/copy_test'
    Result: Illegal instruction
    Output:
  Error running test executable.
    Path: '/builddir/build/BUILD/highway-1.0.1/redhat-linux-build/tests/find_test'
    Result: Illegal instruction
    Output:
```
I am probably missing something simple, just aren't seeing it yet.

**Comment by jan-wassenberg** [comment]
Hi @davidlt , I'm curious about the riscv64 use case, does it make sense to compile Highway when V extension is not supported? Your workaround looks good.

Can you help diagnose which instruction is illegal by running one of those tests in gdb and disassembling at the failing address?

**Comment by davidlt** [comment]
I building Fedora/RISCV distribution. Highway is used by jpegxl package, which is used by another 7 packages. That dependency chain continues to increase the number of packages. All of that is blocked by highway.

Speed is not important. Vector are far away from general availability. All new SoCs that are yet to be released in the products that developers will acquire do not contain it. Slow is fine, because we are slow in general. Today having a package build and run (correctly) is the important thing. The performance comes later with newer standards, new SoCs, new development boards, and software improvements.

I pulled in Debian patch: https://salsa.debian.org/debian-phototools-team/highway/-/blob/debian/experimental/debian/patches/riscv.patch

Now I have:
```
99% tests passed, 2 tests failed out of 179
Total Test time (real) =   3.44 sec
The following tests FAILED:
	144 - HwyMulTestGroup/HwyMulTest.TestAllMulHigh/EMU128  # GetParam() = 2305843009213693952 (Failed)
	145 - HwyMulTestGroup/HwyMulTest.TestAllMulFixedPoint15/EMU128  # GetParam() = 2305843009213693952 (Failed)
```

Which is significant improvement.

```
144/179 Test #144: HwyMulTestGroup/HwyMulTest.TestAllMulHigh/EMU128  # GetParam() = 2305843009213693952 ...................................***Failed    0.06 sec
Running main() from /builddir/build/BUILD/googletest-release-1.12.1/googletest/src/gtest_main.cc
Note: Google Test filter = HwyMulTestGroup/HwyMulTest.TestAllMulHigh/EMU128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyMulTestGroup/HwyMulTest
[ RUN      ] HwyMulTestGroup/HwyMulTest.TestAllMulHigh/EMU128
i16x8 expect [0+ ->]:
  0x3FFF,0x0FFF,0x03FF,0x00FF,0x003F,0x000F,0x0003,
i16x8 actual [0+ ->]:
  0x4001,0xAC01,0xE400,0x00FF,0xF222,0xFA0D,0xFE04,
Abort at /builddir/build/BUILD/highway-1.0.1/hwy/tests/mul_test.cc:131: EMU128, i16x8 lane 0 mismatch: expected '0x3FFF', got '0x4001'.
        Start 148: HwyMulTestGroup/HwyMulTest.TestAllReorderWidenMulAccumulate/EMU128  # GetParam() = 2305843009213693952
145/179 Test #145: HwyMulTestGroup/HwyMulTest.TestAllMulFixedPoint15/EMU128  # GetParam() = 2305843009213693952 ...........................***Failed    0.06 sec
Running main() from /builddir/build/BUILD/googletest-release-1.12.1/googletest/src/gtest_main.cc
Note: Google Test filter = HwyMulTestGroup/HwyMulTest.TestAllMulFixedPoint15/EMU128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyMulTestGroup/HwyMulTest
[ RUN      ] HwyMulTestGroup/HwyMulTest.TestAllMulFixedPoint15/EMU128
Abort at /builddir/build/BUILD/highway-1.0.1/hwy/tests/mul_test.cc:189: EMU128, i32x1 lane 0 mismatch: expected '19043', got '35453'.
```

**Comment by jan-wassenberg** [comment]
Thanks for the context, got it.

> Simply do not build highway with RVV.

I think they are successfully disabling V, but it seems they are running into the GCC compiler bug that we fixed in https://github.com/google/highway/commit/d9927b7cdb9de871fda9eb44ce653e20cddb39dd.

@davidlt , is the "latest stable GCC" older than 12.3? If so, it is indeed affected by this bug, which can be worked around using the above patch, or `-DHWY_BROKEN_EMU128=1`.

**Comment by malaterre** [comment]
> I think they are successfully disabling V,

I do not see a complete log, but starring at the two failing tests reported above, this is 100% identical to Debian/experimental package where I use clang to build highway. Pay attention that OP also imported my riscv.patch (geared toward runtime dispatch on riscv64), so I suspect you are not seeing the correct error message.

**Comment by jan-wassenberg** [comment]
@davidlt any further work required here?

**Comment by davidlt** [comment]
No.

I would suggest to disable RVV implementation for now. To my knowledge there is no "RISC-V V C Intrinsic API v1.0" yet (but probably sooner than later). I am not sure it will compile with any toolchain soon. See LLVM 16: https://github.com/llvm/llvm-project/blob/release/16.x/clang/docs/ReleaseNotes.rst#risc-v-support

I am not sure if GCC or/and LLVM latest version will manage to ship with final ratified version of RISC-V V intrinsics. 

I know that OpenCV was also notified about the change sin V instrinsics: https://github.com/opencv/opencv/issues/22608

**Comment by jan-wassenberg** [comment]
RVV is indeed at a draft stage of 1.0. We are successfully compiling V with current clang and would like to keep that enabled.

There is currently already an opt-out (`#define HWY_BROKEN_TARGETS HWY_RVV`) but I understand that's not always convenient. As a compromise, how about we disable HWY_RVV for GCC until we know what version of GCC supports V, then only disable for older ones?

**Comment by davidlt** [comment]
GCC 13 includes vector intrinsics, but not sure what version will it be. Ju-Zhe Zhong (juzhe.zhong@rivai.ai) is constantly sending the patches.  Until v1.0 is ratified and toolchains are aligned to it it's probably gonna be messy.

IIUC the non-ratified vector intrinsics code will not compile with LLVM/Clang 16, which now incl. a newer version (but still a draft).

**Comment by jan-wassenberg** [comment]
> GCC 13 includes vector intrinsics, but not sure what version will it be.

Last I checked, it wasn't yet the current 1.0-draft. Both GCC and older clang are lacking the __riscv prefix for intrinsics (that's #1156).

> IIUC the non-ratified vector intrinsics code will not compile with LLVM/Clang 16, which now incl. a newer version (but still a draft).

I'm not sure I understand correctly what you mean, here's a description of the current state:
- clang trunk currently compiles Highway's RVV, and includes both the tail policy change and the new __riscv prefix.
- Highway will be updated soon after breaking changes to clang trunk go into our LLVM.
- I believe the intention is to get the 1.0 intrinsics into clang 16.

With that, I think we're done for this issue: RVV is disabled for GCC (with a TODO to re-enable after a GCC release with V), and we can discuss what to do about earlier Clang in #1156.
But if there's anything else you feel we should do here, please re-open this one.
