### ISSUE TITLE
How to deduce the value type and size of hn::Vec<hn::FixedTag<Tp, N>> object?

### ISSUE THREAD

**Issue by Panhaolin2001** [google/highway#1038]
Hi~
    I want to compute the size of hn::Vec<hn::FixedTag<Tp, N>> object in compile-time without passing template parameters to the follow function. However.....
```
template<typename Tp, std::size_t N> 
constexpr auto highway_Size(const hn::Vec<hn::FixedTag<Tp, N>> &) noexcept
{
    return N;
}

int main(){
    highway_Size(hn::Vec<hn::FixedTag<int, 4>>{});
}

```
An error is occured....
```
test.cpp: In function ‘int main()’:
test.cpp:11:17: error: no matching function for call to ‘highway_Size(hwy::N_SSSE3::Vec<hwy::N_SSSE3::Simd<int, 4, 0> >)’
   11 |     highway_Size(hn::Vec<hn::FixedTag<int, 4>>{});
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.cpp:5:16: note: candidate: ‘template<class Tp, long unsigned int N> constexpr auto highway_Size(hwy::N_SSSE3::Vec<typename hwy::N_SSSE3::detail::FixedTagChecker<T, kNumLanes>::type>&)’
    5 | constexpr auto highway_Size(const hn::Vec<hn::FixedTag<Tp, N>> &) noexcept
      |                ^~~~~~~~~~~~
test.cpp:5:16: note:   template argument deduction/substitution failed:
test.cpp:11:17: note:   couldn’t deduce template parameter ‘Tp’
   11 |     highway_Size(hn::Vec<hn::FixedTag<int, 4>>{});
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
So, how can i deduce template parameter ‘Tp’?  thx!

**Comment by jan-wassenberg** [comment]
Hi @Panhaolin2001 , I think this is a C++ language limitation, type deduction does not work for what is already a template argument of an alias.

It seems like you are trying to implement what the `MaxLanes` function does. Maybe this is what you're looking for?
https://gcc.godbolt.org/z/MKPa9W5br

**Comment by Panhaolin2001** [comment]
Thx！ But if i want to get the size by passing **a Vec not a Simd tag object** to the function. Like this :
```
template<typename Vec> 
constexpr size_t highway_Size(const Vec &) noexcept
{
    /* */
}

int main(){
    auto size = highway_Size(hn::Vec<hn::FixedTag<int, 4>>{});
}
```
If there is a solution to complete this function?

**Comment by jan-wassenberg** [comment]
I see. Yes, we have a `DFromV` alias that returns the Simd type matching the V template argument.
Here's the updated code: https://gcc.godbolt.org/z/3bqMPfzx3

**Comment by Panhaolin2001** [comment]
wow!  thx!!  I got it!

**Comment by jan-wassenberg** [comment]
You're welcome :) Closing, feel free to reopen if you have other questions.
