### ISSUE TITLE
when i test 'hn::IfThenElse' api, something wrong happened

### ISSUE THREAD

**Issue by Panhaolin2001** [google/highway#1050]
Hi~ 
Sorry to bother you. I have a question. 
Why the 'tmp'  equals to 'tmp2' in the follow program? I think i should equal to 'tmp1'.
Maybe the decleration  of 'm0'  is wrong? Please help me,thx!!

The arch is x86, and the command is `g++ -std=c++2a -O2 -msse4.2  XXX`

```
int main()
{
    hn::ScalableTag<float> d;
    auto len = hn::Lanes(d);

//////////// Initialization
    float arr[len]{};
    float arr1[len]{};
    float arr2[len]{};
    decltype(hn::Zero(d)) tmp;
    decltype(hn::Zero(d)) tmp1;
    decltype(hn::Zero(d)) tmp2;
    hn::Mask<hn::ScalableTag<float>> m0{1};

    for(std::size_t i = 0; i < len; ++i){
        arr1[i] = i * i;
    }
    for(std::size_t i = 0; i < len; ++i){
        arr2[i] = 2 * i;
    }

//////////// Load arr1 and arr2 to tmp1 and tmp2
    tmp1 = hn::LoadU(d, arr1);
    std::cout<< "tmp1: " << std::endl;
    for(std::size_t i = 0; i < len; ++i){
        std::cout<< hn::ExtractLane(tmp1, i) << ' ';
    }
    std::cout <<  std::endl;

    tmp2 = hn::LoadU(d, arr2);
    std::cout<< "tmp2: " << std::endl;
    for(std::size_t i = 0; i < len; ++i){
        std::cout<< hn::ExtractLane(tmp2, i) << ' ';
    }
    std::cout <<  std::endl;


//////////// Select operation
    tmp = hn::IfThenElse(m0, tmp1, tmp2);
    
    std::cout<< "tmp: " << std::endl;
    for(std::size_t i = 0; i < len; ++i){
        std::cout<< hn::ExtractLane(tmp, i) << ' ';
    }
    std::cout <<  std::endl;
  
  return 0;
}
```

**Comment by jan-wassenberg** [comment]
Hi, the definition of m0 is indeed invalid. The most common way to initialize is to set the mask using `Eq(v,v)` for all-true and `Ne(v,v)` for all-false. There are also a few other functions: https://g3doc.corp.google.com/third_party/highway/g3doc/quick_reference.md#creation

Note that compiling your code for other platforms can help detect such errors. For example, if building for SVE or RISC-V, I believe the compiler will raise an error.

Hope this helps, feel free to reopen if you have any other issues :)
