### ISSUE TITLE
AVX target support?

### ISSUE THREAD

**Issue by antermin** [google/highway#1059]
Some CPUs support AVX but not AVX2, e.g.
* Intel
  * Sandy Bridge
  * Ivy Bridge
* AMD
  * Jaguar-based
  * Puma-based
  * Bulldozer-based
  * Piledriver-based
  * Steamroller-based
 
Will there be support for AVX target to bring speedups to these CPUs (so that libjxl can encode / decode images faster)?

**Comment by jan-wassenberg** [comment]
The [Steam hardware survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) can be useful for such things.
Looks like there's about a 5% increase for AVX vs AVX2 (Haswell). I'm not wildly enthusiastic about that, but if someone else is willing to look into the required changes, I'd be happy to advise and help.

**Comment by jan-wassenberg** [comment]
Closing, feel free to reopen if you'd like to continue the discussion.
