### ISSUE TITLE
Can I convert 8bit unsigned char vector to 32bit float vector?

### ISSUE THREAD

**Issue by HyundongHwang** [google/highway#1090]
Can I convert 8bit unsigned char vector to 32bit float vector?

There doesn't seem to be an API that's perfect for this conversion on highway.
So I would like to implement this by referring to the internal implementations of Bitcast, Promote, etc.
How can I do that easily?

Here's the code I've written so far:
Of course, it seems to be several steps more complicated than BitCast.

```
#include "hwy/highway.h"

HWY_BEFORE_NAMESPACE();
namespace hwy {
namespace HWY_NAMESPACE {

TEST(MY_TEST_SUITE, UCHAR8_TO_FLOAT32) {
  HWY_FULL(unsigned char) uchar8Type;
  auto uchar8Vector = Set(uchar8Type, 123);
  HWY_FULL(float) float32Type;
  auto res = BitCast(float32Type, uchar8Vector);
}
```

```
res : {raw=0x00fff71c {1.30577099E+36, 1.30577099E+36, 1.30577099E+36, 1.30577099E+36}}
```

**Comment by jan-wassenberg** [comment]
Hi @HyundongHwang, yes, this is indeed possible; examples/skeleton.cc has some code showing how.
The idea is to load a quarter-vector of u8, PromoteTo int32, then ConvertTo float. 
Hope this helps?

**Comment by WilliamHwangKakaoBrain** [comment]
Thank you.
@jan-wassenberg 
you saved my day
I modified my code as per the answer.

```
TEST(MY_TEST_SUITE, UCHAR8_TO_FLOAT322) {
  hn::ScalableTag<unsigned char> d_uchar;
  hn::ScalableTag<unsigned int> d_uint;
  hn::ScalableTag<float> d_float;
  auto lanes_float = hn::Lanes(d_float);
  hn::Rebind<unsigned char, decltype(d_uint)> rebind_uchar_uint;
  std::vector<uint8_t> v_uchar = {12, 34, 45, 56};
  auto v_hwy_uchar = hn::Load(rebind_uchar_uint, v_uchar.data());
  auto v_hwy_uint = hn::PromoteTo(d_uint, v_hwy_uchar);
  auto v_hwy_float = hn::ConvertTo(d_float, v_hwy_uint);
  std::vector<float> v_float;
  v_float.resize(lanes_float);
  hn::Store(v_hwy_float, d_float, v_float.data());
  std::stringstream log;
  log << "v_float:[";

  for (auto& f : v_float) {
    log << f << ",";
  }

  log << "]";
  spdlog::info(log.str());
}
```

```
[2022-12-21 19:38:43.570] [info] v_float:[12,34,45,56,]
```

In my opinion, there doesn't seem to be much of a problem.
However, from the original author's point of view, if there is a risky or inefficient implementation, I would appreciate it again if you could comment.

**Comment by HyundongHwang** [comment]
Thank you.
@jan-wassenberg
you saved my day
I modified my code as per the answer.

```
TEST(MY_TEST_SUITE, UCHAR8_TO_FLOAT322) {
  hn::ScalableTag<unsigned char> d_uchar;
  hn::ScalableTag<unsigned int> d_uint;
  hn::ScalableTag<float> d_float;
  auto lanes_float = hn::Lanes(d_float);
  hn::Rebind<unsigned char, decltype(d_uint)> rebind_uchar_uint;
  std::vector<uint8_t> v_uchar = {12, 34, 45, 56};
  auto v_hwy_uchar = hn::Load(rebind_uchar_uint, v_uchar.data());
  auto v_hwy_uint = hn::PromoteTo(d_uint, v_hwy_uchar);
  auto v_hwy_float = hn::ConvertTo(d_float, v_hwy_uint);
  std::vector<float> v_float;
  v_float.resize(lanes_float);
  hn::Store(v_hwy_float, d_float, v_float.data());
  std::stringstream log;
  log << "v_float:[";

  for (auto& f : v_float) {
    log << f << ",";
  }

  log << "]";
  spdlog::info(log.str());
}
```
```
[2022-12-21 19:38:43.570] [info] v_float:[12,34,45,56,]
```
In my opinion, there doesn't seem to be much of a problem.
However, from the original author's point of view, if there is a risky or inefficient implementation, I would appreciate it again if you could comment.

**Comment by jan-wassenberg** [comment]
Sure, happy to have a look.

There is one issue that might crash your code: std::vector's memory is not guaranteed to be vector-aligned, so we should use hn::LoadU instead of hn::Load. Also, the code as written assumes vectors are only 128-bit. If we're running on AVX2, then a quarter vector will be 8 bytes, but v_uchar is only initializing 4 bytes.
One way to solve both issues would be to use hwy::AllocateAligned<uint8_t>(lanes_float), that returns an aligned smart pointer. You can set the first four to your test values, then the remaining lanes_float-4 to zero. This will work for all vector lengths, and also allow you to use hn::Load still.
Similarly, the memory where we Store should also be aligned, or we should use StoreU.

Maybe it is a tiny bit safer to use uint32_t instead of unsigned int, those could possibly be different on some platforms.
The type of lanes_float can be size_t, maybe that is more readable/clear.

Hope this helps :)

**Comment by HyundongHwang** [comment]
@jan-wassenberg 
Perhaps I did something wrong.
I wrote an example that converts a 1280*720 size image from RGBA(uchar) to RGBA(float) by applying a little more.
This is what I was originally trying to do.
For comparison, I made a highway version and a sisd version (= non-highway).
In conclusion, the highway version is much slower.

```
COMPILE_TIME_HWY_NAMESPACE:N_SSSE3
COMPILE_TIME_HWY_NAMESPACE:N_SSE4
COMPILE_TIME_HWY_NAMESPACE:N_EMU128
RUN_TIME_HWY_NAMESPACE == N_SSE4
SIMD_DURATION:149.95ms
```

```
SISD_DURATION:15.38ms
```

I would appreciate it if you could give me another insight.

highway version:
```
#undef HWY_TARGET_INCLUDE
#define HWY_TARGET_INCLUDE "highway_test.cpp"  //NOLINT
#include <hwy/foreach_target.h>  // IWYU pragma: keep
#include <hwy/highway.h>

HWY_BEFORE_NAMESPACE();
namespace hwy {
namespace HWY_NAMESPACE {
namespace hn = hwy::HWY_NAMESPACE;

#define DISPLAY_VALUE2(x) #x
#define DISPLAY_VALUE(x) DISPLAY_VALUE2(x)
#pragma message("COMPILE_TIME_HWY_NAMESPACE:" DISPLAY_VALUE(HWY_NAMESPACE))

HWY_DLLEXPORT void _RGBA_UCHAR_TO_RGBA_FLOAT() {
  spdlog::info("RUN_TIME_HWY_NAMESPACE == {}", DISPLAY_VALUE(HWY_NAMESPACE));
  auto w = 1280;
  auto h = 720;
  std::vector<unsigned char> inImg;
  inImg.resize(w * h * 3);
  std::random_device seed;
  std::mt19937 gen(seed());
  std::uniform_int_distribution<> uniformDist(0, 256);

  for (int i = 0; i < inImg.size(); ++i) {
    inImg[i] = uniformDist(gen);
  }

  std::vector<float> outImg;
  outImg.resize(w * h * 3);

  hn::ScalableTag<unsigned char> d_uchar;
  hn::ScalableTag<unsigned int> d_uint;
  hn::ScalableTag<float> d_float;
  auto lanes_float = hn::Lanes(d_float);
  hn::Rebind<unsigned char, decltype(d_uint)> rebind_uchar_uint;
  auto stepSize = lanes_float * sizeof(unsigned char);

  auto tStart = std::chrono::high_resolution_clock::now();

  for (int i = 0; i < inImg.size(); i += stepSize) {
    auto v_hwy_uchar = hn::Load(rebind_uchar_uint, inImg.data() + i);
    auto v_hwy_uint = hn::PromoteTo(d_uint, v_hwy_uchar);
    auto v_hwy_float = hn::ConvertTo(d_float, v_hwy_uint);
    hn::Store(v_hwy_float, d_float, outImg.data() + i);
  }

  auto tEnd = std::chrono::high_resolution_clock::now();
  auto ts = tEnd - tStart;
  auto tsMs = (float) ts.count() / 1000000;
  spdlog::info("SIMD_DURATION:{:.2f}ms", tsMs);
}

}
}
HWY_AFTER_NAMESPACE();

#if HWY_ONCE
namespace hwy {
namespace HWY_NAMESPACE {
namespace hn = hwy::HWY_NAMESPACE;

HWY_EXPORT(_RGBA_UCHAR_TO_RGBA_FLOAT);

TEST(HIGHWAY_TEST, RGBA_UCHAR_TO_RGBA_FLOAT) {
  HWY_DYNAMIC_DISPATCH(_RGBA_UCHAR_TO_RGBA_FLOAT)();
}

}
}
#endif
```


sisd version:
```
TEST(SISD_TEST, RGBA_UCHAR_TO_RGBA_FLOAT) {
  auto w = 1280;
  auto h = 720;
  std::vector<unsigned char> inImg;
  inImg.resize(w * h * 3);
  std::random_device seed;
  std::mt19937 gen(seed());
  std::uniform_int_distribution<> uniformDist(0, 256);

  for (int i = 0; i < inImg.size(); ++i) {
    inImg[i] = uniformDist(gen);
  }

  std::vector<float> outImg;
  outImg.resize(w * h * 3);

  auto stepSize = sizeof(unsigned char);

  auto tStart = std::chrono::high_resolution_clock::now();

  for (int i = 0; i < inImg.size(); i += stepSize) {
    outImg[i] = (float)inImg[i];
  }

  auto tEnd = std::chrono::high_resolution_clock::now();
  auto ts = tEnd - tStart;
  auto tsMs = (float) ts.count() / 1000000;
  spdlog::info("SISD_DURATION:{:.2f}ms", tsMs);
}
```

**Comment by HyundongHwang** [comment]
@jan-wassenberg 
Jan's comment is also correct.
Great. Thank you.
Also, it was of great help.
I needed compiler option -O2 .
In the previous code, it was because it was continuously tested with Debug, and it was improved as the -O2 option was applied while testing with Release.
So, during the development of any product, I think it should build and link with the -O2 option about highway.
Am I right?
How should highway be set up when building Debug mode for product development?

And, I have one more question.
For a more valid statistic on frame conversion performance, I averaged it after 1000 iterations.
And in addition to the existing code, I also made a test code for buffer I/O using AllocateAligned that jan told me about.

result :
```
sisd(non-highway) : 1.36ms
simd-std-vec(highway, std::vector, un-aligned) : 1.38ms
simd-hwy-aligned(highway, AllocateAligned) : 1.24ms
```

Simd-hwy-aligned is about 20% better than sisd, is this correct?
Is there any problem with the code that I wrote in the simd-hwy-aligned version?

simd-hwy-aligned :

```
HWY_DLLEXPORT void _RGBA_UCHAR_TO_RGBA_FLOAT_HWY_ALIGNED() {
  spdlog::info("RUN_TIME_HWY_NAMESPACE:{}", DISPLAY_VALUE(HWY_NAMESPACE));
  auto w = 1280;
  auto h = 720;
  auto c = 4;
  auto frameBufSize = w * h * c;
  auto inImg = hwy::AllocateAligned<unsigned char>(frameBufSize);
  auto outImg = hwy::AllocateAligned<float>(frameBufSize);

  std::random_device seed;
  std::mt19937 gen(seed());
  std::uniform_int_distribution<> uniformDist(0, 256);

  hn::ScalableTag<unsigned char> d_uchar;
  hn::ScalableTag<unsigned int> d_uint;
  hn::ScalableTag<float> d_float;
  auto lanes_float = hn::Lanes(d_float);
  hn::Rebind<unsigned char, decltype(d_uint)> rebind_uchar_uint;
  auto stepSize = lanes_float * sizeof(unsigned char);

  auto iterMax = 1000;
  auto tsMsSum = 0.0f;

  for (int iter = 0; iter < iterMax; iter++) {
    for (int i = 0; i < frameBufSize; i++) {
      inImg[i] = uniformDist(gen);
    }

    auto tStart = std::chrono::high_resolution_clock::now();

    for (int i = 0; i < frameBufSize; i += stepSize) {
      auto v_hwy_uchar = hn::Load(rebind_uchar_uint, inImg.get());
      auto v_hwy_uint = hn::PromoteTo(d_uint, v_hwy_uchar);
      auto v_hwy_float = hn::ConvertTo(d_float, v_hwy_uint);
      hn::Store(v_hwy_float, d_float, (outImg.get() + i));
    }

    auto tEnd = std::chrono::high_resolution_clock::now();
    auto ts = tEnd - tStart;
    auto tsMs = (float) ts.count() / 1000000;
    tsMsSum += tsMs;

    if (iter % 100 == 0) {
      spdlog::info("HWY_DURATION:{}/{}:{:.2f}ms", iter, iterMax, tsMs);
    }
  }

  spdlog::info("AVG_HWY_DURATION:{:.2f}ms", tsMsSum / iterMax);
}
```

For reference, I have the following environment.

```
OS name:     Microsoft Windows 11 Home
OS version:  10.0.22621 N/A build 22621
processors:  Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2803Mhz
cl :         Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x86
```

**Comment by HyundongHwang** [comment]
Hello @jan-wassenberg .
Thank you for your reply.

Is my understanding of the Loop 2x method correct?

```
auto stepSize = lanes_float * sizeof(unsigned char) * 2;

for (int i = 0; i < frameBufSize; i += stepSize) {
  auto v_hwy_uchar = hn::Load(rebind_uchar_uint, (inImg.get() + i));
  auto v_hwy_uchar1 = hn::Load(rebind_uchar_uint, inImg.get() + i + lanes_float);
  auto v_hwy_uint = hn::PromoteTo(d_uint, v_hwy_uchar);
  auto v_hwy_uint1 = hn::PromoteTo(d_uint, v_hwy_uchar1);
  auto v_hwy_float = hn::ConvertTo(d_float, v_hwy_uint);
  auto v_hwy_float1 = hn::ConvertTo(d_float, v_hwy_uint1);
  hn::Store(v_hwy_float, d_float, (outImg.get() + i));
  hn::Store(v_hwy_float1, d_float, (outImg.get() + i + lanes_float));
}
```

In this way, not only Load and Store, but also Promote and Convert are performed twice, so it becomes slightly slower.
Perhaps this is not the case, and a little more detail would be of great help.

**Comment by jan-wassenberg** [comment]
Yes, that's what I had in mind. Interesting that that is slower, I am a bit surprised.

One other thing you can do is use wider vectors by adding /arch:AVX2 compiler setting, or using runtime dispatch (see this [example](https://gcc.godbolt.org/z/zP7MYe9Yf)). Otherwise, you're only getting 128-bit vectors.

**Comment by HyundongHwang** [comment]
Hi @jan-wassenberg,
Did you enjoy your Christmas holiday?

First of all, thanks for the reply.
As you said, I rebuilt the highway with the /arch:AVX2 and /arch:AVX512 options, and I was able to use up to 512bit registers.
I'm using HWY_ARCH_X86_32, but AVX is caught in HWY_BROKEN_TARGETS, so I deleted it and built it.

- highway's changes
  - CMakeLists.txt
```
if (MSVC)
  message("MSVC_AVX512")
  set(HWY_FLAGS
    # fix build error C1128 in blockwise*_test & arithmetic_test
    /bigobj
    /arch:AVX512
  )
```

  - detect_targets.h
```
#elif HWY_ARCH_X86_32
#define HWY_BROKEN_TARGETS 0
```

So I was able to increase the existing stepSize from 4 to 16, and logically there should be a 4x speedup, but there was little improvement.

```
[2022-12-27 16:40:24.357] [info] HWY_ALIGNED
[2022-12-27 16:40:24.358] [info] RUN_TIME_HWY_NAMESPACE:N_AVX3
[2022-12-27 16:40:24.374] [info] stepSize:16
[2022-12-27 16:40:24.390] [info] HWY_DURATION:0/1000:2.15ms
[2022-12-27 16:40:25.919] [info] HWY_DURATION:100/1000:1.05ms
[2022-12-27 16:40:27.429] [info] HWY_DURATION:200/1000:1.57ms
[2022-12-27 16:40:28.948] [info] HWY_DURATION:300/1000:1.48ms
[2022-12-27 16:40:30.458] [info] HWY_DURATION:400/1000:1.48ms
[2022-12-27 16:40:32.011] [info] HWY_DURATION:500/1000:1.87ms
[2022-12-27 16:40:33.544] [info] HWY_DURATION:600/1000:1.14ms
[2022-12-27 16:40:35.062] [info] HWY_DURATION:700/1000:1.27ms
[2022-12-27 16:40:36.585] [info] HWY_DURATION:800/1000:1.66ms
[2022-12-27 16:40:38.119] [info] HWY_DURATION:900/1000:1.18ms
[2022-12-27 16:40:39.628] [info] AVG_HWY_DURATION:1.34ms
```

The test code is the same as the above, and it is confirmed that 16 are processed in the debug version, but the performance has not improved.
It's already a dangerous move because it's been done while transforming to HWY_BROKEN_TARGETS. Is there anything else I've done wrong?

**Comment by jan-wassenberg** [comment]
> I'm using HWY_ARCH_X86_32

I'm curious why and how? We no longer support 32-bit x86, it is obsoleted by x64, isn't it?

> logically there should be a 4x speedup

It's not always going to be the full 4x, frequency reduces a bit and we can only run 2 512-bit mul/shuffle instructions per cycle, not 3. And most of all, you might be running out of memory bandwidth. But that's unlikely if only one core is doing anything, and 3 GB/s is certainly not the limit of performance.

Want to share a godbolt link with your code so we can have a look at the codegen?
