### ISSUE TITLE
Add an invariant declaration macro

### ISSUE THREAD

**Issue by emilmelnikov** [google/highway#1098]
Since `hwy/base.h` already defines `HWY_LIKELY`, it would be nice to add a similar [`assume`](https://en.cppreference.com/w/cpp/language/attributes/assume) macro.
The following implementation was adapted from [`GSL`](https://github.com/microsoft/GSL/blob/c016bdc77f28891cfc42fc219bd5365e89d3ebda/include/gsl/assert#L72):

```c++
#if defined(__has_cpp_attribute) && __has_cpp_attribute(assume)
#define HWY_ASSUME(x) [[assume(x)]]
#elif defined(_MSC_VER)
#define HWY_ASSUME(x) __assume(x)
#elif defined(__clang__)
#define HWY_ASSUME(x) __builtin_assume(x)
#elif defined(__GNUC__)
#define HWY_ASSUME(x) ((x) ? static_cast<void>(0) : __builtin_unreachable())
#else
#define HWY_ASSUME(x) static_cast<void>(0)
#endif
```

As cppreference.com states, the GCC case is a little bit tricky because it actually evaluates the expression, but for most cases it probably won't be a problem.

**Comment by jan-wassenberg** [comment]
Sounds reasonable. Can you share a use case or example showing what this is intended to do?

**Comment by emilmelnikov** [comment]
Currently, I'm using it to remove redundant instructions in cases where callers guarantee a certain invariant. This is a simplified fragment of code from a project:

```c++
using hn = hwy::HWY_NAMESPACE;

template <typename D>
void f(const hn::TFromD<D> *HWY_RESTRICT data,
       const hn::TFromD<D> *HWY_RESTRICT kernel,
       size_t radius,
       hn::TFromD<D> *HWY_RESTRICT result) {

    D d;

    auto k = hn::Set(d, kernel[0]);
    auto x = hn::LoadU(d, data);
    auto y = hn::Mul(k, x);

    HWY_ASSUME(radius >= 1); // <-- Removes an extra branch test
    for (size_t r = 1; r <= radius; ++r) {
        k = hn::Set(d, kernel[r]);
        x = hn::Add(hn::LoadU(d, data + r), hn::LoadU(d, data - r));
        y = hn::MulAdd(k, x, y);
    }

    hn::StoreU(y, d, result);
}
```

Admittedly, in this case an extra branch won't make a meaningful difference in performance.

I also use a variant of `HWY_ASSUME` in scalar code to inspect compiler-generated code and compare it to Highway-based implementations, for example:

```c++
constexpr size_t TRIP_COUNT = 64;
void g(const float *HWY_RESTRICT a, const float *HWY_RESTRICT b, float *HWY_RESTRICT c, size_t n) {
    HWY_ASSUME(n > 0 && n % TRIP_COUNT == 0);
    for (size_t i = 0; i < n; ++i) {
        c[i] += a[i] * b[i];
    }
}
```

Without those hints, compilers generate a lot of unnecessary (in my case) code to account for all possible lengths, which makes it harder to compare the generated assembly.

**Comment by jan-wassenberg** [comment]
That makes sense, thanks for sharing. We can gladly include this. Would you mind creating a pull request?
