### ISSUE TITLE
No need for a FindHWY.cmake

### ISSUE THREAD

**Issue by malaterre** [google/highway#1114]
HWY is build by cmake there should not be a need to write a FindHWY.cmake which are needed only for other build tools (non-cmake type).

**Comment by jan-wassenberg** [comment]
Can you expand on how FindHWY would be used by non-CMake build tools?

My understanding is that FindHWY would still be useful for CMake builds that wish to use a prebuilt/system Highway for whatever reason. @kfjahnke any thoughts?

**Comment by kfjahnke** [comment]
Hi!
I'd like to refer you to my last post to https://github.com/google/highway/issues/1084
The issue was closed, but I thought my answer would still be seen. I enclosed a patch against your CMakeLists.txt which should make the find file unnecessary.

**Comment by jan-wassenberg** [comment]
@malaterre I think I understand the chicken and egg situation. Thanks for explaining and sending the pull request!

@kfjahnke oops, I had indeed missed your post, sorry about that!
Looks like your patch also does something very similar to the pull request here. Let's go with that :)
