### ISSUE TITLE
BitCast for HWY_SCALAR target copies too many bytes if sizeof(T) < sizeof(FromT)

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1123]
Here is the current implementation of BitCast for HWY_SCALAR target:
https://github.com/google/highway/blob/9ad490b6dc5b3252c525b30e430577a92830653f/hwy/ops/scalar-inl.h#L92-L98

The CopyBytes operation in the current implementation of BitCast for the HWY_SCALAR target has undefined behavior if sizeof(T) < sizeof(FromT) is true.

Here is the corrected implementation of BitCast for HWY_SCALAR target:
```
 template <typename T, typename FromT> 
 HWY_API Vec1<T> BitCast(Sisd<T> /* tag */, Vec1<FromT> v) { 
   static_assert(sizeof(T) <= sizeof(FromT), "Promoting is undefined"); 
   T to; 
   CopyBytes<sizeof(T)>(&v.raw, &to);  // not same size - ok to shrink 
   return Vec1<T>(to); 
 }
```

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts , I agree with your fix. Would you mind sending a pull request for this change?

**Comment by jan-wassenberg** [comment]
This is merged, closing. Thanks again :)
