### ISSUE TITLE
Fixes and enhancements to DemoteTo and ReorderDemote2To methods

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1124]
<b>Update:</b> The _mm_packus_epi16 (packuswb) operation converts signed 16-bit integers to unsigned 8-bit integers using unsigned saturation according to the Intel 64 and IA-32 Architectures Software Developer's Manual. The _mm_packus_epi32 (packusdw) operation converts signed 32-bit integers to unsigned 16-bit integers using unsigned saturation according to the Intel 64 and IA-32 Architectures Software Developer's manual.

The current implementation of DemoteTo for i32->u16, i32->u8, and i16->u8 in hwy/ops/x86_128-inl.h are correct.

Here is how the partial vector ReorderDemote2To implementations can be improved for HWY_SSSE3/HWY_SSE4/HWY_AVX2/HWY_AVX3 targets:
```
// Specializations for partial vectors because packs_epi32 sets lanes above 2*N.
HWY_API Vec128<int16_t, 2> ReorderDemote2To(Simd<int16_t, 2, 0> dn,
                                            Vec128<int32_t, 1> a,
                                            Vec128<int32_t, 1> b) {
  const Twice<DFromV<decltype(a)>> d2;
  return DemoteTo(dn, Combine(d2, b, a));
}
HWY_API Vec128<int16_t, 4> ReorderDemote2To(Simd<int16_t, 4, 0> dn,
                                            Vec128<int32_t, 2> a,
                                            Vec128<int32_t, 2> b) {
  return Vec128<int16_t>{_mm_shuffle_epi32(_mm_packs_epi32(a.raw, b.raw), 0xD8)};
}
```

Overloads of DemoteTo should be added for u16->u8, u32->u8, and u32->u16 as the DemoteTo operations for u16->u8, u32->u8, and u32->u16 can be implemented using Min and TruncateTo if necessary.

Here is how the DemoteTo operations can be implemented for u16->u8, u32->u8, and u32->u16 for HWY_SSSE3/HWY_SSE4/HWY_AVX2/HWY_AVX3:
```
template <size_t N>
HWY_API Vec128<uint16_t, N> DemoteTo(Simd<uint16_t, N, 0> /* tag */,
                                     const Vec128<uint32_t, N> v) {
#if HWY_TARGET <= HWY_AVX3
  // NOTE: The _mm_cvtusepi32_epi16 operation is a saturated conversion
  // of unsigned 32-bit integers to unsigned 16-bit integers.
  return Vec128<uint8_t, N>{_mm_cvtusepi32_epi16(v.raw)};
#else
  const Simd<uint32_t, N, 0> du32;
  
  #if HWY_TARGET == HWY_SSSE3
    const Simd<int32_t, N, 0> di32;
    const Simd<uint16_t, N * 2, 0> du16;
    const auto too_big = VecFromMask(di32, Gt(BitCast(di32, ShiftRight<16>(v)), Zero(di32)));
    const auto clamped = Or(v, BitCast(du32, too_big));
    // Lower 2 bytes from each 32-bit lane; same as return type for fewer casts.
    alignas(16) constexpr uint16_t kLower2Bytes[16] = {
        0x0100, 0x0504, 0x0908, 0x0D0C, 0x8080, 0x8080, 0x8080, 0x8080};
    const auto lo2 = Load(du16, kLower2Bytes);
    return Vec128<uint16_t, N>{TableLookupBytes(BitCast(du16, clamped), lo2).raw};
  #else
    const auto clamped = Min(v, Set(du32, 0xFFFF));
    return Vec128<uint16_t, N>{_mm_packus_epi32(v.raw, v.raw)};
  #endif
#endif
}

template <size_t N>
HWY_API Vec128<uint8_t, N> DemoteTo(Simd<uint8_t, N, 0> d,
                                    const Vec128<uint16_t, N> v) {
#if HWY_TARGET <= HWY_AVX3
  // NOTE: The _mm_cvtusepi16_epi8 operation is a saturated conversion
  // of unsigned 16-bit integers to unsigned 8-bit integers.
  return Vec128<uint8_t, N>{_mm_cvtusepi16_epi8(v.raw)};
#else
  const Simd<uint16_t, N, 0> du16;
  const auto maxInt16 = Set(du16, 0x7FFF);
  #if HWY_TARGET == HWY_SSSE3
    // The HWY_SSSE3 target supports the _mm_min_epu8 operation but not the
    // _mm_min_epu16 operation.
    
    // The _mm_min_epu8 operation below is equivalent to the following, where x is
    // an 16-bit unsigned integer:
    // (x <= 0x7FFF) ? x : (0x7F00 | (x & 0x00FF))
    
    // The _mm_min_epu8 operation below is sufficient here as any value that is greater
    // than or equal to 32768 will be first converted to a value between 32512 and 32767
    // through the _mm_min_epu8 operation, which will then be converted to 255 through
    // the _mm_packus_epi16 operation.
    const __m128i clamped = _mm_min_epu8(v.raw, maxInt16.raw);
  #else
    const auto clamped = _mm_min_epu16(v.raw, maxInt16.raw);
  #endif
  
  return Vec128<uint8_t, N>{_mm_packus_epi16(clamped, clamped)};
#endif
}

template <size_t N>
HWY_API Vec128<uint8_t, N> DemoteTo(Simd<uint8_t, N, 0> d,
                                    const Vec128<uint32_t, N> v) {
#if HWY_TARGET <= HWY_AVX3
  // NOTE: The _mm_cvtusepi32_epi8 operation is a saturated conversion
  // of unsigned 32-bit integers to unsigned 8-bit integers.
  return Vec128<uint8_t, N>{_mm_cvtusepi32_epi8(v.raw)};
#else
  const Simd<int32_t, N, 0> di32;
  const Simd<int16_t, N, 0> di16;
  const auto maxInt32 = Set(di32, 0x7FFFFFFF);
  
  #if HWY_TARGET == HWY_SSSE3
  // The HWY_SSSE3 target supports the _mm_min_epu8 operation but not the
  // _mm_min_epu32 operation.
  
  // The _mm_min_epu8 operation below is equivalent to the following, where x is
  // an 16-bit unsigned integer:
  // (x <= 0x7FFFFFFF) ? x : (0x7F000000 | (x & 0x00FFFFFF))
    
  // The _mm_min_epu8 operation below is sufficient here as any value that is greater
  // than or equal to 2147483648 will first be converted to a value between
  // 2130706432 and 2147483647 through the _mm_min_epu8 operation, which will in
  // turn be converted to 32767 through the _mm_packs_epi32 operation, which will in
  // turn be converted to 255 through the _mm_packus_epi16 operation.
  const Simd<uint8_t, N * 4, 0> du32_as_u8;
  const auto clamped = BitCast(di32, Min(BitCast(du32_as_u8, v),
                                         BitCast(du32_as_u8, maxInt32)));
  #else
  const auto clamped = BitCast(di32, Min(v, maxInt32));
  #endif

  return DemoteTo(d, DemoteTo(di16, clamped));
#endif
}
```

Overloads of the ReorderDemote2To operations should be added for s16->s8, s32->u16, s16 -> u8, u32->u16, and u16 -> u8 as the ReorderDemote2To can be implemented using DemoteTo and Combine operations if necessary.

Here is how the ReorderDemote2To operations can be implemented for s32->u16, s16->s8, s16->u8, u32->u16, and u16->u8 for full 128-bit vectors on HWY_SSSE3/HWY_SSE4/HWY_AVX2/HWY_AVX3 targets:
```
HWY_API Vec128<int8_t> ReorderDemote2To(Full128<int8_t> /*d16*/,
                                        Vec128<int16_t> a, Vec128<int16_t> b) {
  return Vec128<int8_t>{_mm_packs_epi16(a.raw, b.raw)};
}

HWY_API Vec128<uint16_t> ReorderDemote2To(Full128<uint16_t> du16,
                                          Vec128<int32_t> a, Vec128<int32_t> b) {
#if HWY_TARGET == HWY_SSSE3
  const Half<decltype(du16)> dHalfU16;
  return Combine(du16, DemoteTo(dHalfU16, b), DemoteTo(dHalfU16, a));
#else
  (void)du16;
  return Vec128<int8_t>{_mm_packus_epi32(a.raw, b.raw)};
#endif
}

HWY_API Vec128<uint16_t> ReorderDemote2To(Full128<uint16_t> du16,
                                          Vec128<uint32_t> a, Vec128<uint32_t> b) {
  #if HWY_TARGET == HWY_SSSE3
    const Half<decltype(du16)> dHalfU16;
    return Combine(du16, DemoteTo(dHalfU16, b), DemoteTo(dHalfU16, a));
  #else
    const Full128<int32_t> di32;
    const auto maxInt32 = Set(du32, 0x7FFFFFFF);
    const auto clamped_a = BitCast(di32, Min(a, maxInt32));
    const auto clamped_b = BitCast(di32, Min(b, maxInt32));
    return ReorderDemote2To(du16, a, b);
  #endif
}

HWY_API Vec128<uint8_t> ReorderDemote2To(Full128<uint8_t> /*du8*/,
                                         Vec128<int16_t> a, Vec128<int16_t> b) {
  return Vec128<uint8_t>{_mm_packus_epi16(a.raw, b.raw)};
}

HWY_API Vec128<uint8_t> ReorderDemote2To(Full128<uint8_t> du8,
                                         Vec128<uint16_t> a, Vec128<uint16_t> b) {
  const Full128<int16_t> di16;
  const Full128<uint16_t> du16;
  const auto maxInt16 = Set(du16, 0x7FFF);

  #if HWY_TARGET == HWY_SSSE3
    // The HWY_SSSE3 target supports the _mm_min_epu8 operation but not the
    // _mm_min_epu16 operation.
    
    // The _mm_min_epu8 operations below are equivalent to the following, where x is
    // a 16-bit unsigned integer:
    // (x <= 0x7FFF) ? x : (0x7F00 | (x & 0x00FF))
    
    // The _mm_min_epu8 operations below are sufficient here as any value that is greater
    // than or equal to 32768 will be first converted to a value between 32512 and 32767
    // through the _mm_min_epu8 operation, which will then be converted to 255 through
    // the _mm_packus_epi16 operation.
    const auto maxInt16_as_u8 = BitCast(du8, maxInt16);
    const auto clamped_a = BitCast(di16, Min(BitCast(du8, a),
                                             maxInt16_as_u8));
    const auto clamped_b = BitCast(di16, Min(BitCast(du8, b),
                                             maxInt16_as_u8));
  #else
    (void)du8;
    const auto clamped_a = BitCast(di16, Min(a, maxInt16));
    const auto clamped_b = BitCast(di16, Min(b, maxInt16));
  #endif

  return ReorderDemote2To(du8, a, b);
}
```

**Comment by jan-wassenberg** [comment]
Wow, thank you @johnplatts for catching the DemoteTo issues and your detailed analysis. Nice work! I'm currently out of the office and will look into a fix in early Feb.

Would you like to create a pull request for the ReorderDemote2To extensions (new types)? May be a good idea to wait until mid/late Feb because we have a major change to implementation details coming up that will change many lines of code.

**Comment by johnplatts** [comment]
> Wow, thank you @johnplatts for catching the DemoteTo issues and your detailed analysis. Nice work! I'm currently out of the office and will look into a fix in early Feb.
> 
> Would you like to create a pull request for the ReorderDemote2To extensions (new types)? May be a good idea to wait until mid/late Feb because we have a major change to implementation details coming up that will change many lines of code.

I have already implemented DemoteTo for all of the possible integer to integer demotions (including i64->i32/i16/i8, unsigned to signed, and unsigned to unsigned), and I have already tested the implementations for x86, NEON, SVE, HWY_SCALAR, and HWY_EMU128 targets.

I have also added ReorderDemote2To for i32->u16, u32->u16, u32->i16, i16->i8, i16->u8, u16->u8, u8->i8, i64->i32, i64->u32, u64->u32, and u64->i32.

I have also added OrderedDemote2To, which is equivalent to Combine(d, DemoteTo(Half<decltype(d)>(), b), DemoteTo(Half<decltype(d)>(), a)), but is implemented in a more efficient manner on most targets.

I still have some more testing to do for DemoteTo for SVE2, RVV, and WASM targets, but I will upload the changes to GitHub once the testing is completed.

**Comment by johnplatts** [comment]
> Wow, thank you @johnplatts for catching the DemoteTo issues and your detailed analysis. Nice work! I'm currently out of the office and will look into a fix in early Feb.
> 
> Would you like to create a pull request for the ReorderDemote2To extensions (new types)? May be a good idea to wait until mid/late Feb because we have a major change to implementation details coming up that will change many lines of code.

I have implemented the following demotions in the https://github.com/johnplatts/jep_google_highway/tree/jep_hwy_demoteto_enhancements branch for all of the supported targets:
- Additional DemoteTo operations:
  - U16->I8/U8
  - U32->I16/U16/I8/U8
  - I64->I32/U32/I16/U16/I8/U8
  - U64->I32/U32/I16/U16/I8/U8
- Additional ReorderDemote2To operations:
  - I16->I8/U8
  - U16->I8/U8
  - I32->U16
  - U32->I16/U16
  - I64->I32/U32
  - U64->I32/U32
- OrderedDemote2To operations:
  - F32->BF16
  - I16->I8/U8
  - U16->I8/U8
  - I32->I16/U16
  - U32->I16/U16
  - I64->I32/U32
  - U64->I32/U32

I have also updated the unit tests in hwy/tests/demote_test.cc to include the additional operations added above.

**Comment by jan-wassenberg** [comment]
Thank you for implementing this and sending the pull request!
It is great to see that type-casting is now more orthogonal/supported for many more types.
