### ISSUE TITLE
zimt - a SIMD abstraction layer - can use highway as a back-end

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#1128]
Dear all!

I'd like to attract your attention to my new library [zimt](https://github.com/kfjahnke/zimt "zimt - C++11 template library to process n-dimensional arrays with multi-threaded SIMD code"). I am in the process of factoring this code out from my library vspline because I found that the code has a much wider scope than being part of a b-spline library. For now, zimt supports four SIMD back-ends:
- Vc
- highway
- std::simd
- 'goading'

The idea is to make all these back-ends interoperable and accessible via a common API. Building on top of this common API is code to 'roll out' SIMD pipeline code over arbitrarily strided nD arrays of fundamentals or 'xel' data, like pixels. This code is already quite mature, because it's been in use for years with both vspline and my image/panorama viewer lux. You may find it helpful to generate testing and benchmarking code for highway.

**Comment by jan-wassenberg** [comment]
Nice, makes sense to pull this out of vspline to enable broader use. The benchmarking aspect is also interesting.

We're happy to mention this in the README. Any suggestions for a one-line summary? I'm thinking of adding a Users section with a bullet list of link+description.

**Comment by kfjahnke** [comment]
Am 02.02.23 um 10:36 schrieb Jan Wassenberg:

> Nice, makes sense to pull this out of vspline to enable broader use.

I've been wanting to do this for quite some time now. I think it's very 
useful code, and having it only as part of vspline made it hard to find 
and appreciate as a tool in it's own right. I'd appreciate any comments 
you may have - especially on the implementation of hwy_simd_type.

> The benchmarking aspect is also interesting.

zimt helps to quickly roll out SIMD code to large data sets, so it's 
good for that.

> We're happy to mention this in the README.

Thanks!

> Any suggestions for a one-line summary? I'm thinking of adding a Users section with a bullet list of link+description.

I think the title of the git repo makes for a good one-line summary:

zimt - C++11 template library to process n-dimensional arrays with 
multi-threaded SIMD code
