### ISSUE TITLE
Very slow on debug mode.

### ISSUE THREAD

**Issue by xiaozhuai** [google/highway#1130]
When build debug, highway is very slow. Why does this happen?.

**Comment by jan-wassenberg** [comment]
Hi, this is likely because the compiler doesn't inline functions in debug builds, so we have one extra function call per instruction which can be a 10-100x slowdown. You may be able to reduce the impact by enabling inlining in debug mode.

**Comment by xiaozhuai** [comment]
@jan-wassenberg Thanks for your help, and here is my code https://github.com/xiaozhuai/vcpkg_demo/tree/master/highway , then how can I enable inlining in debug mode?

**Comment by jan-wassenberg** [comment]
Hi, you're welcome. This can be done via compiler flags, in your case perhaps something like `target_compile_options(${PROJECT_NAME} PRIVATE -finline-functions -finline-small-functions)` in CMakeLists.txt.

**Comment by xiaozhuai** [comment]
> Hi, you're welcome. This can be done via compiler flags, in your case perhaps something like `target_compile_options(${PROJECT_NAME} PRIVATE -finline-functions -finline-small-functions)` in CMakeLists.txt.

Tried, but it not work
```
clang: warning: optimization flag '-finline-small-functions' is not supported [-Wignored-optimization-argument]
```

**Comment by jan-wassenberg** [comment]
Yes, that one is gcc-specific. But the first one might be enough already for clang - does it give a speedup?

**Comment by xiaozhuai** [comment]
> Yes, that one is gcc-specific. But the first one might be enough already for clang - does it give a speedup?

No, the first one is ok for clang, but it didn't give a speedup.

**Comment by jan-wassenberg** [comment]
huh, surprising that clang doesn't seem to have a reliable flag for this, the equivalent of MSVC /Ob2 or ICL's -inline-level=2.

There is an optimization pass one could manually run (opt -always-inline in.bc -o out.bc) but it's nontrivial to do from CMake. Maybe the easiest way forward is to use an optimized build, plus whatever flags you require to get the benefit of debug mode?

**Comment by xiaozhuai** [comment]
> huh, surprising that clang doesn't seem to have a reliable flag for this, the equivalent of MSVC /Ob2 or ICL's -inline-level=2.
> 
> There is an optimization pass one could manually run (opt -always-inline in.bc -o out.bc) but it's nontrivial to do from CMake. Maybe the easiest way forward is to use an optimized build, plus whatever flags you require to get the benefit of debug mode?

I have no idea of this. I really need debug mode works for highway.
Maybe I should separate the highway part from the main project into a library and compile it with -O2?

**Comment by xiaozhuai** [comment]
@jan-wassenberg Finally I found a way. Override flags for some file is enough. 

```
if(MSVC)
    set_source_files_properties(src/task.cpp src/task.h PROPERTIES COMPILE_FLAGS /O2)
else()
    set_source_files_properties(src/task.cpp src/task.h PROPERTIES COMPILE_FLAGS -O2)
endif()
```

It works good on clang and gcc but not works on msvc.

```
/TP /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /utf-8 -std:c++14 /O2 /Be /Bd /EP<<
	
	cl /TP /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /utf-8 -std:c++14 /O2 /Be /Bd /EP
	cl : Command line warning D9025 : overriding '/Od' with '/O2'
	cl : Command line error D8016 : '/RTC1' and '/O2' command-line options are incompatible
```

`/RTC1` flags needs to be removed from these two source file too. But I didn't found a good method to achieve this.

**Comment by eustas** [comment]
It seems that `CMAKE_BUILD_TYPE=RELWITHDEBINFO` is what you want to achieve...

**Comment by xiaozhuai** [comment]
> It seems that `CMAKE_BUILD_TYPE=RELWITHDEBINFO` is what you want to achieve...

That works. But RELWITHDEBINFO will link to release libraries which is not what I expected.

**Comment by jan-wassenberg** [comment]
Thanks @eustas , RelWithDebInfo indeed sounds suitable.

Per-file compiler flags are also reasonable. For the /Od and /O2 incompatibility, you can just specify /Ob2 (enable inlining) instead of the full /O2.

**Comment by jan-wassenberg** [comment]
Looks like MSVC is pretty terrible at /O0. You can experiment with other flags here: https://gcc.godbolt.org/z/hfdv7Wdrn
but it does indeed look like /O2 is important for MSVC.

**Comment by xiaozhuai** [comment]
This version works.

```cmake
if(MSVC)
    STRING(REGEX REPLACE "/RTC[^ ]*" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
endif()
if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    if(MSVC)
        set_source_files_properties(src/task.cpp src/task.h PROPERTIES COMPILE_FLAGS "/Og /Oi /Ot /Oy /Ob2 /GF /Gy")
    else()
        set_source_files_properties(src/task.cpp src/task.h PROPERTIES COMPILE_FLAGS -O2)
    endif()
endif()
```

According to https://learn.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?view=msvc-170. `/O2` equals to `/Og /Oi /Ot /Oy /Ob2 /GF /Gy`. 

But `/Og` incompatable with `/RTC1`. So `/RTC1` should be remove.

Also tried remove `/Og` and reserve `/RTC1`. But it gives no speedup.

Seems the key flags is `/Og`. But `/Og` has been deprecated.
```
cl : Command line warning D9035 : option 'Og' has been deprecated and will be removed in a future release
```

**Comment by xiaozhuai** [comment]
@jan-wassenberg Thanks a lot! I'll close this issue as completed.
