### ISSUE TITLE
CompressStore copies 1024 bytes of memory on each invocation (GCC / x64 / AVX2)

### ISSUE THREAD

**Issue by jeremiahar** [google/highway#1139]
Hello and thank you for open sourcing this library.

It seems that under GCC with -march=znver2 -mtune=znver2, memcpy is called into a stack buffer for each call to hn::CompressStore. The source operand is the
```c++
// alternative is _pext_u64, but this is extremely slow on Zen2 (18 cycles)
// and unavailable in 32-bit builds. We instead compress each index into 4
// bits, for a total of 1 KiB.
alignas(16) constexpr uint32_t packed_array[256] = {
```

It seems that making the packed_array variable static fixes the problem without unnecessary runtime branching from static initialization.

https://godbolt.org/z/Tab5YE7qb

**Comment by jan-wassenberg** [comment]
Thanks @jeremiahar for the heads-up :)
Indeed. Clang does not require the static but it doesn't hurt either, so we will search for all occurrences of `) constexpr` and insert static.
