### ISSUE TITLE
Use of masked variant of permute instructions on AVX2/AVX512 in ConcatEven/Odd functions

### ISSUE THREAD

**Issue by ag01** [google/highway#1146]
Hi,

I see that the ConcatEven/Odd implementations in AVX2/AVX512 use the masked variant of the permute intrinsic (e.g. _mm512_mask2_permute_*) - with the mask used simply containing all 1s.

Using GCC 7.5 - this results in extra instructions for setting up and using the mask register, see here: https://godbolt.org/z/j9bhc3oer

This doesn't seem to occur using GCC 8 and above (as I presume it is optimised away, and the non-masked variant is used).

I'd be interested to know if there was any reason for the implementation using the masked variant.

Many thanks

**Comment by jan-wassenberg** [comment]
Hi, thanks for raising the issue. I dimly recall using the masked version due to some problem with the non-masked intrinsic (I think they expanded to the masked instruction, but in a form that raised a warning).

Let's go with the non-masked version assuming our CI is (now) happy with that :)
