### ISSUE TITLE
Add s390x support

### ISSUE THREAD

**Issue by malaterre** [google/highway#1153]
The recent generations of IBMz hardware (z13, z14, z15) have SIMD vector extensions and cryptographic accelerators. The SIMD features are similar to Power Altivec and VSX SIMD. Since POWER8/POWER9 support has been added recently, it should be possible to add s390x support.

**Comment by johnplatts** [comment]
Some of the Altivec/VSX intrinsics used in [hwy/ops/ppc_vsx-inl.h](https://github.com/google/highway/blob/master/hwy/ops/ppc_vsx-inl.h) are not available on s390x.

The ```#include <altivec.h>``` also needs to be replaced with ```#include <vecintrin.h>``` on s390x.

s390x also always operates in big-endian mode.

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts . The big-endian mode might be a challenge. Did I understand correctly that the current ppc_vsx doesn't fully work yet with big-endian? This would not be a surprise, I've seen many bugs and difficulties porting from little to big endian.

And again there's a question of who would actually want to use Highway+SIMD on s390x, or whether the scalar fallback is enough if it's only about ensuring builds/tests pass?

**Comment by jan-wassenberg** [comment]
We haven't yet heard of potential Highway users on s390x, but please feel free to reopen if that changes :)
