### ISSUE TITLE
Multiple test failures on PPC8/big-endian

### ISSUE THREAD

**Issue by malaterre** [google/highway#1169]
Currently HWY_PPC8 fails on big-endian arches with:

```
The following tests FAILED:
        149 - HwyCompressTestGroup/HwyCompressTest.TestAllCompress/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        165 - HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        177 - HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        185 - HwyDemoteTestGroup/HwyDemoteTest.TestAllReorderDemote2To/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        221 - HwyInterleavedTestGroup/HwyInterleavedTest.TestAllLoadStoreInterleaved3/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        255 - HwyMaskTestGroup/HwyMaskTest.TestAllStoreMaskBits/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        271 - HwyMulTestGroup/HwyMulTest.TestAllMul/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        281 - HwyMulTestGroup/HwyMulTest.TestAllReorderWidenMulAccumulate/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        283 - HwyMulTestGroup/HwyMulTest.TestAllRearrangeToOddPlusEven/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
        287 - HwyReductionTestGroup/HwyReductionTest.TestAllMinMaxOfLanes/PPC8  # GetParam() = 562949953421312 (SIGTRAP)
```

**Comment by jan-wassenberg** [comment]
@johnplatts would you mind looking into these? Or do you think it is worth supporting big-endian SIMD? One option could be to simply mark HWY_PPC* as broken in big endian, so HWY_EMU128 will instead be used.

**Comment by jan-wassenberg** [comment]
> They are... I am simply investigating why.

Right. It is very easy to have big-endian specific bugs. The BitCast you mention is by itself portable, but generally requires endian-specific indices before/afterwards.

It is certainly possible to fix all the remaining issues, but I'm not sure anyone wants to, or would be negatively affected if big-endian used the fallback implementation.

**Comment by johnplatts** [comment]
A modified version of Highway that uses the LoadInterleaved, StoreInterleaved, Expand, and LoadExpand operations in hwy/ops/generic_ops-inl.h for the HWY_EMU128 target can be found in the jep_hwy_emu128_with_generic_ops branch of the https://github.com/johnplatts/jep_google_highway repository.

The purpose of the modified implementation of [hwy/ops/emu128-inl.h](https://github.com/johnplatts/jep_google_highway/commit/b253e96122da9f30a0518d096d1ead45615e0b8a#diff-de2e65b8fa134a5533c0491b5b41ad6d1b77fada7d81b7317831332e77c7f3a4) in the jep_hwy_emu128_with_generic_ops branch is to detect any bugs that are there in hwy/ops/generic_ops-inl.h or in the unit tests on big-endian targets.

The hwy/contrib/sort/bench_sort.cc test is also disabled in the jep_hwy_emu128_with_generic_ops branch as the hwy/contrib/sort/bench_sort.cc test is extremely slow on the HWY_EMU128 target with the modified hwy/ops/emu128-inl.h in the jep_hwy_emu128_with_generic_ops branch.

**Comment by jan-wassenberg** [comment]
Good point, thanks for bringing up bench_sort. We can reduce the input size 10x and also disable it for SSE2+at least some emu128.
