### ISSUE TITLE
compile with gcc on x86_64-pc-linux-gnu is broken with: cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown

### ISSUE THREAD

**Issue by stefson** [google/highway#1174]
hey, I just compiled latest highway code from git and had this compile error: 

```
/usr/bin/x86_64-pc-linux-gnu-g++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999  -O2 -march=znver1 -pipe -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c /var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/per_target.cc
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
In file included from /var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/highway.h:379,
                 from /var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/per_target.cc:21,
                 from /var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/foreach_target.h:202,
                 from /var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/per_target.cc:20:
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/x86_512-inl.h: In function ‘__m512i hwy::N_AVX3_ZEN4::detail::BitCastToInteger(__m512i)’:
/var/tmp/portage/dev-cpp/highway-9999/work/highway-9999/hwy/ops/x86_512-inl.h:168:46: warning: AVX512F vector return without AVX512F enabled changes the ABI [-Wpsabi]
  168 | HWY_INLINE __m512i BitCastToInteger(__m512i v) { return v; }
      |                                              ^
At global scope:
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
cc1plus: error: attribute ‘avxvnni’ argument ‘target’ is unknown
```

A quick google search suggests that `avxvnni` is not compatible with gcc prior to gcc-11 branch, do you not want users to use these older version in the future? Setting the minimal gcc for compiling to gcc-11? 

It worked for me using gcc-12.2.0

full log: [build.log.gz](https://github.com/google/highway/files/10861079/build.log.gz)

**Comment by jan-wassenberg** [comment]
Makes sense, thanks for reporting this. As with SVE, we'll mark AVX3_DL and AVX3_ZEN4 as broken/unusable if the compiler is too old.

**Comment by johnplatts** [comment]
The HWY_TARGET_STR_AVX3_DL macro in hwy/ops/set_macros-inl.h needs to be changed to the following:
```
#define HWY_TARGET_STR_AVX3_DL                                    \
  HWY_TARGET_STR_AVX3                                             \
  ",vpclmulqdq,avx512vbmi,avx512vbmi2,vaes,avx512vnni,avx512bitalg," \
  "avx512vpopcntdq"
```

Changing ```avxvnni``` to ```avx512vnni``` in HWY_TARGET_STR_AVX3_DL will allow Google Highway to successfully compile with GCC 8/9/10/11.

Line 384 of hwy/detect_targets.h also needs to be changed to the following:
```#if HWY_BASELINE_AVX3 != 0 && defined(__AVX512VNNI__) && defined(__VAES__) && \```

The ```avxvnni``` target string option and the ```-mavxvnni``` gcc/clang option is actually the option for the new VEX-encoded AVX-VNNI instructions added on Alder Lake CPU's that came out last year, and the VEX-encoded AVX-VNNI instructions are available on Alder Lake CPU's that have AVX2 support but that don't have AVX512 support.

There is also a different CPUID bit for the VEX-encoded AVX-VNNI instructions available on Alder Lake and newer CPU's (bit 4 of register eax of CPUID eax=7, ecx=1) than for the EVEX-encoded AVX512_VNNI instructions available on Cascade Lake, Cooper Lake, Ice Lake, Tiger Lake, Rocket Lake, Zen 4, Sapphire Rapids, and later CPU's that have AVX512 support.

The ```avx512vnni``` option in the target string and the ```-mavx512vnni``` gcc/clang option actually enables the EVEX-enabled AVX512_VNNI instructions available on Cascade Lake and newer Intel CPU's that have AVX512 support.

The DetectTargets function hwy/targets.cc correctly checks for the EVEX-encoded AVX512_VNNI instructions (but not for the newer AVX-VNNI instructions available on Alder Lake, Sapphire Rapids, and newer Intel CPU's).

**Comment by jan-wassenberg** [comment]
Fixed by @johnplatts :)
