### ISSUE TITLE
NEON_WITHOUT_AES vs HWY_CMAKE_ARM7:BOOL=ON

### ISSUE THREAD

**Issue by malaterre** [google/highway#1238]
Back in 1.0.3 release HWY_CMAKE_ARM7:BOOL=ON implied the crypto stuff on armhf Debian, so I see HWY_NEON.

Now it seems this setting in 1.0.4 default to NEON_WITHOUT_AES:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=1.0.4%7Egit20230317.8681eb8-1&stamp=1679065762&raw=0

Donno if doc or code should be updated to reflect that change

**Comment by jan-wassenberg** [comment]
Here is my current understanding:
1) Arm V7 actually lacks support for AES instructions, it was only added in Arm V8.
2) the HWCAP_AES vs HWCAP2_AES distinction exists, but is only between aarch64 and aarch32 (both are Arm V8).
3) If someone had used AESRound in Arm V7 in 1.0.3 (so HWY_NEON target), then it would have SIGILLed. Now it will instead use software emulation in the HWY_NEON_WITHOUT_AES target.

I think it's all good now, any suggestions on what to update?
