### ISSUE TITLE
Test failure on ARMv7 with Clang

### ISSUE THREAD

**Issue by eclipseo** [google/highway#124]
The following test fails on ARMv7hl with Clang 12 and version 0.11.1. It works fine with GCC 11.

```
        Start  76: HwyMemoryTestGroup/HwyMemoryTest.TestAllGather/Scalar#GetParam()=536870912
 76/104 Test  #76: HwyMemoryTestGroup/HwyMemoryTest.TestAllGather/Scalar#GetParam()=536870912 ..........................Bus error***Exception:   0.17 sec

The following tests FAILED:
	 76 - HwyMemoryTestGroup/HwyMemoryTest.TestAllGather/Scalar#GetParam()=536870912 (Bus error)
make: Leaving directory '/builddir/build/BUILD/highway-0.11.1/armv7hl-redhat-linux-gnueabi'
```

See log: https://kojipkgs.fedoraproject.org//work/tasks/2926/65532926/build.log

**Comment by eclipseo** [comment]
With GIT tip, I have two errors instead:

```
The following tests FAILED:
	 92 - HwyMemoryTestGroup/HwyMemoryTest.TestAllScatter/Scalar#GetParam()=536870912 (Bus error)
	 93 - HwyMemoryTestGroup/HwyMemoryTest.TestAllGather/Scalar#GetParam()=536870912 (Bus error)
make: Leaving directory '/builddir/build/BUILD/highway-12b174188d4a505ccd6e3e2bb10cc58ddbb423ae/armv7hl-redhat-linux-gnueabi'
```

See log: https://kojipkgs.fedoraproject.org//work/tasks/3695/65533695/build.log

**Comment by jan-wassenberg** [comment]
@eclipseo thanks for reporting this. Scatter was added after 0.11.1, so the additional failure in tip would be expected.

Scatter/Gather share similar code. Note that the failing test is for scalar, i.e. normal C++ code without any SIMD.
There is one somewhat unusual operation: copying from/to a misaligned address, but it uses __builtin_memcpy so should be fine. Probably a compiler issue? Any chance you could run this in a debugger and see where it's faulting?

BTW to test SIMD, I think we need different flags for armv7: currently it's -mfpu=vfpv3-d16, but to get NEON I think we need -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp/hard (depending on what the platform is built for).

**Comment by eclipseo** [comment]
I can't reproduce with latest version. Thnaks.

**Comment by jan-wassenberg** [comment]
@eclipseo thanks for following up!
