### ISSUE TITLE
highway nigtly + gcc 9.4.0 + icelake-cpu : WARNING: CPU supports 6000000000005b80 but software requires 4000000000005bc0

### ISSUE THREAD

**Issue by ax7e** [google/highway#1248]
I'm using static dispatch and it shows

`WARNING: CPU supports 6000000000005b80 but software requires 4000000000005bc0`

the output during compile seems spurious, my cpu does not support avx3_zen4, but it insists to use it.

```c++
Compiled HWY_TARGETS:   AVX3_ZEN4
HWY_ATTAINABLE_TARGETS: AVX3_ZEN4 AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 SCALAR
HWY_BASELINE_TARGETS:   AVX3_ZEN4 AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 SCALAR
HWY_STATIC_TARGET:      AVX3_ZEN4
HWY_BROKEN_TARGETS:     Unknown Unknown Unknown Unknown Unknown
HWY_DISABLED_TARGETS:
WARNING: CPU supports 6000000000005b80 but software requires 4000000000005bc0
Current CPU supports:   AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 EMU128 SCALAR
```

after disabled AVX3_GEN4, the warnning is gone.

**Comment by jan-wassenberg** [comment]
Thanks @ax7e for reporting this. It appears you are compiling with something like `-march=icelake-server`. Our choice of static target is not ideal, it would be better to select AVX3_DL unless you are actually running on AMD.

I will fix this to require opting into the AMD-specific target for AVX3, with the default being Intel, and this will prevent the warning.

**Comment by ax7e** [comment]
https://github.com/google/highway/blob/2c8147a86a5b6f20e23b5448779c122fe241ad6a/hwy/detect_targets.h#L603-L608
btw, in the above code, maybe you could also loop into the disabled targets before report an error? I got an error from here when I disabled AVX3_ZEN4 by setting the HWY_DISABLE_TARGETS.

**Comment by ax7e** [comment]
btw, highway is rellay a great work which solved my problem of having to write different versions of simd code

**Comment by jan-wassenberg** [comment]
Thanks for sharing the output. This seems to be before the recent change, which should prevent AVX3_ZEN4 from showing up in the baseline targets (unless you define HWY_WANT_AVX3_ZEN4, which you probably do not want to).

Now another surprise from your output is why AVX3_DL is not in ATTAINABLE. It should be, but it seems we have another bug: I had written HWY_BASELINE instead of HWY_BASELINE_TARGETS.

After #1251 is merged, would you please share the output again, and re-enable this `#error`?

**Comment by ax7e** [comment]
```
Config: emu128:0 scalar:0 static:0 all_attain:0 is_test:0
Compiled HWY_TARGETS:   AVX3_DL
HWY_ATTAINABLE_TARGETS: AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 SCALAR
HWY_BASELINE_TARGETS:   AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 SCALAR
HWY_STATIC_TARGET:      AVX3_DL
HWY_BROKEN_TARGETS:     Unknown Unknown Unknown Unknown Unknown
HWY_DISABLED_TARGETS:   AVX3_ZEN4
Current CPU supports:   AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 EMU128 SCALAR
```

**Comment by ax7e** [comment]
Now everything seems fine.

**Comment by jan-wassenberg** [comment]
Super, thank you for confirming, and reporting the issue so that we could fix it.

By the way, I believe it is no longer necessary to explicitly disable ZEN4, we will not choose it for static dispatch unless you opt-in by another macro.
