### ISSUE TITLE
make install shouldn't install all headers only public ones

### ISSUE THREAD

**Issue by eclipseo** [google/highway#125]
Currently make install install all headers from HWY_SOURCES:

```
set(HWY_SOURCES
    contrib/image/image.cc
    contrib/image/image.h
    contrib/math/math-inl.h
    hwy/aligned_allocator.cc
    hwy/aligned_allocator.h
    hwy/base.h
    hwy/cache_control.h
    hwy/foreach_target.h
    hwy/highway.h
    hwy/nanobenchmark.cc
    hwy/nanobenchmark.h
    hwy/ops/arm_neon-inl.h
    hwy/ops/scalar-inl.h
    hwy/ops/set_macros-inl.h
    hwy/ops/shared-inl.h
    hwy/ops/wasm_128-inl.h
    hwy/ops/x86_128-inl.h
    hwy/ops/x86_256-inl.h
    hwy/ops/x86_512-inl.h
    hwy/targets.cc
    hwy/targets.h
    hwy/tests/test_util-inl.h
)
```

However we only need the public ones and their deps as defined in `quick_reference.md`:

> 
> The public headers are:
> 
> - hwy/highway.h: main header, included from source AND/OR header files that use vector types. Note that including in headers may increase compile time, but allows declaring functions implemented out of line.
> 
> - hwy/base.h: included from headers that only need compiler/platform-dependent definitions (e.g. HWY_ALIGN_MAX or PopCount) without the full highway.h.
> 
> - hwy/foreach_target.h: re-includes the translation unit (specified by HWY_TARGET_INCLUDE) once per enabled target to generate code from the same source code. highway.h must still be included, either before or after.
> 
> - hwy/aligned_allocator.h: defines functions for allocating memory with alignment suitable for Load/Store.
> 
> - hwy/cache_control.h: defines stand-alone functions to control caching (e.g. prefetching) and memory barriers, independent of actual SIMD.
> 

i.e.

```
hwy/highway.h
hwy/base.h
hwy/foreach_target.h
hwy/aligned_allocator.h
hwy/cache_control.h
hwy/targets.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/ops/arm_neon-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/scalar-inl.h
hwy/ops/shared-inl.h
hwy/set_macros-inl.h
```

**Comment by deymo** [comment]
If I didn't miss anything your proposed list is the same as the headers in the first list except for:
* contrib/*
* test_util-inl.h
* nanobenchmark.h

test_util-inl.h is meant to be public. There's a libhwy-test.pc file being installed too and test_util-inl.h is a helper if you want to run test for multiple SIMD targets in other projects (it is used in most tests in JPEG XL for example).

nanobenchmark and the contrib/image CC files are currently compiled into libhwy.a so it makes sense that the headers are installed. Maybe the request here would be to split out nanobenchmark and contrib to another library, but these being a static library it is very likely that when linking your project the files are dropped if not used anyway so the impact is not huge. Maybe for contrib/ it is logical to split those files as they are probably installed outside hwy/.

**Comment by jan-wassenberg** [comment]
Thanks, @deymo. These are indeed intended to be public. I will mention them in quick_reference.

As to splitting contrib, I believe that would make them slightly harder to use and agree that static linking should just discard unused objects. Do we have any concerns about including contrib in the same library?

**Comment by jan-wassenberg** [comment]
@eclipseo We have split hwy and hwy_contrib libraries and moved the latter into hwy/contrib. Does that resolve your concern?

**Comment by eclipseo** [comment]
Yes this is perfect.

Thank you.
