### ISSUE TITLE
Adding the HWY_AVX2_GFNI target

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1275]
There are some Intel Tiger Lake/Alder Lake/Raptor Lake CPU's that support both AVX2 and GFNI but not AVX512.

There are also some Intel CPU's with AVX512 support that do not support GFNI, but the HWY_AVX2_GFNI target is also supported on CPU's that support HWY_AVX3_DL target.

Here is the current x86 targets:
https://github.com/google/highway/blob/e1c750df456fad8552e692af4f6f8a5974250628/hwy/detect_targets.h#L60-L80

HWY_AVX2_GFNI needs to be less than HWY_AVX2 but greater than HWY_AVX3 as:
- Some of the code in hwy/ops/x86_128-inl.h and hwy/ops/x86_256-inl.h assumes that the AVX512F/AVX512BW/AVX512DQ/AVX512VL intrinsics are available if ```HWY_TARGET <= HWY_AVX3``` is true
- We want the HWY_AVX3_DL target selected on CPU's that support both the HWY_AVX2_GFNI and HWY_AVX3_DL targets if both of these targets are enabled

Adding the HWY_AVX2_GFNI target will also require changing the values of HWY_AVX3, HWY_AVX3_DL, and HWY_AVX3_ZEN4.

There are also some SIMD operations that can be accelerated using the _mm_gf2p8affine_epi64_epi8 intrinsic on HWY_AVX2_GFNI, HWY_AVX3_DL, and HWY_AVX3_ZEN4 targets such as the following:
- ShiftRight for int8_t/uint8_t vectors
- LeadingZeroCount for int8_t/uint8_t vectors
- Bit reversal for int8_t vectors
- Bit permutation for int8_t vectors

**Comment by johnplatts** [comment]
> @johnplatts I am replying with delay due to illness last week, sorry about that. Looks like it is indeed necessary to renumber the targets for adding an AVX2_GFNI. I'm not sure we can safely do that. If someone has compiled a binary and then updates the headers without recompiling, their code breaks. How do you see that, and how important would it be for you to have the AVX2_GFNI instead of only using GFNI in the AVX3_DL target?
> 
> (It might also be a good idea to wait and see what Intel adds next in order to inform this decision.)

The upcoming Intel Sierra Forest CPU's scheduled for release in 2024 will have some new SIMD instruction sets added but no AVX512 support as the Sierra Forest CPU's will be using efficiency cores that do not support AVX512.

The new instruction sets that will be added to Intel Sierra Forest include the following:
- AVX-NE-CONVERT - instructions for converting between float16_t/bfloat16_t and float (including the VEX-encoded version of the AVX512_BF16 VCVTNEPS2BF16 instruction)
- AVX-VNNI-INT8 - additional multiplication and add operations for int8_t/uint8_t vectors
- AVX-IFMA - VEX-encoded versions of the AVX512_IFMA VPMADD52LUQ/VPMADD52HUQ instructions

**Comment by jan-wassenberg** [comment]
Good to know, thanks. I would consider those three worthwhile enough to add a new target for them.

Do you have an opinion whether AVX2+GFNI is by itself worthwhile enough to add a new target (= more compile time and binary size)? Currently I'm leaning towards no.

As to the target reordering: currently we do not yet know whether the Granite Rapids (P cores counterpart to the Sierra Forest E cores) will also support AVX-512, right? If they did, then we would want AVX3 to be considered better than this new target. But if not, then I believe no reordering is required, right?

**Comment by jan-wassenberg** [comment]
FYI in light of the AVX10 announcement, we will likely add a "AVX10.2" target with 256-bit AVX-512 instructions. Numerically this will be greater than AVX3_SPR, so on Xeon we would use the latter if available. But it would be less than AVX2, so used in preference to AVX2 when AVX10.2 is available.
Please reopen if you'd like to discuss this plan or suggest an alternative :)
