### ISSUE TITLE
lux image/panorama viewer now uses highway as default SIMD back-end

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#1300]
Dear highway crew!

With version 1.1.6 of my image and panorama viewer [lux](https://bitbucket.org/kfj/pv/), I have made highway the default SIMD back-end. All rendering code now uses highway. All lux 1.1.6 binaries available from the [download page](https://bitbucket.org/kfj/pv/downloads/) are built using the highway back-end. Can you link to my site in your 'highway is used by ...' section? It may be a bit much to ask for yet another link to my work (you link to [zimt](https://github.com/kfjahnke/zimt) already) - if you find that one link should be all I deserve, I'd prefer the one to lux - zimt is still new and experimental, whereas lux is quite mature.

So far, no bug reports have come in for the new binaries - this does not mean much; the downloads may have been done by robots and antivirus software, and users nowadays tend to bin stuff which doesn't instantly do what they expect - but I'm quite optimistic that my move from the old default - Vc - has been successful, and performance using highway is now en par with what I used previously - and the build for Apple's M1 benefits hugely from highway, which supports it natively! BTW - the freeBSD port of lux also uses the highway back-end and has been doing so for some time.

With regards
Kay F. Jahnke

**Comment by jan-wassenberg** [comment]
Hi Kay, congrats on the seemingly successful port/switch. Sure, happy to link to Lux :)
