### ISSUE TITLE
implicit declaration of function '__riscv_vsseg4e8_v_i8mf8' 

### ISSUE THREAD

**Issue by malaterre** [google/highway#1312]
GCC 13 does not compile `interleaved_test` for example. It fails with:

```
/home/malat/highway/hwy/ops/rvv-inl.h:1566:48: error: '__riscv_vsseg2e32_v_f32m1' was not declared in this scope; did you mean '__riscv_vsse32_v_f32m1'?
 1566 |     __riscv_v##OP##e##SEW##_v_##CHAR##SEW##LMUL(unaligned, v0, v1, Lanes(d));  \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Per upstream/GCC this is considered an "old" API and will never be implemented in GCC (13 or 14).

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109544

**Comment by jan-wassenberg** [comment]
Thanks, I'm aware of the difference in segment APIs. My understanding is that this will soon be added to Clang, then we can implement the existing LoadInterleaved2 ops in terms of that, plus provide a new `LoadTuple2` that accepts a tuple arg instead of 2 vectors.

Any thoughts on what we should do for GCC in the meantime? I'm not sure whether the tuple change will land before the 13 release.

**Comment by jan-wassenberg** [comment]
Interesting that GCC has an 8-bit field for such 'modes'. Sorry to hear this won't land until GCC 14, but thanks for the heads-up.

Yes, we can make it conditional on HWY_HAVE_TUPLE - seems like removing all of RVV until GCC 14 would be much worse than only conditionally granting access to this new and frankly optional feature.

I'll start implementing this soon to unblock your build.

**Comment by jan-wassenberg** [comment]
:) It is still a fairly small instruction set for vectors, at least in terms of opcodes (the LMUL is arguably separate from that).

**Comment by jan-wassenberg** [comment]
#1316 added support for this. Please reopen if that does not work for you :)

**Comment by jan-wassenberg** [comment]
Thanks for pointing this out. Clang currently supports segments using the old API which takes N vector arguments.
AFAIK the new-style tuple interface is under discussion, but is not yet in the compiler.
We will update this to re-enable clang as soon as we have a clang version that supports this.
