### ISSUE TITLE
Documentation regarding of usage of PromoteTo and DemoteTo should be more clear

### ISSUE THREAD

**Issue by ibogosavljevic** [google/highway#1347]
In https://github.com/google/highway/blob/master/g3doc/quick_reference.md, the explanations and examples related to type promotion and demotion, when converting from smaller to larger types or vice verse (e.g. uint32_t to uint64_t) are not clear enough.

For example:
V,D: (f16,f32), (bf16,f32), (f32,f64)
Vec<D> PromoteTo(D, V part): returns part[i] widened to the floating-point type MakeWide<T>.

It never mentions what `part[i]` means.

Also, you should reference `LowerHalf`, `UpperHalf` and `Combine` as these are very often used with type promotion and demotion.

**Comment by jan-wassenberg** [comment]
Thanks @ibogosavljevic and @johnplatts :)
Yes, makes sense to mention LowerHalf because half-vectors are useful for promotions/demotions. Will do.

For the `part[i]`, it's common in this doc to use array notation but you're right that it has not been defined. How about we add something to "Notation in this doc" along the lines of "square brackets refer to an array access, with zero-based index from the starting address"?

**Comment by ibogosavljevic** [comment]
I don't know how to do it. Personally, if it were fixed sized vectors, I would say `[a, b, c, d] is promoted to `[a, b]`. But since you are trying to be vector agnostic, it's much more difficult.

**Comment by jan-wassenberg** [comment]
I think this is done, please reopen if you'd like to discuss further :)

**Comment by FabianSchuetze** [comment]
Thanks for the interesting discussion! As a related question:

Is [`OrderedDemote2To`](https://google.github.io/highway/en/master/quick_reference.html#two-vector-demotion) guaranteed to saturate? I think the intrinsics for x86 and neon for ints saturate, or? I have not checked the other arches. So far, I have pessimistically used `hn::Clamp` before demotions. If saturation is guaranteed, might it be worthwhile to state that in the docs?

**Comment by jan-wassenberg** [comment]
Yes, saturation is guaranteed by the equivalence to DemoteTo. I'll add a quick clarification, thanks :)
