### ISSUE TITLE
Documentation regarding strip mining unclear

### ISSUE THREAD

**Issue by ibogosavljevic** [google/highway#1368]
In https://github.com/google/highway/blob/master/README.md, there is a section about "Strip-mining". The section misses a motivating example, i.e. why would we want to use strip-mining and what kind of problem does it solve. I feel this would make the rest of the section much easier to follow.

**Comment by jan-wassenberg** [comment]
Thanks, makes sense. #1373 will fix this (I typo-ed the number of this issue in the commit message).
