### ISSUE TITLE
help: how to search data in memory?

### ISSUE THREAD

**Issue by esrrhs** [google/highway#1370]
Hi, I had read the document and example, and still don't know how to search data in memory.
and I know I can use the ```_mm_cmpeq_epi8``` and ```_mm_movemask_epi8``` to do such thing,  but don't know how to write the code use ```highway```.
can you tell me which API needed or write some simple code?
thanks

**Comment by ibogosavljevic** [comment]
Here is one alternative, not tested, probably not even the best one, but it would work fine.

```
#include <hwy/highway.h>
namespace hn = hwy::HWY_NAMESPACE;


    const hn::ScalableTag<float> d;
    auto search_value = Set(d, needle);
    for (i = 0; i < n - hn::Lanes(d); i += hn::Lanes(d)) {
        const auto a_val = Load(d, a + i);
        const auto cmp_mask = (a_val == search_value);

        if (!AllFalse(d, cmp_mask)) {
            // Find maximum in scalar code
            for (int j = i; j < i + hn::Lanes(d); j++) {
                if (a[j] == needle) {
                    return j;
                }
            }
        }
    }
```

The loop doesn't go all the way through the end, the last few iterations need to be done in scalar code.

**Comment by esrrhs** [comment]
thank you. I will test the code

**Comment by jan-wassenberg** [comment]
Thanks @ibogosavljevic ! FYI the Find(Known)FirstTrue op can be useful to replace the scalar loop.

@esrrhs one approach that can be useful for translating known x86 intrinsics to Highway is to search for their names in x86_128-inl.h. For example, movemask is wrapped as BitsFromMask which is a private helper function used in the public ops AllFalse and FindFirstTrue.
