### ISSUE TITLE
Dynamic dispatch discussion

### ISSUE THREAD

**Issue by ibogosavljevic** [google/highway#1377]
Let me explain the problem I am trying to solve and I want your opinion about it. I have a piece of code that is very specific. It can be efficiently vectorized only with 128 bit vectors (so even if we have AVX, you should use SSE nevertheless). Also, vectorization only pays off when CPU supports SSE 4.1. If the CPU supports only SSE2, then the CPU should use the scalar version of the code.

The problem with current implementation, at least to my understanding, is that compilation and dispatching are very coarse. If you enable dynamic dispatching, your code will be compiled with all flavors: SSE2, SSE3, SSE4, AVX, AVX2, etc. The dispatching mechanism will then try to find the closest match and dispatch to that.

What I would like is more control. First, I would like to be able to select which targets get compiled. In my case, it would be scalar and SSE4. Then, I want to be able to tell highway to dispatch only between those two. Is this currently possible? Are there any plans to support such functionality?

**Comment by johnplatts** [comment]
Most of the instructions that were added in AVX2/AVX512VL that aren't in SSE4.2 that have versions that can operate on 128-bit vectors.

Here is how using only 128-bit vectors can be accomplished with Google Highway on all supported targets except for than HWY_SCALAR:
```
template<class T>
using Fixed128BitVecTag = FixedTag<T, 16 / sizeof(T)>;

template<class T>
using Fixed128BitVec = Vec<Fixed128BitVecTag<T>>;
```

There is no need to disable the HWY_AVX2/HWY_AVX3/HWY_AVX3_DL/HWY_AVX3_ZEN4 targets to utilize only 128-bit or smaller vectors as using the Fixed128BitVecTag and Fixed128BitVec typedefs above will limit you to 128-bit or smaller vectors (even on AVX2/AVX3/AVX3_DL/AVX3_ZEN4 targets).

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts , agreed :)
It sounds like @ibogosavljevic would still like to disable the targets for reasons of compile time and/or binary size.
Yes, we can do that by setting `HWY_DISABLED_TARGETS` to the ones you want to skip.

Separately, calling `hwy::DisableTargets` allows you to prevent dispatching to any targets (if they are already disabled, then this is unnecessary).

I am curious what is the SSE4 instruction that is necessary for the algorithm to make sense. Maybe it also exists on other platforms?

**Comment by ibogosavljevic** [comment]
It's mm_mul_epi32 which exists on SSE 4.1 but not on earlier. Without it, vectorization doesn't pay off and it is cheaper to use scalar code with imul.

**Comment by ibogosavljevic** [comment]
The documentation doesn't mention DisabledTarget and how to use it (maybe this should be documented).

Also, let' say I disabled SSE2 and SSE3. They are forwarded to HWY_SCALAR, right? Is it possible to forward them to a custom function?

**Comment by jan-wassenberg** [comment]
Good point, will document them, thanks.

Disabling simply means masking out bits in the 64-bit bitfield. Because the runtime dispatch uses ctz(), disabling allows the higher-valued bits to have a chance. But disabling only affects the choice of target made by Highway. User code can freely choose whichever behavior it wants per target.

For example:
`hwy::DisableTargets(HWY_SSE2 | HWY_SSSE3);` and
```
#if HWY_TARGET == HWY_SCALAR
// this was still the best remaining target, e.g. there was nothing better than HWY_SSSE3
CustomFunction();
#else
NormalCode();
#endif
```
(Note also: there is no SSE3 target because its instructions aren't very helpful for the use cases we have, but an S-SSE3 target exists.)

Does that make sense?

**Comment by jan-wassenberg** [comment]
Now that this is documented, I think we can close :) Please feel free to reopen if you'd like to continue the discussion.
