### ISSUE TITLE
Using -msse4.1 for GCC doesn't enable SSE4 in Highway

### ISSUE THREAD

**Issue by ibogosavljevic** [google/highway#1394]
If we provide just -msse4.1 on the command line, SSE4 is not enabled in Highway. Additionally, we need to provide -DHWY_DISABLE_PCLMUL_AES on the compilation line.

**Comment by johnplatts** [comment]
The HWY_SSE4 target requires support for the `_mm_cmpgt_epi64` intrinsic, which is only available on SSE4.2 or later in addition to the SSE4.1 intrinsics.

Most x86 CPU's manufactured in the last 11 years have support for SSE4.2, and it is becoming increasingly rare to find a PC with an x86 CPU that supports SSE4.1 but not SSE4.2.

x86 CPU's with SSE4.2 support include the following:
- Intel Core i3/i5/i7/i9
- Sandy Bridge or newer Intel Celeron/Pentium
- Nehalem or newer Intel Xeon
- Silvermont or newer Intel Atom
- AMD Jaguar processors or newer
- AMD Bulldozer processors or newer
- AMD Zen
- VIA Nano QuadCore C4000
- VIA Eden X4
- Zhaoxin ZX-C processors or newer

Need to specify the `-msse4.2` option (and either the `-DHWY_DISABLE_PCLMUL_AES` or the `-maes -mpclmul` options) on the GCC/Clang command line to enable the HWY_SSE4 target.

**Comment by ibogosavljevic** [comment]
The same problem exists when `-msse4.2` alone is used as well. I need to provide `-msse4.2 -maes -mpclmul` for Highway to use SSE4.

If this is something  you did on purpose, I think a good idea would be to print a warning or info
#warning SSE4 enabled in the compiler but not used by highway. You will need to specify `-maes -mpclmul` or `-DHWY_DISABLE_PCLMUL_AES` to enable SSE4 by in Highway. I debugged this for a few hours thinking it was a problem in compiler.

**Comment by ibogosavljevic** [comment]
Also, this info should be in the quickreference (if you want SSE4 in highway, you should enable `-msse4.2 -maes -mpclmul` or `-DHWY_DISABLE_PCLMUL_AES`).

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts :)
We have some documentation of this at https://github.com/google/highway/blob/master/g3doc/quick_reference.md#targets but we can expand that and mention it in detect_targets and the readme as well, so thanks for bringing this up :)
