### ISSUE TITLE
SinCos math routine

### ISSUE THREAD

**Issue by nicolacandussi** [google/highway#1439]
In some situations (for example, rendering) it's necessary to compute the sine and cosine of a value at the same time. I was wondering if implementing such a function among the math routines provided by Highway would give any performance benefits.

**Comment by jan-wassenberg** [comment]
Thanks for pointing that out. Indeed looks like SinCos would be useful. If you're able to send a pull request, I'd be happy to review and maintain it :) Looks like the license is compatible and there are no exotic instructions, so it's quite a mechanical translation. One could search for the x86 intrinsics used there, inside our x86_128-inl.h, to find the corresponding Highway op name (see also the [reference](https://github.com/google/highway/blob/master/g3doc/quick_reference.md)).

One could also check whether SLEEF has an even more efficient version of SinCos.

**Comment by jan-wassenberg** [comment]
Closing now that this is [added](https://github.com/google/highway/commit/f64cd04aad49f13f3a7b6314075e66359ab57671) - thanks!
