### ISSUE TITLE
TableLookupLanes, TwoTablesLookupLanes, and SetTableIndices enhancements for I8/U8 vectors on RVV

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1440]
One limitation of the SetTableIndices and IndicesFromVec operations on the HWY_RVV target is that it is possible for `Lanes(D())` to be greater than `LimitsMax<MakeUnsigned<TFromD<D>>>()` on the HWY_RVV target if `sizeof(TFromD<D>)` is equal to 1.

Another limitation of the SetTableIndices and IndicesFromVec operations on the HWY_RVV target is that it takes two vuint16m8_t vectors to hold the indices for a full vint8m8_t or vuint8m8_t vector on RVV.

Another limitation is that implementing the SetTableIndices and IndicesFromVec operations for full vint8m8_t or vuint8m8_t vectors with uint16_t indices on the HWY_RVV case either requires support for tuples or requires an extra parameter for the high indices.

Here are the additional functions and typedefs that can be added to deal with the limitations of SetTableIndices and IndicesFromVec on HWY_RVV:
- **IndexTFromD**&lt;D&gt; - The smallest unsigned integer type for which `LimitsMax<MakeUnsigned<TFromD<D>>>() >= MaxLanes(DFromV<Vec<D>>()) - 1` and `sizeof(IndexTFromD<D>) >= sizeof(TFromD<D>)` are both true
- **LoIndicesFromD**&lt;D&gt; - The type for the low indices for a vector of type `Vec<D>`  if `MaxLanes(DFromV<Vec<D>>()) == HWY_MAX_BYTES` and `MaxLanes(DFromV<Vec<D>>()) > LimitsMax<MakeUnsigned<TFromD<D>>>()` are both true, and IndicesFromD&lt;D&gt; otherwise
- **HiIndicesFromD**&lt;D&gt; - The type for the high indices for a vector of type `Vec<D>` if `MaxLanes(DFromV<Vec<D>>()) == HWY_MAX_BYTES` and `MaxLanes(DFromV<Vec<D>>()) > LimitsMax<MakeUnsigned<TFromD<D>>>()` are both true, and an empty unused type which can be passed into SetTableIndices, IndicesFromVec, TableLookupLanes, and TwoTablesLookupLanes overloads that take two index parameters otherwise
- LoIndicesFromD&lt;D&gt;&amp; **SetTableIndices**(D d, const TI* idx, HiIndicesFromD&lt;D&gt;&amp; hi_indices) - Loads indices from `idx`, returning the low indices in the return value and returning the high indices in `hi_indices`
- LoIndicesFromD&lt;D&gt;&amp; **IndicesFromVectors**(D d, VI v_hi_idx, VI v_lo_idx, HiIndicesFromD<D>& hi_indices) - prepares for TableLookupLanes operations that have HiIndicesFromD overloads with integer indices in v_hi_idx and v_lo_idx, returning the low indices in the return value and returning the high indices in `hi_indices`
- V **TableLookupLanes**(V v, HiIndicesFromD&lt;DFromV&lt;V&gt;&gt; hi_indices, LoIndicesFromD&lt;DFromV&lt;V&gt;&gt; lo_indices) - does a table lookup using two index vectors
- V **TwoTablesLookupLanes**(V a, V b, HiIndicesFromD&lt;DFromV&lt;V&gt;&gt; hi_indices, LoIndicesFromD&lt;DFromV&lt;V&gt;&gt; lo_indices) - does a table lookup using two tables and two index vectors

Should the extra overloads that take an extra parameter for the high indices be added for the SetTableIndices, TableLookupLanes, and TwoTablesLookupLanes operations to work around the limitations that are there on the HWY_RVV target?

**Comment by jan-wassenberg** [comment]
Thanks for starting the discussion. I agree it will be good to settle the semantics of this.

Currently, we have TableLookupLanes for any type, and we have promised backwards compatibility. Perhaps HiIndices could be an optional (third) parameter. But I have the feeling that because RVV is the only one that potentially requires this, code will generally not be written to correctly handle high indices, and so we'd actually be reducing portability by introducing/encouraging a stumbling block.

How about an alternative fix, which is to update the documentation saying that results are implementation defined for indices >= Lanes(d) *or* >= `LimitsMax<MakeUnsigned<T>>()`?

And then we could update the implementations of `Interleave*` and `LoadDup128` to either avoid 8-bit lookups or extend to 16-bit. I think those are the only remaining users of 8-bit lookups. What do you think?

**Comment by johnplatts** [comment]
> Thanks for starting the discussion. I agree it will be good to settle the semantics of this.
> 
> Currently, we have TableLookupLanes for any type, and we have promised backwards compatibility. Perhaps HiIndices could be an optional (third) parameter. But I have the feeling that because RVV is the only one that potentially requires this, code will generally not be written to correctly handle high indices, and so we'd actually be reducing portability by introducing/encouraging a stumbling block.
> 
> How about an alternative fix, which is to update the documentation saying that results are implementation defined for indices >= Lanes(d) _or_ >= `LimitsMax<MakeUnsigned<T>>()`?
> 
> And then we could update the implementations of `Interleave*` and `LoadDup128` to either avoid 8-bit lookups or extend to 16-bit. I think those are the only remaining users of 8-bit lookups. What do you think?

I think that updating the documentation to stating that the results of TableLookupLanes are implementation defined for indices >= Lanes(d) _or_ >= `LimitsMax<MakeUnsigned<T>>()` is a good point.

8-bit indices are sufficient for LoadDup128 as only the first `HWY_MIN(Lanes(d), 16)` lanes of `loaded` are accessed by the TableLookupLanes in LoadDup128.

Also fixing RVV InterleaveLower and InterleaveUpper to avoid TableLookupLanes with uint8_t indices would be a good point.

**Comment by jan-wassenberg** [comment]
Thanks! I'll update the documentation. Good point about LoadDup128, adding a comment on that. The original block-based `Broadcast` is also affected. I don't yet have a good idea how to fix that on RVV without resorting to 16-bit indices.

BTW we can consider adding a HWY_RVV_LE256 target for up to 256-bit vectors, such that their max length even with LMUL=8 does not exceed 2048 bit and thus indices <= 255. But that's still too much for TwoTableLookupLanes and plenty of HW actually has 512 bit already, so the usefulness of this seems very questionable.

**Comment by jan-wassenberg** [comment]
I think we can close now that this is documented? Please let me know if you'd like any further action here.
