### ISSUE TITLE
Add SlideUpLanes, SlideDownLanes, CompressLoAndConcatHi, and CombineFirstNOfLoWithHi operations

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1442]
Here are the additional operations that I would like to add to Highway:
- **SlideUpLanes**(D d, VFromD&lt;D&gt; v, size_t N) - equivalent to RVV vslideup (detail::SlideUp)
- **SlideDownLanes**(D d, VFromD&lt;D&gt; v, size_t N) - equivalent to RVV vslidedown (detail::SlideDown)
- **CompressLoAndConcatHi**(D d, VFromD&lt;D&gt; hi, VFromD&lt;D&gt; lo, MFromD&lt;D&gt; mask) - equivalent to SVE svsplice (detail::Splice)
- **CombineFirstNOfLoWithHi**(D d, VFromD&lt;D&gt; hi, VFromD&lt;D&gt; lo, size_t N) - equivalent to detail::SlideUp(hi, lo, N) on RVV

In the case where `Lanes(d) * sizeof(TFromD<D>) > 16 is true` (which is possible on AVX2/AVX3/RVV/SVE/WASM_EMU256), the above operations cross block boundaries and operate on the first `Lanes(d)` lanes of each vector.

`SlideUpLanes(d, v, N)` is equivalent to doing a `TwoTableLookupLanes(d, v, Zero(d), idx)` with the following indices if `N < Lanes(d)` is true:
`{ (-N) & idx_mask, (-N + 1) & idx_mask, (-N + 2) & idx_mask, ... }` (where `idx_mask` is equal to `2 * Lanes(d) - 1`)

`SlideDownLanes(d, v, N)` is equivalent to doing a `TwoTableLookupLanes(d, v, Zero(d), idx)` with the following indices if `N < Lanes(d)` is true:
`{ N, N + 1, N + 2, ... }`

`CombineFirstNOfLoWithHi(d, hi, lo, N)` is equivalent to `IfThenElse(FirstN(d, N), lo, SlideUpLanes(d, hi, N))`.

`CompressLoAndConcatHi(d, hi, lo, mask)` is equivalent to `CombineFirstNOfLoWithHi(d, hi, Compress(lo, mask), CountTrue(mask))` (and `detail::Splice(hi, lo, mask)` on SVE targets).

Should SlideUpLanes and SlideDownLanes have implementation-defined behavior in the case where `N >= Lanes(d)`, or should SlideUpLanes and SlideDownLanes require returning `Zero(d)` in the case where `N >= Lanes(d)`?

**Comment by jan-wassenberg** [comment]
Hi @johnplatts , thanks for proposing these, the Slide operations sound useful. We could also add Slide1Up/Down, that might allow better codegen especially on AVX2/3 without AVX3_DL.

Requiring N (possibly better to rename to lanes to avoid confusion with the other N) < Lanes() seems reasonable.

For the other two operations, I have mixed feelings - generally it is nice to cover instructions where possible without major performance cliffs across platforms, but these seem a bit exotic/rare. Do you have a use case in mind? Also, we at one point renamed Lo/Hi to Lower/Upper, would be nice to keep that for consistency.

**Comment by johnplatts** [comment]
Added SlideUpLanes, SlideDownLanes, Slide1Up, Slide1Down, SlideUpBlocks, and SlideDownBlocks in pull request #1496

**Comment by jan-wassenberg** [comment]
Thank you for implementing those! Closing.
