### ISSUE TITLE
AArch64 SVE compilation fails when bfloat16 is not enabled

### ISSUE THREAD

**Issue by kleisauke** [google/highway#1443]
Using this test script:
```bash
ssh -i /path/key.pem ec2-user@hostname

sudo dnf install -y git cmake clang

export CC="clang-15"
export CXX="clang++-15"
export CFLAGS="-march=armv8.2-a+sve"
export CXXFLAGS="-march=armv8.2-a+sve"

# Fix compilation
# export CFLAGS="-march=armv8.2-a+sve+bf16"
# export CXXFLAGS="-march=armv8.2-a+sve+bf16"

# Optionally, force HWY_SVE_256
# export CFLAGS+=" -msve-vector-bits=256"
# export CXXFLAGS+=" -msve-vector-bits=256"

git clone https://github.com/google/highway.git
cd highway
# Fix compilation
# sed -i '/bfloat16 is not included in FOREACH/,+1d' hwy/ops/arm_sve-inl.h
cmake -S . -B build \
  -DCMAKE_INSTALL_PREFIX="/usr" \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_TESTING=ON
cmake --build build -- -j$(nproc)
sudo cmake --install build
ctest --test-dir build -j$(nproc) --output-on-failure
```

Fails to compile on Amazon Linux 2023 arm64 (c7g.8xlarge instance) with Clang 15 when `+bf16` is omitted from the `-march` option.

To fix this, I think these 2 lines needs to be guarded with `#ifdef __ARM_FEATURE_SVE_BF16`:
https://github.com/google/highway/blob/46fb57d4bafc869f1261e6463ead7d002f330795/hwy/ops/arm_sve-inl.h#L433-L434
https://github.com/google/highway/blob/46fb57d4bafc869f1261e6463ead7d002f330795/hwy/ops/arm_sve-inl.h#L407-L408

Full compilation logs: https://gist.github.com/kleisauke/a8deda6969004453fda744895514bab9
(there is also [a failing test](https://gist.github.com/kleisauke/a8deda6969004453fda744895514bab9#file-test-log), let me know if you want to track that in a separate issue)

**Comment by jan-wassenberg** [comment]
Thanks for confirming and raising the other issue :)
