### ISSUE TITLE
error: #error Use the "-maltivec" flag to enable PowerPC AltiVec support

### ISSUE THREAD

**Issue by malaterre** [google/highway#1449]
I can no longer compile highway on default ppc32/ppc64 setup:

```
$ git checkout master 
$ mkdir bin32 && cd bin32 
$ cmake -DHWY_SYSTEM_GTEST:BOOL=1 .. && make -j16
[...]
[  2%] Building CXX object CMakeFiles/hwy.dir/hwy/per_target.cc.o
In file included from /home/malat/highway/hwy/ops/ppc_vsx-inl.h:27,
                 from /home/malat/highway/hwy/highway.h:407,
                 from /home/malat/highway/hwy/per_target.cc:21,
                 from /home/malat/highway/hwy/foreach_target.h:233,
                 from /home/malat/highway/hwy/per_target.cc:20:
/usr/lib/gcc/powerpc-linux-gnu/12/include/altivec.h:34:2: error: #error Use the "-maltivec" flag to enable PowerPC AltiVec support
   34 | #error Use the "-maltivec" flag to enable PowerPC AltiVec support
      |  ^~~~~
In file included from /home/malat/highway/hwy/highway.h:23:
/home/malat/highway/hwy/base.h:81:28: error: target attribute or pragma changes AltiVec ABI
   81 | #define HWY_PRAGMA(tokens) _Pragma(#tokens)
      |                            ^~~~~~~
/home/malat/highway/hwy/base.h:123:32: note: in expansion of macro 'HWY_PRAGMA'
  123 |   HWY_PRAGMA(GCC push_options) HWY_PRAGMA(GCC target targets_str)
      |                                ^~~~~~~~~~
/home/malat/highway/hwy/ops/set_macros-inl.h:541:3: note: in expansion of macro 'HWY_PUSH_ATTRIBUTES'
  541 |   HWY_PUSH_ATTRIBUTES(HWY_TARGET_STR) \
      |   ^~~~~~~~~~~~~~~~~~~
```

**Comment by jan-wassenberg** [comment]
Thanks for letting us know. Looks like [2c8147a](https://github.com/google/highway/commit/2c8147a86a5b6f20e23b5448779c122fe241ad6a) (March 13) is only adding a NEON target, I don't see anything that would affect Altivec.

Is it possible this might be related to a compiler update around that time? We do depend on compiler support for enabling vector code without -m flags, and it is possible that regressed.

**Comment by johnplatts** [comment]
> Thanks for letting us know. Looks like [2c8147a](https://github.com/google/highway/commit/2c8147a86a5b6f20e23b5448779c122fe241ad6a) (March 13) is only adding a NEON target, I don't see anything that would affect Altivec.
> 
> Is it possible this might be related to a compiler update around that time? We do depend on compiler support for enabling vector code without -m flags, and it is possible that regressed.

Pull request #1450, which updates HWY_ATTAINABLE_PPC to only include HWY_PPC8/HWY_PPC9/HWY_PPC10 on PowerPC if the `__ALTIVEC__` macro is defined, should fix the compilation errors on PowerPC.

**Comment by jan-wassenberg** [comment]
Thanks for bisecting! On a closer look, I see we did indeed [change PPC](https://github.com/google/highway/commit/2c8147a86a5b6f20e23b5448779c122fe241ad6a#diff-bfe5635b4f0b39e741ed4ce8f585674994a3434568c7caa471c0e7be9a7938c8R565) in that PR, without mentioning in the commit message :(

Thank you @johnplatts for fixing this!
