### ISSUE TITLE
vqsort_128a.cc.o build error for aarch64 with gcc

### ISSUE THREAD

**Issue by Ray-V** [google/highway#1460]
Built to commit f5f35e144c6e45beeb3caa28c6b1ee460705a86b
```
CXX=aarch64-linux-gnu-g++  cmake -DBUILD_TESTING=no -DBUILD_SHARED_LIBS=yes ..
make

..
[ 18%] Linking CXX shared library libhwy.so
[ 18%] Built target hwy
[ 21%] Building CXX object CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o
In file included from highway/hwy/contrib/sort/vqsort_128a.cc:23,
                 from highway/hwy/foreach_target.h:152,
                 from highway/hwy/contrib/sort/vqsort_128a.cc:20:
highway/hwy/contrib/sort/traits128-inl.h: In member function ‘hwy::N_NEON::Vec<D> hwy::N_NEON::detail::Traits128<Base>::SortPairsReverse4(D, hwy::N_NEON::Vec<D>) const’:
highway/hwy/contrib/sort/traits128-inl.h:508:36: warning: requested alignment 64 is larger than 16 [-Wattributes]
  508 |     alignas(64) uint64_t kIndices[8] = {7, 7, 5, 5, 5, 5, 7, 7};
      |                                    ^
In file included from highway/hwy/contrib/sort/vqsort_128a.cc:23:
highway/hwy/contrib/sort/traits128-inl.h: In member function ‘hwy::N_NEON_WITHOUT_AES::Vec<D> hwy::N_NEON_WITHOUT_AES::detail::Traits128<Base>::SortPairsReverse4(D, hwy::N_NEON_WITHOUT_AES::Vec<D>) const’:
highway/hwy/contrib/sort/traits128-inl.h:508:36: warning: requested alignment 64 is larger than 16 [-Wattributes]
  508 |     alignas(64) uint64_t kIndices[8] = {7, 7, 5, 5, 5, 5, 7, 7};
      |                                    ^
In file included from highway/hwy/contrib/sort/vqsort.h:27,
                 from highway/hwy/contrib/sort/vqsort_128a.cc:16:
highway/hwy/base.h: In function ‘void hwy::N_NEON::detail::BaseCase(D, Traits, T*, size_t, T*) [with D = hwy::N_NEON::Simd<long unsigned int, 2, 0>; Traits = hwy::N_NEON::detail::SharedTraits<hwy::N_NEON::detail::Traits128<hwy::N_NEON::detail::OrderAscending128> >; T = long unsigned int]’:
highway/hwy/base.h:883:16: error: inlining failed in call to always_inline ‘size_t hwy::Num0BitsAboveMS1Bit_Nonzero32(uint32_t)’: target specific option mismatch
  883 | HWY_API size_t Num0BitsAboveMS1Bit_Nonzero32(const uint32_t x) {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from highway/hwy/contrib/sort/vqsort_128a.cc:24,
                 from highway/hwy/foreach_target.h:152,
                 from highway/hwy/contrib/sort/vqsort_128a.cc:20:
highway/hwy/contrib/sort/vqsort-inl.h:465:41: note: called from here
  465 |       32 - Num0BitsAboveMS1Bit_Nonzero32(static_cast<uint32_t>(num_keys - 1));
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/hwy_contrib.dir/build.make:76: CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/hwy_contrib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
The build failure is caused by the  
`#define HWY_TARGET_STR "arch=armv8-a+crypto"`  
in hwy/ops/set_macros-inl.h - commit f8a6ea58387c9d6aafc4a0cb32c53d4b79d85254.

The build succeeds if this is changed to the value set in the compiler  
`#define HWY_TARGET_STR "arch=armv8-a+crc"`  
although still with the warnings.

**Comment by jan-wassenberg** [comment]
Thanks for reporting the issue. What we're trying to enable there is the AES instructions - is that implied by +crc?

From a [quick experiment](https://gcc.godbolt.org/z/djchz11z8), it looks the arch= works with recent GCC. Which version are you using?

**Comment by Ray-V** [comment]
I'm using my own compiler optimised for RPi3, which has --with-arch=armv8-a+crc and --with-cpu=cortex-a53 set.

Building to commit 8aa5886.  
Using the gcc-12.2 compiler from developer.arm.com, which doesn't have pre-set values for cpu, arch, or fpu,  
```
CXX=aarch64-none-linux-gnu-g++ cmake -DBUILD_TESTING=no -DBUILD_SHARED_LIBS=yes ..
make
```
builds ok, but
```
CXX="aarch64-none-linux-gnu-g++ -mcpu=cortex-a53" cmake -DBUILD_TESTING=no -DBUILD_SHARED_LIBS=yes ..
make
```
fails with the 'target specific option mismatch' error.

So the fixed value of arch= is incompatible with that cpu setting.

**Comment by Ray-V** [comment]
> Are there any predefined macros we could check to determine whether the compiler was preconfigured with -march/mcpu, or those have been explicitly set?

Not that I know of.

> Alternatively, it sounds like it could be useful to detect such cases where the compiler isn't going to be able to compile for all targets. If so, then we should not enable all (this happens in the lines #if HWY_ARCH_ARM_A64 && HWY_HAVE_RUNTIME_DISPATCH #define HWY_ATTAINABLE_NEON (HWY_NEON | HWY_NEON_WITHOUT_AES) )

In detect_targets.h, HWY_BASELINE_NEON is defined to include HWY_NEON depending on whether __ARM_FEATURE_AES is defined - in the case of my compiler, not:
```
#if defined(__ARM_FEATURE_AES)
#define HWY_BASELINE_NEON (HWY_NEON | HWY_NEON_WITHOUT_AES)
#else
#define HWY_BASELINE_NEON (HWY_NEON_WITHOUT_AES)
```

and HWY_HAVE_RUNTIME_DISPATCH is set because,  
a] from detect_compiler-arch.h, HWY_ARCH_ARM == 1:
```
// Any *supported* version of Arm, i.e. 7 or later
#if HWY_ARCH_ARM_A64 || HWY_ARCH_ARM_V7
#define HWY_ARCH_ARM 1
#else
#define HWY_ARCH_ARM 0
#endif
```
and b]
```
// On Arm/PPC, currently only GCC does, and we require Linux to detect CPU
// capabilities.
#elif (HWY_ARCH_ARM || HWY_ARCH_PPC) && HWY_COMPILER_GCC_ACTUAL && \
    HWY_OS_LINUX && !defined(TOOLCHAIN_MISS_SYS_AUXV_H)
#define HWY_HAVE_RUNTIME_DISPATCH 1
```

so couldn't
```
#if HWY_ARCH_ARM_A64 && HWY_HAVE_RUNTIME_DISPATCH
#define HWY_ATTAINABLE_NEON (HWY_NEON | HWY_NEON_WITHOUT_AES)
#elif HWY_ARCH_ARM  // static dispatch, or HWY_ARCH_ARM_V7
#define HWY_ATTAINABLE_NEON (HWY_BASELINE_NEON)
#else
#define HWY_ATTAINABLE_NEON 0
#endif
```
be rewritten as
```
#if ( HWY_ARCH_ARM_A64 && HWY_HAVE_RUNTIME_DISPATCH ) || HWY_ARCH_ARM
#define HWY_ATTAINABLE_NEON (HWY_BASELINE_NEON)
#else
#define HWY_ATTAINABLE_NEON 0
#endif
```
to use the already defined HWY_BASELINE_NEON ?  
That works for me for aarch64 and arm

**Comment by jan-wassenberg** [comment]
Checking __ARM_FEATURE_AES at compile time is the static-dispatch model; it sets the baseline required by each CPU.
What we're aiming for is that HWY_ATTAINABLE* includes everything the compiler can generate code for, including CPUs with capabilities beyond the baseline (here: AES). That is the dynamic dispatch model.

It's unfortunate there seems to be no way to detect that the compiler is limited in its ability to generate code. Then I'd suggest you use one of the workarounds, defining TOOLCHAIN_MISS_SYS_AUXV_H and/or HWY_COMPILE_ONLY_STATIC, given that you seem to be using the static-dispatch model :)

**Comment by jan-wassenberg** [comment]
Hopefully this workaround works for you? Please reopen if you'd like to continue the discussion.
