### ISSUE TITLE
ppc32: Measurement failed: overhead 17157640784 < 17157669744

### ISSUE THREAD

**Issue by malaterre** [google/highway#1468]
I am seeing some odd results on ppc32:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=powerpc&ver=1.0.5%7Egit20230612.46fb57d-2&stamp=1686759192&raw=0

```
make[1]: Entering directory '/<<PKGBUILDDIR>>'
obj-*/examples/hwy_benchmark

F(x)->2*x^2, F(3) = 18.0
------------------------ PPC8
       dot:   3456: 387740103.111 (+/- 9188154.444)
     delta:   3456: 849424232.296 (+/- 2487350.046)
dh_install
```

**Comment by jan-wassenberg** [comment]
Interesting. Would you mind changing both `#if HWY_ARCH_PPC && defined(__GLIBC__)` in timer-inl.h to `#if 0`? Then we will use clock_gettime instead of mfspr. If that fixes it, then we have narrowed down the cause to mfspr.

**Comment by jan-wassenberg** [comment]
Thanks for experimenting :) clock_gettime is definitely the safer option. I am not sure what this mfspr timer is and what exactly it requires, but only using it on ppc64 seems very reasonable.
