### ISSUE TITLE
Gracefully exit when the minimum instructions set is not found

### ISSUE THREAD

**Issue by eclipseo** [google/highway#147]
I'm trying to package highway for Fedora Linux, and it has the following requirements:

> Libraries packaged in Fedora may require ISA extensions, however
> any packaged application must not crash on any officially supported
> architecture, either by providing a generic fallback implementation OR
> by cleanly exiting when the requisite hardware support is unavailable.

However when building the package on an old system, I get the following error:

> /usr/bin/cmake -D TEST_TARGET=hwy_test -D TEST_EXECUTABLE=/builddir/build/BUILD/highway-0.11.1/x86_64-redhat-linux-gnu/tests/hwy_test -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/builddir/build/BUILD/highway-0.11.1/x86_64-redhat-linux-gnu -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=hwy_test_TESTS -D CTEST_FILE=/builddir/build/BUILD/highway-0.11.1/x86_64-redhat-linux-gnu/hwy_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=60 -D TEST_XML_OUTPUT_DIR= -P /usr/share/cmake/Modules/GoogleTestAddTests.cmake
> CMake Error at /usr/share/cmake/Modules/GoogleTestAddTests.cmake:77 (message):
>   Error running test executable.
>     Path: '/builddir/build/BUILD/highway-0.11.1/x86_64-redhat-linux-gnu/tests/hwy_test'
>     Result: Illegal instruction
>     Output:

Fedora officially support SSE2, not SSE4, as a minimum. Would it be possible to gracefully exit when the minimum instructions set is not found?

Thank you.

**Comment by jan-wassenberg** [comment]
Hi, thanks for reporting this! The intention is definitely to gracefully fall back to a generic fallback implementation.

The HWY_SCALAR fallback might be disabled if we compile with say -msse4 (targets.h could then consider HWY_SCALAR superseded and only generate sse4, which would crash when run on an old enough CPU). Our CMake file does not specify such a flag, though.

It's also possible that the builtin_trap in hwy::Abort (called when a test fails) would manifest as SIGILL, but it's surprising that we do not see any other output if that were the case.

Any chance you could run this in a debugger to see where exactly this is happening?

FYI tests/hwy_test has moved to highway_test in 0.12.0.

**Comment by eclipseo** [comment]
Sadly I can't test it myself as I don't have an old system laying around. It was reported to me by another user.
Could setting DHWY_COMPILE_ALL_ATTAINABLE help?

**Comment by jan-wassenberg** [comment]
> Could setting DHWY_COMPILE_ALL_ATTAINABLE help?

Yes, that would prevent disabling the fallback, if that is indeed the problem.

**Comment by eclipseo** [comment]
This has been worked out downstream with bug reviewer.
