### ISSUE TITLE
x86: HwyMathTestGroup/HwyMathTest.TestAllAtanh/EMU128 failure

### ISSUE THREAD

**Issue by malaterre** [google/highway#1488]
I see a tst failure on Debian/x86 (32bits) on the floating point comparison:

Truncated:

```
[...]
814/894 Test #814: HwyMathTestGroup/HwyMathTest.TestAllAtanh/EMU128  # GetParam() = 2305843009213693952 ...................................Subprocess aborted***Exception:   0.03 sec
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = HwyMathTestGroup/HwyMathTest.TestAllAtanh/EMU128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyMathTestGroup/HwyMathTest
[ RUN      ] HwyMathTestGroup/HwyMathTest.TestAllAtanh/EMU128
f32x4: Atanh max_ulp 2
f32x2: Atanh(0.000000) expected 0.000000 actual 0.000000 ulp 5.20158e+08 max ulp 4
f32x2: Atanh(0.000000) expected 0.000000 actual 0.000000 ulp 5.20424e+08 max ulp 4
f32x2: Atanh(0.000000) expected 0.000000 actual 0.000000 ulp 5.20691e+08 max ulp 4
f32x2: Atanh(0.000000) expected 0.000000 actual 0.000000 ulp 5.20957e+08 max ulp 4
f32x2: Atanh(0.000000) expected 0.000000 actual 0.000000 ulp 5.21223e+08 max ulp 4
[...]
```
ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=i386&ver=1.0.5%7Egit20230620.ed184dc-2&stamp=1687332732&raw=0

**Comment by nicolacandussi** [comment]
TestAtan2 was giving a loss of precision warning in the following code:

const Vec<D> tolerance = Set(d, 1E-5);

so I changed to 

const Vec<D> tolerance = Set(d, T(1E-5));

Might that be the cause of the issue?

**Comment by nicolacandussi** [comment]
This is the PR, but looking closely, I doubt it has anything to do with the issue you are experiencing:

https://github.com/google/highway/pull/1448

**Comment by jan-wassenberg** [comment]
@malaterre yes, the code looks good. Let's run it in [Godbolt](https://gcc.godbolt.org/z/35W4b6fv3).
Interestingly, the compiler manages to see through/optimize out the Log1p (by running it at compile time), impressive. If we want to ensure the code actually runs, see https://gcc.godbolt.org/z/vfsdvbz3W.

Looks like it works on both gcc 13 and clang-16 with -m32?

**Comment by jan-wassenberg** [comment]
I was able to repro this on GCC 12.2 with HWY_SCALAR. HWY_EMU128 only comes up if we set `-DHWY_BROKEN_EMU128=0`, right? GCC <12.3 did have several bugs which is why we introduced this flag.

Appears to be another wacky compiler bug, because 1.0f == 1.0f was false, and adding a noinline 'fixes' it at least for the scalar target.

**Comment by jan-wassenberg** [comment]
Thank you for filing the bug!

**Comment by jan-wassenberg** [comment]
Thanks, good point. Will provide an opt-out, and also gracefully fail (disable the test with a warning) if the opt-in isn't given.
