### ISSUE TITLE
API changes for variable vectors

### ISSUE THREAD

**Issue by jan-wassenberg** [google/highway#15]
Highway was designed with an eye towards variable vectors, and porting to RVV is going fairly smoothly, but a few changes are required:

- V VecFromMask(M) does not have enough information to identify V from M, which is a built-in type shared between several V (for example, both V=vuint32m1_t and vfloat32m1_t use M=vbool32_t). We can add VecFromDMask(D, M) to resolve this, and deprecate VecFromMask.
- uint64_t BitsFromMask(M) no longer works because large vectors can have more than 64 lanes. This will be deprecated (use CountTrue instead).
- SumsOfU8x8 is rather niche, and hard to emulate. Also proposed for deprecation.

Please let us know if you have any concerns about these proposals, or other suggestions.

**Comment by jan-wassenberg** [comment]
(Renamed VecFromDMask to VecFromMask, we can just overload.)

**Comment by jan-wassenberg** [comment]
SetTableIndices currently has an int* parameter but this is a poor fit for 64-bit lanes. Better would be to use an unsigned type of the same size. Similarly, the second argument to TableLookupLanes should be unsigned.

**Comment by jan-wassenberg** [comment]
RVV shifts use only the low log2(lanesize) bits whereas Highway defines larger shift counts as zeroing the result.

**Comment by veluca93** [comment]
> RVV shifts use only the low log2(lanesize) bits whereas Highway defines larger shift counts as zeroing the result.

By the way, I think that's also true on other architectures - I remember that one of x86 and arm in scalar mode only uses the lowest <whatever> bits, not sure in SIMD.

**Comment by jan-wassenberg** [comment]
> I remember that one of x86 and arm in scalar mode only uses the lowest bits, not sure in SIMD.

Yes, that is true of scalar x86, but not of x86 SIMD. From what I could see in ARM's documentation, there is no masking of the SIMD shift counts.

**Comment by veluca93** [comment]
> > I remember that one of x86 and arm in scalar mode only uses the lowest bits, not sure in SIMD.
> 
> Yes, that is true of scalar x86, but not of x86 SIMD. From what I could see in ARM's documentation, there is no masking of the SIMD shift counts.

Then it's not quite true that hwy defines larger shift counts as zeroing, at least not in Scalar (https://github.com/google/highway/blob/master/hwy/ops/scalar-inl.h#L139)

**Comment by jan-wassenberg** [comment]
Right, the documentation says "ARM requires the count be less than the lane size." but below that "which is zero when b[i] >= sizeof(T)*8". The latter was true of x86 vsl/r, but not scalar. Will change documentation to say larger counts cause implementation-defined results.

**Comment by jan-wassenberg** [comment]
All of the above are implemented except

> SetTableIndices currently has an int* parameter but this is a poor fit for 64-bit lanes. Better would be to use an unsigned type of the same size. Similarly, the second argument to TableLookupLanes should be unsigned.

Another observation is that the U32FromU8 contract does not scale for >64 byte vectors, so we'll mark this as deprecated. The preferred approach is PromoteTo(PromoteTo()).

**Comment by jan-wassenberg** [comment]
These are done, closing.
