### ISSUE TITLE
VQSortStatic doesn't work without VQSort

### ISSUE THREAD

**Issue by Mousius** [google/highway#1500]
Because https://github.com/google/highway/blob/master/hwy/contrib/sort/vqsort-inl.h includes https://github.com/google/highway/blob/master/hwy/contrib/sort/vqsort.h, it means that the exported functions are still expected in the eventual binary. It could be a simple as having a macro defined and ifdef surrounding https://github.com/google/highway/blob/79dd583b0f93db0f35830563b7c2647adab392ec/hwy/contrib/sort/vqsort.h#L39-L155 but I don't know if there's a better solution which unpicks the dependency better.

**Comment by jan-wassenberg** [comment]
Ah, thanks for bringing this up. I think the vqsort.h was actually no longer required, prior to VQSortStatic.
It may be possible to split out SortAscending into a separate header (sort_order.h) that both vqsort-inl and vqsort.h include. Will look into this soon :)
