### ISSUE TITLE
AVX512 IfThenElse implementation question

### ISSUE THREAD

**Issue by ag01** [google/highway#1510]
Is there any specific reason Highway uses _mm512_mask_mov_X versus _mm512_mask_blend_X?

According to the Intel Intrinsics guide, blend has a lower latency on Ice Lake compared to mov (and the same latency for other microarchitectures). And blend has the same throughput versus mov.

(Though the Intel guide looks like it has incorrect data for Sapphire Rapids)

**Comment by johnplatts** [comment]
Clang 5 and later and GCC 11 and later actually do generate a vpblendmb instruction for the _mm512_mask_mov_X instruction when optimizations are enabled according to https://www.godbolt.org/z/e91aP5a44.

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts, good to know.
@ag01, I understand you are using earlier GCC and uops.info also says 3 cycle latency on ICL. Seems like we could explicitly use blend then. Would you like to send a pull request for that?

**Comment by ag01** [comment]
Thanks @johnplatts @jan-wassenberg  - i'll raise a PR for IfThenElse.

In the IfThenElseZero case there's no maskz_* variant for blend (and it looks like latest Clang/GCC still prefer using the mov instead of zeroing a vector register and using blend), so I shall keep that implementation the same
