### ISSUE TITLE
`_mm_packus_epi32` use attempted on SSE4 and older

### ISSUE THREAD

**Issue by risicle** [google/highway#1538]
In 1.0.4 and master, at several points in `x86_128-inl.h`, `_mm_packus_epi32` is used in a "fallback" path - but `PACKUSDW` is only added in SSE4.1, and indeed `_mm_packus_epi32` is only defined in `smmintrin.h`. Example: the specialization of `Pow2` for emulating 16-bit shifts.

I think it's easily confused with `_mm_packs_epi32`, which is defined in `emmintrin.h` and goes all the way back to SSE2.

**Comment by johnplatts** [comment]
PACKUSDW (`_mm_packus_epi32`) does a int32_t to uint16_t demotion, which is equivalent to `HWY_MIN(HWY_MAX(x, 0), 65535)`, where `x` is the value of the source int32_t lane.

PACKSSDW (`_mm_packs_epi32`) does an int32_t to int16_t demotion, which is equivalent to `HWY_MIN(HWY_MAX(x, -32768), 32767)`, where `x` is the value of the source int32_t lane.

`_mm_packus_epi32(a, b)` is equivalent to NEON `vcombine_u16(vqmovun_s32(a), vqmovun_s32(b))` or Altivec `vec_packsu((__vector signed int)a, (__vector signed int)b)`.

The use of the _mm_packus_epi32 intrinsic is okay on the HWY_SSE4 target as the HWY_SSE4 target requires support for both SSE4.1 and SSE4.2 and as the PACKUSDW instruction is available on SSE4.1.

**Comment by risicle** [comment]
Sure, but it appears to be trying to use it as part of variable shifts even for the baseline x86_64 target.

**Comment by johnplatts** [comment]
> Sure, but it appears to be trying to use it as part of variable shifts even for the baseline x86_64 target.

Here is the implementation of detail::Pow2 for SSE2/SSSE3/SSE4 in x86_128-inl.h:
https://github.com/google/highway/blob/1ccdb54e9502a27e4fac30f1b273957efd8d163b/hwy/ops/x86_128-inl.h#L6318-L6377

Note that the detail::Pow2 implementation above (which is used to implement variable shifts on SSE2/SSSE3/SSE4) only calls _mm_packus_epi32 on the SSE4 target (but not the SSE2 or SSSE3 targets).

**Comment by johnplatts** [comment]
Here are the other functions in x86_128-inl.h that use the _mm_packus_epi32 intrinsic on the SSE4/AVX2/AVX3 targets:
https://github.com/google/highway/blob/1ccdb54e9502a27e4fac30f1b273957efd8d163b/hwy/ops/x86_128-inl.h#L5860-L5882
https://github.com/google/highway/blob/1ccdb54e9502a27e4fac30f1b273957efd8d163b/hwy/ops/x86_128-inl.h#L7140-L7162
https://github.com/google/highway/blob/1ccdb54e9502a27e4fac30f1b273957efd8d163b/hwy/ops/x86_128-inl.h#L7351-L7376

Note that the above functions do not call _mm_packus_epi32 on SSE2/SSSE3 targets.

**Comment by risicle** [comment]
Absolutely - this does look like it's fixed on master, I must have been looking at an old checkout of master where it's doing the same thing as 1.0.4, i.e.: https://github.com/google/highway/blob/46e365d6770f5d7a4240d8ac9d8e928a520478ea/hwy/ops/x86_128-inl.h#L5137-L5152

**Comment by jan-wassenberg** [comment]
Thank you @risicle for reaching out, and @johnplatts for confirming the current code is fine.

FYI there will be a release soon, in perhaps a week or two.
