### ISSUE TITLE
Help with creation/conversion of masks

### ISSUE THREAD

**Issue by fbarbari** [google/highway#1580]
Hello everyone. First of all, really nice library!
I ended up writing an issue because I couldn't find a solution in the documentation or the examples.
I just started using this library in a codebase at work in which, many times, some work needs to be perfomed on an array of `double`s based on the value of a mask in the form of an array of `uint_fast8_t`s. Something like this:
```
void foo(double *data, uint_fast8_t *mask, size_t length) {
    for(size_t i{0}; i<length; i++) {
        if (mask[i] == 0xff) {
            // process data[i]
        }
    }
}
```

I couldn't find a way to load such mask and use it for `MaskedLoad` or logical expressions on the `double` array.
The "closest" function I found is `ResizeBitCast` but that converts a `uint_fast8_t` vector like this:
```
lane  :  0  1  2  3  4  5  6  7
value : 00 ff 00 ff 00 ff 00 ff
```
into this vector of `double`s:
```
lane  :                0                1                2                3                4                5                6                7
value : 00ff00ff00ff00ff 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000
```
While I would prefer something like this:
```
lane  :                0                1                2                3                4                5                6                7
value : 0000000000000000 00000000000000ff 0000000000000000 00000000000000ff 0000000000000000 00000000000000ff 0000000000000000 00000000000000ff
```
or like this:
```
lane  :                0                1                2                3                4                5                6                7
value : 0000000000000000 ffffffffffffffff 0000000000000000 ffffffffffffffff 0000000000000000 ffffffffffffffff 0000000000000000 ffffffffffffffff
```

Right now, my (ugly) workaround is to convert the mask vector into a `double` vector like this:
```
double resized_mask[max_size];
for (size_t i{0}; i < max_size; i++) {
    if (mask[i] == 0xff) {
        std::memset(resized_mask + i, ~(0x0), sizeof(double));
    } else {
        std::memset(resized_mask + i, 0x0, sizeof(double));
    }
}
```
So that I can later load the mask as a vector with the same type as my data and use `And`s instead of `If`s.

Am I missing something or is this functionality actually missing?

**Comment by johnplatts** [comment]
Here is an example of mask creation/conversion on Compiler Explorer:
https://godbolt.org/z/x16feKePc

**Comment by jan-wassenberg** [comment]
Nice, thanks @johnplatts :) Some of the complexity comes because we do not know the size of uint_fast8_t.

Hi @fbarbari, I'm curious whether that type is actually required in your application, and how the masks are being produced? If the original source produces bits, we can load those directly via `LoadMaskBits`. If it is actual bytes with 0xFF or 0, a somewhat simpler approach is to PromoteTo(ScalableTag<int64_t>(), your_u8_vector), then Gt(that, zero) to get a mask, then RebindMask to double.
If it really must be uint_fast8_t, then John's general solution looks good.

**Comment by fbarbari** [comment]
Hi everyone, thanks for the quick response.
@johnplatts thank you for the detailed example. As I can see, it's all about rebinding the mask vector to change its signedness, then its width and then converting it to a floating point type. This raises a doubt about `Mask`s: aren't they just arrays of single bits (one per lane)? Why should it matter what types they refer to? Shouldn't the number of lanes be the only parameter needed to define a `Mask` vector?
@jan-wassenberg actually the mask vector is not used as a proper mask, because its possible values are 0x00, 0x01 and 0x0a. This is unfortunately out of my control and I cannot change it. About your solution with `PromoteTo(ScalableTag<int64_t>(), ...)`, I implemented it this way and this produces the same output as my fourth "example":
```
HWY_ATTR void foo(double *data, uint_fast8_t *mask, size_t length) {
    namespace hn = hwy::HWY_NAMESPACE;
    const hn::ScalableTag<double> double_vector_tag;
    using vecD = hn::Vec<decltype(double_vector_tag)>;
    const size_t num_lanes = static_cast<size_t>(hn::Lanes(double_vector_tag));

    const hn::Rebind<uint_fast8_t, decltype(double_vector_tag)> mask_vector_tag;
    using vecM = hn::Vec<decltype(mask_vector_tag)>;

    static_assert(hn::Lanes(coordinate_vector_tag) == hn::Lanes(mask_vector_tag));

    for(size_t i{0}; i + (num_lanes-1) < length; i += num_lanes) {
        vecD v_i = hn::LoadU(coordinate_vector_tag, v + i);
        const vecM m_i = hn::LoadU(mask_vector_tag, m + i);

        const auto i64_m_i = hn::PromoteTo(hn::ScalableTag<int64_t>(), m_i);
        const auto i64_m_i_mask = hn::Gt(i64_m_i, hn::Zero(hn::ScalableTag<int64_t>()));
        const auto f64_m_i_mask = hn::RebindMask(double_vector_tag, i64_m_i_mask);

        // process v_i

        hn::BlendedStore(v_i, i64_m_i_mask, double_vector_tag, v + i);
    }
}
```
Is this what you meant?

**Comment by jan-wassenberg** [comment]
> Masks: aren't they just arrays of single bits (one per lane)? Why should it matter what types they refer to?

It depends on the platform. That's true on AVX-512 (special k reg) and RVV (bits stored in a vector).
On SVE we have one mask bit per vector byte, and on SSE/NEON we have 0 and ~0 in normal vectors.

For some of these representations, changing the type that these masks act upon can change the value of the mask elements.

Your code looks good to me. Sounds like it is indeed generating FF..FF or 00..00 masks as desired?

**Comment by fbarbari** [comment]
> For some of these representations, changing the type that these masks act upon can change the value of the mask elements.

Interesting, I didn't know that.

> Sounds like it is indeed generating FF..FF or 00..00 masks as desired?

Yes, it is. Thank you very much for your help.

**Comment by jan-wassenberg** [comment]
You're welcome :)
