### ISSUE TITLE
Sort issue with K64V64 or uint128_t 

### ISSUE THREAD

**Issue by jeromeDelrieu** [google/highway#1581]
When using 128bit sort an assert can occur in the Recurse method:
  HWY_DASSERT(bound != 0);

Or the sort is not sorted correctly (we have a signed sort instead).

Small example:

  const int nbValues = 1000;
  hwy::K64V64 listValues[nbValues];

  for (int i = 0; i < nbValues; i++) {
    listValues[i].key = i;
    listValues[i].value = i - 500;
  }
  hwy::VQSort(listValues, nbValues, hwy::SortAscending());
  for (int i = 1; i < nbValues; i++) {
    HWY_DASSERT(listValues[i - 1].value <= listValues[i].value);
  }

It is compiled on windows for x64, with clang, and the dispatch used is AVX2.

**Comment by jeromeDelrieu** [comment]
Any thoughts on this issue ?

**Comment by jan-wassenberg** [comment]
Oops, somehow I missed this issue, sorry about that and thanks for pinging it. I will investigate soon :)

**Comment by jan-wassenberg** [comment]
I have run your code and it looks like there might be a misunderstanding :) `.key` is what we are actually sorting on, whereas the repro checks `value` (this is a 'payload' that the sort comparator ignores). When changing the assert to check key, the test passes. I've tried this in release and debug builds, also with asan, and also printing information on each recursion, which looks reasonable.

Can you confirm it's fine if we switch the assert to `key`?

**Comment by jan-wassenberg** [comment]
Oh, interesting, glad you found the root cause. Generally it is a good idea to element-align data (so alignof == sizeof), some platforms can fault otherwise. But I do not yet understand why we would sort incorrectly if unaligned.

**Comment by jeromeDelrieu** [comment]
Here is the correct repro code.
Better in debug to see the assert in "vqsort-inl.h" :
// ChoosePivot* ensure pivot != last, so the right partition is never empty
// except in the rare case of the pivot matching the last-in-sort-order value,
// which implies we anyway skip the right partition due to kWasLast.
HWY_DASSERT(bound != num || result == PivotResult::kWasLast);



const int nbValues = 1000;
size_t sizeData = sizeof(hwy::K64V64) * (nbValues + 1);
unsigned char *pBuffer = (unsigned char *)malloc(sizeData + 8);
unsigned char *pUsedBuffer = pBuffer;
if ((size_t(pUsedBuffer) & 0xF) == 0) {
   pUsedBuffer += 8;
}
hwy::K64V64 *pArray = (hwy::K64V64 *)pUsedBuffer;
for (int i = 0; i < nbValues; i++) {
  pArray[i].value = i;
  pArray[i].key = i - 500;
}

hwy::VQSort(pArray, nbValues, hwy::SortAscending());
for (int i = 1; i < nbValues; i++) {
  HWY_DASSERT(pArray[i - 1].key <= pArray[i].key);
}
free(pBuffer);


For me this is an issue, because i cannot force 16 byte alignment on the buffer easily.

**Comment by jan-wassenberg** [comment]
Apologies this has taken so long. There were several issues with 128-bit keys which are now [fixed](https://github.com/google/highway/commit/67f768b07b9993c7efe499d5d563858bf1f166e3).
