### ISSUE TITLE
Adding WidenMulPairwiseAccumulate, AccumSumOf4Products, WidenMulPairwiseSatAccumulate and SatAccumSumOf4Products operations

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1628]
Here are the descriptions of the WidenMulPairwiseAccumulate, AccumSumOf4Products, WidenMulPairwiseSatAccumulate and SatAccumSumOf4Products operations:
*   `V`: `{bf,i,u}16`, `D`: `RepartitionToWide<DFromV<V>>`, `VW`: `Vec<D>` \
    <code>Vec&lt;D&gt; **WidenMulPairwiseAccumulate**(D d, V a, V b, VW sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[2*i+1]*b[2*i+1] + a[2*i+0]*b[2*i+0]`.
`WidenMulPairwiseAccumulate(d, a, b, sum)` is equivalent to `Add(sum, WidenMulPairwiseAccumulate(d, a, b))`.
*   `V`: `{u,i}{8,16}`, `D`: `RepartitionToWide<RepartitionToWide<DFromV<V>>>`, `VW`: `Vec<D>` \
    <code>Vec&lt;D&gt; **AccumSumOf4Products**(D d, V a, V b, VW sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[4*i+3]*b[4*i+3] + a[4*i+2]*b[4*i+2] + a[4*i+1]*b[4*i+1] + a[4*i+0]*b[4*i+0]`.
*   <code>VI32 **AccumSumOf4Products**(DI32 d, VU8 a, VI8 b, VI32 sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[4*i+3]*b[4*i+3] + a[4*i+2]*b[4*i+2] + a[4*i+1]*b[4*i+1] + a[4*i+0]*b[4*i+0]`.
*   `V`: `{i,u}16`, `D`: `RepartitionToWide<DFromV<V>>`, `VW`: `Vec<D>` \
    <code>Vec&lt;D&gt; **WidenMulPairwiseSatAccumulate**(D d, V a, V b, VW sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[2*i+1]*b[2*i+1] + a[2*i+0]*b[2*i+0]`, saturated to the range of `TFromD<D>`.
`WidenMulPairwiseAccumulate(d, a, b, sum)` is equivalent to `SaturatedAdd(sum, WidenMulPairwiseAccumulate(d, a, b))` if `TFromD<D>` is a signed integer type.
*   `V`: `{u,i}{8,16}`, `D`: `RepartitionToWide<RepartitionToWide<DFromV<V>>>`, `VW`: `Vec<D>` \
    <code>Vec&lt;D&gt; **SatAccumSumOf4Products**(D d, V a, V b, VW sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[4*i+3]*b[4*i+3] + a[4*i+2]*b[4*i+2] + a[4*i+1]*b[4*i+1] + a[4*i+0]*b[4*i+0]`, saturated to the range of `TFromD<D>`.
*   <code>VI32 **SatAccumSumOf4Products**(DI32 d, VU8 a, VI8 b, VI32 sum)</code>: widens `a` and `b` to `TFromD<D>` and computes
`sum[i] + a[4*i+3]*b[4*i+3] + a[4*i+2]*b[4*i+2] + a[4*i+1]*b[4*i+1] + a[4*i+0]*b[4*i+0]`, saturated to the range of `int32_t`.

Should WidenMulPairwiseAccumulate, AccumSumOf4Products, WidenMulPairwiseSatAccumulate and SatAccumSumOf4Products be called something else instead?

Note that WidenMulPairwiseSatAccumulate does not have the same behavior as ReorderWidenMulAccumulate on some targets.

The AVX3_DL, PPC, and SVE targets can carry out some of the above operations using a single instruction.

Here are the instructions that WidenMulPairwiseAccumulate, AccumSumOf4Products, WidenMulPairwiseSatAccumulate and SatAccumSumOf4Products operations map to:
- I16xI16->I32 WidenMulPairwiseAccumulate: AVX3_DL vpdpwssd, PPC vmsumshm
- U16xU16->U32 WidenMulPairwiseAccumulate: PPC vmsumuhm
- I8xI8->I32 AccumSumOf4Products: SVE sdot
- U8xU8->U32 AccumSumOf4Products: SVE udot, PPC vmsumubm
- U8xI8->I32 AccumSumOf4Products: AVX3_DL vpdpbusd, PPC vmsummbm, SVE usdot
- I16xI16->I64 AccumSumOf4Products: SVE sdot
- U16xU16->U64 AccumSumOf4Products: SVE udot
- I16xI16->I32 WidenMulPairwiseSatAccumulate: AVX3_DL vpdpwssds, PPC vmsumshs
- U16xU16->U32 WidenMulPairwiseSatAccumulate: PPC vmsumuhs
- U8xI8->I32 SatAccumSumOf4Products: AVX3_DL vpdpbusds

**Comment by jan-wassenberg** [comment]
Interesting, do I understand correctly that you are proposing to add these new operations?

Do you require the exact semantics of WidenMulPairwiseAccumulate, i.e. ReorderWidenMulAccumulate is insufficient?

AccumSumOf4Products looks very useful. I suppose it would be more consistent with the existing ops to call it SumOfMul4Accumulate or SumOfMulQuadAccumulate? NEON also supports this (SDOT/UDOT).

I'm not sure about adding the Sat* versions yet. Do you have a use case for that?

**Comment by johnplatts** [comment]
> Interesting, do I understand correctly that you are proposing to add these new operations?
> 
> Do you require the exact semantics of WidenMulPairwiseAccumulate, i.e. ReorderWidenMulAccumulate is insufficient?

ReorderWidenMulAccumulate+SumOfLanes, BitCast+MulAdd, or SumOfMulQuadAccumulate are sufficient for most of the use cases of WidenMulPairwiseAccumulate.

> AccumSumOf4Products looks very useful. I suppose it would be more consistent with the existing ops to call it SumOfMul4Accumulate or SumOfMulQuadAccumulate? NEON also supports this (SDOT/UDOT).

I agree that SumOfMulQuadAccumulate is a good name for the AccumSumOf4Products operation described above.

**Comment by johnplatts** [comment]
> NEON also supports this (SDOT/UDOT).

The NEON SDOT/UDOT instructions require the Armv8.2-A DotProd instruction set extension and the NEON USDOT instruction requires the Armv8.2-A I8MM instruction set extension. There are also some ARM CPU's that support the HWY_NEON_WITHOUT_AES target but do not support the Armv8.2-A SDOT/UDOT/USDOT instructions.

The SVE USDOT instruction requires the SVE I8MM extension, which is not available on all of the ARM CPU's that support SVE.

**Comment by johnplatts** [comment]
> OK, let's go with that. Do you plan to implement SumOfMulQuadAccumulate, or shall I add it to our list?
I have implemented SumOfMulQuadAccumulate in pull request #1637.

**Comment by jan-wassenberg** [comment]
Super, thank you :) Will review soon.

**Comment by jan-wassenberg** [comment]
It's merged, looks like we can close :)
