### ISSUE TITLE
VQSort crash with certain datasets

### ISSUE THREAD

**Issue by bwx0** [google/highway#1643]
When I was sorting some uint128 data files produced by other applications, I found the program crashed on calling VQSort.

**Environment**
- Highway 1.0.5
- Windows 10
- clang 16.0.2
- Intel Core i7-10750H
more info can be found in attached files.

**How I run into problems**

1. I compiled Highway 1.0.5 into libhwy.a and libhwy_contrib.a with clang, 
2. I wrote a simple program and compiled it along with the two .a files to sort all the numbers in the file "data.bin", which is ~210MB and contains ~13M 128-bit numbers.
3. On calling VQSort, SIGSEGV was signalled, windbg shows "Access violation - code c0000005"

**Notes**
1. Interpreting the file as an uint64 array and sorting will work
2. Sorting only the first 4M numbers or less will work, but the first 5M won't
3. Replacing VQSort with std::sort works
4. Replacing the hi or lo part of each uint128 with random numbers will make it work. (see test code below)
5. Sorting any amount of randomly generated numbers/all zeros works. (And it works with randomly generated files of the same size.)
6. For all 128bit numbers, take the xor sum of each 16bit, the lowest 3-bit part of the results are always the same. (i.e. for any number A[127:0] in the data file, we calculate Y=A[15:0]^A[31:16]^A[47:32]^A[63:48]^....^A[127:112], then Y&0x7 always gives the same result. This is because I take this number as a hash, and numbers with the same hashes go to the same file.)

**Test Code**
```
#include "hwy/contrib/sort/vqsort.h"
#include <iostream>
#include <fstream>
#include <random>

// read the entire file to buf, file size stored to "size_t &filesize"
bool readFile(const std::string &filename, void *buf, size_t &filesize) {
    std::ifstream file(filename, std::ios::binary | std::ios::ate);
    if (!file) {
        std::cerr << "Error opening the file: " << filename << '\n';
        return false;
    }
    std::streamsize size = file.tellg();
    filesize = size;
    std::cout << "filesize=" << filesize << "  nInt128s=" << std::fixed << filesize / 16.0 << std::endl;
    
    file.seekg(0, std::ios::beg);
    if (file.read(static_cast<char *>(buf), size)) {
    	file.close();
        return true;
    } else {
    	file.close();
        std::cerr << "Error reading the file: " << filename << '\n';
        return false;
    }
}

hwy::uint128_t *buff = new hwy::uint128_t[20000000]; // data file contains only 13900338 int128s, should be enough
bool sortAsInt64 = true;
std::mt19937_64 mt;

int main() {
    size_t fileSize;
    std::cout << "reading data" << std::endl;
    readFile("data.bin", buff, fileSize);
    
    for(int i = 0 ; i < fileSize / sizeof(hwy::uint128_t); i++){
    	//uncommenting any of the following two makes it work
    	//buff[i].hi = mt();
    	//buff[i].lo = mt();
    }

    std::cout << "sort as int64 or int128? (0 for int128, 1 for int64): ";
    std::cin >> sortAsInt64;

    if(sortAsInt64) { // it works
        std::cout << "sort as int64" << std::endl;
        VQSort((uint64_t*) buff, fileSize / sizeof(uint64_t), hwy::SortAscending());
        std::cout << "finished" << std::endl;
    } else { // it crashes
        std::cout << "sort as int128" << std::endl;
        VQSort((hwy::uint128_t*) buff, fileSize / sizeof(hwy::uint128_t), hwy::SortAscending());
        std::cout << "finished" << std::endl;
    }
    
    system("pause");
    return 0;
}
```

**Codes and files and more sysinfos**
[Google Drive Link (221MB)](https://drive.google.com/file/d/1Vj7-Pai7XvYoavEvxR6GA0OFyN8fWhJe/view?usp=sharing)

**update:** I found a smaller dataset that has ~15% chance to crash the program
[dataset2.zip](https://github.com/google/highway/files/12302664/dataset2.zip)

**Comment by jan-wassenberg** [comment]
Thank you for letting us know and sharing such a detailed repro! Very helpful.
I will be looking into this soon, but am out of office next week, so might have to resume after returning :)

**Comment by bwx0** [comment]
No problem, take your time, and thank you for the quick response! I will do more research to figure more out and see if it was just my mistake that caused the issue.

**Comment by jan-wassenberg** [comment]
I'm back and have taken a first stab at reproducing. Thanks again for sharing the files!
With clang near trunk, asan/msan builds of your code (slightly modified) succeed 40 times for each target with data2.bin. It's a simple loop that loads from disk/cache and sorts as 128-bit.
I also tried 5 runs of data.bin with msan.

The compiler version you mention is quite new, so that's likely fine.

The sort has not meaningfully changed since 1.0.5 (Jul 19): https://github.com/google/highway/commits/master/hwy/contrib/sort

From your system info, looks like this is a Comet Lake CPU which is apparently Skylake with only AVX2, which should also be fine.

Perhaps noteworthy is that the `int i` triggers asan/ubsan (int overflow) and the cast of buff to (hwy::uint128_t*) is unnecessary, but it's very doubtful those are causing the problem.

Until I'm able to reproduce this, it would be great if you could help narrow this down. Are you able to compile with asan/msan, or with a recent GCC, or on Linux? Does it also happen with Highway trunk?

**Comment by jan-wassenberg** [comment]
Thanks for sharing the log. Indeed interesting. The prefetch error is safe to ignore, invalid addresses there do not raise exceptions. Looks like the other warnings are inside the Windows kernel - it's unfortunate that isn't 'warning-clean'.

hm, that's a largish difference in binary size. Seems something indeed changed in the compiler.

No worries, always good to investigate. Thanks for reporting the issue. BTW I'm curious what your use case is for vqsort?

**Comment by bwx0** [comment]
I'm using sorting to find the intersection of two large sets. Since the sets are large, elements are firstly partitioned into smaller sets, and then we find the intersections one by one. Each partition contains elements encoded as 128-bit integers and may have up to 1 billion elements. So I am currently doing that by sorting both files and then using two pointers to find identical elements, like the ones used in merge sort.
