### ISSUE TITLE
advapi32.lib is linked from source code

### ISSUE THREAD

**Issue by kmilos** [google/highway#1646]
https://github.com/google/highway/blob/ff1ad85a96c0bc8483b582d6dbceb8bc07edd226/hwy/contrib/sort/vqsort.cc#L75

is not portable, this is the warning on both MSYS2 UCRT64 and CLANG64:
```
[34/40] Building CXX object CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort.cc.obj
  C:/_/B/src/highway-1.0.5/hwy/contrib/sort/vqsort.cc:75: warning: ignoring '#pragma comment ' [-Wunknown-pragmas]
     75 | #pragma comment(lib, "advapi32.lib")
        | 
```

Should probably be gated by `#ifdef _MSC_VER`, or handled by the build scripts.

Luckily both toolchains (at least when using CMake) seem to link this library in by default so there is no failure per se...

https://gitlab.kitware.com/cmake/cmake/-/blob/e162bbc8cbefdd998e35fc690483aa801fb3362b/Modules/Platform/Windows-GNU.cmake#L28

https://gitlab.kitware.com/cmake/cmake/-/blob/e162bbc8cbefdd998e35fc690483aa801fb3362b/Modules/Platform/Windows-Clang.cmake#L126

Seems to be the case for MSVC as well, so could potentially even be removed (depending on other build systems being used on Windows):

https://gitlab.kitware.com/cmake/cmake/-/blob/e162bbc8cbefdd998e35fc690483aa801fb3362b/Modules/Platform/Windows-MSVC.cmake#L256

**Comment by jan-wassenberg** [comment]
Thanks for letting us know. We like to fix warnings.
Yes, let's gate it on MSVC. Sending a patch soon :)

**Comment by kmilos** [comment]
Thanks for the quick response!

P.S., feel free to also update the readme that highway is also available in the MSYS2 repos. 😉

**Comment by jan-wassenberg** [comment]
Thank you, we will add it :)
(FYI it turns out that one of our build configs actually requires the pragma.)

**Comment by kmilos** [comment]
> Thank you, we will add it :)

Or simply refer to https://repology.org/project/highway-simd-library/versions

> (FYI it turns out that one of our build configs actually requires the pragma.)

Good catch. `clang-cl` should define `_MSC_VER` AFAIK (or it could be a CMake thing again), but I see now you're not using directly.

**Comment by jan-wassenberg** [comment]
Oh nice, will link to repology, thanks.

> clang-cl should define _MSC_VER AFAIK (or it could be a CMake thing again), but I see now you're not using this macro directly.

Yes indeed, our `_MSVC` refers to the actual MSVC compiler because it behaves differently in important ways vs the clang frontend.
