### ISSUE TITLE
Mask invariant workaround

### ISSUE THREAD

**Issue by bkille** [google/highway#1660]
Hi, 

**Is there a vectorized way to set all bits in a lane if any of the bits are set?**

I have a use-case where I have a Vec that I would like to convert to a mask where `m[i] == True` iff `PopCount(a[i]) > 0`. I'm unable to use `hwy::MaskFromVec`, as

> The result is implementation-defined if v[i] is neither zero nor all bits set.

**Comment by johnplatts** [comment]
> I have a use-case where I have a Vec that I would like to convert to a mask where `m[i] == True` iff `PopCount(a[i]) > 0`. I'm unable to use `hwy::MaskFromVec`, as
> 
> > The result is implementation-defined if v[i] is neither zero nor all bits set.

Here is the correct way to convert `PopulationCount(a[i]) > 0` to a mask:
```Gt(PopulationCount(a[i]), Zero(d))```

**Comment by bkille** [comment]
Ahh, simple as that, thank you!
