### ISSUE TITLE
VQSort nth_element and partial_sort

### ISSUE THREAD

**Issue by zbjornson** [google/highway#1681]
Hi - Do you have any plans to add the equivalent of `std::nth_element` and/or `std::partial_sort` to VQSort? (`std::nth_element` in particular would be useful for me.)

**Comment by jan-wassenberg** [comment]
Hi @zbjornson , a QuickSelect/nth_element indeed sounds useful and would be fairly straightforward to add. Would you like to implement it? I am happy to advise. FYI will be out of office from Aug30 to Sep5.

**Comment by zbjornson** [comment]
I have a start in https://github.com/google/highway/compare/master...zbjornson:zbjornson/1681?expand=1. It's not working fully, but I'll keep working at it while you're away.

**Comment by jan-wassenberg** [comment]
Congrats, that looks great :) One tiny nit: we use `kIsSelect` for constants and template args.
See you next week :)

**Comment by jan-wassenberg** [comment]
Thanks to @zbjornson and @enum-class this is now done :)
