### ISSUE TITLE
armhf: HwyMulTestGroup/HwyMulTest.TestAllSatWidenMulPairwiseAdd/EMU128

### ISSUE THREAD

**Issue by malaterre** [google/highway#1683]
Version c7b1348 currently fails on armhf/gcc-13:

Total Test time (real) =  24.78 sec

The following tests FAILED:
	350 - HwyMulTestGroup/HwyMulTest.TestAllSatWidenMulPairwiseAdd/EMU128  # GetParam() = 2305843009213693952 (Subprocess aborted)
	356 - HwyMulTestGroup/HwyMulTest.TestAllSumOfMulQuadAccumulate/EMU128  # GetParam() = 2305843009213693952 (Subprocess aborted)
Errors while running CTest

ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=1.0.7%7Egit20230825.c7b1348-1&stamp=1693207147&raw=0

**Comment by jan-wassenberg** [comment]
Thanks for reporting this. GCC-13 is unfortunately quite broken :/ Looks like this is 13.2.
In detect_targets, how about we change this
`HWY_COMPILER_GCC_ACTUAL && HWY_COMPILER_GCC_ACTUAL < 1203`
to 1303? Or perhaps less optimistically 1400?

**Comment by jan-wassenberg** [comment]
Sounds good, thanks for filing a bug :)

**Comment by jan-wassenberg** [comment]
Thanks for filing the bug :)
