### ISSUE TITLE
Adding VecFromValues and Dup128VecFromValues operations

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1706]
I would like to add the VecFromValues and Dup128VecFromValues operations to Google Highway as VecFromValues and Dup128VecFromValues have better codegen than using a temporary array followed by Load or LoadDup128 on some targets.

VecFromValues is equivalent to _mm_set_epi8, _mm_set_epi16, _mm_set_epi32, _mm_set_epi64, _mm_set_ps, and _mm_set_pd on SSE2/SSSE3/SSE4/AVX2/AVX3.

Dup128VecFromValues is equivalent to VecFromValues followed by BroadcastBlock or svdupq_n_s8, svdupq_n_s16, svdupq_n_s32, svdupq_n_s64, svdupq_n_u8, svdupq_n_u16, svdupq_n_u32, svdupq_n_u64, svdupq_n_f16, svdupq_n_f32, svdupq_n_f64 on SVE.

VecFromValues/Dup128VecFromValues can be implemented for PPC/WASM/NEON using GCC/Clang vector extensions when compiled with GCC or Clang.

Here are generic implementations for VecFromValues and Dup128VecFromValues:
```
template <class D, class... TVal>
HWY_API VFromD<D> VecFromValues(D d, TVal&&... vals) {
#if HWY_HAVE_SCALABLE
  constexpr size_t kArraySize = HWY_MAX(sizeof...(TVal), 1);
#else
  constexpr size_t kArraySize = HWY_MAX(sizeof...(TVal), HWY_MAX_LANES_D(D));
#endif

  HWY_ALIGN const TFromD<D> src_values[kArraySize] = {
      static_cast<TFromD<D>>(static_cast<TVal&&>(vals))...};
#if HWY_HAVE_SCALABLE
  return LoadN(d, src_values, kArraySize);
#else
  return Load(d, src_values);
#endif
}

template <class D, class... TVal>
HWY_API VFromD<D> Dup128VecFromValues(D d, TVal&&... vals) {
  constexpr size_t kMaxLanesToLoad =
      HWY_MIN(HWY_MAX_LANES_D(D), 16 / sizeof(TFromD<D>));
  constexpr size_t kArraySize = HWY_MAX(sizeof...(TVal), kMaxLanesToLoad);

  alignas(16) const TFromD<D> src_values[kMaxLanesToLoad] = {
      static_cast<TFromD<D>>(static_cast<TVal&&>(vals))...};
  return LoadDup128(d, src_values);
}
```

**Comment by johnplatts** [comment]
Here is a possible implementation of VecFromValues and Dup128VecFromValues for vectors that have 16 or fewer bytes on SSE2/SSSE3/SSE4/AVX2/AVX3:
```
namespace detail {

template <class D, class... RemainingVals, HWY_IF_T_SIZE_D(D, 1),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(
    D d, TFromD<D> val0, TFromD<D> val1, TFromD<D> val2, TFromD<D> val3,
    TFromD<D> val4, TFromD<D> val5, TFromD<D> val6, TFromD<D> val7,
    TFromD<D> val8, TFromD<D> val9, TFromD<D> val10, TFromD<D> val11,
    TFromD<D> val12, TFromD<D> val13, TFromD<D> val14, TFromD<D> val15,
    RemainingVals&&...) {
  return VFromD<D>{_mm_set_epi8(
      static_cast<char>(val15), static_cast<char>(val14),
      static_cast<char>(val13), static_cast<char>(val12),
      static_cast<char>(val11), static_cast<char>(val10),
      static_cast<char>(val9), static_cast<char>(val8), static_cast<char>(val7),
      static_cast<char>(val6), static_cast<char>(val5), static_cast<char>(val4),
      static_cast<char>(val3), static_cast<char>(val2), static_cast<char>(val1),
      static_cast<char>(val0))};
}

template <class D, class... RemainingVals, HWY_IF_UI16_D(D),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(D d, TFromD<D> val0, TFromD<D> val1,
                                   TFromD<D> val2, TFromD<D> val3,
                                   TFromD<D> val4, TFromD<D> val5,
                                   TFromD<D> val6, TFromD<D> val7,
                                   RemainingVals&&...) {
  return VFromD<D>{
      _mm_set_epi16(static_cast<int16_t>(val7), static_cast<int16_t>(val6),
                    static_cast<int16_t>(val5), static_cast<int16_t>(val4),
                    static_cast<int16_t>(val3), static_cast<int16_t>(val2),
                    static_cast<int16_t>(val1), static_cast<int16_t>(val0))};
}

template <class D, class... RemainingVals, HWY_IF_UI32_D(D),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(D d, TFromD<D> val0, TFromD<D> val1,
                                   TFromD<D> val2, TFromD<D> val3,
                                   RemainingVals&&...) {
  return VFromD<D>{
      _mm_set_epi32(static_cast<int16_t>(val3), static_cast<int16_t>(val2),
                    static_cast<int16_t>(val1), static_cast<int16_t>(val0))};
}

template <class D, class... RemainingVals, HWY_IF_UI64_D(D),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(D d, TFromD<D> val0, TFromD<D> val1,
                                   RemainingVals&&...) {
  return VFromD<D>{
      _mm_set_epi64x(static_cast<int16_t>(val1), static_cast<int16_t>(val0))};
}

template <class D, class... RemainingVals, HWY_IF_F32_D(D),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(D d, TFromD<D> val0, TFromD<D> val1,
                                   TFromD<D> val2, TFromD<D> val3,
                                   RemainingVals&&...) {
  return VFromD<D>{_mm_set_ps(val3, val2, val1, val0)};
}

template <class D, class... RemainingVals, HWY_IF_F64_D(D),
          HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_INLINE VFromD<D> VecFromValues(D d, TFromD<D> val0, TFromD<D> val1,
                                   RemainingVals&&...) {
  return VFromD<D>{_mm_set_pd(val1, val0)};
}

}  // namespace detail

template <class D, class... Args, HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_API VFromD<D> VecFromValues(D d, Args&&... vals) {
  return detail::VecFromValues(d, static_cast<TFromD<D>>(vals)...);
}

template <class D, class... Args, HWY_IF_V_SIZE_LE_D(D, 16)>
HWY_API VFromD<D> Dup128VecFromValues(D d, Args&&... vals) {
  return detail::VecFromValues(d, static_cast<TFromD<D>>(vals)...);
}
```

**Comment by jan-wassenberg** [comment]
I like your idea of Dup128VecFromValues, it seems useful to target the SVE dupq capability.
Can we ensure that exactly 16 bytes of inputs are given, to reduce the chance of bugs?

I'm a bit concerned about vector-length dependencies creeping in with VecFromValues. Someone might pass in 32 bytes of parameters and it may then work with some SVE lengths but not others. Can you help me understand the use case? Is is mainly to improve code generation vs a Load()? If so, I wonder whether Dup128VecFromValues could also be used instead?

**Comment by johnplatts** [comment]
> I like your idea of Dup128VecFromValues, it seems useful to target the SVE dupq capability. Can we ensure that exactly 16 bytes of inputs are given, to reduce the chance of bugs?
> 
> I'm a bit concerned about vector-length dependencies creeping in with VecFromValues. Someone might pass in 32 bytes of parameters and it may then work with some SVE lengths but not others. Can you help me understand the use case? Is is mainly to improve code generation vs a Load()? If so, I wonder whether Dup128VecFromValues could also be used instead?

Dup128VecFromValues is sufficient for most of the use cases.

Should the lane value arguments to Dup128VecFromValues be in the same order as the SSE2 _mm_set_epi*/_mm_set_ps/_mm_set_pd intrinsics (with the value of the highest-indexed lane first), or should the lane value arguments to Dup128VecFromValues be in the same order as the SSE2 _mm_setr_epi*/_mm_setr_ps/_mm_setr_pd intrinsics, SVE svdupq intrinsics, or C++ constant array declaration (with the the value of the lowest-indexed lane first)?

**Comment by jan-wassenberg** [comment]
Thanks for implementing this :) Strange, I did not get a notification for this issue, sorry to reply late.

For the argument order, generally I'd prefer most significant first, we usually have (hi, lo) for ConcatUpperLower etc. But for loading constants, C++/x86 little endian order does make sense, it makes it easy to switch between arrays and a call to the new op, so nice that you've implemented it that way 👍
