### ISSUE TITLE
ppc: inlining failed in PreventElision

### ISSUE THREAD

**Issue by jbicha** [google/highway#1707]
highway 1.0.7 fails to build on Ubuntu's ppc64el official builder but builds on Debian's ppc64el. Ubuntu apparently has different baseline in its hardware.

Excerpt from Debian build log
=============================
https://buildd.debian.org/status/logs.php?pkg=highway&arch=ppc64el

```
Compiled HWY_TARGETS: PPC10 PPC9 PPC8
HWY_ATTAINABLE_TARGETS: PPC10 PPC9 PPC8 EMU128
HWY_BASELINE_TARGETS: PPC8 EMU128
HWY_STATIC_TARGET: PPC8
HWY_BROKEN_TARGETS:
HWY_DISABLED_TARGETS:
Current CPU supports: PPC8 EMU128 SCALAR
```

Excerpt from Ubuntu build log
=============================
https://launchpad.net/ubuntu/+source/highway/1.0.7-1/+latestbuild/ppc64el

```
Compiled HWY_TARGETS: PPC10 PPC9
HWY_ATTAINABLE_TARGETS: PPC10 PPC9 PPC8 EMU128
HWY_BASELINE_TARGETS: PPC9 PPC8 EMU128
HWY_STATIC_TARGET: PPC9
HWY_BROKEN_TARGETS:
HWY_DISABLED_TARGETS:
Current CPU supports: PPC9 PPC8 EMU128 SCALAR

…

In file included from /<<PKGBUILDDIR>>/hwy/examples/skeleton.h:24,
                 from /<<PKGBUILDDIR>>/hwy/examples/skeleton_test.cc:18:
/<<PKGBUILDDIR>>/hwy/base.h: In member function
 ‘skeleton::N_PPC10::TestFloorLog2::operator()<float, hwy::N_PPC10::Simd<float, 4ul, 0> >
(float, hwy::N_PPC10::Simd<float, 4ul, 0>)void’:
/<<PKGBUILDDIR>>/hwy/base.h:1511:14: error: inlining failed in call to ‘always_inline’
 ‘hwy::PreventElision<int&>(int&)void’: target specific option mismatch
 1511 | HWY_API void PreventElision(T&& output) {
      | ^~~~~~~~~~~~~~
In file included from /<<PKGBUILDDIR>>/hwy/foreach_target.h:266,
                 from /<<PKGBUILDDIR>>/hwy/examples/skeleton_test.cc:24:
/<<PKGBUILDDIR>>/hwy/examples/skeleton_test.cc:73:24: note: called from here
   73 | hwy::PreventElision(sum);
      | ~~~~~~~~~~~~~~~~~~~^~~~~
/<<PKGBUILDDIR>>/hwy/base.h:1511:14: error: inlining failed in call to ‘always_inline’
 ‘hwy::PreventElision<int&>(int&)void’: target specific option mismatch
 1511 | HWY_API void PreventElision(T&& output) {
      | ^~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/hwy/examples/skeleton_test.cc:73:24: note: called from here
   73 | hwy::PreventElision(sum);
      | ~~~~~~~~~~~~~~~~~~~^~~~~
```

Other Info
==========
Based on https://github.com/google/highway/blob/master/run_tests.sh , I applied a workaround to Ubuntu's package which fixed the build: `-DCMAKE_CXX_FLAGS='-mcpu=power9 -mno-power9-vector -mpower8-vector'`

**Comment by jbicha** [comment]
Yes, building with [GCC 13](https://launchpad.net/ubuntu/+source/highway/1.0.7-1) fails with the same error.

**Comment by jbicha** [comment]
I don't know enough background here to have anything to add. My main interest is in getting a newer libjxl into  Ubuntu but it needs to build on the right architectures. :)

**Comment by jan-wassenberg** [comment]
> My main interest is in getting a newer libjxl into Ubuntu but it needs to build on the right architectures. :)

I understand :) It looks like an actual compiler bug, I've replied on the GCC bug. Thanks @malaterre for filing it!
In the meantime, is it an option for you to add `-DHWY_COMPILE_ONLY_STATIC` to the required build flags?

If not, we can also consider a PPC-specific workaround that basically forces that flag to be set.

**Comment by jan-wassenberg** [comment]
On further thought, it's not really a compiler bug. Different behavior than x86, but understandable. We'll have to do the workaround and I'm looking into it.

**Comment by jan-wassenberg** [comment]
Wow, there are actually multiple issues here:

- The "PPC8 with -mcpu=power9" - that should now be fixed: https://gcc.godbolt.org/z/Mc9MWdKfr
- Apparently POWER10 has less features ('HTM') than power9. This can be fixed with -mno-htm (verified in the above godbolt), or we can add ",htm" to the pragma target so no user action is required. Will make that change soon.
- The compiler bug relating to handling of (empty) inline asm. Given that compilers will remain in use for years, we have to work around it independently of any fix. I think the second point is sufficient for that.

**Comment by jan-wassenberg** [comment]
I am open to discussion, but my first thought would be to keep that change: it is less surprising for users if we skip ppc8 when they request ppc9 as the baseline, right? Also helps with code size.

**Comment by jan-wassenberg** [comment]
Yes, I agree we generally want to test on all targets. Whenever the baseline is not set, we will :) Our pre-release testing still covers PPC8 (`-mno-power9-vector -mpower8-vector`).

**Comment by jbicha** [comment]
Thanks, that version didn't work on Ubuntu though:

https://launchpad.net/~jbicha/+archive/ubuntu/arch/+sourcepub/15156354/+listing-archive-extra

**Comment by jbicha** [comment]
1.07-6 did not work for Ubuntu either

https://launchpad.net/~jbicha/+archive/ubuntu/arch/+sourcepub/15156501/+listing-archive-extra

**Comment by jbicha** [comment]
1.07-7 works for Ubuntu

**Comment by jan-wassenberg** [comment]
Thanks for confirming :D
