### ISSUE TITLE
GCC: FLT_EVAL_METHOD is not fexcess-precision

### ISSUE THREAD

**Issue by malaterre** [google/highway#1708]
In commit a02c342b logic was added to detected GCC `-fexcess-precision` value. It turns this is not `FLT_EVAL_METHOD`. 

Some work would be needed to refactor this logic.

For ref:
* https://gcc.gnu.org/pipermail/gcc-help/2023-September/142856.html

cc: @jwakely

**Comment by jan-wassenberg** [comment]
Thanks, I've read the thread.
It looks like your conclusion is that it is not possible to detect the correct flags have been set.

Any suggestions where to go from here? I suppose we should remove the FLT_EVAL_METHOD == 0 check.

Then there is the question whether we simply disable the test on i386, or detect GCC 13 in CMake and if so, add `-fexcess-precision` to CXXFLAGS?

**Comment by jan-wassenberg** [comment]
Thanks, that's good news. I think it's helpful to keep some of that change for gcc <13, but it's nice that on GCC 13 no action is required.
