### ISSUE TITLE
Can't build with Clang 16

### ISSUE THREAD

**Issue by zbjornson** [google/highway#1709]
Even with the latest f16 fixes (fed142a03f11ff0ac71594ac0225cf60b63ee741), I can't build highway with LLVM Clang 16.

```
highway/build$ lsb_release -d
Description:    Ubuntu 20.04.6 LTS

highway/build$ cmake ..
-- The C compiler identification is Clang 16.0.6
-- The CXX compiler identification is Clang 16.0.6
...

highway/build$ make -j
...
Config: emu128:0 scalar:0 static:0 all_attain:0 is_test:0
Compiled HWY_TARGETS:   AVX3_SPR AVX3_ZEN4 AVX3 AVX2 SSE4 SSSE3 SSE2
HWY_ATTAINABLE_TARGETS: AVX3_SPR AVX3_ZEN4 AVX3 AVX2 SSE4 SSSE3 SSE2 EMU128
HWY_BASELINE_TARGETS:   SSE2 EMU128
HWY_STATIC_TARGET:      SSE2
HWY_BROKEN_TARGETS:
HWY_DISABLED_TARGETS:
Current CPU supports:   AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2 EMU128 SCALAR
...
[ 69%] Linking CXX executable tests/base_test
[ 69%] Linking CXX executable tests/image_test
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
libhwy_test.a(test_util.cc.o): in function `hwy::detail::IsEqual(hwy::detail::TypeInfo const&, void const*, void const*)':
test_util.cc:(.text+0x1b7): undefined reference to `__extendhfsf2'
/usr/bin/ld: test_util.cc:(.text+0x1c7): undefined reference to `__extendhfsf2'
... (repeated for several targets)
```

It sounds like this is some ABI issue, but out of my area of knowledge to debug.

More of an FYI, not a high priority. I can build with Clang-15.

**Comment by jan-wassenberg** [comment]
Thank you @johnplatts ! Good point about libclang-rt-16-dev, that would seem to get us the matching compiler-rt and thus solve the ABI incompatibility.

I'll add mention of this to the FAQ.

**Comment by zbjornson** [comment]
Thanks a lot, I didn't realize I need that package.

**Comment by ImanHosseini** [comment]
I have a similar issue and I am using clang-17. I tried to check whether wrong libclang was being picked up, so I straced the compilation command but nowhere in the trace do I see libclang-rt being picked up, what I do see is this:
```
34758 openat(AT_FDCWD, "/usr/local/cuda-11.8/lib64/libclang-cpp.so.17", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
34758 openat(AT_FDCWD, "/usr/lib/llvm-17/bin/../lib/libclang-cpp.so.17", O_RDONLY|O_CLOEXEC) = 3
```
Is libclang-cpp.so.17 different? & why is it failing despite being 17 (same version as compiler)?
