### ISSUE TITLE
1.0.7 fails to build with clang 7 (missing _knot_mask8)

### ISSUE THREAD

**Issue by jmroot** [google/highway#1711]
The `_knot_mask8` intrinsic and the underlying builtin were added in clang 8: https://github.com/llvm/llvm-project/commit/c330ca861139d6b43766885007069b0e05e15b72

So building with clang 7 fails like this:
```
In file included from …/work/highway-1.0.7/hwy/per_target.cc:20:
In file included from …/work/highway-1.0.7/hwy/foreach_target.h:105:
In file included from …/work/highway-1.0.7/hwy/per_target.cc:21:
In file included from …/work/highway-1.0.7/hwy/highway.h:410:
In file included from …/work/highway-1.0.7/hwy/ops/x86_512-inl.h:84:
…/work/highway-1.0.7/hwy/ops/x86_256-inl.h:5781:33: error: use of undeclared identifier '_knot_mask8'
      _mm256_maskz_cvttpd_epu32(_knot_mask8(MaskFromVec(v).raw), v.raw)};
                                ^
```

**Comment by jan-wassenberg** [comment]
Thank you @johnplatts for fixing this and @jmroot for raising the issue.

I notice we have clang-6 but not 7 in the github actions. We'll add other versions, let's see if the actions still complete within the deadline for our internal CI.

**Comment by jmroot** [comment]
Thank you for the fix.
