### ISSUE TITLE
Add hwy::IsInteger and hwy::IsFixedSizeInteger type traits

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1727]
`hwy::IsInteger<T>()` returns true if and only if T is any of the following types:
`bool`, `char`, `signed char`, `unsigned char`, `short`, `unsigned short`, `int`, `unsigned int`, `long`, `unsigned long`, `long long`, `unsigned long long`, `int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t`, `uint32_t`, `int64_t`, `uint64_t`, `char8_t`, `char16_t`, `char32_t`, `wchar_t`, `intptr_t`, `uintptr_t`, `size_t`, `ptrdiff_t`

`hwy::IsFixedSizeInteger<T>()` returns true if and only if T is any of the following types:
`int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t`, `uint32_t`, `int64_t`, `uint64_t`

`hwy::IsFixedSizeInteger<T>()` only includes the integer types that are valid for a Highway vector lane whereas `hwy::Integer<T>()` includes some additional integer types.

There are some use cases for a separate `hwy::Integer<T>()` that returns true for some additional integer types, including enabling operations such as `PopCount`, `Num0BitsBelowLS1Bit`, and `Num0BitsAboveMS1Bit` for additional integer types other than those for which `hwy::IsFixedSizeInteger<T>()` would return true.

**Comment by jan-wassenberg** [comment]
These sound like useful traits to add 👍 Would you like to add them?
I wonder about the name: char8_t and even char (by definition size 1) are also fixed-size. Perhaps the real distinction is whether we support/allow them as lane types. Then maybe IsIntegerLaneType or IsSupportedIntegerType?

**Comment by johnplatts** [comment]
> These sound like useful traits to add 👍 Would you like to add them? I wonder about the name: char8_t and even char (by definition size 1) are also fixed-size. Perhaps the real distinction is whether we support/allow them as lane types. Then maybe IsIntegerLaneType or IsSupportedIntegerType?

IsIntegerLaneType is a better name for integer types that are supported as Highway lane types.
