### ISSUE TITLE
What is the cl/448957386 in FAQ document?

### ISSUE THREAD

**Issue by LXYan2333** [google/highway#1728]
When I read the document, I found weired `cl/448957386` `cl/450480902` (and more) in [FAQ](https://google.github.io/highway/en/master/faq.html). what are them?

![图片](https://github.com/google/highway/assets/15712263/a9155db0-0531-4ed2-82cb-292c242e41bf)

![图片](https://github.com/google/highway/assets/15712263/b3745a0e-bfd2-4b12-87bd-83665a3490d2)

**Comment by jan-wassenberg** [comment]
Hi, these are CL (changelist) numbers, i.e. references to our version control system. The contents of the CL are internal to Google, but the existence and numbers themselves are public.

You can see similar examples in the Compiler Explorer links in the [readme](https://github.com/google/highway#examples).

**Comment by LXYan2333** [comment]
Hello, thank you for your reply.
If the content of these changelist is internal to Google, maybe the document can be improved by removing those `cl/`s? Or add some notes?
