### ISSUE TITLE
Add custom Shuffle

### ISSUE THREAD

**Issue by MattiaMontanari** [google/highway#1731]
Firstly, HWY is awesome! 
I would like to implement shuffle operations that are not provided by default. For example, `Shuffle3021`, is useful to implement cross-product on 3D vectors. What is the best solution? Should I create my own macro combining shuffles and swizzles, or I should create a PR and implement a native HWY op? 
I don't see other solutions to achieve `Shuffle3021`, if I miss it, let me know as that could help others too :)

**Comment by jan-wassenberg** [comment]
Thank you, that's nice to hear :)

I think the Per4LaneBlockShuffle op can be used for this, assuming you want 3021 within each 128-bit block?

**Comment by MattiaMontanari** [comment]
Great! For reference, here's the solution on [compiler explorer](https://gcc.godbolt.org/z/aPMY5W9E5)
