### ISSUE TITLE
riscv64/LTO: lto1: fatal error: target specific builtin not available

### ISSUE THREAD

**Issue by malaterre** [google/highway#1740]
Seems like default flag: ` -march=rv64gcv1p0` is conflicting with `-flto=auto`. Will need to dig further.

ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=1.0.7-3&stamp=1694507044&raw=0

**Comment by jan-wassenberg** [comment]
Thanks for reporting. Sounds like a compiler bug. Would you suggest any code changes or documentation updates?

**Comment by jan-wassenberg** [comment]
Yes indeed, I think you mean #838?
And in the meantime, your proposal is to add HWY_CMAKE_RVV that if set, adds -march=rv64gcv1p0 to HWY_FLAGS?

**Comment by jan-wassenberg** [comment]
Thanks, that makes sense. hm, I had forgotten that we already detect HWY_RISCV in CMake and add that flag to HWY_FLAGS. Is the issue that HWY_RISCV is not being detected correctly in CMake? (by checking __riscv)

Or should we add `target_link_options(hwy PRIVATE ${HWY_FLAGS})` as you mention, unconditionally or only for HWY_RISCV?

**Comment by jan-wassenberg** [comment]
Right. Ah, I see, you wanted to make the existing "always set march=gcv" conditional upon both RISCV and the user-specified flag. That makes sense, thanks for sending the PR!

**Comment by k0tran** [comment]
Just tested it out on pioneer
@jan-wassenberg for compiling it required `-march` in linker flags too so I propose adding this line after CMakeLists:381
```CMakeLists.txt
      add_link_options(-march=rv64gcv1p0)
```
This turns on flag for all targets, I tried turning it on for hwy only, but it did not work
If this is fine by you I could make it into PR.

**Comment by jan-wassenberg** [comment]
Thanks @k0tran :) As mentioned above, we'd like to eventually get to a state where we don't have any -march, and that pragma attributes take care of enabling V extension.

Clang is not quite ready for this yet, see https://github.com/llvm/llvm-project/issues/56592. But if you make the add_link_options conditional on HWY_CMAKE_RVV, that would be fine and we'd welcome a PR :)

**Comment by k0tran** [comment]
Yes @jan-wassenberg , I understand that this is temporary solution, but these bugs are old. Would be nice to have solution at least for now.
I've also ran tests and two of them are failing (see logs below)
As I'm quite new to the project I would like to ask If you have some wild guesses what it may be caused
```
99% tests passed, 2 tests failed out of 365

Total Test time (real) =   6.12 sec

The following tests FAILED:
    308 - ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904 (ILLEGAL)
    309 - ImageTestGroup/ImageTest.TestUnaligned/SCALAR  # GetParam() = 4611686018427387904 (ILLEGAL)
Errors while running CTest
Output from these tests are in: /usr/src/RPM/BUILD/highway-1.2.0/riscv64-alt-linux/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
In LastTest.log (the other test fails similarly):
```
308/365 Testing: ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904
308/365 Test: ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904
Command: "/usr/src/RPM/BUILD/highway-1.2.0/riscv64-alt-linux/tests/image_test" "--gtest_filter=ImageTestGroup/ImageTest.TestAligned/SCALAR" "--gtest_also_run_disabled_tests"
Directory: /usr/src/RPM/BUILD/highway-1.2.0/riscv64-alt-linux
"ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904" start time: Aug 14 06:32 UTC
Output:
----------------------------------------------------------
WARNING: CPU supports 0x6000000000000000, software requires 0x4000002000000000
WARNING: CPU supports 0x6000000000000000, software requires 0x4000002000000000
Running main() from /usr/src/RPM/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = ImageTestGroup/ImageTest.TestAligned/SCALAR
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ImageTestGroup/ImageTest
[ RUN      ] ImageTestGroup/ImageTest.TestAligned/SCALAR
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904" end time: Aug 14 06:32 UTC
"ImageTestGroup/ImageTest.TestAligned/SCALAR  # GetParam() = 4611686018427387904" time elapsed: 00:00:00
```
It's just falls silently. I'm not sure where to start

**Comment by jan-wassenberg** [comment]
I agree the bugs are old. Progress in compilers is a bit uneven :)

The issue is likely identified by 'WARNING: CPU supports 0x6000000000000000'. Bit 37 being zero indicates RVV is not supported, or at least that we are unable to detect it. Are we sure the CPU and OS actually support V?

Some Linux versions require opting in to V, e.g. because they don't save the vector regs in context switches otherwise.

**Comment by k0tran** [comment]
Thanks! Actually it's not supported on machine at the moment, but compiler says it does. So it's not related to highway. I will test it on rvv machine though, If I get one at some point
