### ISSUE TITLE
one more warning :)

### ISSUE THREAD

**Issue by boxerab** [google/highway#175]
@jan-wassenberg thank you for the fixes, my builds are looking nice and clean now.

There seems to be just one more warning left, on windows:
https://my.cdash.org/viewBuildError.php?type=1&buildid=2005411

**Comment by jan-wassenberg** [comment]
@boxerab You're welcome! Can you help diagnose this one? It's the only spot where we use `suppress`, that does not seem to work.
I figured it applies to the next line *after* preprocessing, but the `#endif` might interfere.
Alternatively, it might not be enough to disable it inside the function and we need it outside, like the other `HWY_DIAGNOSTICS_OFF`.

Can you confirm that
```
HWY_DIAGNOSTICS(push)
HWY_DIAGNOSTICS_OFF(disable : 4556, ignored "-Wsign-conversion")
```
before DemoteTo  and `HWY_DIAGNOSTICS(push)` afterwards, fixes it? (The  "sign conversion" is just so gcc/clang have a well-formed directive, I do not see an equivalent warning setting for them.)

**Comment by boxerab** [comment]
thanks, warning is no more with following code: 

```
HWY_DIAGNOSTICS(push)
HWY_DIAGNOSTICS_OFF(disable : 4556, ignored "-Wsign-conversion")
HWY_API Vec128<float16_t> DemoteTo(Full128<float16_t> /* tag */,
                                   const Vec256<float> v) {
  return Vec128<float16_t>{_mm256_cvtps_ph(v.raw, _MM_FROUND_NO_EXC)};
}
HWY_DIAGNOSTICS(pop)
```

**Comment by jan-wassenberg** [comment]
Thanks for confirming, will update the code accordingly.
