### ISSUE TITLE
powerpc / no-htm issue (was inlining failed in PreventElision)

### ISSUE THREAD

**Issue by malaterre** [google/highway#1751]
Since #1707 has been closed, let me open a new one to track progress. Either:

1. Apply `-mno-htm` on entire codebase (like a PPC_FLAG in cmake)
2. Apply a #pragma on PreventElision 

In commit 725e0a6532b5580e2d1b31007f01931fa4acfc1d the following was added:

`#define HWY_TARGET_STR_PPC10 HWY_TARGET_STR_PPC9 ",cpu=power10,no-htm"`

this is incorrect as power10 implies no-htm.

**Comment by jan-wassenberg** [comment]
Thanks for opening a new issue. If you prefer, re-opening is also an option :)
The fix is coming shortly.

**Comment by jan-wassenberg** [comment]
No worries at all. Thank you for helping to get this properly fixed :)

Hah, the fix is indeed very low-level and documentation is very scarce. I appreciate you filing/linking to the GCC bugs, the hints there from GCC devs were very helpful.
