### ISSUE TITLE
Add ops that wrap SSE4 _mm_mpsadbw_epu8 and AVX3 _mm_dbsad_epu8

### ISSUE THREAD

**Issue by johnplatts** [google/highway#1779]
`_mm_mpsadbw_epu8(a, b, (kAOffset << 2) | kBOffset)` is equivalent to the operation below:
```
template <int kAOffset, int kBOffset, class VU8>
static Vec<RepartitionToWide<DFromV<VU8>>> Mpsadbw(VU8 a, VU8 b) {
  static_assert(0 <= kAOffset && kAOffset <= 1,
                "kAOffset must be between 0 and 1");
  static_assert(0 <= kBOffset && kBOffset <= 3,
                "kBOffset must be between 0 and 3");
  const DFromV<decltype(a)> du8;
  const RepartitionToWide<decltype(du8)> du16;
  const RepartitionToWide<decltype(du16)> du32;

  /* a01: { a[kAOffset*4+0], a[kAOffset*4+1], a[kAOffset*4+1], a[kAOffset*4+2],
            a[kAOffset*4+2], a[kAOffset*4+3], a[kAOffset*4+3], a[kAOffset*4+4],
            a[kAOffset*4+4], a[kAOffset*4+5], a[kAOffset*4+5], a[kAOffset*4+6],
            a[kAOffset*4+6], a[kAOffset*4+7], a[kAOffset*4+7], a[kAOffset*4+8] }
   */
  const auto a01 = InterleaveLower(du8, ShiftRightBytes<kAOffset * 4>(du8, a),
                                   ShiftRightBytes<kAOffset * 4 + 1>(du8, a));
  /* a23: { a[kAOffset*4+2], a[kAOffset*4+3], a[kAOffset*4+3], a[kAOffset*4+4],
            a[kAOffset*4+4], a[kAOffset*4+5], a[kAOffset*4+5], a[kAOffset*4+6],
            a[kAOffset*4+6], a[kAOffset*4+7], a[kAOffset*4+7], a[kAOffset*4+8],
            a[kAOffset*4+8], a[kAOffset*4+9], a[kAOffset*4+9], a[kAOffset*4+10]
     } */
  const auto a23 =
      InterleaveLower(du8, ShiftRightBytes<kAOffset * 4 + 2>(du8, a),
                      ShiftRightBytes<kAOffset * 4 + 3>(du8, a));

  /* b0123: { b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+2],
     b[kBOffset*4+3], b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+2],
     b[kBOffset*4+3], b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+2],
     b[kBOffset*4+3], b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+2],
     b[kBOffset*4+3] } */
  const auto b0123 = BitCast(du8, Broadcast<kBOffset>(BitCast(du32, b)));

  /* b01: { b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+0], b[kBOffset*4+1],
            b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+0], b[kBOffset*4+1],
            b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+0], b[kBOffset*4+1],
            b[kBOffset*4+0], b[kBOffset*4+1], b[kBOffset*4+0], b[kBOffset*4+1] }
   */
  /* b23: { b[kBOffset*4+2], b[kBOffset*4+3], b[kBOffset*4+2], b[kBOffset*4+3],
            b[kBOffset*4+2], b[kBOffset*4+3], b[kBOffset*4+2], b[kBOffset*4+3],
            b[kBOffset*4+2], b[kBOffset*4+3], b[kBOffset*4+2], b[kBOffset*4+3],
            b[kBOffset*4+2], b[kBOffset*4+3], b[kBOffset*4+2], b[kBOffset*4+3] }
   */
  const auto b01 = BitCast(du8, DupEven(BitCast(du16, b0123)));
  const auto b23 = BitCast(du8, DupOdd(BitCast(du16, b0123)));

  const auto absdiff_sum_01 = SumsOf2(AbsDiff(a01, b01));
  const auto absdiff_sum_23 = SumsOf2(AbsDiff(a23, b23));
  return Add(absdiff_sum_01, absdiff_sum_23);
}
```

`_mm_mpsadbw_epu8(a, b, (kAOffset << 2) | kBOffset)` is more efficient than the generic Mpsadbw implementation above on SSE4/AVX2/AVX3.

`Mpsadbw<kAOffset, kBOffset>(a, b)` returns `|a[kAOffset*4+i] - b[kBOffset*4]| +
|a[kAOffset*4+i+1] - b[kBOffset*4+1]| + |a[kAOffset*4+i+2] - b[kBOffset*4+2]| +
|a[kAOffset*4+i+3] - b[kBOffset*4+3]|`, promoted to an uint16_t lane.

For vectors that are 32 bytes or larger, `Mpsadbw<kAOffset, kBOffset>(a, b)` is a blockwise operation that operates on each 16-byte block of `a` and `b`.

`_mm_dbsad_epu8(a, b, _MM_SHUFFLE(kIdx3, kIdx2, kIdx1, kIdx0))` is equivalent to
the following:
```
template <size_t kIdx3, size_t kIdx2, size_t kIdx1, size_t kIdx0, class VU8>
static Vec<RepartitionToWide<DFromV<VU8>>> Dbsad(VU8 a, VU8 b) {
  const DFromV<decltype(a)> du8;
  const RepartitionToWide<decltype(du8)> du16;
  const RepartitionToWide<decltype(du16)> du32;
  const RepartitionToWide<decltype(du32)> du64;

  const auto b_shuf = BitCast(
      du8, Per4LaneBlockShuffle<kIdx3, kIdx2, kIdx1, kIdx0>(BitCast(du32, b)));
  const auto b_0123_2345 =
      BitCast(du8, OddEven(BitCast(du32, ShiftLeftLanes<2>(du8, b_shuf)),
                           BitCast(du32, b_shuf)));
  const auto b_1234_3456 =
      BitCast(du8, OddEven(BitCast(du32, ShiftLeftLanes<3>(du8, b_shuf)),
                           BitCast(du32, ShiftLeftLanes<1>(du8, b_shuf))));

  auto even_sums = BitCast(du16, SumsOf4(AbsDiff(a, b_0123_2345)));
  auto odd_sums = BitCast(du16, SumsOf4(AbsDiff(a, b_1234_3456)));

#if HWY_IS_LITTLE_ENDIAN
  odd_sums = DupEven(odd_sums);
#else
  even_sums = DupOdd(even_sums);
#endif

  return OddEven(odd_sums, even_sums);
}
```

`_mm_dbsad_epu8(a, b, _MM_SHUFFLE(kIdx3, kIdx2, kIdx1, kIdx0))` is more efficient than the generic Dbsad implementation above on AVX3.

`Dbsad<kIdx3, kIdx2, kIdx1, kIdx0>(a, b)` returns `|a[(i/2)*4] - b_shuf[(i/4)*8+(i&3)]| + |a[(i/2)*4+1] - b_shuf[(i/4)*8+(i&3)+1]| + |a[(i/2)*4+2] - b_shuf[(i/4)*8+(i&3)+2]| + |a[(i/2)*4+3] - b_shuf[(i/4)*8+(i&3)+3]|`, promoted to an uint16_t lane, where `b_shuf` is equal to `BitCast(du8, Per4LaneBlockShuffle<kIdx3, kIdx2, kIdx1, kIdx0>(BitCast(du32, b)))`.

Mpsadbw can also be implemented using Dbsad (and this can be used to implement Mpsadbw for 64-bit uint8_t vectors on AVX3 as there is no _mm512_mpsadbw_epu8 intrinsic available on AVX3):
```
template <int kAOffset, int kBOffset, class VU8>
static Vec<RepartitionToWide<DFromV<VU8>>> Mpsadbw(VU8 a, VU8 b) {
  static_assert(0 <= kAOffset && kAOffset <= 1,
                "kAOffset must be between 0 and 1");
  static_assert(0 <= kBOffset && kBOffset <= 3,
                "kBOffset must be between 0 and 3");
  return Dbsad<kAOffset + 2, kAOffset + 1, kAOffset + 1, kAOffset>(
      Broadcast<kBOffset>(b), a);
}
```

There are actual use cases for adding operations that wrap the above Dbsad and Mpsadbw operations to Google Highway, including video codecs.

The Dbsad and Mpsadbw operations above are not supported on the HWY_SCALAR target.

**Comment by johnplatts** [comment]
Here is a possible implementation of Dbsad for SSE4/AVX2:
```
template <size_t kIdx3, size_t kIdx2, size_t kIdx1, size_t kIdx0, class VU8>
static Vec<RepartitionToWide<DFromV<VU8>>> Dbsad(VU8 a, VU8 b) {
  const DFromV<decltype(a)> du8;
  const RepartitionToWide<decltype(du8)> du16;
  const RepartitionToWide<decltype(du16)> du32;

  const auto b_shuf = BitCast(
      du8, Per4LaneBlockShuffle<kIdx3, kIdx2, kIdx1, kIdx0>(BitCast(du32, b)));

  const auto r10 = Mpsadbw<0, 0>(b_shuf, a);
  const auto r32 = Mpsadbw<0, 1>(b_shuf, a);
  const auto r54 = Mpsadbw<1, 2>(b_shuf, a);
  const auto r76 = Mpsadbw<1, 3>(b_shuf, a);

  const auto r3210 = BitCast(du16, OddEven(BitCast(du32, r32), BitCast(du32, r10)));
  const auto r7654 = BitCast(du16, OddEven(BitCast(du32, r76), BitCast(du32, r54)));
  return BitCast(du16, OddEven(BitCast(du64, r7654), BitCast(du64, r3210)));
}
```

**Comment by jan-wassenberg** [comment]
Thanks for proposing these. I am pleasantly surprised that emulating MPSADBW is not unreasonable.

If there is a project that will use, or better yet: already is using these instructions, we can certainly add them. Can you point us to more information about them?

FYI at one point we were using MPSADBW in JPEG XL but 8-bit precision is not quite enough, and instead of brute-force 3x4 pattern search in a large window, it turned out to be better and still affordable to use normal i16 instructions for just a 4-tap kernel and a sparse search region. My understanding is that video codecs have also moved toward diamond-shaped or sparse windows, and they also often want more than 8 bit pixels. Hence the question about where this would be used :)

While we're at it, I notice that `_mm*_dbsad_epu8` could be used to speed up the new SumsOf4 - would you be interested in adding such an optimization? Otherwise I can :)

**Comment by johnplatts** [comment]
> Thanks for proposing these. I am pleasantly surprised that emulating MPSADBW is not unreasonable.
> 
> If there is a project that will use, or better yet: already is using these instructions, we can certainly add them. Can you point us to more information about them?

The  _mm_mpsadbw_epu8/_mm256_mpsadbw_epu8 intrinsics are used to accelerate motion detection, game physics, text searching, and some video codecs such as VP9/AV1/HEVC.

**Comment by jan-wassenberg** [comment]
Thanks for pointing that out. I am surprised VP9 and SVT-AV1 are actually still using this instruction ([search](https://sourcegraph.com/search?q=context:global+count:4000+mpsadbw_epu8+-path:rs%24+-path:cs%24+-path:intrin%5C.+-path:sse2neon+-repo:sse2neon+-path:scala%24+-path:simde/+-repo:/simde+-path:test/codegen/+-path:gcc/testsuite+-path:GCC/DJGPP+-path:BackUpThis+-path:html%24+-path:md%24+-path:SSEPlus+-path:nim%24+-path:js%24+-path:json%24+-path:odin%24+-path:xml%24+-path:rb%24+-path:%5C.go%24+-repo:cheatsheats+-path:rst%24+-path:test/+-path:tests/+-path:pik/+-path:svn-base%24+-path:traps.c%24+-path:gcc.target+-path:%5C.m%24+-path:singeli%24+-path:builtins_icc+-path:intrinsics.h%24++-path:py%24+-path:patch%24&patternType=standard&sm=1&groupBy=repo)). Also a couple other hits, including for strstr.

I think this meets our bar of potential usefulness and we'd welcome a PR for these ops 👍
