### ISSUE TITLE
ARM64 `SVE` target failed tests

### ISSUE THREAD

**Issue by fbarbari** [google/highway#1799]
Hello,
I compiled Highway 1.0.7 on a Fujitsu A64FX and these tests failed.
```
400 - HwyCryptoTestGroup/HwyCryptoTest.TestAllAES/NEON  # GetParam() = 268435456 (ILLEGAL)
404 - HwyCryptoTestGroup/HwyCryptoTest.TestAllAESInverse/NEON  # GetParam() = 268435456 (ILLEGAL)
408 - HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/NEON  # GetParam() = 268435456 (ILLEGAL)
```

I configured Highway with these flags with cmake 3.26.3:
```bash
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`realpath ~/local` -DHWY_SYSTEM_GTEST=ON -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -mcpu=a64fx"
```

When compiling (with clang 16.0.6), these are the detected targets:
```
Compiled HWY_TARGETS:   SVE_256 SVE
HWY_ATTAINABLE_TARGETS: SVE_256 SVE NEON NEON_WITHOUT_AES EMU128
HWY_BASELINE_TARGETS:   SVE NEON NEON_WITHOUT_AES EMU128
HWY_STATIC_TARGET:      SVE
HWY_BROKEN_TARGETS:    
HWY_DISABLED_TARGETS:  
Current CPU supports:   SVE NEON NEON_WITHOUT_AES EMU128 SCALAR
```

**Comment by jan-wassenberg** [comment]
Thanks for reporting the issue. Looks like AES related tests, and the NEON target indeed includes AES instructions. I see from the A64FX microarchitecture guide that AESD/AESE etc are supported.

Are you able to run with `ctest --output-on-failure option` to print details on what exactly is failing? And if it actually is a SIGILL exception, can you run the crypto_test inside a debugger to see which instruction it is?

**Comment by fbarbari** [comment]
`ctest --output-on-failure option` output:
```
Test project /ccc/cont005/home/cineca/barbarif/highway-1.0.7/build
    Start 400: HwyCryptoTestGroup/HwyCryptoTest.TestAllAES/NEON  # GetParam() = 268435456
1/3 Test #400: HwyCryptoTestGroup/HwyCryptoTest.TestAllAES/NEON  # GetParam() = 268435456 ..........***Exception: Illegal  0.17 sec
Running main() from /ccc/cont005/home/cineca/barbarif/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyCryptoTestGroup/HwyCryptoTest.TestAllAES/NEON
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyCryptoTestGroup/HwyCryptoTest
[ RUN      ] HwyCryptoTestGroup/HwyCryptoTest.TestAllAES/NEON

    Start 404: HwyCryptoTestGroup/HwyCryptoTest.TestAllAESInverse/NEON  # GetParam() = 268435456
2/3 Test #404: HwyCryptoTestGroup/HwyCryptoTest.TestAllAESInverse/NEON  # GetParam() = 268435456 ...***Exception: Illegal  0.17 sec
Running main() from /ccc/cont005/home/cineca/barbarif/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyCryptoTestGroup/HwyCryptoTest.TestAllAESInverse/NEON
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyCryptoTestGroup/HwyCryptoTest
[ RUN      ] HwyCryptoTestGroup/HwyCryptoTest.TestAllAESInverse/NEON

    Start 408: HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/NEON  # GetParam() = 268435456
3/3 Test #408: HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/NEON  # GetParam() = 268435456 ........***Exception: Illegal  0.18 sec
Running main() from /ccc/cont005/home/cineca/barbarif/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/NEON
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyCryptoTestGroup/HwyCryptoTest
[ RUN      ] HwyCryptoTestGroup/HwyCryptoTest.TestAllCLMul/NEON


```

`crypto_test` source:
```
hwy::N_NEON::AESRound(hwy::N_NEON::Vec128<unsigned char, 16ul>, hwy::N_NEON::Vec128<unsigned char, 16ul>) ()
```
`crypto_test` asm:
```
aese   v0.16b, v1.16b
```
(do you need the asm of the whole function?)

**Comment by jan-wassenberg** [comment]
Thanks for confirming. Interesting, it does seem to be an AES instruction that is faulting.
It is possible that AES instructions are disabled/trapped by the OS? Does /proc/cpuinfo mention "aes"?

**Comment by fbarbari** [comment]
Actually, it doesn't support AES instructions, to my surprise! These are the flags reported in `/proc/cpuinfo`: `fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve`. So I guess it's Highway's fault.

**Comment by jan-wassenberg** [comment]
Interesting, thanks for confirming. Indeed we are detecting that the CPU supports AES, according to the OS, via this code in targets.cc:

```
  const CapBits hw = getauxval(AT_HWCAP);
#if HWY_ARCH_ARM_A64
  // .. but not necessarily AES, which is required for HWY_NEON.
#if defined(HWCAP_AES)
  if (hw & HWCAP_AES) {
    bits |= HWY_NEON;
```

Can you confirm via printf or abort that this `    bits |= HWY_NEON;` line is in fact reached?

If so, it's very curious that getauxval would be incorrect. Our code seems to match an [example](https://community.arm.com/arm-community-blogs/b/operating-systems-blog/posts/runtime-detection-of-cpu-features-on-an-armv8-a-cpu).

Are there any other flags we could check to detect this properly on your system?

**Comment by jan-wassenberg** [comment]
Thanks for adding the printfs! I see that we only add HWY_NEON to HWY_BASELINE_NEON if the compiler sets __ARM_FEATURE_AES, which looks correct. 

As to why the printf is skipped: we are compiling with clang, but the runtime dispatch is only known to work with (and thus enabled for) GCC. If !HWY_HAVE_RUNTIME_DISPATCH [1], then we assume the presence of all CPU features enabled by compiler flags instead of detecting. This is risky but reasonable because the compiler could also be generating those instructions, and if they weren't supported by the CPU, the binary would crash anyway.

But it seems that your -mcpu sets __ARM_FEATURE_AES, which might be a misunderstanding; I think that's NEON AES, which your CPU indeed does not support.

To work around this, we could still run the CPU feature detection, and thus skip the HWY_NEON target which requires AES.
In targets.cc, could you change the second `HWY_ARCH_ARM && HWY_HAVE_RUNTIME_DISPATCH` (in DetectTargets) to `HWY_ARCH_ARM` and confirm that fixes the problem?


1: The prereqs for HWY_HAVE_RUNTIME_DISPATCH are `HWY_COMPILER_GCC_ACTUAL && HWY_OS_LINUX && !defined(TOOLCHAIN_MISS_SYS_AUXV_H)`

**Comment by jan-wassenberg** [comment]
A quick update, we are getting close to enabling runtime dispatch for aarch64+clang, which would fix that.

Per the output you provided above, we are correctly detecting that the system somehow does not support AES, even though the CPU should. That should prevent the SIGILL crash.

**Comment by jan-wassenberg** [comment]
I think the crashes are now resolved. FYI and update on the runtime dispatch: it now works also for Arm, but requires Clang 17 or later.
Closing, please reopen if there is still an issue :)
