### ISSUE TITLE
arm_sve-inl.h:1530:73: error: unsigned conversion from 'int' to 'uint32_t' {aka 'unsigned int'} changes value from '-16777216' to '4278190080' [-Werror=sign-conversion]

### ISSUE THREAD

**Issue by malaterre** [google/highway#1824]
sign-conversion is now part of the compilation flag. aarch64 fails to compile with:

[ 32%] Building CXX object CMakeFiles/highway_test.dir/hwy/highway_test.cc.o
In file included from /home/malat/m/highway/hwy/highway.h:418,
                 from /home/malat/m/highway/hwy/highway_test.cc:25,
                 from /home/malat/m/highway/hwy/foreach_target.h:174,
                 from /home/malat/m/highway/hwy/highway_test.cc:24:
/home/malat/m/highway/hwy/ops/arm_sve-inl.h: In instantiation of 'svbool_t hwy::N_SVE::IsInf(V) [with V = __SVFloat32_t; svbool_t = svbool_t]':
/home/malat/m/highway/hwy/highway_test.cc:434:5:   required from 'void hwy::N_SVE::TestIsInf::operator()(T, D) [with T = float; D = hwy::N_SVE::Simd<float, 64, 0>]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:195:13:   required from 'static void hwy::N_SVE::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = float; long unsigned int kMul = 64; long unsigned int kMinArg = 1; Test = hwy::N_SVE::TestIsInf; int kPow2 = 0; size_t = long unsigned int]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:341:63:   required from 'void hwy::N_SVE::ForExtendableVectors<Test, kPow2>::operator()(T) const [with T = float; Test = hwy::N_SVE::TestIsInf; int kPow2 = 0]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:565:36:   required from 'void hwy::N_SVE::ForPartialVectors<Test>::operator()(T) const [with T = float; Test = hwy::N_SVE::TestIsInf]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:679:7:   required from 'void hwy::N_SVE::ForFloat3264Types(const Func&) [with Func = ForPartialVectors<TestIsInf>]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:686:20:   required from 'void hwy::N_SVE::ForFloatTypes(const Func&) [with Func = ForPartialVectors<TestIsInf>]'
/home/malat/m/highway/hwy/highway_test.cc:446:16:   required from here
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:1530:73: error: unsigned conversion from 'int' to 'uint32_t' {aka 'unsigned int'} changes value from '-16777216' to '4278190080' [-Werror=sign-conversion]
 1530 |   return RebindMask(d, Eq(Add(vu, vu), Set(du, hwy::MaxExponentTimes2<T>())));
      |                                                ~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by jan-wassenberg** [comment]
Thanks, fixing shortly :)
