### ISSUE TITLE
arm_sve-inl.h:2819:20: error: no matching function for call to 'IfThenElse(const svbool_t&, const __SVBfloat16_t&, const __SVBfloat16_t&)'

### ISSUE THREAD

**Issue by malaterre** [google/highway#1827]
Could you also check this one:

[ 52%] Building CXX object CMakeFiles/dup128_vec_test.dir/hwy/tests/dup128_vec_test.cc.o
In file included from /home/malat/m/highway/hwy/highway.h:418,
                 from /home/malat/m/highway/hwy/tests/dup128_vec_test.cc:19,
                 from /home/malat/m/highway/hwy/foreach_target.h:196,
                 from /home/malat/m/highway/hwy/tests/dup128_vec_test.cc:18:
/home/malat/m/highway/hwy/ops/arm_sve-inl.h: In instantiation of 'V hwy::N_SVE_256::ConcatUpperUpper(D, V, V) [with D = Simd<hwy::bfloat16_t, 16, 0>; V = __SVBfloat16_t]':
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:3413:45:   required from 'V hwy::N_SVE_256::BroadcastBlock(V) [with int kBlockIdx = 0; V = __SVBfloat16_t]'
/home/malat/m/highway/hwy/tests/dup128_vec_test.cc:114:29:   required from 'static hwy::N_SVE_256::Vec<D> hwy::N_SVE_256::TestDup128VecFromValues::BlockwiseIota(D, T) [with D = hwy::N_SVE_256::Simd<hwy::bfloat16_t, 16, 0>; T = int; hwy::EnableIf<IsSame<typename D::T, hwy::bfloat16_t>()>* <anonymous> = 0; hwy::N_SVE_256::Vec<D> = __SVBfloat16_t]'
/home/malat/m/highway/hwy/tests/dup128_vec_test.cc:174:5:   required from 'void hwy::N_SVE_256::TestDup128VecFromValues::operator()(T, D) [with T = hwy::bfloat16_t; D = hwy::N_SVE_256::Simd<hwy::bfloat16_t, 16, 0>]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:195:13:   required from 'static void hwy::N_SVE_256::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = hwy::bfloat16_t; long unsigned int kMul = 16; long unsigned int kMinArg = 1; Test = hwy::N_SVE_256::TestDup128VecFromValues; int kPow2 = 0; size_t = long unsigned int]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:341:63:   required from 'void hwy::N_SVE_256::ForExtendableVectors<Test, kPow2>::operator()(T) const [with T = hwy::bfloat16_t; Test = hwy::N_SVE_256::TestDup128VecFromValues; int kPow2 = 0]'
/home/malat/m/highway/hwy/tests/test_util-inl.h:565:36:   required from 'void hwy::N_SVE_256::ForPartialVectors<Test>::operator()(T) const [with T = hwy::bfloat16_t; Test = hwy::N_SVE_256::TestDup128VecFromValues]'
/home/malat/m/highway/hwy/tests/dup128_vec_test.cc:219:7:   required from here
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:2819:20: error: no matching function for call to 'IfThenElse(const svbool_t&, const __SVBfloat16_t&, const __SVBfloat16_t&)'
 2819 |   return IfThenElse(mask_upper, hi, lo_upper);
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:1199:39: note: candidate: 'svuint8_t hwy::N_SVE_256::IfThenElse(svbool_t, svuint8_t, svuint8_t)'
 1199 | HWY_SVE_FOREACH(HWY_SVE_IF_THEN_ELSE, IfThenElse, sel)
      |                                       ^~~~~~~~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:1195:7: note: in definition of macro 'HWY_SVE_IF_THEN_ELSE'
 1195 |       NAME(svbool_t m, HWY_SVE_V(BASE, BITS) yes, HWY_SVE_V(BASE, BITS) no) { \
      |       ^~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:97:3: note: in expansion of macro 'HWY_SVE_FOREACH_U08'
   97 |   HWY_SVE_FOREACH_U08(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:148:3: note: in expansion of macro 'HWY_SVE_FOREACH_U'
  148 |   HWY_SVE_FOREACH_U(X_MACRO, NAME, OP)     \
      |   ^~~~~~~~~~~~~~~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:1199:1: note: in expansion of macro 'HWY_SVE_FOREACH'
 1199 | HWY_SVE_FOREACH(HWY_SVE_IF_THEN_ELSE, IfThenElse, sel)
      | ^~~~~~~~~~~~~~~
/home/malat/m/highway/hwy/ops/arm_sve-inl.h:1195:46: note:   no known conversion for argument 2 from 'const __SVBfloat16_t' to 'svuint8_t'

... and so on

**Comment by jan-wassenberg** [comment]
Fix is on the way :)

**Comment by jan-wassenberg** [comment]
I think this is done, closing :)
