### ISSUE TITLE
Build on minor platforms

### ISSUE THREAD

**Issue by saschanaz** [google/highway#183]
I got a report that [highway causes build failures on minor platforms](https://bugzilla.mozilla.org/show_bug.cgi?id=1707590#c25), at:

https://github.com/google/highway/blob/79dd4884e6b2d4a9804b250af6f5ac57a35edae1/hwy/base.h#L252-L255

Could there be a fallback for those?

**Comment by jan-wassenberg** [comment]
@saschanaz thanks for reaching out. I will audit all uses of HWY_ARCH and then remove this `#error`.
