### ISSUE TITLE
Potential sub-optimal AVX512 codegen for DupEven/DupOdd for 16-bit integer types

### ISSUE THREAD

**Issue by ag01** [google/highway#1870]
Hi,

Just to share what I think is some sub-optimal codegen for the AVX target that was spotted for the DupEven/DupOdd functions.

I see vbroadcasti32x4 and vpshufb being generated, where this could really be implemented with a single vpshufb.

See https://godbolt.org/z/Teencnfhc

I presume this is due to the use of LoadDup128 within the DupEven/DupOdd implementation instead of Dup128VecFromValues?

Regards

**Comment by jan-wassenberg** [comment]
FYI I am first finishing a major revamp of f16/bf16. This is taking longer than expected and might spill into early next week.
