### ISSUE TITLE
`Error: unknown architectural extension 'sve2-aes'` when compiling on Graviton3

### ISSUE THREAD

**Issue by fbarbari** [google/highway#1881]
Steps to reproduce:
```
git clone https://github.com/google/highway.git
cd highway
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cd build
make all
```

Commit SHA: 326ac6cd2aaa7c5944ca120d6a4d12ee7efd4717
Cmake version: 3.26.3
GCC version: 13.1.0

Output of `lscpu`:
```
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               1
Stepping:            r1p1
BogoMIPS:            2100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            32768K
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs paca pacg dcpodp svei8mm svebf16 i8mm bf16 dgh rng
```

**Comment by jan-wassenberg** [comment]
Hi, thanks for reporting this.
Interestingly, in Godbolt GCC 13.1 seems to work fine: https://gcc.godbolt.org/z/5jfdfn7ab

Does anyone know if Graviton3 ships with a GCC tailored to what their core can do? If so, is there any way to detect this?

**Comment by jan-wassenberg** [comment]
Nice. It's probably helpful to use a newer GCC than 7.3, so perhaps one good way forward is to build GCC from source, or is there some other package repo available?

**Comment by fbarbari** [comment]
I just tried with a freshly compiled gcc 13.2.0 and the problem still persists. I will try with clang in the next hours and update you.

**Comment by Xarbirus** [comment]
Just got the same problem with gcc-11.4 building [gemma.cpp](https://github.com/google/gemma.cpp)

**Comment by jan-wassenberg** [comment]
Thanks, gcc-11.4 is a different issue. That compiler is too old to know about SVE2 and we should not be attempting to use it. I will update Highway to fix this. In the meantime, `-DHWY_DISABLED_TARGETS=(HWY_SVE2|HWY_SVE2_128)` should work around this.

**Comment by jan-wassenberg** [comment]
Sounds like progress :) I think [support was added](https://sourceware.org/pipermail/binutils-cvs/2019-May/050836.html) for that in GAS in 2019. Upgrading binutils sounds good!

**Comment by jan-wassenberg** [comment]
I think this is now resolved, please reopen if not :)

**Comment by sachin9689** [comment]
Still facing issues with gcc 13
