### ISSUE TITLE
Compilation error with GCC 10 and older 'call to non-constexpr function 'float hwy::F32FromF16'

### ISSUE THREAD

**Issue by ag01** [google/highway#1898]
Compilation error in hwy/base.h when using GCC 10 or older: https://godbolt.org/z/P9rWqnrbE

/opt/compiler-explorer/libs/highway/trunk/hwy/base.h: In function 'constexpr bool hwy::operator==(hwy::float16_t, hwy::float16_t)':
/opt/compiler-explorer/libs/highway/trunk/hwy/base.h:1049:20: error: call to non-constexpr function 'float hwy::F32FromF16(hwy::float16_t)'
   return F32FromF16(lhs) == F32FromF16(rhs);
          ~~~~~~~~~~^~~~~

**Comment by johnplatts** [comment]
Pull request #1884 has a fix for this compilation error
