### ISSUE TITLE
Support for AVX_VNNI as an extension to the AVX2 target

### ISSUE THREAD

**Issue by ag01** [google/highway#1912]
Hi there,

I was wondering if there was any planned support for adding support for the AVX_VNNI extension when targeting AVX2?

This would be useful for targeting Intel Raptor Lake/Meteor Lake platforms.

I imagine the main change would be surrounding the use of ReorderWidenMulAccumulate

Many thanks

**Comment by jan-wassenberg** [comment]
Hi @ag01 , I am not wildly enthusiastic about AVX_VNNI, nor int4/int8 arithmetic.
We can consider it depending on how useful this would be for your applications - and is anyone else interested?

One difficulty is which target bit this would get. We have one reserved between SPR and Zen4 for AVX10.2, and that would include AVX_VNNI. But I am not aware of the launch date for 10.2 being announced yet. Would you be OK to wait for that?

If not, and we add an AVX_VNNI target considered 'better' than SPR, then that would supplant the SPR target on P-cores with AVX10.1 and 10.2, right? That seems undesirable.

**Comment by ag01** [comment]
> Hi @ag01 , I am not wildly enthusiastic about AVX_VNNI, nor int4/int8 arithmetic. We can consider it depending on how useful this would be for your applications - and is anyone else interested?
> 
> One difficulty is which target bit this would get. We have one reserved between SPR and Zen4 for AVX10.2, and that would include AVX_VNNI. But I am not aware of the launch date for 10.2 being announced yet. Would you be OK to wait for that?
> 
> If not, and we add an AVX_VNNI target considered 'better' than SPR, then that would supplant the SPR target on P-cores with AVX10.1 and 10.2, right? That seems undesirable.

We only have a single, quite small use case for AVX_VNNI - I was mainly just interested to see if it was on the roadmap.

Thanks for explaining, that makes sense - we can happily wait for AVX10.2 and have no immediate need for AVX_VNNI.

**Comment by jan-wassenberg** [comment]
Sounds good, thanks for sharing :)
