### ISSUE TITLE
Test #537 failure upon building Highway-1.0.4 with GCCcore-12.3.0 on x86_64

### ISSUE THREAD

**Issue by monfortm** [google/highway#1913]
Trying to build Highway 1.0.4 fails on Zen4 CPU. 1 test (#537) is failing with the following log

```
537/1187 Test  #537: HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/AVX3_ZEN4  # GetParam() = 64 ........................................Subprocess aborted***Exception:   0.20 sec
Running main() from [...]/googletest/1.13.0/GCCcore-12.3.0/googletest-1.13.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/AVX3_ZEN4
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyConvertTestGroup/HwyConvertTest
[ RUN      ] HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/AVX3_ZEN4


u8x16 expect [0+ ->]:
  0x00,0x01,0x02,0x03,0x04,0x05,0x06,
u8x16 actual [0+ ->]:
  0x00,0x1A,0x02,0x1A,0x04,0x1A,0x06,
Abort at [...]/Highway/1.0.4/GCCcore-12.3.0/highway-1.0.4/hwy/tests/convert_test.cc:423: AVX3_ZEN4, u8x16 lane 1 mismatch: expected '0x01', got '0x1A'.

[...]

99% tests passed, 1 tests failed out of 1187

Total Test time (real) =  30.58 sec

The following tests FAILED:
        537 - HwyConvertTestGroup/HwyConvertTest.TestAllTruncate/AVX3_ZEN4  # GetParam() = 64 (Subprocess aborted)
Errors while running CTest
```

cc: @jpecar

**Comment by jan-wassenberg** [comment]
Thanks for letting us know. 1.04 is pretty old. Are you able to update to 1.0.7 or HEAD and see if that is also affected?

**Comment by monfortm** [comment]
Hello, thanks for the prompt answer. The thing is we need this specific version, as it's part of a dependency tree we have for a fairly recent software release...

**Comment by monfortm** [comment]
OK, we have moved from `1.0.4` to `1.0.7` and it solved the issue. Thanks for the heads up!

**Comment by jan-wassenberg** [comment]
Ah, I have been working on repro-ing the issue with SDE. Glad to hear it is solved for you, closing :)

**Comment by monfortm** [comment]
> Ah, I have been working on repro-ing the issue with SDE. Glad to hear it is solved for you, closing :)

Oh, I'm sorry, hope I did not waste your time 😳 thx again

**Comment by jan-wassenberg** [comment]
No worries, was anyway good to set up SDE, it's easier than going to a separate machine.
