### ISSUE TITLE
Build failure in tests

### ISSUE THREAD

**Issue by dbermond** [google/highway#1918]
I'm getting the the following build error in the tests:

```
/usr/bin/ld: /tmp/ccG3VOf7.ltrans0.ltrans.o: in function `hwy::(anonymous namespace)::ThreadPoolTest_TestCounter_Test::TestBody()':
<artificial>:(.text+0xc71): undefined reference to `hwy::ThreadPool::ThreadPool(unsigned long)'
/usr/bin/ld: <artificial>:(.text+0xcdd): undefined reference to `hwy::ThreadPool::StartWorkers(unsigned long)'
/usr/bin/ld: <artificial>:(.text+0xce6): undefined reference to `hwy::ThreadPool::WorkersReadyBarrier()'
/usr/bin/ld: <artificial>:(.text+0xdf0): undefined reference to `hwy::ThreadPool::~ThreadPool()'
```

There are tons of these errors. Complete log: [log.txt](https://github.com/google/highway/files/13772557/log-nodebug.txt)

Version 1.0.7 builds fine, but the current git master fails.

Steps used to build:
```
$ cmake -B build -S highway \
        -G 'Unix Makefiles' \
        -DCMAKE_BUILD_TYPE:STRING='None' \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DBUILD_SHARED_LIBS:BOOL='ON' \
        -DHWY_SYSTEM_GTEST:BOOL='ON' \
        -Wno-dev
$ cmake --build build
```

System information:
- OS: Arch Linux
- Compiler: gcc 13.2.1
- highway: git master (currently at commit ed26737)
- gtest: 1.14.0

**Comment by jan-wassenberg** [comment]
Happy new year! Thanks for letting us know. I think we are missing `HWY_CONTRIB_DLLEXPORT` on the declarations, will add them shortly :)

**Comment by dbermond** [comment]
Happy new year! I can confirm that it's now fixed on latest git master. Thank you for fixing this.
