### ISSUE TITLE
build fails on armv7 with neon enabled in: hwy/ops/arm_neon-inl.h:876:326: error: no matching function for call to 'hwy::N_NEON::Mask128<float

### ISSUE THREAD

**Issue by stefson** [google/highway#192]
hey, I decided to open a seperate issue for this. 

I ran into this when compiling latest firefox nightly on armv7, with neon enabled. I'm unaware of which highway version firefox devs do pull into their source tree, but here are the results: 

19:53.10 /usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox-90.0/third_party/highway/hwy/ops/arm_neon-inl.h:876:326: error: no matching function for call to 'hwy::N_NEON::Mask128<float, 4>::Mask128(uint32x4_t)'

here is the full build log, in case you're interested: [firefox-90-nightly-broken-arm.patch.zip](https://github.com/google/highway/files/6488918/firefox-90-nightly-broken-arm.patch.zip) , grep for error:` to find them all 

@jan-wassenberg you can delete the two unrelated postings from #188 I believe, I will relink this issue to the firefox upstream bug for reference. Thanks for your hard work :)

**Comment by jan-wassenberg** [comment]
@stefson thank you for opening the separate issue. I managed to build with a cross compiler and fixed the mask type and casts (surprising that clang and gcc diverged so much).

We'll look into making the cross compile part of the pre-release testing.

Can you please confirm that 4a47570daf29bfff0577541f8a0c0c342bf363cd fixes it?

**Comment by stefson** [comment]
I very much like to test compile this, but can you please provide some information about the standalone build? I'm not a cmake guy, all I know about this is doing: 

`git --clone https://github.com/google/highway.git`
`cd highway && mkdir build && cd build`
`cmake -DCMAKE_BUILD_TYPE=Release .. ` 
`make -jN `

**Comment by jan-wassenberg** [comment]
@stefson sure, I've added the [command line](https://github.com/google/highway/pull/197/commits/a07986fbab0da2391f1e554219e0d467d0c632ae).
There's also a [guide](https://ownyourbits.com/2018/06/13/transparently-running-binaries-from-any-architecture-in-linux-with-qemu-and-binfmt_misc/) with some background, including which packages to install.
Is that useful as a starting point?

**Comment by stefson** [comment]
ok, so I did two standalone test compiles from the build_dir: one with `cmake .. -DHWY_CMAKE_ARM7:BOOL=ON` , and one with only `cmake .. ` ; both with gcc-10.3.0

there are no compile errors, and no test failures

**Comment by jan-wassenberg** [comment]
@stefson excellent, thank you for confirming, closing the issue :)

**Comment by stefson** [comment]
so I'm going to ask the firefox devs to update the snapshot to the latest revision, and then hopefully armv7 will be just fine.

**Comment by jan-wassenberg** [comment]
@stefson sounds good, thanks.

FYI #93 (ARM64) is also fixed.

Later today I will start the testing for a new 0.12.1 release, in case that's helpful for Firefox?
