### ISSUE TITLE
One test failure on s390x

### ISSUE THREAD

**Issue by eclipseo** [google/highway#194]
Fedora Rawhide, w/ GCC 11.1.1, highway 4a47570daf29bfff0577541f8a0c0c342bf363cd

On s390x, the test 71 fails:

```
111/111 Test  #71: HwyConvertTestGroup/HwyConvertTest.TestAllF16/Scalar#GetParam()=536870912 ...........................***Exception: Illegal  0.22 sec
Running main() from /builddir/build/BUILD/googletest-release-1.10.0/googletest/src/gtest_main.cc
Note: Google Test filter = HwyConvertTestGroup/HwyConvertTest.TestAllF16/Scalar
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyConvertTestGroup/HwyConvertTest
[ RUN      ] HwyConvertTestGroup/HwyConvertTest.TestAllF16/Scalar
f32 expect [0+ ->]:
  1,
f32 actual [0+ ->]:
  0,
Abort at /builddir/build/BUILD/highway-4a47570daf29bfff0577541f8a0c0c342bf363cd/hwy/tests/convert_test.cc:351: Scalar, f32 lane 0 mismatch: expected '1', got '0'.
99% tests passed, 1 tests failed out of 111
```

See log: https://kojipkgs.fedoraproject.org//work/tasks/7057/68147057/build.log

**Comment by jan-wassenberg** [comment]
@eclipseo thanks for reporting this. I believe the only test case for which we can expect 1 is 1.0;
that's the first one so probably they are all broken.

s390x is big endian, right? I think line 970 of scalar-inl.h is where we're getting in trouble: 
`CopyBytes<2>(&bits16, &out);` but bits16 is actually 32-bit.

Any suggestions on how to better test/debug this? Looks like the other float16 CopyBytes are fine, but I'll do a more thorough check tomorrow for any other occurrences.

**Comment by eclipseo** [comment]
I can confirm the issue is fixed.

https://koji.fedoraproject.org/koji/taskinfo?taskID=68210023
