### ISSUE TITLE
 Does VQSort support custom object and comparison function ?

### ISSUE THREAD

**Issue by Narutoworld** [google/highway#1977]
After reading this [blog](https://opensource.googleblog.com/2022/06/Vectorized%20and%20performance%20portable%20Quicksort.html), I am interested in this super fast `VQSort()` and want to use it to replace the `spec_qsort()` function inside **mcf** benchmark.

However, instead of comparing values, the `spec_qsort()` function sorts custom objects using a compare function which is passed as one of function arguments.

May I ask how does `VQSort()` compare custom object ? Any documentation or sample I should read ?

**Comment by jan-wassenberg** [comment]
Hi, VQSort currently does not support custom comparators. As a workaround, if the comparator is just a lexicographic ordering of up to 128 bits of data, you can use the K64V64 type.
It is possible to implement a vectorized comparator, but that would require large changes to the sorting network.

**Comment by Narutoworld** [comment]
Thanks Dr.@jan-wassenberg for reply. I think the custom comparator just compares a value in lexicographic ordering, but it requires deferencing pointers and branches. The branches in the comparator might prevent vecorization. But my target machine supports ARM SVE with scalable predicate registers. Could you hint at me what are the non-trivial changes to replace the `spec_qsort()` with `VQSort()` ?

FYI
```
// the struct to compare 
typedef struct arc arc_t;
struct arc
{
  int32_t id;
  int32_t cost;
  int64_t tail, head;
  int16_t ident;
  int64_t flow;
 };
```
```
// the definition of spec_qsort() function
void spec_qsort(void *array, size_t nitems, size_t size, int (*cmp)(const void*,const void*));
1. void *array : an array of arc_t**.
2. size_t nitems: numbers of arc_t** in the array.
3. size_t size: sizeof(arc_t*)
4. function pointer of the comparator.
```
```
// the comparator
static int arc_compare( arc_t **a1, arc_t **a2 )
{
  if( (*a1)->flow > (*a2)->flow )
    return 1;
  if( (*a1)->flow < (*a2)->flow )
    return -1;
  if( (*a1)->id < (*a2)->id )
    return -1;
    return 1;
}
```

**Comment by jan-wassenberg** [comment]
The nontrivial change would be to write a vectorized comparator, perhaps using gather to load from the pointers. Then you'd also have to change the sorting networks from min+max to comparator+IfThenElse.

The current approach of sorting pointers makes sense if objects are quite large. This one is not really big. If you can bit-pack everything into 128 bits, then sorting the objects directly (casted to K64V64 type) would likely be faster.

**Comment by jan-wassenberg** [comment]
Closing, feel free to reopen if you'd like to continue the discussion.

**Comment by 77009833** [comment]
What is the use case of K64V64 ? 
I thought the use case of K64V64 is to calculate Top-K, where the key is 64-bit and the value is 64-bit, sorted by the key, and the value stores associated data.
Many Thanks!

**Comment by 77009833** [comment]
> Yes, that is one good use case. Another example would be sorting an opaque 128-bit type, in which only 64 bits (the most-significant) have to participate in the sort. This is cheaper than a full 128-bit comparison.

I tried using K64V64 for a Top-K scenario, but the interface is VQSort(K64V64* keys), and since K64V64 is a struct, I have to copy my keys(which are scores) and values(which are ids) into a K64V64 array, which leads to poor performance. Is there a better way?

Thanks a lot!

**Comment by jan-wassenberg** [comment]
Is it an option to cast your array to the K64V64 type? You'd have to be careful to ensure the memory layout is correct (key goes in MSB in a little-endian perspective).

**Comment by yinqiwen** [comment]
> Is it an option to cast your array to the K64V64 type? You'd have to be careful to ensure the memory layout is correct (key goes in MSB in a little-endian perspective).

is possible to split K64V64 into two different array like `x86simdsort`?  
https://github.com/intel/x86-simd-sort/blob/main/lib/x86simdsort.h#L48
