### ISSUE TITLE
Arm NEON compilation error with GCC 10

### ISSUE THREAD

**Issue by ag01** [google/highway#1984]
Hi, 

Seeing a compilation error for aarch64 using GCC 10 (and GCC 9):

highway/hwy/ops/arm_neon-inl.h:7612:26: error: call of overloaded ‘ReduceMin(hwy::N_NEON::Simd<double, 2, 0>&, hwy::N_NEON::VFromD<hwy::N_NEON::Simd<double, 2, 0> >&)’ is ambiguous
 7612 |   return Set(d, ReduceMin(d, v));

Seen on both HWY_NEON and  HWY_NEON_WITHOUT_AES targets.

Build commands:
CC=gcc-10 CXX=g++-10 cmake -DBUILD_TESTING=OFF -DHWY_ENABLE_CONTRIB=ON ..

Cannot reproduce with GCC 11 or newer.

Kind regards,

**Comment by jan-wassenberg** [comment]
Thank you @johnplatts for fixing this :)
