### ISSUE TITLE
Minor issue with docs

### ISSUE THREAD

**Issue by fbarbari** [google/highway#2002]
Many pages have a `[TOC]` at the beginning right below the title, I think the table of contents is missing.

Also, with the new release (1.1.0) some new operations (in particular, `MaskedDivOr`, `MaskedMulOr` ecc.) have been added and their documentation is available inside the `g3doc/quick_reference.md` file but it is not available on the online version.

Also, many pages have the `Edit on GitHub` button on the top right corner pointing at a non-existing `.rst` file.

**Comment by jan-wassenberg** [comment]
Thanks for reporting! Sorry about the late reply, I am catching up on issues.

The [Edit on Github](https://github.com/google/highway/blob/master/docs/index.rst) link seems to work for me.

TOC is meant to _create_ a doc, but this depends on the Markdown viewer/translator. It indeed seems not to work, so I'll remove it, thanks :)
