### ISSUE TITLE
Does the Highway have partial sort functionality?

### ISSUE THREAD

**Issue by enum-class** [google/highway#2018]
If not, are there any plans to add it in the future ?

**Comment by jan-wassenberg** [comment]
I assume for TopK? We do not have it, but it sounds useful.
Would you like to add a variant of Quicksort that just skips the right partition (if it is beyond K)?

**Comment by enum-class** [comment]
Yes for TopK, I will do it

**Comment by jan-wassenberg** [comment]
Thanks @enum-class for adding this :)
