### ISSUE TITLE
ReorderWidenMulAccumulate with guaranteed lanes order and sum

### ISSUE THREAD

**Issue by awxkee** [google/highway#2062]
It would be very nice when `ReorderWidenMulAccumulate` or similar api that will do always guaranteed widen `a[i] * b[i] + c[i]` because it is base operation when you're trying to apply transformation matrix in integer space. For ex. whole `libyuv` done using `vmlal_u16` or it's similars on other than NEON platforms. At the moment it is necessary to check ReorderWidenMulAccumulate on platforms I know and write tons of if like this one `#if (HWY_ARCH_ARM_A64 && (HWY_TARGET == HWY_NEON`. Of course it is possible to write generic backed by MulAdd but benefits will be lost.

**Comment by jan-wassenberg** [comment]
Hi, thanks for reaching out. Does WidenMulPairwiseAdd work for your use case? That's just missing the accumulate part which is an extra add.
If not, any thoughts on how to bridge the difference between SVE and NEON, where the former handles odd/even lanes, and the latter upper/lower halves? This is why we relaxed the interface to allow reordering.

**Comment by awxkee** [comment]
Hi. No WidenMulPairwiseAdd doesn't do that required. I'm using ReorderWidenMulAccumulate because it is based ( in NEON version ) on vmlal where [vmlal](https://developer.arm.com/architectures/instruction-sets/intrinsics/vmlal_u16) function wide lower/upper part and multiplies it on corresponding vectors. There is not deal with even/odd lanes so I think it will be easy to implement generic on platforms where it is not supported.

I don't tested this, however idea is simple.
```c++
template<typename D, HWY_IF_U16_D(D), HWY_IF_LANES_D(D, 8), typename VW = Vec<RepartitionToWide<D>>>
void WidenMul(D d, Vec<D> v, VW hi, VW lo, VW &hiSum, VW& loSum) {
  const VW dw;
  loSum = MulAdd(PromoteLowerTo(dw, v), lo, loSum);
  hiSum = MulAdd(PromoteUpperTo(dw, v), hi, hiSum);
}
```

Especially for your question about deal with even/odd lanes it can be achieved by bit masking, however it is not needed in this case I believe.

```c++
template<typename D, HWY_IF_I16_D(D), HWY_IF_LANES_D(D, 8), typename VH = Vec<Half<D>>>
VH GetOdd(D d, Vec<D> v) {
  const Half<D> dh;
  const Rebind<int32_t, decltype(dh)> du32;
  return DemoteTo(dh, ShiftRight<16>(BitCast(du32, v)));
}

template<typename D, HWY_IF_U16_D(D), HWY_IF_LANES_D(D, 8), typename VH = Vec<Half<D>>>
VH GetEven(D d, Vec<D> v) {
  const Half<D> dh;
  const Rebind<uint32_t, decltype(dh)> du32;
  const auto erase = Set(du32, static_cast<uint32_t>(0x0000FFFF));
  return DemoteTo(dh, And(BitCast(du32, v), erase));
}
```

**Comment by jan-wassenberg** [comment]
Got it, you just want widen + mul, not pairwise add.

The reason I ask about odd/even is that SVE [does not provide](https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=[sve2,sve]&f:@navigationhierarchiesreturnbasetype=[int]&f:@navigationhierarchieselementbitsize=[32]&q=mlal) an instruction like vmlal.

Building the proposed WidenMul from the SVE ops at least halves performance there: either we promote beforehand, as with your generic code, or zip afterwards. We generally try to avoid encouraging user code to target ops that will have such performance cliffs. If I were targeting SVE, I'd seriously consider special-casing the data layout to deal with this.

Does anyone else have an opinion on how to deal with this? Maybe @Ryo-not-rio?

**Comment by awxkee** [comment]
Hw, possibly I'm missing something however `smlalb`/`smlalt` does exactly the same? For ex. [svmlalt_s32](https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=[%5Bsve2,sve%5D,sve,sve2]&f:@navigationhierarchiesreturnbasetype=[%5Bint%5D,int]&f:@navigationhierarchieselementbitsize=[%5B32%5D,32]&q=svmlalt_s32)

**Comment by jan-wassenberg** [comment]
The pseudocode format of NEON and SVE differs. Note the i*2+1 in SVE, vs just `e` in NEON.

**Comment by awxkee** [comment]
> Got it, you just want widen + mul, not pairwise add.
> 
> The reason I ask about odd/even is that SVE [does not provide](https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=%5Bsve2,sve%5D&f:@navigationhierarchiesreturnbasetype=%5Bint%5D&f:@navigationhierarchieselementbitsize=%5B32%5D&q=mlal) an instruction like vmlal.
> 
> Building the proposed WidenMul from the SVE ops at least halves performance there: either we promote beforehand, as with your generic code, or zip afterwards. We generally try to avoid encouraging user code to target ops that will have such performance cliffs. If I were targeting SVE, I'd seriously consider special-casing the data layout to deal with this.
> 
> Does anyone else have an opinion on how to deal with this? Maybe @Ryo-not-rio?

I completely agree that performance will be worse. However, at the moment it requires sometimes write at least twice more code, otherwise not receive benefits of wide+mul+add on all the platforms. Build special-case data ( permuting channels for SVE and probably also write twice more code ) it also not sounds very practical, even not everyone will know about that case.

**Comment by jan-wassenberg** [comment]
I find your argument convincing. SVE is the only one doing it this way, so it makes sense to put the extra cost on that platform.
If no one raises a concern, I'm happy to review and accept a patch that adds WidenMul, using vmlal on NEON and the generic code you proposed.

**Comment by johnplatts** [comment]
> I find your argument convincing. SVE is the only one doing it this way, so it makes sense to put the extra cost on that platform. If no one raises a concern, I'm happy to review and accept a patch that adds WidenMul, using vmlal on NEON and the generic code you proposed.

Clang 9 and later on Armv7/AArch64 and GCC 11 and later on AArch64 will optimize `MulAdd(PromoteTo(di32, a), PromoteTo(di32, b), sum)` to smlal/vmlal, `Mul(PromoteTo(di32, a), PromoteTo(di32, b))` to vmull/smull, and `Add(PromoteTo(di32, a), PromoteTo(di32, b))` to saddl/vaddl if optimizations are enabled.

Here is link to a snippet showing the optimizations that GCC and Clang make with PromoteTo+Add, PromoteTo+Mul, and PromoteTo+MulAdd on Armv7 and AArch64: https://godbolt.org/z/n3YPY9f13

**Comment by awxkee** [comment]
Can confirm that clang does optimization to `vmlal` if needed. 
However, direct use performs still significantly better than promote + mul.

Version with vmlal

```bash
-------------------------------------------------------
Benchmark             Time             CPU   Iterations
-------------------------------------------------------
VmlalVersion     565559 ns       563968 ns         1247
```

Version MulAdd only -O3 clang

```bash
--------------------------------------------------------
Benchmark              Time             CPU   Iterations
--------------------------------------------------------
MulAddVersion     754743 ns       751232 ns          982
```

Code does exactly the same. 

Probably, if other archs, not only SVE do not have direct widen+mul/widen+mul+add do not add this to avoid only NEON bound API calls.

**Comment by awxkee** [comment]
There is a main test part of code if someone interested.

<details> 
  <summary>vmlal</summary>
      

      V32 YhRh = vBiasY;
      V32 YhRl = WidenMulAccumulate(di16, Rh, vYR, vBiasY, YhRh);
      YhRl = WidenMulAccumulate(di16, Gh, vYG, YhRl, YhRh);
      YhRl = WidenMulAccumulate(di16, Bh, vYB, YhRl, YhRh);

      const auto
          Yh = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, YhRh), ShiftRightNarrow<8>(d32, YhRl)));

      V32 Chbh = vBiasUV;
      V32 Chbl = WidenMulAccumulate(di16, Rh, vCbR, vBiasUV, Chbh);
      Chbl = WidenMulAccumulate(di16, Gh, vCbG, Chbl, Chbh);
      Chbl = WidenMulAccumulate(di16, Bh, vCbB, Chbl, Chbh);

      const auto
          Chbf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Chbh), ShiftRightNarrow<8>(d32, Chbl)));

      V32 Chrh = vBiasUV;
      V32 Chrl = WidenMulAccumulate(di16, Rh, vCrR, vBiasUV, Chrh);
      Chrl = WidenMulAccumulate(di16, Gh, vCrG, Chrl, Chrh);
      Chrl = WidenMulAccumulate(di16, Bh, vCrB, Chrl, Chrh);

      const auto
          Chrf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Chrh), ShiftRightNarrow<8>(d32, Chrl)));

      V32 YlRh = vBiasY;
      V32 YlRl = WidenMulAccumulate(di16, Rl, vYR, vBiasY, YlRh);
      YlRl = WidenMulAccumulate(di16, Gl, vYG, YlRl, YlRh);
      YlRl = WidenMulAccumulate(di16, Bl, vYB, YlRl, YlRh);

      const auto
          Yl = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, YlRh), ShiftRightNarrow<8>(d32, YlRl)));

      V32 Clbh = vBiasUV;
      V32 Clbl = WidenMulAccumulate(di16, Rl, vCbR, vBiasUV, Clbh);
      Clbl = WidenMulAccumulate(di16, Gl, vCbG, Clbl, Clbh);
      Clbl = WidenMulAccumulate(di16, Bl, vCbB, Clbl, Clbh);

      const auto
          Clbf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Clbh), ShiftRightNarrow<8>(d32, Clbl)));

      V32 Clrh = vBiasUV;
      V32 Clrl = WidenMulAccumulate(di16, Rl, vCrR, vBiasUV, Clrh);
      Clrl = WidenMulAccumulate(di16, Gl, vCrG, Clrl, Clrh);
      Clrl = WidenMulAccumulate(di16, Bl, vCrB, Clrl, Clrh);

      const auto
          Clrf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Clrh), ShiftRightNarrow<8>(d32, Clrl)));
</details>

<details> 
  <summary>MulAdd</summary>
       

      V32 R32l = PromoteLowerTo(d32, Rh);
      V32 R32h = PromoteUpperTo(d32, Rh);
      V32 B32l = PromoteLowerTo(d32, Bh);
      V32 B32h = PromoteUpperTo(d32, Bh);
      V32 G32l = PromoteLowerTo(d32, Gh);
      V32 G32h = PromoteUpperTo(d32, Gh);
      const auto Yhl = MulAdd(R32l, vYR,
                             MulAdd(G32l, vYG,
                                    MulAdd(B32l, vYB, vBiasY)));
      const auto Yhh = MulAdd(R32h, vYR,
                             MulAdd(G32h, vYG,
                                    MulAdd(B32h, vYB, vBiasY)));

      const auto Chbl = Add(MulAdd(B32l, vCbB,
                                   MulAdd(G32l, vCbG,
                                         Mul(R32l, vCbR))), vBiasUV);
      const auto Chbh = Add(MulAdd(B32h, vCbB,
                                   MulAdd(G32h, vCbG,
                                         Mul(R32h, vCbR))), vBiasUV);

      const auto Chrh = Add(MulAdd(R32h, vCrR,
                                   MulAdd(G32h, vCrG,
                                         Mul(B32h, vCrB))), vBiasUV);

      const auto Chrl = Add(MulAdd(R32l, vCrR,
                                   MulAdd(G32l, vCrG,
                                         Mul(B32l, vCrB))), vBiasUV);

      const auto Yh = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Yhh), ShiftRightNarrow<8>(d32, Yhl)));
      const auto Chbf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Chbh), ShiftRightNarrow<8>(d32, Chbl)));
      const auto Chrf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Chrh), ShiftRightNarrow<8>(d32, Chrl)));

      V32 R32ll = PromoteLowerTo(d32, Rl);
      V32 R32lh = PromoteUpperTo(d32, Rl);
      V32 B32ll = PromoteLowerTo(d32, Bl);
      V32 B32lh = PromoteUpperTo(d32, Bl);
      V32 G32ll = PromoteLowerTo(d32, Gl);
      V32 G32lh = PromoteUpperTo(d32, Gl);
      const auto Yll = MulAdd(R32ll, vYR,
                              MulAdd(G32ll, vYG,
                                     MulAdd(B32ll, vYB, vBiasY)));
      const auto Ylh = MulAdd(R32lh, vYR,
                              MulAdd(G32lh, vYG,
                                     MulAdd(B32lh, vYB, vBiasY)));

      const auto Clbl = Add(MulAdd(B32ll, vCbB,
                                   MulAdd(G32ll, vCbG,
                                          Mul(R32ll, vCbR))), vBiasUV);
      const auto Clbh = Add(MulAdd(B32lh, vCbB,
                                   MulAdd(G32lh, vCbG,
                                          Mul(R32lh, vCbR))), vBiasUV);

      const auto Clrh = Add(MulAdd(R32lh, vCrR,
                                   MulAdd(G32lh, vCrG,
                                          Mul(B32lh, vCrB))), vBiasUV);

      const auto Clrl = Add(MulAdd(R32ll, vCrR,
                                   MulAdd(G32ll, vCrG,
                                          Mul(B32ll, vCrB))), vBiasUV);

      const auto Yl = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Ylh), ShiftRightNarrow<8>(d32, Yll)));
      const auto Clbf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Clbh), ShiftRightNarrow<8>(d32, Clbl)));
      const auto Clrf = BitCast(du16, Combine(di16, ShiftRightNarrow<8>(d32, Clrh), ShiftRightNarrow<8>(d32, Clrl)));
</details>
