### ISSUE TITLE
 Compile failure: SVE vector type 'svbool_t' (aka '__SVBool_t') cannot be used in a target without sve

### ISSUE THREAD

**Issue by jgouly** [google/highway#2108]
I have a compile time error, building master:

```
hwy/ops/arm_sve-inl.h:321:33: error: SVE vector type 'svbool_t' (aka '__SVBool_t') cannot be used in a target without sve
HWY_SVE_FOREACH(HWY_SVE_FIRSTN, FirstN, whilelt)
```

This is on an Apple M2 running Asahi. It's building as a dependency as part of a program written in Zig. I haven't tried to repro with just highway,

**Comment by johnplatts** [comment]
A workaround is to disable the HWY_SVE, HWY_SVE2, HWY_SVE_256, and HWY_SVE2_128 targets on Apple Silicon Macs as none of the current Apple Silicon CPU's support SVE or SVE2.

**Comment by jgouly** [comment]
Can I do that by defining some macros before including highway headers?

**Comment by johnplatts** [comment]
> Can I do that by defining some macros before including highway headers?

You can add `-DHWY_DISABLED_TARGETS=(HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128)"` to CXXFLAGS or CMAKE_CXX_FLAGS disable the SVE and SVE2 targets.

You can also add the following lines to disable SVE/SVE2 before the includes of any Highway headers:
```
#if defined(__APPLE__) && defined(__aarch64__) && !defined(HWY_DISABLED_TARGETS)
#define HWY_DISABLED_TARGETS (HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128)
#endif
```

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts , the workaround sounds good. @jgouly , can you share the compiler version so we can disable SVE on it?

**Comment by jgouly** [comment]
It's using zig 12.0, using clang 13.0 libraries.

**Comment by jan-wassenberg** [comment]
Thanks! We recently [added](https://github.com/google/highway/commit/d4f791175f826b0114896bd9f561c35c41e641bd) a check for clang >= 14. Are you using that already, perhaps we are mis-detecting the clang version?

**Comment by jgouly** [comment]
Sorry, I just realised the LLVM/clang version is 17.0. https://godbolt.org/z/f8WvWf8hh

**Comment by jan-wassenberg** [comment]
Got it, that explains why we are still enabling SVE. I'm curious how exactly the integration of Highway into Zig works?
Is it something like building C++ code with a Zig FFI?

I think the actual error here is a compiler limitation or even bug. It is definitely useful to compile a single binary for multiple targets, and this requires NOT setting +sve for all the source files. We are moving towards compiling more code in this way and also finding such bugs.

In the meantime, John's workaround is probably good. We are also open to opting out of SVE if certain (which?) macros are defined.

**Comment by jgouly** [comment]
I will try work out a small Zig reproducer. This is a project I'm just compiling as a user, not author of. Also I don't have Zig experience!

It's compiling highway with `zig cc` and yes using some GFI to call it.

I tried to get that workaround working, but I wasn't sure if the compiler was passing through the -D options properly. Note that this is compiling the project without actually using CMake (as far as I can tell..)

**Comment by jan-wassenberg** [comment]
I understand, thanks. Unfortunately I don't see a predefined macro that would help. clang_version would be difficult to parse at compile-time in an `#if` :)
If we're not sure about -D working, you could also insert `#define HWY_DISABLED_TARGETS (HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128)" at the top of detect_targets.h.

**Comment by jgouly** [comment]
Just to go back to something you said:

```
I think the actual error here is a compiler limitation or even bug. It is definitely useful to compile a single binary for multiple targets, and this requires NOT setting +sve for all the source files. We are moving towards compiling more code in this way and also finding such bugs.
```
What did you mean by 'in this way'? I was looking at the code to see if there was some compiler attribute to enable SVE for a particular file. I think CI runs on an (emulated) target with SVE, which is why it works there. I think if you use SVE types directly, you need to pass a compiler option to enable them, but it seems to currently just expect the CPU target to enable them.

I'm working on the Zig example now, and have reproduced it, and I'm also trying to figure out how to work around it (by actually enabling SVE from Zig)

**Comment by jan-wassenberg** [comment]
Right, in this way = with Highway's dynamic dispatch. This builds the same source file several times with different -m arguments, and with different `#pragma target` flags on the function to enable SVE in one, and NEON in the other. In order for this to work, the compiler has to check for and honor the per-function attributes, rather than rely on a global "we have SVE so this is the calling convention etc" check.

We check at runtime whether SVE is actually supported and only if so do we call into that version of the code.

**Comment by jgouly** [comment]
Alright, I have finally figured out the issue with Zig, and hope you're willing to do a (tiny) workaround for it.

Given the following file, `foo.c`
```
#include <arm_sve.h>

#pragma clang attribute push(__attribute__((target("+sve2"))), apply_to = function)
#pragma GCC push_options 
#pragma GCC target "+sve2"

void foo(svbool_t a){}

#pragma GCC pop_options
#pragma clang attribute pop
```

This compiles:
```
$ clang -c foo.c
```

However using Zig as a frontend to Clang doesn't:
```
$ zig cc -c foo.c
 error: SVE vector type 'svbool_t' (aka '__SVBool_t') cannot be used in a target without sve
      | void fo(svbool_t a){}
      |      ^
1 error generated.
Compiler returned: 1
```

I couldn't understand why, but I was told about trying `ZIG_VERBOSE_CC=1`. That showed that Zig is actually resolving all the target features before calling Clang.

It actually calls Clang like (simplified:)
```
$ clang -Xclang -target-feature -sve2 -Xclang -target-feature -sve -c foo.c
```

Since it's using a 'generic' mcpu, sve is not enabled and when it sees the pragma and enables `sve2`, it seems that it doesn't automatically enable `sve` too. I don't know exactly how this is handled by Clang, but that's just my assumption on how it looks like. I think the pragma should take precedence over the `-target-feature` maybe, but it doesn't currently.

A simple fix would be to set multiple features in `HWY_TARGET_STR`, such as `+sve,+sve2`, etc. Would you be willing to do that such that this file could be compiled by Zig easily?

**Comment by jan-wassenberg** [comment]
Oh, great find with the command line flags! That makes sense, we'd be happy to add +sve as well. Thanks for digging into this :)
