### ISSUE TITLE
highway.h --> undeclared identifier 'AllExports'

### ISSUE THREAD

**Issue by temis01** [google/highway#2169]
Hi

Sorry super noob here !

I'm trying to compile mpv in which highway is included.

I am getting these errors :

highway.h:306:21: error: use of undeclared identifier 'AllExports'
  306 |     const auto it = AllExports::Get().find(kHash);

highway.h:307:22: error: use of undeclared identifier 'AllExports'
  307 |     HWY_ASSERT(it != AllExports::Get().end());
      |                      ^
2 errors generated.
ninja: build stopped: subcommand failed.

Does that make any sense or is it just mpv 

Thanks for your help

**Comment by jan-wassenberg** [comment]
Hi, apologies, this build error has just been fixed :) Updating to Git HEAD will solve this.

**Comment by temis01** [comment]
thank you for that instant response 👍
