### ISSUE TITLE
Debian i386/x32 fails to build arithmetic_test.cc

### ISSUE THREAD

**Issue by malaterre** [google/highway#2208]
Some systems with limited amount of memory fails to compile the arithmetic_test.cc code. Typical error is:
`
cc1plus: out of memory allocating 2708160 bytes after a total of 288514048 bytes`

Would it be possible to split this test into multiple TUs ?

ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=i386&ver=1.1.0-2&stamp=1716968265&raw=0

**Comment by jan-wassenberg** [comment]
Certainly, fix coming up :)
