### ISSUE TITLE
hwy 1.1.0:  Dynamic dispatch support for s390x

### ISSUE THREAD

**Issue by malaterre** [google/highway#2210]
AFAIK the dynamic dispatch on s390x is not setup properly. Would it be possible to turn it on by default:
```

[100/160] : && /usr/bin/c++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wdate-time -D_FORTIFY_SOURCE=2 -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now     -fPIE -pie CMakeFiles/hwy_list_targets.dir/hwy/tests/list_targets.cc.o -o hwy_list_targets  -Wl,-rpath,/<<PKGBUILDDIR>>/obj-s390x-linux-gnu  libhwy.so.1.1.0 && cd /<<PKGBUILDDIR>>/obj-s390x-linux-gnu && /<<PKGBUILDDIR>>/obj-s390x-linux-gnu/hwy_list_targets || ( exit 0 )
Config: emu128:0 scalar:0 static:0 all_attain:0 is_test:0
Compiled HWY_TARGETS:   EMU128
HWY_ATTAINABLE_TARGETS: EMU128
HWY_BASELINE_TARGETS:   EMU128
HWY_STATIC_TARGET:      EMU128
HWY_BROKEN_TARGETS:    
HWY_DISABLED_TARGETS:  
Current CPU supports:   Z15 Z14 EMU128 SCALAR
```

ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=s390x&ver=1.1.0-2&stamp=1716968607&raw=0

**Comment by jan-wassenberg** [comment]
Thanks for reporting. The condition for enabling runtime dispatch is:
`#elif (.. HWY_ARCH_S390X ..) &&    \
    (HWY_COMPILER_GCC_ACTUAL || HWY_COMPILER_CLANG >= 1700) && HWY_OS_LINUX && \
    HWY_HAVE_AUXV`
Can you help figure out which of them is not set?

**Comment by jan-wassenberg** [comment]
FYI HEAD is very close to being released as 1.2, in case that helps?

**Comment by jan-wassenberg** [comment]
Thanks, yes, looking. Most are complaining about symbols added - isn't that legit?

**Comment by jan-wassenberg** [comment]
PPC is hopefully fixed by #2215. The docs sound like unsigned __int128 and unsigned char are equivalent, but I kept the original codepath for clarity.

**Comment by jan-wassenberg** [comment]
For RISC-V, seems some clang and gcc still require -march=rv64gcv1p0. Interestingly, riscv64-linux-gnu-g++-13 does not. I'm also fixing one missing macro in #2216.

**Comment by jan-wassenberg** [comment]
For armhf, the warning is that HWY_NEON is enabled, but at runtime we detect that it is not supported due to lack of AES. That is correct on armhf. The question is why we would select HWY_NEON as a target, because we check for AES via predefined macro:

```
#if defined(__ARM_NEON__) || defined(__ARM_NEON)
#undef HWY_BASELINE_NEON
#if defined(__ARM_FEATURE_AES) &&                    \
    defined(__ARM_FEATURE_FP16_VECTOR_ARITHMETIC) && \
    defined(__ARM_FEATURE_DOTPROD) &&                \
    defined(__ARM_FEATURE_BF16_VECTOR_ARITHMETIC)
#define HWY_BASELINE_NEON HWY_ALL_NEON
#elif defined(__ARM_FEATURE_AES)
#define HWY_BASELINE_NEON (HWY_NEON_WITHOUT_AES | HWY_NEON)
#else
#define HWY_BASELINE_NEON (HWY_NEON_WITHOUT_AES)
#endif  // __ARM_FEATURE*
#endif  // __ARM_NEON
```

Perhaps `__ARM_FEATURE_AES` is actually being set?

**Comment by jan-wassenberg** [comment]
Unable to repro the arm64 SVE issue on [godbolt](https://gcc.godbolt.org/z/4YE8K3Po1), even with the flags from the Debian builder. Any ideas?
