### ISSUE TITLE
Unable to build shared library on Windows (MinGW-w64)

### ISSUE THREAD

**Issue by brechtsanders** [google/highway#2225]
When building highway 1.2.0 on Windows using MinGW-w64 the shared build fails with the following error:
```raw
hwy/contrib/thread_pool/topology.cc:67:20: error: function 'bool hwy::HaveThreadingSupport()' definition is marked dllimport
```

When looking at this section in `hwy/highway_export.h`:
```c
#if !defined(HWY_SHARED_DEFINE)
#define HWY_DLLEXPORT
#define HWY_CONTRIB_DLLEXPORT
#define HWY_TEST_DLLEXPORT
#else  // !HWY_SHARED_DEFINE

#ifndef HWY_DLLEXPORT
#if defined(hwy_EXPORTS)
/* We are building this library */
#ifdef _WIN32
#define HWY_DLLEXPORT __declspec(dllexport)
#else
#define HWY_DLLEXPORT __attribute__((visibility("default")))
#endif
...
```
and this section in `CMakeLists.txt`:
```raw
if("${HWY_LIBRARY_TYPE}" STREQUAL "SHARED")
  set(DLLEXPORT_TO_DEFINE "HWY_SHARED_DEFINE")
else()
  set(DLLEXPORT_TO_DEFINE "HWY_STATIC_DEFINE")
endif()
```
it's clear that `set(DLLEXPORT_TO_DEFINE "HWY_SHARED_DEFINE")` causes `HWY_DLLEXPORT` to be defined as nothing instead of `__declspec(dllexport)`.

I was able to build successfully after changing `CMakeLists.txt` so `HWY_SHARED_DEFINE` is not defined.

**Comment by vtorri** [comment]
same here

**Comment by vtorri** [comment]
when I compile with verbose mode, what is passed to compiler is `-Dhwy_contrib_EXPORTS` not `-Dhwy_EXPORTS`. So, according to highway_export.h, `HWY_DLLEXPORT` is defined to `__declspec(dllimport)`

**Comment by brechtsanders** [comment]
That is only true if `HWY_SHARED_DEFINE` is not defined, because if it is `HWY_DLLEXPORT` is empty, see the code from `hwy/highway_export.h` I mentioned above.

**Comment by jan-wassenberg** [comment]
Apologies, I used the wrong macro: it should have been HWY_CONTRIB_DLLEXPORT for anything in hwy/contrib. Fixing shortly.

That aside, I'm not sure it actually makes sense to use shared libraries for Highway. There's not a lot of code that can actually go into the .so/.dll, and maybe it's more trouble than it is worth?

**Comment by jan-wassenberg** [comment]
@kmilos we can certainly add the LANGUAGES CXX to CMakelists, I'm not sure the other prefix change is still relevant because we now instead set RUNTIME_OUTPUT_DIRECTORY?

**Comment by jan-wassenberg** [comment]
hm, when we last tried enabling it, there were numerous issues. Do you have any statistics on how many projects are using Highway with MSYS/MinGW? Would anyone be willing to help with these and future issues?
