### ISSUE TITLE
s390x/Z14:  error: inlining failed in call to ‘always_inline’

### ISSUE THREAD

**Issue by malaterre** [google/highway#2241]
I started the first build of hwy on s390x/Z14. The build fails with:

FAILED: CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o 
/usr/bin/c++ -DHWY_SHARED_DEFINE -DTOOLCHAIN_MISS_ASM_HWCAP_H -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -march=z15 -mzvector -Wdate-time -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG -std=c++17 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -Wcast-align -fmath-errno -fno-exceptions -Wno-psabi -Werror -DHWY_IS_TEST=1 -DGTEST_HAS_PTHREAD=1 -MD -MT CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o -MF CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o.d -o CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o -c '/<<PKGBUILDDIR>>/hwy/contrib/algo/copy_test.cc'
In file included from /<<PKGBUILDDIR>>/hwy/aligned_allocator.h:32,
                 from /<<PKGBUILDDIR>>/hwy/contrib/algo/copy_test.cc:18:
/<<PKGBUILDDIR>>/hwy/base.h: In function ‘hwy::N_Z14::Load<hwy::N_Z14::Simd<unsigned short, 1ul, 0>, (void*)0, unsigned short>(hwy::N_Z14::Simd<unsigned short, 1ul, 0>, unsigned short const*)decltype (Zero((hwy::N_Z14::Simd<unsigned short, 1ul, 0>)()))’:
/<<PKGBUILDDIR>>/hwy/base.h:336:14: error: inlining failed in call to ‘always_inline’ ‘hwy::CopyBytes<2ul, unsigned short, unsigned short>(unsigned short const*, unsigned short*)void’: target specific option mismatch
  336 | HWY_API void CopyBytes(const From* HWY_RESTRICT from, To* HWY_RESTRICT to) {
      |              ^~~~~~~~~
In file included from /<<PKGBUILDDIR>>/hwy/highway.h:586,
                 from /<<PKGBUILDDIR>>/hwy/contrib/algo/copy_test.cc:24,
                 from /<<PKGBUILDDIR>>/hwy/foreach_target.h:290,
                 from /<<PKGBUILDDIR>>/hwy/contrib/algo/copy_test.cc:23:
/<<PKGBUILDDIR>>/hwy/ops/ppc_vsx-inl.h:697:26: note: called from here
  697 |   CopyBytes<d.MaxBytes()>(p, &bits);
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~

ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=s390x&ver=1.2.1%7Egit20240610.f384204-1&stamp=1718090615&raw=0

**Comment by johnplatts** [comment]
> I started the first build of hwy on s390x/Z14. The build fails with:
> 
> FAILED: CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o /usr/bin/c++ -DHWY_SHARED_DEFINE -DTOOLCHAIN_MISS_ASM_HWCAP_H -I"/<>" -g -O2 -ffile-prefix-map=/<>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -march=z15 -mzvector -Wdate-time -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG -std=c++17 -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -Wcast-align -fmath-errno -fno-exceptions -Wno-psabi -Werror -DHWY_IS_TEST=1 -DGTEST_HAS_PTHREAD=1 -MD -MT CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o -MF CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o.d -o CMakeFiles/copy_test.dir/hwy/contrib/algo/copy_test.cc.o -c '/<>/hwy/contrib/algo/copy_test.cc' In file included from /<>/hwy/aligned_allocator.h:32, from /<>/hwy/contrib/algo/copy_test.cc:18: /<>/hwy/base.h: In function ‘hwy::N_Z14::Load<hwy::N_Z14::Simd<unsigned short, 1ul, 0>, (void*)0, unsigned short>(hwy::N_Z14::Simd<unsigned short, 1ul, 0>, unsigned short const*)decltype (Zero((hwy::N_Z14::Simd<unsigned short, 1ul, 0>)()))’: /<>/hwy/base.h:336:14: error: inlining failed in call to ‘always_inline’ ‘hwy::CopyBytes<2ul, unsigned short, unsigned short>(unsigned short const*, unsigned short*)void’: target specific option mismatch 336 | HWY_API void CopyBytes(const From* HWY_RESTRICT from, To* HWY_RESTRICT to) { | ^~~~~~~~~ In file included from /<>/hwy/highway.h:586, from /<>/hwy/contrib/algo/copy_test.cc:24, from /<>/hwy/foreach_target.h:290, from /<>/hwy/contrib/algo/copy_test.cc:23: /<>/hwy/ops/ppc_vsx-inl.h:697:26: note: called from here 697 | CopyBytes<d.MaxBytes()>(p, &bits); | ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
> 
> ref:
> 
> * https://buildd.debian.org/status/fetch.php?pkg=highway&arch=s390x&ver=1.2.1%7Egit20240610.f384204-1&stamp=1718090615&raw=0

The above compiler error happens due to the `-march=z15` option, and the `-march=z15` option assumes that you are targeting a z15 or z16 mainframe.

It is possible to work around the above compiler error by disabling the HWY_Z14 target if you only need to support z15 or later.

**Comment by johnplatts** [comment]
> @johnplatts I can build and run PPC9 & PPC8 hwy on ppc64el.
> 
> What compiler options should I use to build and run Z15 & Z14 hwy on s390x ?

To compile for Z14 or later, use the `-march=z14 -mzvector` compiler options.

**Comment by jan-wassenberg** [comment]
No worries, MeasureClosure can spuriously 'fail'. It just indicates various sources of noise were too large. For example, it could be that the thread migrated to a different core and thus the timer went off a bit. It's fine to ignore that.
