### ISSUE TITLE
Question: how to declare template method for dynamic dispatch ?

### ISSUE THREAD

**Issue by boxerab** [google/highway#2251]
I am able to set up dynamic dispatch for non-template methods. But for the following method,
for example, how can I set up dynamic dispatch ?

```
 template<typename T>
  void fetch_cols(const T* res, T* scratch, uint32_t height, uint32_t stride, uint32_t numcols) {
}
```

Thanks!

**Comment by jan-wassenberg** [comment]
Hi, we recently added `HWY_EXPORT_T` for this purpose, check out the comments in highway.h :)
