### ISSUE TITLE
HTML documentation appears to be out of date?

### ISSUE THREAD

**Issue by jwnimmer-tri** [google/highway#2257]
First, thanks for the really great library.  We are starting to use it now in https://drake.mit.edu/.

I was looking for the documentation about `InterleaveEven`, which was added in PR #2008. I first looked at [the html page](https://google.github.io/highway/en/master/quick_reference.html#interleave) but didn't find it. Then, I checked the [quick_reference.md](https://github.com/google/highway/blob/master/g3doc/quick_reference.md#interleave) source directly, and it was there.

Possibly the markdown => html updating pipeline has bitrotted?

I know GitHub this year deprecated they legacy pages worker.  Drake [had to add some github actions](https://github.com/RobotLocomotion/RobotLocomotion.github.io/pull/1) to keep our docs publishing.

**Comment by jan-wassenberg** [comment]
Hi @jwnimmer-tri , thanks for the kind words and for reaching out.
Glad to hear Highway is useful. If you like, feel free to add Drake to the [list of users](https://github.com/google/highway?tab=readme-ov-file#examples).

huh, I haven't seen a pipeline failure. It reports green though there is actually a permissions issue in the [log](https://github.com/google/highway/actions/runs/9657823920/job/26637798872). Will fix shortly, please let us know whether that clears the logjam :)

**Comment by jwnimmer-tri** [comment]
Confirmed as fixed. Thanks!
