### ISSUE TITLE
Question: can I create an array of SIMD vectors ?

### ISSUE THREAD

**Issue by boxerab** [google/highway#2270]
I am using dynamic dispatch for my highway code. Is it possible to declare an array of SIMD vectors,
so that the type of the array is resolved dynamically ?

**Comment by jan-wassenberg** [comment]
Array of vector isn't possible for all targets due to RVV/SVE compiler limitations.
What we instead do is to pass a pointer to lanes (not vectors) into the entry point of dynamic dispatch. Then, the dispatched code can Load() from it to whatever the vector type is. Does that make sense?
