### ISSUE TITLE
Ramp up minimum CMake version to 2.8.12

### ISSUE THREAD

**Issue by eustas** [google/highway#228]
In `CMakeLists.txt.in` minimal CMake version is set to 2.8.2.
Currently CMake gives a deprecation note:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

Most popular distros have version >2.8.12 (CentOS seems to be the slowpoke, but even it has 2.8.12.2).

**Comment by jan-wassenberg** [comment]
Thanks for bringing this up, would be happy to update it. Would you suggest 2.8.12 or something else?

**Comment by eustas** [comment]
I think 2.8.12 should be good for now.
Another option is 3.10, it is already used in root CMakeLists.txt, so it is considered to be available.

**Comment by jan-wassenberg** [comment]
OK, thanks, let's go with the more widely available one for users outside of JPEG XL. Will send the change shortly.

**Comment by jan-wassenberg** [comment]
Oh, I misunderstood. By root you meant within Highway. Right.
The googletest CMakeLists.in is minimal and might be copied into other projects, so let's still go with 2.8.12.
