### ISSUE TITLE
complete compilation failure

### ISSUE THREAD

**Issue by themaddoctor** [google/highway#2301]
from /sources/jxl/highway-1.2.0/hwy/tests/table_test.cc:20:
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h: In instantiation of 'hwy::N_AVX3::Vec256<T> hwy::N_AVX3::TableLookupLanes(hwy::N_AVX3::Vec256<T>, hwy::N_AVX3::Indices256<T>) [with T = long int; hwy::EnableIf<(sizeof (T) == 8)>* <anonymous> = 0]':
/sources/jxl/highway-1.2.0/hwy/tests/table_test.cc:57:52:   required from 'void hwy::N_AVX3::TestTableLookupLanes::operator()(T, D) [with T = long int; D = hwy::N_AVX3::Simd<long int, 4, 0>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:259:13:   required from 'static void hwy::N_AVX3::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = long int; long unsigned int kMul = 4; long unsigned int kMinArg = 1; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0; size_t = long unsigned int]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:261:58:   required from 'static void hwy::N_AVX3::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = long int; long unsigned int kMul = 8; long unsigned int kMinArg = 1; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0; size_t = long unsigned int]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:405:63:   required from 'void hwy::N_AVX3::ForExtendableVectors<Test, kPow2>::operator()(T) const [with T = long int; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:629:36:   required from 'void hwy::N_AVX3::ForPartialVectors<Test>::operator()(T) const [with T = long int; Test = hwy::N_AVX3::TestTableLookupLanes]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:678:7:   required from 'void hwy::N_AVX3::ForSignedTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:694:17:   required from 'void hwy::N_AVX3::ForIntegerTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:762:18:   required from 'void hwy::N_AVX3::ForAllTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/table_test.cc:102:56:   required from here
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h:4518:44: error: '_mm256_permutexvar_epi64' was not declared in this scope
   return Vec256<T>{_mm256_permutexvar_epi64(idx.raw, v.raw)};
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h:4518:44: note: suggested alternative: '_mm256_permutex2var_epi64'
   return Vec256<T>{_mm256_permutexvar_epi64(idx.raw, v.raw)};
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
                    _mm256_permutex2var_epi64
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h: In instantiation of 'hwy::N_AVX3::Vec256<T> hwy::N_AVX3::TableLookupLanes(hwy::N_AVX3::Vec256<T>, hwy::N_AVX3::Indices256<T>) [with T = long unsigned int; hwy::EnableIf<(sizeof (T) == 8)>* <anonymous> = 0]':
/sources/jxl/highway-1.2.0/hwy/tests/table_test.cc:57:52:   required from 'void hwy::N_AVX3::TestTableLookupLanes::operator()(T, D) [with T = long unsigned int; D = hwy::N_AVX3::Simd<long unsigned int, 4, 0>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:259:13:   required from 'static void hwy::N_AVX3::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = long unsigned int; long unsigned int kMul = 4; long unsigned int kMinArg = 1; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0; size_t = long unsigned int]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:261:58:   required from 'static void hwy::N_AVX3::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = long unsigned int; long unsigned int kMul = 8; long unsigned int kMinArg = 1; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0; size_t = long unsigned int]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:405:63:   required from 'void hwy::N_AVX3::ForExtendableVectors<Test, kPow2>::operator()(T) const [with T = long unsigned int; Test = hwy::N_AVX3::TestTableLookupLanes; int kPow2 = 0]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:629:36:   required from 'void hwy::N_AVX3::ForPartialVectors<Test>::operator()(T) const [with T = long unsigned int; Test = hwy::N_AVX3::TestTableLookupLanes]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:688:7:   required from 'void hwy::N_AVX3::ForUnsignedTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:695:19:   required from 'void hwy::N_AVX3::ForIntegerTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/test_util-inl.h:762:18:   required from 'void hwy::N_AVX3::ForAllTypes(const Func&) [with Func = hwy::N_AVX3::ForPartialVectors<hwy::N_AVX3::TestTableLookupLanes>]'
/sources/jxl/highway-1.2.0/hwy/tests/table_test.cc:102:56:   required from here
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h:4518:44: error: '_mm256_permutexvar_epi64' was not declared in this scope
/sources/jxl/highway-1.2.0/hwy/ops/x86_256-inl.h:4518:44: note: suggested alternative: '_mm256_permutex2var_epi64'
   return Vec256<T>{_mm256_permutexvar_epi64(idx.raw, v.raw)};
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
                    _mm256_permutex2var_epi64
CMakeFiles/table_test.dir/build.make:75: recipe for target 'CMakeFiles/table_test.dir/hwy/tests/table_test.cc.o' failed
make[2]: *** [CMakeFiles/table_test.dir/hwy/tests/table_test.cc.o] Error 1
CMakeFiles/Makefile2:482: recipe for target 'CMakeFiles/table_test.dir/all' failed
make[1]: *** [CMakeFiles/table_test.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jan-wassenberg** [comment]
Hi, it seems that this was an error in GCC [fixed in 2017](https://gcc.gnu.org/legacy-ml/gcc-patches/2017-06/msg02137.html). Which version of the compiler are you using? Is it an option to upgrade? If not, you can build with `-DHWY_DISABLED_TARGETS=(HWY_AVX3|(HWY_AVX3-1))`.

**Comment by themaddoctor** [comment]
Thanks. I will try that. I have a newer GXX at
/opt/gcc-14.1.0/bin/g++
but I am not familiar with cmake. Would
GXX=/opt/gcc-14.1.0/bin/g++ cmake .
work, or is it something like
cmake -DPLEASE_USE_THIS_COMPILER=/opt/gcc-14.1.0/bin/g++ .
? Thanks again.

**Comment by jan-wassenberg** [comment]
YW :) Setting CC=/path/gcc CXX /path/g++ cmake ... should work. CMake prints the detected compiler early in its output.

**Comment by themaddoctor** [comment]
/tmp/ccXpFv7X.s:143275: Error: no such instruction: `vfpclassphz $153,%zmm0,%k2'
/tmp/ccXpFv7X.s:143387: Error: no such instruction: `vmaxph %zmm2,%zmm1,%zmm1'
/tmp/ccXpFv7X.s:143400: Error: no such instruction: `vcmpph $30,%zmm0,%zmm1,%k0'
/tmp/ccXpFv7X.s:143472: Error: no such instruction: `vmaxph (%rax),%zmm1,%zmm1'
/tmp/ccXpFv7X.s:143517: Error: no such instruction: `vmaxph -192(%rax),%zmm1,%zmm1'
/tmp/ccXpFv7X.s:143548: Error: no such instruction: `vmaxph -128(%rax),%zmm1,%zmm1'
/tmp/ccXpFv7X.s:143579: Error: no such instruction: `vmaxph -64(%rax),%zmm1,%zmm1'
/tmp/ccXpFv7X.s:143611: Error: no such instruction: `vcmpph $30,%zmm0,%zmm1,%k0'
/tmp/ccXpFv7X.s:144078: Error: no such instruction: `vfpclassphz $129,(%rax),%k1'
/tmp/ccXpFv7X.s:144261: Error: no such instruction: `vfpclassphz $129,%zmm1,%k1'
/tmp/ccXpFv7X.s:144827: Error: no such instruction: `vfpclassphz $129,%zmm0,%k2'
/tmp/ccXpFv7X.s:145210: Error: no such instruction: `vfpclassphz $129,%zmm0,%k2'
/tmp/ccXpFv7X.s:145658: Error: no such instruction: `vfpclassphz $129,(%rax),%k1'
/tmp/ccXpFv7X.s:145830: Error: no such instruction: `vfpclassphz $129,%zmm1,%k1'
CMakeFiles/hwy_contrib.dir/build.make:103: recipe for target 'CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16a.cc.o' failed
make[2]: *** [CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16a.cc.o] Error 1
CMakeFiles/Makefile2:1372: recipe for target 'CMakeFiles/hwy_contrib.dir/all' failed
make[1]: *** [CMakeFiles/hwy_contrib.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

With new GCC, I get the above.
I can't post the beginning of the errors, because it overflows my terminal.

Will try -DHWY_DISABLED_TARGETS=(HWY_AVX3|(HWY_AVX3-1)).

**Comment by johnplatts** [comment]
Need to pass HWY_DISABLED_TARGETS in the -DCMAKE_CXX_FLAGS parameter.

The correct way to disable AVX3 targets when building Highway is to pass the `-DCMAKE_CXX_FLAGS='-DHWY_DISABLED_TARGETS="(HWY_AVX3|(HWY_AVX3-1))"'` option to cmake.

**Comment by johnplatts** [comment]
> /tmp/ccXpFv7X.s:143275: Error: no such instruction: `vfpclassphz $153,%zmm0,%k2' /tmp/ccXpFv7X.s:143387: Error: no such instruction: `vmaxph %zmm2,%zmm1,%zmm1' /tmp/ccXpFv7X.s:143400: Error: no such instruction: `vcmpph $30,%zmm0,%zmm1,%k0' /tmp/ccXpFv7X.s:143472: Error: no such instruction: `vmaxph (%rax),%zmm1,%zmm1' /tmp/ccXpFv7X.s:143517: Error: no such instruction: `vmaxph -192(%rax),%zmm1,%zmm1' /tmp/ccXpFv7X.s:143548: Error: no such instruction: `vmaxph -128(%rax),%zmm1,%zmm1' /tmp/ccXpFv7X.s:143579: Error: no such instruction: `vmaxph -64(%rax),%zmm1,%zmm1' /tmp/ccXpFv7X.s:143611: Error: no such instruction: `vcmpph $30,%zmm0,%zmm1,%k0' /tmp/ccXpFv7X.s:144078: Error: no such instruction: `vfpclassphz $129,(%rax),%k1' /tmp/ccXpFv7X.s:144261: Error: no such instruction: `vfpclassphz $129,%zmm1,%k1' /tmp/ccXpFv7X.s:144827: Error: no such instruction: `vfpclassphz $129,%zmm0,%k2' /tmp/ccXpFv7X.s:145210: Error: no such instruction: `vfpclassphz $129,%zmm0,%k2' /tmp/ccXpFv7X.s:145658: Error: no such instruction: `vfpclassphz $129,(%rax),%k1' /tmp/ccXpFv7X.s:145830: Error: no such instruction: `vfpclassphz $129,%zmm1,%k1' CMakeFiles/hwy_contrib.dir/build.make:103: recipe for target 'CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16a.cc.o' failed make[2]: *** [CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16a.cc.o] Error 1 CMakeFiles/Makefile2:1372: recipe for target 'CMakeFiles/hwy_contrib.dir/all' failed make[1]: *** [CMakeFiles/hwy_contrib.dir/all] Error 2 Makefile:145: recipe for target 'all' failed make: *** [all] Error 2
> 
> With new GCC, I get the above. I can't post the beginning of the errors, because it overflows my terminal.

The reason why you are getting the above compiler errors is that you are using an older version of GNU binutils whose assembler does not support AVX512 instructions.

**Comment by themaddoctor** [comment]
Thank you very much. I have now compiled and successfully linked into another package (libjxl).

**Comment by jan-wassenberg** [comment]
Sounds good. Thank you @johnplatts :) Closing for now, please feel free to reopen.
