### ISSUE TITLE
Feature: add option to disable testing

### ISSUE THREAD

**Issue by eustas** [google/highway#232]
Currently testing controlled by "BUILD_TESTING" option. The problem is that it is all-or-nothing solution.
It might be useful to disable testing of library but still have testing enabled in root project.

**Comment by eustas** [comment]
Moreover:

1. Root project can not use the snippets given by googletest - cmake will complain that gtest library already exists (added in HWY)
2. If HWY is included with EXCLUDE_FROM_ALL option, then HWY tests fail (as those are not built)

Perhaps configuration should be different, for HWY as a root project and as library (added via add_subdirectory).

**Comment by jan-wassenberg** [comment]
@eustas is the biggest pain point that you want to do something with gTest in JXL, but Hwy's adding of gTest prevents that?
Does `HWY_SYSTEM_GTEST` help?

I'm open to suggestions on what we should do/improve.

**Comment by eustas** [comment]
HWY_SYSTEM_GTEST results in "Could NOT find GTest (missing: GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)".
I'll prepare PR / CL with a variant of fix.

**Comment by jan-wassenberg** [comment]
Yes, we might need to set GTEST_ROOT when building for that to work: https://stackoverflow.com/questions/17469843/cmake-cannot-find-a-required-library

> I'll prepare PR / CL with a variant of fix.

Sounds good!

**Comment by eustas** [comment]
Resolved by not adding test targets when project is used as library.
