### ISSUE TITLE
Parallel sorting and bench_parallel.cc

### ISSUE THREAD

**Issue by kccqzy** [google/highway#2357]
Thank you for the good work on this library! 

I tried out the sorting part of this library and the single-threaded sort is indeed amazing. But I have some questions on parallel sorting. The [paper](https://arxiv.org/pdf/2205.05982) states that "our proposed vqsort algorithm integrates into the state-of-the-art parallel sorter ips4o" but I'm not sure how this algorithm is actually integrated into ips4o. 

In my investigation to figure this out, I noticed that the `bench_parallel.cc` file is by default not compiled in CMake. While it is easy to change the CMake configuration to compile it, I have also found that 

*   the `RunWithoutVerify` function generates the input inside the thread pool so it appears that different threads operate on independent input
*   the input generation happens inside the timer so the throughput figure includes the overhead of generating input;
*   it appears to benchmark the throughout of different threads sorting different data simultaneously, and not using multiple threads to sort the same data collaboratively.

I'm not sure what the purpose of `bench_parallel.cc` is. It certainly isn't benchmarking what the paper says about integrating the vqsort into ips4o. I suppose it is the library user's responsibility to do this integration then? And `bench_parallel.cc` probably should come with a disclaimer that it doesn't really benchmark what the user intuitively thinks it is benchmarking?

**Comment by jan-wassenberg** [comment]
Thank you for reaching out :)
Integration is just a matter of calling vqsort from baseCaseSort and increasing IPS4OML_BASE_CASE_SIZE to say 8192.

The purpose of bench_parallel is to study performance when multiple threads are active and we're bandwidth-limited.

We can indeed add such a note.

**Comment by kccqzy** [comment]
Thank you for adding this note! I do hope this clarifies things for people in the future.
