### ISSUE TITLE
HWY_AVX is returning the nullptr when i do HWY_DISPATCH

### ISSUE THREAD

**Issue by sachin9689** [google/highway#2361]
#define HWY_CHOOSE_TARGET_LIST(func_name)                     \
  nullptr,                             /* reserved */         \
      nullptr,                         /* reserved */         \
      nullptr,                         /* reserved */         \
      nullptr,                         /* reserved */         \
      HWY_CHOOSE_AVX3_SPR(func_name),  /* AVX3_SPR */         \
      nullptr,                         /* reserved */         \
      HWY_CHOOSE_AVX3_ZEN4(func_name), /* AVX3_ZEN4 */        \
      HWY_CHOOSE_AVX3_DL(func_name),   /* AVX3_DL */          \
      HWY_CHOOSE_AVX3(func_name),      /* AVX3 */             \
      HWY_CHOOSE_AVX2(func_name),      /* AVX2 */             \
      nullptr,                         /* AVX */              \
      HWY_CHOOSE_SSE4(func_name),      /* SSE4 */             \
      HWY_CHOOSE_SSSE3(func_name),     /* SSSE3 */            \
      nullptr,                         /* reserved - SSE3? */ \
      HWY_CHOOSE_SSE2(func_name)       /* SSE2 */

AVX is returning nullptr, which is not an ideal situation. My machine has AVX and lower target it does not have avx2, how should i manage this problem. Please fix this so that I will be able to dispatch highway for AVX target. 

![Image](https://github.com/user-attachments/assets/0cd565ff-f1e7-418d-8cd2-effe1bb2903d)

**Comment by johnplatts** [comment]
The reason why the AVX slot is nullptr is that there is currently no HWY_AVX target implemented.

On x86 systems that support AVX but not AVX2, the dispatch will select the function for the HWY_SSE4 target (or the HWY_SSSE3, HWY_SSE2, HWY_SCALAR, or HWY_EMU128 if the HWY_SSE4 target is disabled).

**Comment by sachin9689** [comment]
The way I am using Highway is different, I am not using the HWY_DISPATCH, I am using HWY_DISPATCH_TABLE[]and passing the dispatch table index. If I only have AVX machine then I can not pass the index of the AVX2 after export. So in this case what should i pass if I pass AVX index it  gives nullptr and I do not want to give sse4 index which is lower version than AVX.

**Comment by jan-wassenberg** [comment]
As @johnplatts mentioned, we do not implement a HWY_AVX target.
I think sse4 index is the best that can be done in this case :)

**Comment by sachin9689** [comment]
Thank you very much for your reply and valuable feedback. I will take it into consideration. I also wanted to mention that there are some machines that only support AVX, and they might require this implementation in the future. I hope you consider making this change going forward.

**Comment by jan-wassenberg** [comment]
I understand. Currently we have no plans to implement HWY_AVX, but if you or someone else would like to add it, I'd be happy to advise on that and we will then continue to support it.
