### ISSUE TITLE
Performance Regression in GatherIndexN

### ISSUE THREAD

**Issue by Mousius** [google/highway#2382]
In https://github.com/numpy/numpy/pull/25934, we see up to 3x slow down in gathering loads on AArch64 when using Highway.

I believe this is due to https://github.com/google/highway/pull/2116, which seems to have subtly changed the code path.

**Comment by jan-wassenberg** [comment]
Good catch, thanks for noticing this change.
It seems if() indeed has better codegen: https://gcc.godbolt.org/z/vsKdTYYj1
