### ISSUE TITLE
Help implementing Transform1Reverse

### ISSUE THREAD

**Issue by chinwobble** [google/highway#2398]
Hi there,
I have a usecase where I want to reverse a string and transform the elements.
This is a vectorised version of a gene sequencing algorithm.

I have the scalar version here:
```cpp
static string reverseComplementSerial(string* origin) {
    string str(origin->length(), 0);
    int len = origin->length();
    for (int c = 0; c < origin->length(); c++)
    {
      char base = (*origin)[c];
      switch (base)
      {
      case 'A':
      case 'a':
        str[len - c - 1] = 'T';
        break;
      case 'T':
      case 't':
        str[len - c - 1] = 'A';
        break;
      case 'C':
      case 'c':
        str[len - c - 1] = 'G';
        break;
      case 'G':
      case 'g':
        str[len - c - 1] = 'C';
        break;
      default:
        str[len - c - 1] = 'N';
      }
    }
    return str;
}
```

This is the vectorised version.

```cpp
#pragma once
#include <string>
#include "hwy/highway.h"

HWY_BEFORE_NAMESPACE();
namespace hwy {
namespace HWY_NAMESPACE {

template <class D, class Func, typename T = hwy::HWY_NAMESPACE::TFromD<D>>
void Transform1Reversed(D d, T* HWY_RESTRICT inout, size_t count,
                const T* HWY_RESTRICT in1, const Func& func) {
  const size_t N = hwy::HWY_NAMESPACE::Lanes(d);

  size_t idx = 0;
  if (count >= N) {
    for (; idx <= count - N; idx += N) {
      const Vec<D> v = hwy::HWY_NAMESPACE::LoadU(d, inout + idx);
      const Vec<D> v1 = hwy::HWY_NAMESPACE::LoadU(d, in1 + idx);
      hwy::HWY_NAMESPACE::StoreU(hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), d, inout + count - N - idx);
    }
  }

  // `count` was a multiple of the vector length `N`: already done.
  if (HWY_UNLIKELY(idx == count)) return;

  const size_t remaining = count - idx;
  HWY_DASSERT(0 != remaining && remaining < N);
//   const HWY_CAPPED(T, 4) df;
  const auto v = MaskedLoad(FirstN(d, remaining), d, inout + idx);
  const auto v1 = MaskedLoad(FirstN(d, remaining), d, in1 + idx);
//   const Vec<D> v = hwy::HWY_NAMESPACE::LoadN(d, inout + idx, remaining);
//   const Vec<D> v1 = hwy::HWY_NAMESPACE::LoadN(d, in1 + idx, remaining);
  hwy::HWY_NAMESPACE::StoreN(hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), d, inout, remaining);
}

std::string reverseComplement(std::string *HWY_RESTRICT origin) {

    auto length = origin->length();
    const ScalableTag<uint8_t> d;
    const auto sequence = reinterpret_cast<const uint8_t*>(origin->c_str());
    const auto transform = [](const auto d, auto output, const auto sequence) HWY_ATTR
    {
        const auto a = Set(d, 'A');
        const auto t = Set(d, 'T');
        const auto c = Set(d, 'C');
        const auto g = Set(d, 'G');
        const auto n = Set(d, 'N');
        output = IfThenElse(Eq(sequence, a), t, n);
        output = IfThenElse(Eq(sequence, t), a, output);
        output = IfThenElse(Eq(sequence, g), c, output);
        output = IfThenElse(Eq(sequence, c), g, output);
        return output;
    };
    if (length <= 1000000) {
        uint8_t output[length];
        Transform1Reversed(d, output, length, sequence, transform);
        auto retVal = reinterpret_cast<char *>(output);
        std::string reversed(retVal, length);
        return reversed;
    } else {
        const auto allocated = AllocateAligned<uint8_t>(length);
        Transform1Reversed(d, allocated.get(), length, sequence, transform);
        auto retVal = reinterpret_cast<char *>(allocated.get());
        std::string reversed(retVal, length);
        return reversed;
    }
}

}
}
HWY_AFTER_NAMESPACE();
```

I have tested this on AMD64.
My transform lambda works as expected for the case when there is a full width vector.
When my array is a non-full vector the transforms don't work as expected.
Any help would be appreciated.

I have the full code with tests here.
https://github.com/chinwobble/fastplong/actions/runs/12136293268/job/33837118546#step:13:63

**Comment by johnplatts** [comment]
Need to replace `hwy::HWY_NAMESPACE::StoreN(hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), d, inout, remaining);` at the end of the Transform1Reversed function with the following:
```
hwy::HWY_NAMESPACE::StoreN(
      hwy::HWY_NAMESPACE::SlideDownLanes(
          d, hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), N - remaining),
      d, inout, remaining);
```

Note that the SlideDownLanes op is needed to slide down the reversed elements down to the beginning of the vector if `remaining < N` is true.

**Comment by chinwobble** [comment]
> Need to replace `hwy::HWY_NAMESPACE::StoreN(hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), d, inout, remaining);` at the end of the Transform1Reversed function with the following:
> 
> ```
> hwy::HWY_NAMESPACE::StoreN(
>       hwy::HWY_NAMESPACE::SlideDownLanes(
>           d, hwy::HWY_NAMESPACE::Reverse(d, func(d, v, v1)), N - remaining),
>       d, inout, remaining);
> ```
> 
> Note that SlideDownLanes is needed to slide down the reversed elements down to the beginning of the vector if `remaining < N` is true.

@johnplatts thanks that worked!

Would this algorithm be more efficient with a table based lookup?
I see in the documentation there is `TableLookupLanes` but I don't quite understand how to use them.

**Comment by johnplatts** [comment]
> Would this algorithm be more efficient with a table based lookup? I see in the documentation there is `TableLookupLanes` but I don't quite understand how to use them.

`TableLookupLanes(tbl, indices)` is equivalent to the following pseudocode:
```
using D = hwy::HWY_NAMESPACE::DFromV<hwy::RemoveCvRef<decltype(tbl)>>;
D d;
hwy::HWY_NAMESPACE::Vec<D> result;

const size_t N = hwy::HWY_NAMESPACE::Lanes(d);
for (size_t i = 0; i < N; i++) {
  result[i] = tbl[indices[i]];
}

return result;
```

`TwoTablesLookupLanes(d, tbl1, tbl2, indices)` is equivalent to the following pseudocode:
```
using D = hwy::RemoveCvRef<decltype(d)>;
using T = hwy::HWY_NAMESPACE::TFromD<D>;
using TU = hwy::MakeUnsigned<T>;
hwy::HWY_NAMESPACE::Vec<D> result;

const size_t N = hwy::HWY_NAMESPACE::Lanes(d);
for (size_t i = 0; i < N; i++) {
  const TU src_lane_idx = indices[i];
  result[i] = (src_lane_idx < N) ? tbl1[src_lane_idx] : tbl2[src_lane_idx];
}

return result;
```

The `indices` parameter that is passed into the TableLookupLanes or TwoTablesLookupLanes op is expected to be created using `IndicesFromVec(d, idx)` or `SetTableIndices(d,  idx)`.

**Comment by jan-wassenberg** [comment]
To briefly expand on John's comment on how tables work: we have the general principle that specialized approaches such as Reverse/SlideDownLanes should be at least as efficient as a table lookup which would have the result (or else we should have implemented Reverse/SlideDownLanes in terms of that faster approach).
This means John's suggestion with SlideDownLanes seems good already.
