### ISSUE TITLE
[Neon] Use Table Three Lookups with Highway?

### ISSUE THREAD

**Issue by FabianSchuetze** [google/highway#2402]
Is there a way to port vqtbl3q_u8 lookups (or interleaving with a stride of three) to Highway? 

I try to convert the following algorithm to Highway:
```
void zip(uint8x16x3_t src1, uint8x16x3_t src2, uint8_t* dest) {
    constexpr uint8x16_t lookup0 = {0, 1,  2,  16, 17, 18, 3, 4,
                                    5, 19, 20, 21, 6,  7,  8, 22};
    constexpr uint8x16_t lookup1 = {23, 24, 9,  10, 11, 25, 26, 27,
                                    12, 13, 14, 28, 29, 30, 15, 32};
   ...
 uint8x16x3_t out;

    // Combine src1 and src2 vectors into pairs for the lookups
 uint8x16x2_t tbl0 = {src1.val[0], src2.val[0]};
 uint8x16x3_t tbl1 = {src1.val[0], src2.val[0], src1.val[1]};
 

 out1.val[0] = vqtbl2q_u8(tbl0, lookup0);
 out1.val[1] = vqtbl3q_u8(tbl1, lookup1);
...
 vst1q_u8_x3(dest, out1);
}
```
The function is on [Godbolt](https://godbolt.org/z/ETK49bM7h). The input vectors are RGB values and need to be interleaved with stride 3: Take three values from src1, three from src2, etc. until all 96 values from src1 and src2 are taken. Because of the indivisibility of 16 by 3, the interleaving spans two or three source arrays. 

I could easily replicate a different variant of my algorithm to Highway. That variant splits the source arrays into three for each color (already at the data loading stage), interleaves the colors (r1 and r2, say), and stores them with `StoreInterleaved3`. That variant is more elegant but also 20% slower. 

I could think of complex ways to mimic the three table lookup, with `TwoTablesLookupLanes` and `InsertLane`. However, I was wondering if there is a more elegant way to do that? I'm grateful for any tips or suggestions.

**Comment by jan-wassenberg** [comment]
hm, there really is no way around the u8x3 layout, e.g. inserting a fourth channel, or keeping the data de-interleaved and only doing this once, off the critical path?

We do not have a ThreeTables.. op because all targets except NEON (including SVE) would struggle to implement that efficiently.

**Comment by FabianSchuetze** [comment]
Thanks for the reply.

Changing to four channels would be possible. I would use BitCast to cast to 32bit, Interleave*, and cast again (or store)?

I didn't see a similar OP for X86 targets, but I  didn't look for the SVE ops and am surprised that something like vqtbl3q_u8 isn't implemented. Thanks for this interesting info!

**Comment by johnplatts** [comment]
> We do not have a ThreeTables.. op because all targets except NEON (including SVE) would struggle to implement that efficiently.

PPC10 can actually do a three-table or four-table lookup using 2 xxpermx instructions followed by a xxlor instruction.

RVV can efficiently do a three-table or four-table lookup using a single vrgather.vv instruction in the case where all of the table vectors and index vector are full vectors and where the LMUL of the table and LMUL vectors is 1 or 2.

AVX3_DL/AVX10 targets can efficiently do a three-table or four-table lookup of 16-byte I8/U8 vectors using two vinserti32x4 instructions (or only 1 vinserti32x4 instruction in the case of a three-table lookup) followed by a vpermb instruction. Clang 7 or later can also optimize out the load of 2 contiguous 16-byte vectors down to a single 32-byte vector load on AVX3 targets as demonstrated in a snippet that can be found at https://godbolt.org/z/oq748afn6.

**Comment by FabianSchuetze** [comment]
@johnplatts : thanks a lot for your very interesting and insightful comment. The code snippet is also very useful.

**Comment by jan-wassenberg** [comment]
Yes, I am often impressed how John is able to emulate missing instructions :)
In this case I think it is fair to say that ThreeTables is still expensive at least on RVV and AVX3 because high-LMUL vrgather can be dozens of cycles and we'd only be processing quarter vectors on x86.
