### ISSUE TITLE
HWY_TARGET_INCLUDE seems to need a full path?

### ISSUE THREAD

**Issue by 7sharp9** [google/highway#2408]
I get the following erorr when I try add the `HWY_TARGET_INCLUDE` for my current source file:

```
In file included from /Users/davethomas/Plugins/Test/source/DSP/secondOrder.cpp:6:
/Users/davethomas/Plugins/Test/cmake-build-release/_deps/highway-src/hwy/foreach_target.h:94:10: fatal error: 'DSP/secondOrder.cpp' file not found
   94 | #include HWY_TARGET_INCLUDE
      |          ^~~~~~~~~~~~~~~~~~
/Users/davethomas/Plugins/Test/source/DSP/secondOrder.cpp:4:28: note: expanded from macro 'HWY_TARGET_INCLUDE'
    4 | #define HWY_TARGET_INCLUDE "DSP/secondOrder.cpp"
      |                            ^~~~~~~~~~~~~~~~~~~~~
```

The file looks like this, I snipped off the end:

```
#include "secondOrder.h"

#undef HWY_TARGET_INCLUDE
#define HWY_TARGET_INCLUDE "DSP/secondOrder.cpp"

#include <hwy/foreach_target.h> // must come before highway.h
#include <hwy/highway.h>

HWY_BEFORE_NAMESPACE();
namespace project {
    namespace HWY_NAMESPACE { // required: unique per target

        // Can skip hn:: prefixes if already inside hwy::HWY_NAMESPACE.
        namespace hn = hwy::HWY_NAMESPACE;
```

If I edit `HWY_TARGET_INCLUDE` to use the full path it works?
```
#define HWY_TARGET_INCLUDE "/Users/davethomas/Plugins/Test/source/DSP/secondOrder.cpp"
```

I would rather not have to use the full path.  The path is correct though, I have a source folder then DSP folder with `secondOrder.cpp` and `secondOrder.h` inside there.  The `secondOrder.cpp` file references the include file with `secondOrder.h`

Any ideas?

**Comment by johnplatts** [comment]
For HWY_TARGET_INCLUDE to work without the full path, the directory containing the DSP/secondOrder.cpp file needs to be passed as an include directory to GCC or Clang.

For libraries that are built using CMake-based projects, this can be done by including the source directories of C++ files that possibly use Google Highway dynamic dispatch in the include path by adding a `target_include_directories` line in CMakeLists.txt like the line shown below (which was taken from https://github.com/johnplatts/simdhwyhash/blob/main/CMakeLists.txt), with `simdhwyhash` replaced with the target of the library or application that you are building:
```target_include_directories(simdhwyhash PRIVATE ${PROJECT_SOURCE_DIR}/src)```

**Comment by 7sharp9** [comment]
Thanks @johnplatts that did it.  I ended up adding `target_include_directories("${PROJECT_NAME}" PRIVATE ${PROJECT_SOURCE_DIR}/source/dsp)` and droping the dsp prefix in the cpp file.   I really appreciate all your help!
