### ISSUE TITLE
How to Target Architectures with Different Register Counts?

### ISSUE THREAD

**Issue by FabianSchuetze** [google/highway#2418]
How do experienced Highway users write portable code across architectures with different register counts?

If I target armv8-a, I usually try to unroll loops to reach 32 registers, whilst for AVX2 I target 16 registers. I then write loops with compile-time constant bounds and use various `pragma unroll`s. However, these `pragma unroll`s differ slightly across gcc and clang and are a bit of a pain to maintain. I wanted to ask how experienced highway users deal with such complications?

**Comment by johnplatts** [comment]
Here are the number of SIMD registers available on some architectures that have SIMD instruction set extensions supporting 128-bit or larger vectors:
- SSE2/SSSE3/SSE4/AVX2/AVX3/AVX10 on x86_32 - 8
- SSE2/SSSE3/SSE4/AVX2 on x86_64 - 16
- AVX3/AVX10 on x86_64 - 32
- RVV - 32 (vectors with LMUL >= 2 occupy more than one vector register)
- PPC8/PPC9/PPC10 - 64 (some of the PPC8/PPC9/PPC10 vector ops only operate on VS32-VS63, which are the AltiVec vector registers)
- Armv7 NEON - 32 64-bit vector registers (128-bit vectors are stored in a pair of 2 64-bit vector registers on Armv7)
- AArch64 NEON/SVE - 32
- Z14/Z15 - 32
- LSX/LASX - 32

**Comment by FabianSchuetze** [comment]
Thanks, @johnplatts ! My question was more how do you write portable Highway code that works well across these different architectures with different register counts? 

Do you maybe use loops with `pragma unroll` and carry the data around in `std::arrays<vec, N>` ?

**Comment by FabianSchuetze** [comment]
To make it more concrete, I tried unrolling by the size of a template argument, but that seems to produce poor code. 

See the following (also on [CE](https://godbolt.org/z/rPar3qaqG) ):
```c++
#include <array>
#include <hwy/highway.h>
namespace hn = hwy::HWY_NAMESPACE;
using InpT = const float* __restrict__;

template <size_t unroll_cout>
auto __attribute__((noinline)) load(InpT data, size_t index) {
    constexpr hn::ScalableTag<float> d;
    constexpr size_t lane_count = hn::Lanes(d);
    using vec = hn::Vec<decltype(d)>;
    using vecs = std::array<vec, unroll_cout>;
    vecs loaded;
    for (size_t i = 0; i < unroll_cout; ++i) {
        loaded[i] = hn::Load(d, data + index);
        index += lane_count;
    }
    return loaded;
}

template auto load<3ul>(InpT data, size_t index);
```
which produced:
```asm
auto load<3ul>(float const*, unsigned long):
        mov     rax, rdi
        vmovaps ymm0, ymmword ptr [rsi + 4*rdx]
        vmovaps ymm1, ymmword ptr [rsi + 4*rdx + 32]
        vmovaps ymm2, ymmword ptr [rsi + 4*rdx + 64]
        vmovaps ymmword ptr [rdi + 64], ymm2
        vmovaps ymmword ptr [rdi + 32], ymm1
        vmovaps ymmword ptr [rdi], ymm0
        vzeroupper
        ret
```
The assembly seems as if the loaded data is just transferred between two memory regions? When I just return one vector, everything seems reasonable to me.

**Comment by johnplatts** [comment]
> Thanks, [@johnplatts](https://github.com/johnplatts) ! My question was more how do you write portable Highway code that works well across these different architectures with different register counts?
> 
> Do you maybe use loops with `pragma unroll` and carry the data around in `std::arrays<vec, N>` ?

Here is a link to a snippet that demonstrates loop unrolling using C++ lambdas and C++ templates (requires C++17 or later):
https://godbolt.org/z/131vK96hr

**Comment by jan-wassenberg** [comment]
@johnplatts that's a nifty solution :) Would you like to add this to contrib/unroller, or examples/, or link to the Godbolt in the examples section of the README?

@FabianSchuetze pragma unroll has the limitation that the compiler is unlikely to split up your accumulator(s), especially with floating-point. Hence I usually manually unroll, sometimes using infra similar to John's above, but more basic ([example](https://github.com/google/gemma.cpp/blob/9dfe2a76be63bcfe679b94335f171674420f92e8/compression/compress-inl.h#L565)).

**Comment by FabianSchuetze** [comment]
Thanks for the great answers to you John and Jan! Thanks also to you John for the great and impressive code example.

[@jan-wassenberg](https://github.com/jan-wassenberg): Can you explain more what you mean by "pragma unroll has the limitation that the compiler is unlikely to split up your accumulator(s), especially with floating-point". I know the limitation of auto-vectorization with floats, but I am unaware of the unwillingness to unroll vectorized floats. I tried to document your comment here https://godbolt.org/z/5oK3PTYo5, but I believe the code unrolls well.

If I may ask in passing something about the design of HW: Why is it often necessary to pass the Tag `d` to a function in addition to the input vector? For example: `T ReduceSum(D, V v)`. I always think that `D` should be retrievable from `V`, or?

**Comment by jan-wassenberg** [comment]
Sure :)
The issue is that it is necessary for you to manually create an array of `accums`. The compiler is not able to split one accum into several by itself, hence merely unrolling the main loop is not enough - you also had to change the structure of your code.

The `d` arg is necessary for SVE/RVV, where the vector size is not constexpr. For this reason, an array of vectors is also not allowed by the compiler. Hence what I usually do is to 'unroll' the array into accum0 and accum1, and then manually unroll the loop to update both of them, without pragma unroll.

**Comment by FabianSchuetze** [comment]
Thanks for the interesting and illuminating comment! I'll close the ticket now.
