### ISSUE TITLE
New functions to add

### ISSUE THREAD

**Issue by jan-wassenberg** [google/highway#3]
Looks like Abs for floating-point would be able to take advantage of AVX-512 instructions for that.

Other suggestions by @cwfitzgerald which we'd like to add:

* ZeroExtendVector to go from 128bit to 256 etc.
* Combine(hi, lo) to concatenate

**Comment by jan-wassenberg** [comment]
These are now pushed :) @cwfitzgerald FYI

**Comment by cwfitzgerald** [comment]
Amazing to hear! 🎉
