### ISSUE TITLE
Question: best way of linking statically to highway ?

### ISSUE THREAD

**Issue by boxerab** [google/highway#336]
Has highway's management of cmake targets changed recently ?

My cmake codec links to highway cmake targets using `add_subdirectory`

https://github.com/GrokImageCompression/grok/blob/master/src/lib/jp2/CMakeLists.txt#L264

What is the best way of linking statically to highway ?  When I turn `BUILD_SHARED_LIBS` off for my parent project,
I get this error when generating with cmake:

```
CMake Error: install(EXPORT "GrokTargets" ...) includes target "grokj2k" which requires target "hwy" that is not in any export set
```

Thanks!!

**Comment by jan-wassenberg** [comment]
@boxerab is this resolved?

In the last few weeks there was a change to hwy_list_targets, extra warnings, and the library version - nothing that looks relevant.

**Comment by boxerab** [comment]
@jan-wassenberg thanks, it looks like something I need to figure out on my side.
