### ISSUE TITLE
Num0BitsBelowLS1Bit_Nonzero64 is broken on 32 bit MSVC

### ISSUE THREAD

**Issue by dlemstra** [google/highway#337]
The `_BitScanForward64` method is not available in 32 bit MSVC and causes a build failure. There is a fix for this available in the jpeg-xl repository: https://github.com/libjxl/libjxl/blob/810ecc358b21834da88e5c82d5d142ff7195c218/lib/jxl/base/bits.h#L97-L106

**Comment by jan-wassenberg** [comment]
Fixed by your #338, thanks!
