### ISSUE TITLE
Question: why static libraries only?

### ISSUE THREAD

**Issue by novomesk** [google/highway#380]
Hello,
Some of my friends are asking why libhwy.a and libhwy_contrib.a are build as static libraries only:

`add_library(hwy STATIC ${HWY_SOURCES})`

`add_library(hwy_contrib STATIC ${HWY_CONTRIB_SOURCES})`

Some distributions (for example Gentoo) [prefer to avoid static libraries](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies), shared/dynamic are preferred.

What are the reasons why only static libs are built now?

Would it it good to enable optional building of dynamic libraries according the `BUILD_SHARED_LIBS` setting?

**Comment by jan-wassenberg** [comment]
@novomesk Hi, thanks for reaching out. There is no reason beyond that I had thought static would be sufficient, and I'm not yet familiar with what it takes to make it dynamic.

Do you have a reference handy on the minimum required for a static build? The [documentation](https://cmake.org/cmake/help/latest/guide/tutorial/Selecting%20Static%20or%20Shared%20Libraries.html) involves quite a lot of boilerplate, and hopefully we can avoid dllexport for all the ops, which are mostly templates.

Do you think it's possible to only export the few functions which are actually in a .cc such as SupportedTargets?

**Comment by novomesk** [comment]
My idea was to solve it by few edits in CMakeLists.txt. It would allow packages to select if they want to build shared or static libraries:

Somewhere in the beginning I would put:
```
# SOVERSION scheme: MAJOR.MINOR.PATCH
#   If there was an incompatible interface change:
#     Increment MAJOR. Set MINOR and PATCH to 0
#   If there was a compatible interface change:
#     Increment MINOR. Set PATCH to 0
#   If the source code was changed, but there were no interface changes:
#     Increment PATCH.
set(LIBRARY_VERSION_MAJOR 1)
set(LIBRARY_VERSION_MINOR 0)
set(LIBRARY_VERSION_PATCH 0)
set(LIBRARY_VERSION "${LIBRARY_VERSION_MAJOR}.${LIBRARY_VERSION_MINOR}.${LIBRARY_VERSION_PATCH}")
set(LIBRARY_SOVERSION ${LIBRARY_VERSION_MAJOR})

option(BUILD_SHARED_LIBS "Build shared libraries" ON)
```

Remove *STATIC* from `add_library(` (it will build shared/static according BUILD_SHARED_LIBS option) and add `set_target_properties`:
```
add_library(hwy ${HWY_SOURCES})

set_target_properties(hwy
                      PROPERTIES
                          VERSION ${LIBRARY_VERSION}
                          SOVERSION ${LIBRARY_SOVERSION})



add_library(hwy_contrib ${HWY_CONTRIB_SOURCES})

set_target_properties(hwy_contrib
                      PROPERTIES
                          VERSION ${LIBRARY_VERSION}
                          SOVERSION ${LIBRARY_SOVERSION})

add_library(hwy_test ${HWY_TEST_SOURCES})

set_target_properties(hwy_test
                      PROPERTIES
                          VERSION ${LIBRARY_VERSION}
                          SOVERSION ${LIBRARY_SOVERSION})
```

**Comment by deymo** [comment]
@novomesk  I don't think the common arguments listed in gentoo apply here. hwy.a includes the targets.cc and the aligned_allocator.cc (it today still includes nanobenchmark.cc but I think that one should not be part of hwy.a anyway). The argument of "bundling dependencies" doesn't apply here because most of hwy is inline header functions; so if you have a bug in a header in hwy, even if you use a shared library, the bug will still be present in the downstream build code. The only way to deal with this is to always bump the soversion.

Regarding visibility, the libhwy.a should be marked as hidden and that just works.

The "wasted" allocated space in a binary attributed to hwy.a (in the case of libjxl / djxl / etc) in x86_64 is 864 bytes; the wasted space of the function tables and strings for the shared library is probably more, so that doesn't really apply either.

Your proposed set-up is fine for building either shared or static libs, but doesn't let you build both.

**Comment by novomesk** [comment]
I think for myself these answers are sufficient to leave the things as they are. Thanks for the answers, if someone asks me, I will redirect them here.

**Comment by jan-wassenberg** [comment]
@novomesk thanks for sharing the CMake example! @deymo , would it be helpful if we used this proposal for "either static or dynamic" builds?

**Comment by malaterre** [comment]
@jan-wassenberg Would it be possible to re-open this issue. I'd love to be able to build highway as shared libary (with proper SONAME/SOVERSION setup).

**Comment by jan-wassenberg** [comment]
Hi @malaterre , sure, happy to reopen. I'd like to do this in a way that does not break existing uses.

What do you think of the approach proposed by novomesk?

**Comment by malaterre** [comment]
@jan-wassenberg I've re-used a portion of the patch suggested by @novomesk. I've simplified the versioning mechanism by directly using the one built-in cmake `project()` command. I've also preserved the legacy behavior of building `STATIC` by default.
