### ISSUE TITLE
Test failures with identical values on aarch64

### ISSUE THREAD

**Issue by Hello71** [google/highway#398]
Hi, I am trying to package highway for Alpine Linux. It builds and passes tests on all archs except aarch64, where 34 out of 219 tests fail: https://gitlab.alpinelinux.org/alxu/aports/-/jobs/506957. I patched the test to use %a instead of %g for printing output: https://gitlab.alpinelinux.org/alxu/aports/-/blob/libjxl/testing/highway/full-test-values.patch, but it still prints the same values for expected and got.

This is near-identical to the reported output for #350, but 0.14.2 contains the alleged fix for that issue. I haven't tested any other versions or tried bisecting yet. Let me know what additional information you need.

**Comment by jan-wassenberg** [comment]
> I found that HWY_ARCH_ARM64 does not appear to be defined anywhere. 

Oops, thanks for catching that. I'll fix that first while investigating what else might be happening.

> It didn't work: https://gitlab.alpinelinux.org/alxu/aports/-/jobs/507626.

Looks like the logs are already deleted?

@eclipseo 
> Fedora Rawhide, gcc 12, v0.15.0 and fbe5705
> combine_test.cc:107: Neon, i16x1 lane 0 mismatch: expected '0x0003', got '0x0000'.
> mask_test.cc:224: Assert !AllTrue(d, MaskFromVec(Load(d, mask_lanes.get())))
> mask_test.cc:358: Neon, u64x1 lane 0 mismatch: expected '1', got '0'.

Thanks for sharing the summary. I'm happy to look into this but haven't been able to repro so far.
The most recent cross-compiler package I see is g++-11-aarch64-linux-gnu.
With that, the following passes:

```
export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
rm -rf build_arm8
mkdir build_arm8
cd build_arm8
CC=aarch64-linux-gnu-gcc-11 CXX=aarch64-linux-gnu-g++-11 cmake .. -DHWY_WARNINGS_ARE_ERRORS:BOOL=ON
make -j8
ctest
cd ..
```
Looks like this might be specific to GCC 12?

**Comment by Hello71** [comment]
Not sure why, but most of the tests seem to be passing now, except HwyMaskTestGroup/HwyMaskTest.TestAllAllTrueFalse/Neon: https://gitlab.alpinelinux.org/alxu/aports/-/jobs/604889. This seems to be related to -Os; it doesn't fail with -O2.

**Comment by jan-wassenberg** [comment]
I just tested again using the above commands, and latest Highway commit. Indeed the test fails now with GCC 11.2.0 - investigating. We already had trouble at this spot with GCC 10.2, indeed looks like a compiler issue.

**Comment by malaterre** [comment]
@jan-wassenberg I've cherry-picked commit a1302c69192cfbea44cd5330ac828d40fba958e2 over release 0.17.0, and it appears that armhf is still failing the test suite:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=0.17.0-2&stamp=1655882301&raw=0

```
140/164 Test #140: HwyMulTestGroup/HwyMulTest.TestAllMulAdd/Emu128  # GetParam() = 268435456 ....................................Subprocess aborted***Exception:   0.07 sec
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = HwyMulTestGroup/HwyMulTest.TestAllMulAdd/Emu128
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyMulTestGroup/HwyMulTest
[ RUN      ] HwyMulTestGroup/HwyMulTest.TestAllMulAdd/Emu128


f32x4 expect [0+ ->]:
  5,11,19,29,
f32x4 actual [0+ ->]:
  -9,11,19,29,
Abort at ./hwy/tests/mul_test.cc:308: Emu128, f32x4 lane 0 mismatch: expected '5', got '-9'.

```

Should I report a new bug report, or does it belong here (#398) ?

**Comment by jan-wassenberg** [comment]
hm. The test is checking that -(-(i+2) * (i+2)) + (i+1) = i*i + 5*i + 5. Very strange that only the first lane (i=0) should mismatch.

I see this is GNU 11.3.0, and that this is the only test that fails. Possible options include disabling EMU128 for this compiler (using the previous HWY_SCALAR instead), or skipping this test for this specific compiler/platform - what do you think?

**Comment by malaterre** [comment]
@jan-wassenberg If I do:

```
 -DHWY_DISABLED_TARGETS='(HWY_EMU128)'
```

I get:

```
/home/malat/highway-0.17.0/hwy/detect_targets.h:324:2: error: #error "At least one baseline target must be defined and enabled"
  324 | #error "At least one baseline target must be defined and enabled"
```

What is the correct way to disable a targets (typically I do: `-DHWY_DISABLED_TARGETS='(HWY_SSE4|HWY_SSSE3)'` on Debian/i386 builds machine).

Thanks!

**Comment by jan-wassenberg** [comment]
:) Yes, we must always have at least one fallback enabled. We select it here:
```
#if defined(HWY_COMPILE_ONLY_SCALAR)
#define HWY_BASELINE_SCALAR HWY_SCALAR
#else
#define HWY_BASELINE_SCALAR HWY_EMU128
#endif
```

Thus `-DHWY_COMPILE_ONLY_SCALAR` is what you want in this case.

**Comment by malaterre** [comment]
arm64 test suite seems to be working just fine in git/master. I suspect this can be closed.

**Comment by jan-wassenberg** [comment]
Excellent, thanks :)
