### ISSUE TITLE
lzcnt64

### ISSUE THREAD

**Issue by yzazik** [google/highway#426]
Hello,
I need some sort of 64-bit `lzcnt` or `bsr` (or similar) value from a `Mask<>` in portable way, could be something like `FindLastTrue()`.
Or maybe even better (if possible) expose `detail::BitsFromMask()` (I guess, up to 64 lanes) to call `Num0BitsAboveMS1Bit_Nonzero64()` on the result.
Strangely, x86_512-inl.h doesn't have `detail::BitsFromMask()`, not sure how exactly `FindFirstTrue()` works there.
Thank you.

**Comment by yzazik** [comment]
Man, my company is moving from Github to GCP, I though I would leverage something from learning Github.

**Comment by yzazik** [comment]
@jan-wassenberg Hi Jan, first of all, my company is very meticulous and diligent when it comes to open source, I'm currently in the process of getting proper procedures to follow (if this activity would be approved at all).
But in general, here is what I'm still trying to figure out and it would be great if someone could help me out.
1. Do I have to have a signed Google CLA?
2. Will it expose my employment?
3. What do I need to do for creating pull request? specifically, do I need to fork, or somehow stash/shelve?
Thank you.

**Comment by jan-wassenberg** [comment]
@yzazik thanks for sharing the update and looking into the procedure. I'm happy to help:

1. Yes, we need a CLA. It can be agreed online: https://cla.developers.google.com/about/google-individual The key point here is that you need permission from your employer to sign this.
2. No, this does not expose who you are working for.
3. To create a pull request, you first need to click Fork at the top right of the github page (once only). Then you can push your change to github.com/yzazik/highway, open that in the browser, click branches, select the one you pushed to, and from there you can click pull request.

**Comment by yzazik** [comment]
@jan-wassenberg  Alright, thank you, this may take a few days, IT/Legal is bit slow on their responses.

**Comment by yzazik** [comment]
Takes much more time for legal to respond and in general, to procedures are much more unreasonable than I thought. I have those implemented locally, so I'm closing this for now.

**Comment by jan-wassenberg** [comment]
@yzazik I understand that the legal process is lengthy. Sorry to hear it's much more unreasonable than expected.
Out of curiosity, do they allow patches made from non-work computers outside work hours?

**Comment by yzazik** [comment]
@jan-wassenberg It's not about mechanics (which computer, tools or time), it's about who I am (ie employee of the company, all my work is technically its property and Google wants a part of it to be _relinquished_) and about the content (the company wants to make sure that no CCI (company confidential information) would be leaked out).
Well, it's all understandable, but none of it that is _one click away_ easy, so I have some paperwork to do (describe the intent, the change, the project, future involvement, asses potential conflicts, projects relations, any algorithms I might have used from the last 20 years, etc.) The requirements are so extensive, it's kills all the motivation. For now I just want to see how far I would get.

**Comment by jan-wassenberg** [comment]
@yzazik Ah, the "they own all work" part is a challenge. I understand, thanks for sharing :)

**Comment by yzazik** [comment]
@jan-wassenberg Ok, it would require to set some sort of a sandbox for the review process, it's basically a description of what I'm giving away. As for the CLA, the response I've got is this:

_We have a range of specific agreements with Google based on each project. We do not sign the general CLA for these. We have a contact in Google legal and can reach out based on this project once we understand your plans with the sandbox review._

In essence, as I see it, general CLA signing is out of the picture, the question is whether all this could still be worked out without it (but instead, with some other type of agreements), if yes, I would go through the sandbox setup and all, if not, then I guess, that's about it. Please let me know (PM if preferable).

Thank you.

**Comment by jan-wassenberg** [comment]
@yzazik thanks for following up! I am asking internally what we can do.

Would you prefer a PM? If so, please share your preferred address; I believe PMs are not possible on github.

**Comment by yzazik** [comment]
@jan-wassenberg Not until there is something confidential, but if there is, let me know and I'll send you a "hello" email :).

**Comment by jan-wassenberg** [comment]
@yzazik OK :)
I've heard back that the general CLA is indeed required.
Unfortunately it doesn't look like we can proceed, but thank you for looking into it!
