### ISSUE TITLE
Poor Compress<U16>() performance on AVX2

### ISSUE THREAD

**Issue by yzazik** [google/highway#442]
Hi Jan,
I'm getting rather poor Comrpess() performance with uint16_t, I saw some comments saying that 2 LUT lookups probably worse than promoting twice to uint32_t. That is rather debatable but probably simpler from maintenance point of view.
But the code has 4 extra explicit loads anyways in `SetTableIndices()` and `IndicesFromBits()` and those are a definite killers there.
I think explicit loads (`_mm256_load*()`) perform somehow worse than implicit ones (in instructions with m32/m64 operands).
Memory operands probably organized better and cached right away by CPU through some sort of inline hint and compiler (at least msvc) is quite hesitant converting to those from loads.
The hint is probably somehow berried in `_mm256_set_*()` intrinsics which are not used in the library (neither has interface for those), but I run some benchmarks and they have more reasons to be there rather than not.
I reworked it with 2 LUTs (called it Squeeze), tried with separate high and low indices workouts and combined, combined actually performed better with modified uint8_t pairs for 8-bit shuffle:
```
Run on (8 X 2304 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 8192 KiB (x1)
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_Compress       43.0 ns         43.3 ns     16592593
BM_Compress       42.7 ns         42.4 ns     16592593
BM_Compress       42.4 ns         42.0 ns     16000000
BM_Compress       43.0 ns         43.0 ns     16000000
BM_Squeeze        3.34 ns         3.30 ns    213333333
BM_Squeeze        3.34 ns         3.30 ns    213333333
BM_Squeeze        3.38 ns         3.37 ns    213333333
BM_Squeeze        3.34 ns         3.37 ns    213333333
```
So there are two questions, can we have a plan to revisit the use of `load_*()`s vs `set_*()`s for constants and what do I do with my `Squeeze()`, anyone want's it at all or I just keep it to myself?

**Comment by jan-wassenberg** [comment]
Interesting, thanks @yzazik for sharing your observations.
Can you share a godbolt/llvm-mca link to show the difference between load and set? I have not seen a difference on clang but it is certainly possible.

Wow, that's quite a speedup from squeeze. I'd be very happy to include that, would you like to try creating a pull request?

**Comment by yzazik** [comment]
This maybe a false positive. Surprisingly clang and gcc generates quite adequate code, need to profile it, a tad bigger than mine, more permutes and all but MSVC for some reason generates 3 times more code, all static arrays for `Load()` are converted to a bunch of `mov`s, repushed on stack I guess (alignment issue?), and HWY is not available on godbolt, Matt told me just "not all libraries available for all compilers" (even for header only part, weird). It's not annotated disassembly but here what comes out from it (VS2019, release, x64, avx2, /Oi, /Oy, /O2):

```
		auto tight = Compress(loose, pick);
00007FF6D6C929C9  vpmovmskb   ecx,ymm5  
00007FF6D6C929CD  mov         ecx,ecx  
00007FF6D6C929CF  mov         rax,r11  
00007FF6D6C929D2  pext        r8,rcx,r14  
00007FF6D6C929D7  movzx       r9d,r8b  
00007FF6D6C929DB  lea         rcx,[rbp]  
00007FF6D6C929DF  mov         edx,8  
00007FF6D6C929E4  nop         dword ptr [rax]  
00007FF6D6C929E8  nop         dword ptr [rax+rax]  
00007FF6D6C929F0  lea         rcx,[rcx+80h]  
00007FF6D6C929F7  vmovups     ymm0,ymmword ptr [rax]  
00007FF6D6C929FB  vmovups     xmm1,xmmword ptr [rax+70h]  
00007FF6D6C92A00  lea         rax,[rax+80h]  
00007FF6D6C92A07  vmovups     ymmword ptr [rcx-80h],ymm0  
00007FF6D6C92A0C  vmovups     ymm0,ymmword ptr [rax-60h]  
00007FF6D6C92A11  vmovups     ymmword ptr [rcx-60h],ymm0  
00007FF6D6C92A16  vmovups     ymm0,ymmword ptr [rax-40h]  
00007FF6D6C92A1B  vmovups     ymmword ptr [rcx-40h],ymm0  
00007FF6D6C92A20  vmovups     xmm0,xmmword ptr [rax-20h]  
00007FF6D6C92A25  vmovups     xmmword ptr [rcx-20h],xmm0  
00007FF6D6C92A2A  vmovups     xmmword ptr [rcx-10h],xmm1  
00007FF6D6C92A2F  sub         rdx,1  
00007FF6D6C92A33  jne         BM_Compress+0E0h (07FF6D6C929F0h)  
00007FF6D6C92A35  vpbroadcastd ymm0,dword ptr [rbp+r9*4]  
00007FF6D6C92A3C  mov         dword ptr [pick],esi  
00007FF6D6C92A42  lea         rax,[rbp+400h]  
00007FF6D6C92A49  mov         dword ptr [rbp+804h],4  
00007FF6D6C92A53  mov         rcx,r11  
00007FF6D6C92A56  mov         dword ptr [rbp+808h],8  
00007FF6D6C92A60  mov         edx,8  
00007FF6D6C92A65  mov         dword ptr [rbp+80Ch],0Ch  
00007FF6D6C92A6F  mov         dword ptr [rbp+810h],10h  
00007FF6D6C92A79  mov         dword ptr [rbp+814h],14h  
00007FF6D6C92A83  mov         dword ptr [rbp+818h],18h  
00007FF6D6C92A8D  mov         dword ptr [rbp+81Ch],1Ch  
00007FF6D6C92A97  vpsrlvd     ymm1,ymm0,ymmword ptr [rbp+800h]  
00007FF6D6C92AA0  vpmovzxwd   ymm0,xmm6  
00007FF6D6C92AA5  vpermd      ymm4,ymm1,ymm0  
00007FF6D6C92AAA  nop         word ptr [rax+rax]  
00007FF6D6C92AB0  lea         rax,[rax+80h]  
00007FF6D6C92AB7  vmovups     ymm0,ymmword ptr [rcx]  
00007FF6D6C92ABB  vmovups     xmm1,xmmword ptr [rcx+70h]  
00007FF6D6C92AC0  lea         rcx,[rcx+80h]  
00007FF6D6C92AC7  vmovups     ymmword ptr [rax-80h],ymm0  
00007FF6D6C92ACC  vmovups     ymm0,ymmword ptr [rcx-60h]  
00007FF6D6C92AD1  vmovups     ymmword ptr [rax-60h],ymm0  
00007FF6D6C92AD6  vmovups     ymm0,ymmword ptr [rcx-40h]  
00007FF6D6C92ADB  vmovups     ymmword ptr [rax-40h],ymm0  
00007FF6D6C92AE0  vmovups     xmm0,xmmword ptr [rcx-20h]  
00007FF6D6C92AE5  vmovups     xmmword ptr [rax-20h],xmm0  
00007FF6D6C92AEA  vmovups     xmmword ptr [rax-10h],xmm1  
00007FF6D6C92AEF  sub         rdx,1  
00007FF6D6C92AF3  jne         BM_Compress+1A0h (07FF6D6C92AB0h)  
00007FF6D6C92AF5  popcnt      rdx,r9  
00007FF6D6C92AFA  shr         r8,8  
00007FF6D6C92AFE  lea         rcx,[rbp+860h]  
00007FF6D6C92B05  mov         dword ptr [loose],esi  
00007FF6D6C92B0B  mov         rax,rdx  
00007FF6D6C92B0E  shr         rax,1  
00007FF6D6C92B11  shl         rax,2  
00007FF6D6C92B15  vpbroadcastd ymm0,dword ptr [rbp+r8*4+400h]  
00007FF6D6C92B1F  sub         rcx,rax  
00007FF6D6C92B22  mov         dword ptr [rbp+824h],4  
00007FF6D6C92B2C  movsx       eax,dx  
00007FF6D6C92B2F  mov         dword ptr [rbp+828h],8  
00007FF6D6C92B39  mov         dword ptr [rbp+82Ch],0Ch  
00007FF6D6C92B43  mov         dword ptr [rbp+830h],10h  
00007FF6D6C92B4D  mov         dword ptr [rbp+834h],14h  
00007FF6D6C92B57  mov         dword ptr [rbp+838h],18h  
00007FF6D6C92B61  mov         dword ptr [rbp+83Ch],1Ch  
00007FF6D6C92B6B  vpsrlvd     ymm2,ymm0,ymmword ptr [rbp+820h]  
00007FF6D6C92B74  vextracti128 xmm0,ymm7,1  
00007FF6D6C92B7A  vpmovzxwd   ymm1,xmm0  
00007FF6D6C92B7F  vpxor       xmm0,xmm0,xmm0  
00007FF6D6C92B83  vpermd      ymm3,ymm2,ymm1  
00007FF6D6C92B88  vmovdqu     ymm1,ymmword ptr [__ymm@0000000700000006000000050000000400000003000000020000000100000000 (07FF6D6CBDE80h)]  
00007FF6D6C92B90  vmovdqu     ymmword ptr [rbp+840h],ymm0  
00007FF6D6C92B98  vmovdqu     ymmword ptr [rbp+860h],ymm1  
00007FF6D6C92BA0  vpackusdw   ymm0,ymm3,ymm3  
00007FF6D6C92BA5  vpermq      ymm1,ymm0,88h  
00007FF6D6C92BAB  vmovdqu     ymm0,ymmword ptr [rcx]  
00007FF6D6C92BAF  vmovdqu     xmm2,xmm1  
00007FF6D6C92BB3  vpermd      ymm3,ymm0,ymm2  
00007FF6D6C92BB8  vmovd       xmm0,eax  
00007FF6D6C92BBC  vpbroadcastw ymm0,xmm0  
00007FF6D6C92BC1  vpand       ymm0,ymm0,ymmword ptr [__ymm@0001000100010001000100010001000100010001000100010001000100010001 (07FF6D6CBDEA0h)]  
00007FF6D6C92BC9  vpcmpeqw    ymm2,ymm0,ymmword ptr [__ymm@0001000100010001000100010001000100010001000100010001000100010001 (07FF6D6CBDEA0h)]  
00007FF6D6C92BD1  vpackusdw   ymm0,ymm4,ymm4  
00007FF6D6C92BD6  vpermq      ymm1,ymm0,88h  
00007FF6D6C92BDC  vperm2i128  ymm0,ymm3,ymm3,8  
00007FF6D6C92BE2  lea         rax,[rdx+rdx]  
00007FF6D6C92BE6  mov         qword ptr [loose],0FFFFFFFFFFFFFFFFh  
00007FF6D6C92BF1  vmovdqu     xmm4,xmm1  
00007FF6D6C92BF5  vpalignr    ymm1,ymm3,ymm0,0Eh  
00007FF6D6C92BFB  vpblendvb   ymm3,ymm3,ymm1,ymm2  
00007FF6D6C92C01  lea         rcx,[rbp+8A0h]  
00007FF6D6C92C08  mov         qword ptr [rbp+888h],0FFFFFFFFFFFFFFFFh  
00007FF6D6C92C13  sub         rcx,rax  
00007FF6D6C92C16  mov         qword ptr [rbp+890h],0FFFFFFFFFFFFFFFFh  
00007FF6D6C92C21  mov         qword ptr [rbp+898h],0FFFFFFFFFFFFFFFFh  
00007FF6D6C92C2C  mov         qword ptr [rbp+8A0h],rsi  
00007FF6D6C92C33  mov         qword ptr [rbp+8A8h],rsi  
00007FF6D6C92C3A  mov         qword ptr [rbp+8B0h],rsi  
00007FF6D6C92C41  mov         qword ptr [rbp+8B8h],rsi  
00007FF6D6C92C48  vmovdqu     ymm2,ymmword ptr [rcx]  
00007FF6D6C92C4C  vpblendvb   ymm0,ymm3,ymm4,ymm2  

```

**Comment by jan-wassenberg** [comment]
> not all libraries available for all compilers

True. I noticed Hwy is available for MSVC 19.10 on Wine: https://gcc.godbolt.org/z/15cdbxqYP Unfortunately that's a very old compiler and can only do SSE4.

> mov         dword ptr [rbp+80Ch],0Ch  

This is indeed undesirable. Does adding `static` prevent this? 

BTW /Gv flag might also help with argument passing.

**Comment by yzazik** [comment]
static doesn't help, only the use of _mm256_set_*() functions helps. /Gv doesn't help either.
Alright, I'll check Compress() performance with gcc tomorrow, then I'll close this.
Will handle the Squeeze() separately.

**Comment by yzazik** [comment]
New Info [godbolt](https://godbolt.org/z/WqbPe7Y8r), GCC is putting those movs too on -O2 in every version except trunk (where it also uses `call memcpy`, lines 280 and 291), still twice more code than clang's.
Everything lower than GCC9 is pretty much like MSVC, lots of movs, could I be missing some flags?
Clang rocks, even 7.0 is better than anything GCC outputs, not sure what's the clang's back end for x64.

**Comment by jan-wassenberg** [comment]
@yzazik thanks for checking, interesting, I hadn't seen set outperform loads before (clang is indeed quite good for vector code). What's your suggestion, would it be enough to change the loads in Compress(u16)?

Wow, the GCC codegen is quite a bit longer. I do not understand why it's writing vectors to stack and memcpy. I don't think any flags are missing, -O3 does not help.

**Comment by yzazik** [comment]
I'll try replacing loads on my side, will let you know whether it helps.

Replacing loads only in `Compress()` would be solving only `Compress()` problem, I mean, it would be enough to close this issue, but if it has this rather compiler-adverse effect, it wold probably make sense to just replace all loads (for constants) with `set_*()`s just to get this one out of the way, maybe macro it with compiler switch in case load would ever be faster?

The immediate need would be those two I mentioned - `SetTableIndices()` and `IndicesFromBits()`, and also other things like `Iota()`.

Specifically to `Iota()`, well, I guess, you would have to establish a minimum supported C++ ISO standard (that probably deserves a separate discussion), but it could be done `constexpr`-essingly with something like this (just a direction, there are some details to it to work out):
```cpp
		template <typename T, size_t... N>
		constexpr auto _set256_epi16(T first, std::index_sequence<N...>)
		{
			return _mm256_setr_epi16((N + first)...);
		}

		template <typename T, typename T2>
		Vec256<T> Iota(const Full256<T> d, const T2 first)
		{
			return Vec256<T>{_set256_epi16(first, std::make_index_sequence<MaxLanes(d)>{})};
		}
```
As for the `Squeeze()`, I'm having trouble building google/benchmark with clang (missing regexp), IT guys always have something missing in their installs, and I only have GCC 10.2, so I guess it would have to wait till I test it vs Compress() with clang.

**Comment by jan-wassenberg** [comment]
@yzazik sounds good, thanks. I don't mind replacing some more Load() if we have data to make sure it's actually an improvement in the other cases as well.

For the C++ standard, we're still targeting C++11 for compatibility.

> I'm having trouble building google/benchmark with clang (missing regexp)

Sorry to hear. You may also consider using hwy/nanobenchmark.h? There's an example in nanobenchmark_test.cc.

**Comment by yzazik** [comment]
I replaced 3 loads in `Compress()`, it's twice faster on MSVC, not a lot in total, but it's rather significant for such a small change.
`std::index_sequence<>` is C++14, but I've seen some C++11 replacements. `Iota()` is quite useful for permutes.
But in general, direct interface to `set_*()` would probably be more useful, and would shift sequence implementation to the user.
