### ISSUE TITLE
googletest pull fails

### ISSUE THREAD

**Issue by yzazik** [google/highway#457]
Tried to build tests on Windows (with MSVC), googletest clone fails to pull **master**:
```
Cloning into 'googletest-src'...
fatal: invalid reference: master
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'

```
Looking at googletest, there is actually no **master** tag [there](https://github.com/google/googletest/tags), changing GIT_TAG from **master** to the latest **release-1.11.0** in highway/CMakeLists.txt.in works.

**Comment by jan-wassenberg** [comment]
@yzazik thanks for letting us know. Looks like churn from Googletest renaming the branch to main. Would you please verify that `main` works? If so, I'll change to that, otherwise we can use the release tag you mention.

**Comment by yzazik** [comment]
Confirmed, **main** works.
