### ISSUE TITLE
build fails when building on manjaro, cannot convert const raw(const_512d) to _m512i

### ISSUE THREAD

**Issue by silverhikari** [google/highway#478]
```
/home/silver/.cache/yay/highway-git/src/highway/hwy/ops/x86_512-inl.h:2466:44: error: cannot convert ‘const Raw’ {aka ‘const __m512d’} to ‘__m512i’
 2466 |   return Vec512<T>{_mm512_permutex_epi64(v.raw, _MM_SHUFFLE(0, 1, 2, 3))};
      |                                          ~~^~~
      |                                            |
      |                                            const Raw {aka const __m512d}
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/immintrin.h:49,
                 from /home/silver/.cache/yay/highway-git/src/highway/hwy/ops/x86_256-inl.h:22,
                 from /home/silver/.cache/yay/highway-git/src/highway/hwy/highway.h:297,
                 from /home/silver/.cache/yay/highway-git/src/highway/hwy/tests/swizzle_test.cc:25,
                 from /home/silver/.cache/yay/highway-git/src/highway/hwy/foreach_target.h:102,
                 from /home/silver/.cache/yay/highway-git/src/highway/hwy/tests/swizzle_test.cc:24:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/avx512fintrin.h:6809:32: note:   initializing argument 1 of ‘__m512i _mm512_permutex_epi64(__m512i, int)’
 6809 | _mm512_permutex_epi64 (__m512i __X, const int __I)
      |                        ~~~~~~~~^~~
make[2]: *** [CMakeFiles/swizzle_test.dir/build.make:76: CMakeFiles/swizzle_test.dir/hwy/tests/swizzle_test.cc.o] Error 1
```
gcc is 11.1 incase that helps

**Comment by jan-wassenberg** [comment]
Hi @silverhikari , thanks for reporting this. Oops, missed an overload. Unfortunately clang is permissive about such things and we only catch them during manual pre-release testing. Will send the fix for review shortly :)

**Comment by dbermond** [comment]
Here is a a complete build log when building on Arch Linux x86_64: https://paste.ee/p/KKG8S

Maybe it can be helpful, since there is also tons of warnings that eventually could be fixed.

A git bisect shows the offending commit is c19ff461ddc4994340aec14d124900c67c041f92.

**Comment by jan-wassenberg** [comment]
@dbermond thanks for sharing the log! It's good to fix warnings and I'll start that today.
(We only compile with GCC for pre-release testing, so I'd recommend using a release unless you need the latest.)

**Comment by dbermond** [comment]
Thank you @jan-wassenberg

**Comment by jan-wassenberg** [comment]
@dbermond YW :) I've send this second change for review.

**Comment by dbermond** [comment]
Awesome!

I can confirm that applying both pull requests fixes the build error and all the warnings, with tests passing fine. Building cleanly now, and with LTO enabled.

libjxl git master also builds fine against it, with tests passing fine.

Thank you for working on this :)

**Comment by jan-wassenberg** [comment]
@dbermond Great, thanks for confirming!
