### ISSUE TITLE
Question: why c++11 only?

### ISSUE THREAD

**Issue by malaterre** [google/highway#486]
When compiling highway on Debian buildds machine, one can notice the c++ code is being compiled with explicit `-std=c++11` flag:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=ppc64el&ver=0.15.0-1&stamp=1639773317&raw=0

Since Debian/sid currently ships with GCC-11 which now default to -std=gnu++17 (*), I am wondering if there is a strong reason for doing so.

I believe the cmake code can be relaxed (CMAKE_CXX_STANDARD_REQUIRED=OFF) so that no explicit `-std=c++11` is being passed.

Please clarify c++ target version in highway in the documentation.

Thanks.

(*) https://gcc.gnu.org/gcc-11/changes.html

**Comment by jan-wassenberg** [comment]
Hi @malaterre, thanks for starting the discussion.
We are OK with compiling for newer C++ versions, but it seems useful to document that C++11 is the minimum.

We can also add a comment saying it's currently intended to remain sufficient, though perhaps we'll
optionally start using C++14/17 features at some point.

In CMake documentation I see:

"For example, if C++ 11 features are used extensively in a project's header files, then clients must use a compiler mode that is no less than C++ 11. This can be requested with the code:
target_compile_features(mylib PUBLIC cxx_std_11)"

That seems reasonable to me, would that meet your needs?

**Comment by malaterre** [comment]
@jan-wassenberg That looks correct to me. For completness the actual patch should be:

```
@@ -21,9 +21,7 @@ endif()

 project(hwy VERSION 0.15.0)  # Keep in sync with highway.h version

-set(CMAKE_CXX_STANDARD 11)
 set(CMAKE_CXX_EXTENSIONS OFF)
-set(CMAKE_CXX_STANDARD_REQUIRED YES)

 # Enabled PIE binaries by default if supported.
 include(CheckPIESupported OPTIONAL RESULT_VARIABLE CHECK_PIE_SUPPORTED)
@@ -196,6 +194,7 @@ add_library(hwy STATIC ${HWY_SOURCES})
 target_compile_options(hwy PRIVATE ${HWY_FLAGS})
 set_property(TARGET hwy PROPERTY POSITION_INDEPENDENT_CODE ON)
 target_include_directories(hwy PUBLIC ${CMAKE_CURRENT_LIST_DIR})
+target_compile_features(hwy PUBLIC cxx_std_11)

 add_library(hwy_contrib STATIC ${HWY_CONTRIB_SOURCES})
 target_compile_options(hwy_contrib PRIVATE ${HWY_FLAGS})
```

I believe this is important for your project to keep CMAKE_CXX_EXTENSIONS to OFF (no gnu extension).

**Comment by jan-wassenberg** [comment]
Thanks @malaterre! I've made the change. It works on GNU 11.2.0 and Clang 7.0.1.

> I believe this is important for your project to keep CMAKE_CXX_EXTENSIONS to OFF (no gnu extension).

Interesting, independently of this I commented out that line and it compiles fine. Although we do not use extensions, I do not think they are harmful. FYI I am not the original author of that CMake line. Can you comment on why it is important to keep it OFF?

**Comment by malaterre** [comment]
@jan-wassenberg Does your code rely on GNU extension or not (basically -std=c++11 or -std=gnu++11):

* https://cmake.org/cmake/help/latest/prop_tgt/CXX_EXTENSIONS.html

Since your codebase seems to be portable c++ code, I believe you should reflect that in your cmake setup (IMHO).

**Comment by jan-wassenberg** [comment]
@malaterre Thanks. FYI I am fine with keeping it OFF, it is helpful documentation that we indeed do not use extensions.
