### ISSUE TITLE
highway does not compile with `CXXFLAGS=-fvisibility=hidden`

### ISSUE THREAD

**Issue by malaterre** [google/highway#488]
Using the following:

* https://github.com/google/highway/pull/487

and setting: CXXFLAGS=-fvisibility=hidden

leads to:

```
[ 16%] Linking CXX executable hwy_list_targets
/usr/bin/ld: CMakeFiles/hwy_list_targets.dir/hwy/tests/list_targets.cc.o: in function `main':
/home/mathieu/Perso/highway/hwy/tests/list_targets.cc:35: undefined reference to `hwy::SupportedTargets()'
collect2: error: ld returned 1 exit status
```

**Comment by jan-wassenberg** [comment]
@malaterre Nice, thanks for patching this in!
I think we'll also need GENERATE_EXPORT_HEADER to generate a header that defines an EXPORT symbol which we'd want to add to SupportedTargets, DisableTargets, SetSupportedTargetsForTest, SupportedTargetsCalledForTest, ChosenTarget::Update. Would you like to add that to the patch?

**Comment by malaterre** [comment]
@jan-wassenberg OK, Let me find some time to work on this.
