### ISSUE TITLE
HWY_CMAKE_ARM7:BOOL=ON triggers illegal instructions on armhf

### ISSUE THREAD

**Issue by malaterre** [google/highway#495]
As seen on Debian armhf buildds:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003218

**Comment by malaterre** [comment]
```
3: Note: Google Test filter = DotTestGroup/DotTest.TestAllDotBF16/Neon
3: [==========] Running 1 test from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 1 test from DotTestGroup/DotTest
3: [ RUN      ] DotTestGroup/DotTest.TestAllDotBF16/Neon
  1/247 Test   #1: DotTestGroup/DotTest.TestAllDot/Neon#GetParam()=8192 ....................................................***Exception: Illegal  0.03 sec
Note: Google Test filter = DotTestGroup/DotTest.TestAllDot/Neon
```

Ref:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=0.15.0-3&stamp=1641476548&raw=0

**Comment by jan-wassenberg** [comment]
This looks familiar, and the codegen is very broken (even TestAllEqual fails). I suspect we're hitting the same GCC issue we've already seen on ARM64 and Windows.
Would you be able to change the VecArg `#if` condition at the bottom of hwy/ops/shared-inl.h from HWY_ARCH_ARM64 to HWY_ARCH_ARM?

If you can confirm that solves it, I'm happy to make that change.

**Comment by malaterre** [comment]
@jan-wassenberg I'll try asap. Your comment above makes me wonder whether or not `HWY_CMAKE_ARM7` should be turned on for arm64. It seems it should not (at least on Debian buildds):

```
c++: error: unrecognized command-line option ‘-mfpu=neon-vfpv4’
```

Reference:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=arm64&ver=0.15.0-3&stamp=1641476042&raw=0

Thanks !

**Comment by jan-wassenberg** [comment]
@malaterre sounds good, thanks!

> Your comment above makes me wonder whether or not HWY_CMAKE_ARM7 should be turned on for arm64.

Indeed it should not. The fragmentation of ARM was reduced somewhat for aarch64 / A64 - that one guarantees ASIMD is available. Before that, in ARMv7, we had several VFP.. variants and extra flags were required to enable NEON instructions.

**Comment by malaterre** [comment]
> This looks familiar, and the codegen is very broken (even TestAllEqual fails). I suspect we're hitting the same GCC issue we've already seen on ARM64 and Windows. Would you be able to change the VecArg `#if` condition at the bottom of hwy/ops/shared-inl.h from HWY_ARCH_ARM64 to HWY_ARCH_ARM?
> 
> If you can confirm that solves it, I'm happy to make that change.

The symptoms appears to be unchanged:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=0.15.0-4&stamp=1641752465&raw=0

With:

* https://salsa.debian.org/debian-phototools-team/highway/-/blob/master/debian/patches/bug1003218.patch

I'll try a debug session on an actual armhf later this week and report back.

**Comment by jan-wassenberg** [comment]
hm, your patch looks good and TestAllEqual is still failing.

> I'll try a debug session on an actual armhf later this week and report back.

Sounds good, would appreciate any light you can shed on this!

**Comment by malaterre** [comment]
```
(gdb) layout asm
│   0x433748 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j>                                                                                                              cbz     r2, 0x433770 <_ZN3hwy6N_NEON9Simple ││  >0x43374a <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+2>                                                                                                            vmov.i64        d0, #0x0000000000000000     ││   0x43374e <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+6>                                                                                                            add.w   r2, r0, r2, lsl #2                  ││   0x433752 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+10>                                                                                                           vldmia  r0!, {s15}                          ││   0x433756 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+14>                                                                                                           vldmia  r1!, {s14}                          ││   0x43375a <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+18>                                                                                                           cmp     r2, r0                              ││   0x43375c <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+20>                                                                                                           vmul.f32        s15, s15, s14               ││   0x433760 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+24>                                                                                                           vcvt.f64.f32    d16, s15                    ││   0x433764 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+28>                                                                                                           vadd.f64        d0, d0, d16                 ││   0x433768 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+32>                                                                                                           bne.n   0x433752 <_ZN3hwy6N_NEON9SimpleDotI ││   0x43376a <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+34>                                                                                                           vcvt.f32.f64    s0, d0                      ││   0x43376e <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+38>                                                                                                           bx      lr                                  ││   0x433770 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+40>                                                                                                           vldr    s0, [pc, #4]    ; 0x433778 <_ZN3hwy ││   0x433774 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+44>                                                                                                           bx      lr                                  ││   0x433776 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+46>                                                                                                           nop                                         ││   0x433778 <_ZN3hwy6N_NEON9SimpleDotIfEET_PKS2_S4_j+48>                                                                                                           andeq   r0, r0, r0                
...
```

**Comment by malaterre** [comment]
* https://lists.debian.org/debian-arm/2022/01/msg00003.html

> A package built with those options is likely to not work on currently supported
> processors that only have VFPv3 rather than VFPv4 (All Cortex-A8, A9 and more).
> The highest supported FPU implemetnation at the moment is "vfpv3-d16", so
> no VFPv4 extensions, NEON or extra double-precision registers, see also [1].
> 
> A future Debian release might drop support for implementations with less than 32
> double-precision registers or with no NEON, but would likely still need runtime
> detection for vfpv4 features that are not in vfpv3 (fused
> multiply-accumulate and
> half precision floats).
> 
>       Arnd
> 
> [1] https://wiki.debian.org/ArmHardFloatPort/VfpComparison

I'll go ahead and set `HWY_CMAKE_ARM7:BOOL=OFF` on Debian/armhf for now.

Sorry for the noise.

**Comment by jan-wassenberg** [comment]
@malaterre ahh! I didn't think VFPv3 was still in wide use. Thanks for sharing the disassembly, this makes the situation clear.

I've been conditioned to overlook SIGILL because our error/assert handling uses __builtin_trap(). Perhaps we should change that to simply abort(), that would have made this issue much easier to understand.
