### ISSUE TITLE
/usr/include/hwy/tests/test_util.h:26:10: fatal error: 'hwy/tests/include_farm_sve.h' file not found

### ISSUE THREAD

**Issue by andrius4669** [google/highway#497]
when compiling libjxl-git from AUR with current highway-git (and `-DJPEGXL_FORCE_SYSTEM_HWY:BOOL='true'`), i get an error:
```
[ 66%] Linking CXX executable tests/ans_common_test
In file included from /home/anon/.cache/yay/libjxl-git/src/libjxl/lib/jxl/ac_strategy_test.cc:13:
In file included from /usr/include/hwy/tests/test_util-inl.h:22:
/usr/include/hwy/tests/test_util.h:26:10: fatal error: 'hwy/tests/include_farm_sve.h' file not found
#include "hwy/tests/include_farm_sve.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
it seems that error source is hwy, and i think it got broken within past week or so. https://github.com/google/highway/commit/74e064041e3d380d720cc8484a8975ca5bd31872 could possibly be related to something

**Comment by jan-wassenberg** [comment]
Hi @andrius4669 , the missing header is indeed new, but I don't understand why it's missing in AUR.

Looks like [AUR's highway-git](https://aur.archlinux.org/packages/highway-git/) is just pointing to upstream github and the header is indeed there: https://github.com/google/highway/blob/master/hwy/tests/include_farm_sve.h

Assuming the AUR checkout is somehow incomplete, I'm curious why we want -DJPEGXL_FORCE_SYSTEM_HWY:BOOL='true' ?
If you disable that, JPEG XL will use highway as a Git submodule.

**Comment by andrius4669** [comment]
```
% file /usr/include/hwy/tests/test_util.h
/usr/include/hwy/tests/test_util.h: C++ source, ASCII text
% file /usr/include/hwy/tests/include_farm_sve.h
/usr/include/hwy/tests/include_farm_sve.h: cannot open `/usr/include/hwy/tests/include_farm_sve.h' (No such file or directory)
```
it's not installed though!

in `CMakeLists.txt`:
```
set(HWY_TEST_SOURCES
    hwy/tests/hwy_gtest.h
    hwy/tests/test_util-inl.h
    hwy/tests/test_util.cc
    hwy/tests/test_util.h
)
```

>I'm curious why we want -DJPEGXL_FORCE_SYSTEM_HWY:BOOL='true' ?
>If you disable that, JPEG XL will use highway as a Git submodule.

agreed, I've commented something in that direction at https://aur.archlinux.org/packages/libjxl-git/#comment-845695

**Comment by jan-wassenberg** [comment]
@andrius4669 oh yes, I see, thanks for pointing that out :) Will fix shortly.
