### ISSUE TITLE
A few build/analyzer issues

### ISSUE THREAD

**Issue by yzazik** [google/highway#498]
Hello, I'm getting a few build issues, but I have a question first since the answer may just invalidate the rest (including it anyways):
What's the tolerance for build/analyze/sanitize warnings? Ie maximum warning level that is being targeted?

1.
```cpp
template <typename T>
HWY_API constexpr T LimitsMax() {
  static_assert(!IsFloat<T>(), "Only for integer types");
  return IsSigned<T>() ? T((1ULL << (sizeof(T) * 8 - 1)) - 1)    <-- HERE
                       : static_cast<T>(~0ull);
}
```
Getting MSVC 2017 Analyzer warning:
`highway\hwy\base.h(349): warning C26454: Arithmetic overflow: '-' operation produces a negative unsigned result at compile time (io.5).`
Could `T((1ULL << (sizeof(T) * 8 - 1)) - 1)` be replaced with something like `static_cast<T>(~0ull) >> 1`?

2. This is seen in a few places:
```cpp
HWY_API void StoreInterleaved3(const Vec128<uint8_t> v0,
                               const Vec128<uint8_t> v1,
                               const Vec128<uint8_t> v2,
                               Full128<uint8_t> /*tag*/,
                               uint8_t* HWY_RESTRICT unaligned) {
  const uint8x16x3_t triple = {v0.raw, v1.raw, v2.raw};         <-- HERE
  vst3q_u8(unaligned, triple);
}
```
MSVC 2017 Android NDK's Clang 5.0/9.0 ARM64 with **-mfpu=neon** throws:
```
../highway\hwy/ops/arm_neon-inl.h(4950,32): warning : suggest braces around initialization of subobject [-Wmissing-braces]
  const uint8x16x3_t triple = {v0.raw, v1.raw, v2.raw};
                               ^~~~~~~~~~~~~~~~~~~~~~
                               {                     }
```
This looks legit since `uint8x16x3_t` has an array in a `struct`:
```cpp
typedef struct uint8x16x3_t {
  uint8x16_t val[3];
} uint8x16x3_t;

```
3. Not sure about this one, could be my fault. I'm getting troubles building with GCC (let's say 10.x) with **-g** (debug) and `__OPTIMIZE__`.
I prefer to use Highway as header-only lib (just because I have several build systems in the project and none of them is cmake) but I also need debug build (not always but often enough), and it is quite annoying having release build for my project to build (link) fine and debug not because of `HWY_DASSERT` all over the place, one of the ways is to use `__OPTIMIZE__` to get rid of Abort() dependency but then I hit `error: the last argument must be an 8-bit immediate` across the board, same setup (debug with `__OPTIMIZE__`) builds fine with Clang or MSVC.
The question here is whether Highway could be kept as header-only (if I don't need aligned allocator) or whether some other `#define` could be introduced to opt out `HWY_DASSERT` (and possibly other things that need building a binary).

4. In the math-inl.h `V Log(const D d, V x)`:
```cpp
  const VI kLowerBits = Set(di, kIsF32 ? static_cast<TI>(0x00000000L)
                                       : static_cast<TI>(0xFFFFFFFFLL));      <-- HERE, C4309
  const VI kMagic = Set(di, kIsF32 ? static_cast<TI>(0x3F3504F3L)
                                   : static_cast<TI>(0x3FE6A09E00000000LL));
  const VI kExpMask = Set(di, kIsF32 ? static_cast<TI>(0x3F800000L)
                                     : static_cast<TI>(0x3FF0000000000000LL));
  const VI kExpScale =
      Set(di, kIsF32 ? static_cast<TI>(-25) : static_cast<TI>(-54));
  const VI kManMask = Set(di, kIsF32 ? static_cast<TI>(0x7FFFFFL)
                                     : static_cast<TI>(0xFFFFF00000000LL));

  // Scale up 'x' so that it is no longer denormalized.
  VI exp_bits;
  V exp;
  if (kAllowSubnormals == true) {  <-- HERE, C4127
```
I'm getting  warning C4309: `'static_cast': truncation of constant value` with MSVC on all LL-suffix constants above. Is math-inl maintained separately? I also get C4127 which is level 4, thus the first question.
Thank you.

**Comment by jan-wassenberg** [comment]
Hi @yzazik , our policy is to fix all enabled GCC/clang warnings before a release. Would be happy to discuss any additional warnings we should enable. For MSVC, it looks like our toolchain ignores /W4, so those warnings aren't visible. I am happy to periodically help fix them, thanks for reporting them.

> The question here is whether Highway could be kept as header-only (if I don't need aligned allocator) or whether some other #define could be introduced to opt out HWY_DASSERT

Header-only sounds useful. For the DASSERT, we already have `HWY_IS_DEBUG_BUILD` - you can set that to 0 and it will override the default check which looks at `__OPTIMIZE__`. Do we need any other changes for header-only?

**Comment by yzazik** [comment]
@jan-wassenberg
1. this one is analyzer one, but it only became mandatory in our builds recently, it helps quite a bit. But in general, unless I need to handle N==0 (which is almost never), I do prefer to create masks with **all-ones shifted down**, rather than with **1 shifted up minus 1**, seems to be less troublesome.
/W4 is rather preferable, at least it does raise the awareness (sometimes does catch bugs), although with some expense of satisfying a needy compiler.
2. This one I have to fix locally, would appreciate to get this one adopted, it goes to Android production builds, no tolerance.
3. Tried `HWY_IS_DEBUG_BUILD`, works, thank you, somehow I need to get all those details into my Highway introduction slideshow :). I don't think there is anything else needed to have header-only going.
4. MSVC is very stubborn about this one, the only way I found is to remove `static_cast` and make constant unsigned (go figure):
```cpp
  const VI kLowerBits = Set(di, kIsF32 ? static_cast<TI>(0x00000000L)
                                       : 0xFFFFFFFFULL);      <-- HERE, no C4309
```
It is also somewhat unfair about C4127 (conditional expression is constant) unless there is a syntax to avoid it (as for example, using assignment in the `if` clause), `if constexpr` is only available in C++17 then the warning should only be there. Otherwise it pushes me to use preprocessor #if or SFINAE, SFINAE is preferable and probably would squeeze out some mediocrity in this profession, but it is not as straightforward, so I guess, I'll be just disabling this one for now.

**Comment by yzazik** [comment]
@jan-wassenberg Hi Jan, so would you be able to fix #2?

**Comment by jan-wassenberg** [comment]
@yzazik sure! I've had a bit of a backlog but am catching up now.

> Tried HWY_IS_DEBUG_BUILD, works, thank you, somehow I need to get all those details into my Highway introduction slideshow :). I don't think there is anything else needed to have header-only going.

Sounds good :) I'm curious what your intro slideshow contains?

Looks like 1) is straightforward with your suggestion of bit-shifting down, though I've moved the entire section downwards so we can use MakeUnsigned.
2) is fixed, hopefully got them all.
Unfortunately the proposed fixed for 4 looks like it will cause clang to complain :/ We might consider a template specialization CastI64BitsFor<T> that returns int32_t or int64_t, what do you think?

**Comment by yzazik** [comment]
Just a powerpoint with some introduction to SIMD in general and ramping down to Highway :)
About #4, I think template specialization might look cleaner than seeding `kIsF32 ? :`, but again this is rather minor.
Appreciate for putting in other fixes, closing this.

**Comment by jan-wassenberg** [comment]
Sounds good. You're welcome :)
