### ISSUE TITLE
Fails test on amd64 (ivy bridge): `SSE4#GetParam()=64 (ILLEGAL)` - SSE4, u32 lane 0 mismatch

### ISSUE THREAD

**Issue by wyatt8740** [google/highway#52]
I encountered a failed test while trying to make a Debian package with `dpkg-buildpackage -uc -us -b` (building the master branch; last release works fine.). I've tried it on a Nehalem and an Ivy Bridge machine. I apologize in advance since am not very familiar with SIMD stuff; I am trying to build it so I can build some JPEG-XL code that depends on this library.

My distro is Debian Sid on both machines, and my kernel is 5.10.0.
````
 10/190 Test  #10: HwyArithmeticTestGroup/HwyArithmeticTest.TestAllShifts/SSE4#GetParam()=64 ...........................***Exception: Illegal  0.00 sec
Running main() from /build/googletest-YnT0O3/googletest-1.10.0.20201025/googletest/src/gtest_main.cc
Note: Google Test filter = HwyArithmeticTestGroup/HwyArithmeticTest.TestAllShifts/SSE4
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyArithmeticTestGroup/HwyArithmeticTest
[ RUN      ] HwyArithmeticTestGroup/HwyArithmeticTest.TestAllShifts/SSE4


u32 expect [0+ ->]:
  2147483648,
u32 actual [0+ ->]:
  2147483647,
Abort at /home/wyatt/development/jpeg-xl/highway/hwy/tests/arithmetic_test.cc:244: SSE4, u32 lane 0 mismatch: expected '2147483648', got '2147483647'.

-- SNIP --

99% tests passed, 1 tests failed out of 190

Total Test time (real) =   0.22 sec

The following tests FAILED:
	 10 - HwyArithmeticTestGroup/HwyArithmeticTest.TestAllShifts/SSE4#GetParam()=64 (ILLEGAL)
Errors while running CTest
````

**Comment by jan-wassenberg** [comment]
@wyatt8740 Thank you for reporting this!
To unblock your testing, you could comment out `HWY_EXPORT_AND_TEST_P(HwyArithmeticTest, TestAllShifts);` in that file.

The variable shift emulation was indeed added since the last release. This is very interesting, it passes on Coffee Lake and Skylake (compiled with clang). Are you using gcc? Looks like that is the [default on Sid](https://linux.softpedia.com/blog/gnu-compiler-collection-gcc-6-now-enabled-by-default-in-debian-unstable-507088.shtml).

Any chance you could also try with clang, e.g. `CC=clang CXX=clang++ cmake ..`?

**Comment by jan-wassenberg** [comment]
@wyatt8740 I am able to reproduce this on SKX with GCC 10.2.1. Investigating..

**Comment by jan-wassenberg** [comment]
@wyatt8740 please do let us know if this resolves the problem. It does with gcc 10.2.1.

**Comment by wyatt8740** [comment]
OK, testing now, sorry for the silence.

**Comment by wyatt8740** [comment]
@jan-wassenberg Sorry for the long wait; the tests are in. Building git master, my Ivy Bridge machine with GCC 10.2.1 now passes, and it also does my Nehalem (actually Westmere, my bad) machine.

I really should have thought to try Clang from the beginning; I know Google projects are heading in that direction but I guess it still just never occurred to me. Thanks for the fixes!

**Comment by jan-wassenberg** [comment]
@wyatt8740 glad to hear it, thanks for letting us know!

hm, this is not the most clear-cut case of a compiler issue, it requires a largish non-standalone test to repro and the fixed implementation works on both gcc and clang, so I suppose it's fine to leave as-is?
