### ISSUE TITLE
Is hwy_test meant to be public?

### ISSUE THREAD

**Issue by hmaarrfk** [google/highway#529]
I'm trying to package highway for conda-forge and I'm trying to understand what is supposed to be end user facing.

Is the library `libhwy_test` and the associated headers in `hwy/tests/` supposed to be public?

Would it be OK if I skipped them from the build and the end user package?

If I do skip this, I would happily submit the patches upstream. Let me know.

**Comment by jan-wassenberg** [comment]
@hmaarrfk the test library is indeed public and used by some users of Highway.

**Comment by hmaarrfk** [comment]
Thank you for confirming
