### ISSUE TITLE
Question: Issues when using with CMake

### ISSUE THREAD

**Issue by umgefahren** [google/highway#591]
I tried using this library with CMake FetchContent and I ran into troubles during compilation.
Could you provide an example project for use with CMake? I'm actually quite new to C++ and i have a hard time getting started with this library.

**Comment by yzazik** [comment]
Same here, it can't get the hash for the tag id, but you can force it with url_md5:

```cmake
include(FetchContent)
set(BUILD_TESTING OFF CACHE INTERNAL "") # turn off tests, well, I wish I could turned off sub pieces
FetchContent_Declare(
    highway
    GIT_REPOSITORY  https://github.com/google/highway.git
    URL_MD5         08ac74b29af43455d0401667393ba78e51b29c2b   # release tag "0.16.0"
)
FetchContent_MakeAvailable(highway)

```

**Comment by jan-wassenberg** [comment]
Thank you @yzazik ! Does that solve the trouble, @umgefahren ?
It may also help to copy what hwy_benchmark in CMakeLists.txt is doing.
