### ISSUE TITLE
Any plan for ARM SVE and RiscV support ?

### ISSUE THREAD

**Issue by devnull31** [google/highway#6]
In the readme, you speak about the compatibility of those sets visions with yours, through the length agnostic approach, any plan to support those instruction sets (am more interested by SVE). Thanks !

**Comment by jan-wassenberg** [comment]
Yes indeed, we would like to eventually support SVE[2]. Some updates to the ARM intrinsics would help, we've had some discussions about that.

**Comment by devnull31** [comment]
Great !
