### ISSUE TITLE
lane count differs for -mavx2 and -march=native on AVX2 CPU

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#606]
To work my way into highway, I did a simple test program with fixed architecture enforced via compiler arguments. When I compiled with -mavx2, I got a lane count of four, with -march=native I got the (correct) lane count of eight. Is this a bug or am I missing something? I can supply the test program if you like.

**Comment by jan-wassenberg** [comment]
Hi @kfjahnke, I think it's because -mavx2 isn't enough to trigger HWY_AVX2: that also requires -maes.
Please see the recommended flags in this example: https://gcc.godbolt.org/z/rGnjMevKG

Hope that helps?

BTW I have begun working on the "emulated 128-bit" target :)

**Comment by kfjahnke** [comment]
Thanks for the hint! I got it to use eight lanes with these flags (from the example you quoted):
-march=haswell -maes
-mavx2 -maes did not suffice.
> BTW I have begun working on the "emulated 128-bit" target :)
I'm not sure what that is, can you elaborate?

**Comment by jan-wassenberg** [comment]
Glad to hear! Ah yes, CPUID bits other than avx2+aes are indeed required; march=haswell covers those.

> I'm not sure what that is, can you elaborate?

Something like HWY_SCALAR, but always 16/sizeof(T) lanes stored in an array.

**Comment by kfjahnke** [comment]
> Ah yes, CPUID bits other than avx2+aes are indeed required; march=haswell covers those.

I have my doubts about this. The documentation for g++ simply states about the -mavx2 and similar flags "These switches enable the use of instructions in the ... AVX2, ... extended instruction sets." clang++, which I use, tries to be compatible to g++. And when I compile my AVX2-specific TUs, that's the only architecture-specific flag I use and I get AVX2 instructions with it. Therefore I think it's not unreasonable to expect this behaviour of the highway code, so maybe you want to rethink which compiler flags should be sufficient to trigger use of AVX2 instructions.

**Comment by jan-wassenberg** [comment]
@kfjahnke I sympathize with that viewpoint. We often end up wanting to use FMA at the same time as AVX2, hence those are coupled (there would be too many targets if we supported each combination).
I've added documentation to explain this, does that help?
https://github.com/google/highway/pull/611

**Comment by kfjahnke** [comment]
I'll have to see how it goes, I haven't attempted the switch to highway yet - still sounding the waters. If the flags I need to make highway produce the binary I want don't mess with my fallback code (using goading) this should be manageable with my CMake code. Thanks for your sympathy ;)

**Comment by jan-wassenberg** [comment]
OK :) I don't think those extra flags would negatively impact codegen of the fallback, it might even help.
