### ISSUE TITLE
please recommend suitable containers for small homogeneous aggregates of vectors

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#608]
In the quickstart documentation, under "Using unspecified vector types", it says:

> Vectors are sizeless types on RVV/SVE. Therefore, vectors must not be used in arrays/STL containers (use the lane type T instead)

I'd like to write my highway code so that it will run everywhere. But I have a large body of code which is currently using Vc or std::simd and fixed-sized vectors (like Vc::SimdArray), and my code frequently uses e.g. vectorized pixels and coordinates ('xel' data), which I code as vigra::TinyVector, which is a small fixed-size container type which internally holds the data as a plain C array. If I can't use this approach on SVE, I'd like advice on how to code such vectorized 'xel' data. My typical functional code units looks like this:

```
template < typename T , size_t nchannels , size_t vsize >
void func ( const vigra::TinyVector < simd_type < T , vsize > , nchannels > & input ,
                  vigra::TinyVector < simd_type < T , vsize > , nchannels > & output )
{ ... }
```
As long as I used fixed-sized vectors this is fine, but I'd rather follow your advice and make the code size-independent. Maybe you can point me to a suitable bit of example code?

**Comment by kfjahnke** [comment]
Her's a first attempt, backing the vectors up in a std::vector<T>. I tested this with -march=armv8a+sve on armv8-a clang 11.0.1 and it compiled. But I can't yet say how much performance is lost by buffering and how well the optimizer will make up for the loss. What do you say?
```
// class xel_v implements a small homogeneous aggregate of vectors.
// the implementation is meant to work for sized and sizeless vector
// types, hence the trickery of holding an internal std::vector<T>
// to store the vectors' content - if the vectors are sizeless, they
// can't be stored as such in a container.
// operator[] returns a proxy object which has a conversion operator
// to the vector type, producing the vector fresh from memory.
// If the caller uses xel_v::take_t as LHS, the std::vector<T> is
// updated by storing the vector passed as RHS. If xel_v::take_t
// is used as RHS in an expression expecting a vector, the conversion
// function yields the vector.

template < typename D , std::size_t N >
class xel_v
{
  typedef typename hn::TFromD < D > T ;
  typedef decltype ( hn::Zero ( D() ) ) v_t ;
  std::vector < T > inner ;
  
public:

  // problematic: if the lane count changes during the object's
  // lifetime, the buffer doesn't fit anymore

  xel_v()
  : inner ( N * Lanes( D() ) )
    { }

  class take_t
  {
    friend class xel_v ;
    T * target ;

    take_t ( T * _target )
    : target ( _target ) { }

    public:
    
    operator v_t() const
    {
      return hn::LoadU ( D() , target ) ;
    }
    
    v_t operator= ( v_t v )
    {
      hn::StoreU ( v , D() , target ) ;
      return v ;
    }
  } ;

  take_t operator[] ( std::size_t i )
  {
    return take_t ( inner.data() + i * Lanes ( D() ) ) ;
  }
} ;
```

**Comment by jan-wassenberg** [comment]
In our previous work it was typical for nchannels to be 3 or 4, not any arbitrary value, so we typically just passed around three pointers to per-channel arrays.

If you prefer to keep it generic, I believe the simplest reasonable approach is to replace simd_type with an array of the built-in lane type. That is to say: you pretend the "vector size" is something greater than the hardware size (everywhere except RISC-V that's currently guaranteed to be 2048 bits, and RVV realistically seems unlikely to see more than 16384 even with LMUL=8). Then you still operate on such 'virtual vectors', but with a loop like (i=0; i< 2048/sizeof(T)/8; i += Lanes(d)) {}.

This allows you to have static allocation/offset computation and still works for sizeless vectors.
Does that make sense?

Your code looks reasonable, but it might be helpful to use a plain array instead of vector to avoid allocation.

FYI as to lane count changing: I am not aware of any instruction set where that can happen without explicit user request at runtime.

**Comment by kfjahnke** [comment]
> In our previous work it was typical for nchannels to be 3 or 4, not any arbitrary value, so we typically just passed around three pointers to per-channel arrays.

I want to use it first in vspline, then in lux. Especially vspline is completely generic, and has to be able to deal with arbitrary element count. And even in lux I often have counts of two (coordinates) three (RGB) and four (RGBA). It'd be a horror trip to tear apart my entire pixel pipeline logic and hand-code all the variants. I have to 'slot in' highway to take up tasks which I specifically delegate to it, but I need to stick to the call structure as it is.

> This allows you to have static allocation/offset computation and still works for sizeless vectors.
Does that make sense?

Not really - I thought that Lanes(d) is only known at run-time for sizeless vectors, so allocation would have to be dynamic. That's why in my simple example I used a std::vector - later on it dawned on me I might just as well use hwy::AllocateAligned and replace the LoadU/StoreU with Load/Store, because, after all, increasing the access address by Lanes(d) should safely land me at another aligned address, isn't that so?

> Your code looks reasonable, but it might be helpful to use a plain array instead of vector to avoid allocation.

Would hwy::AllocateAligned necessarily allocate dynamic memory? Then, yes, a plain C array may be better.

The code I gave only has operator= for the proxy type, this would have to be extended to the augmented assignment operators, but that's easily done with macros, I'll check it out.

> FYI as to lane count changing: I am not aware of any instruction set where that can happen without explicit user request at runtime.

So one might simply state in the docu 'behaviour of the program is undefined if the user changes the lane count while it's running'. hah! blame it on the user :D

**Comment by jan-wassenberg** [comment]
I understand you want a generic solution, makes sense.

Let me expand on the virtual vectors. For SSE4 a simd_type<float> might be replaced with float[4]. But when we switch to AVX2, that's smaller than a native vector, so we have a problem. If instead we replace simd_type with float[64], this will be big enough for all platforms except RVV, and even there float[512] is enough for practical purposes. Indeed we don't know how big an actual vector is until we query Lanes(d). But we do know that your 'virtual' vector is bigger than that, and both are powers of two, so you can wrap your usage of actual HW vectors with a loop as described, to process all lanes of the simd_type replacement no matter how big actual vectors are.

Yes, AllocateAligned guarantees alignment, but it is a dynamic allocation. If it were a stack array you could use HWY_ALIGN. For class members, you could use that and also on the class itself, but still might get into trouble if someone does `new AlignedClass` which might not be aligned unless you also override operator new.

But yes, AllocateAligned and `Load(d, ptr + i*Lanes(d))` would be safe.

**Comment by jan-wassenberg** [comment]
Yes, this is fixed by [#631](https://github.com/google/highway/pull/621), which has been held up by our CI/CD.
In the meantime, you can work around it by `#include <atomic>` before highway.h.

**Comment by kfjahnke** [comment]
Am 01.04.22 um 10:32 schrieb Jan Wassenberg:
> |#include <atomic>|
Okay, workaround works, thanks!

**Comment by jan-wassenberg** [comment]
You're welcome :) Meanwhile, the fix is in so the workaround will no longer be necessary once godbolt picks it up (probably 24h).

**Comment by kfjahnke** [comment]
Am 01.04.22 um 10:47 schrieb Jan Wassenberg:
> You're welcome :) Meanwhile, the fix is in so the workaround will no 
> longer be necessary once godbolt picks it up (probably 24h).

okay, cool.

Next thing: when my operator[] produces proxy objects to mediate access 
to the contained vectors (stored in a T[]), some hwy functions refuse to 
accept them as arguments where a vector of T would be expected, even 
though there is a conversion function. Maybe the templates are too 
narrow, like, expecting precisely the vector type, rather than anything 
that can be converted to a vector? just guessing...

When it comes to shift operators, wouldn't it make sense to code 
operator<<, operator<<=, operator>> and operator>>= overloads taking an 
integral argument? I suppose that's even the more common use case. And 
operator%, operator%= also might like to see a bit of TLC, both for 
vector and integral arguments ;)

**Comment by jan-wassenberg** [comment]
hm, do you have a quick example of the problem? One possible cause might be that x86 Vec256 etc are structs without an explicit ctor (this was to work around a Clang IIRC v9 bug).

For operators in general, we currently aren't able to use those due to SVE and RVV compiler limitations. I remain hopeful they can be resolved but don't have an ETA. Until then, we require Shl/ShiftLeft.

BTW another reason we require templates in this case (even if operator+ were later to work) is that some ISAs require the shift count to be a compile-time constant, and some compilers (IIRC MSVC) did not manage to constant-propagate them unless they were template arguments.

**Comment by kfjahnke** [comment]
> hm, do you have a quick example of the problem? One possible cause might be that x86 Vec256 etc are structs without an explicit ctor (this was to work around a Clang IIRC v9 bug).

Oops... silly me, I had forgotten to declare the conversion function const, with that addition it works. Sorry for the noise, there is no problem.

> For operators in general ...

I take it you mean shift operators in general? Okay, I hope you find a way to provide them, until then I'll have to route my code via the shift functions.

> some ISAs require the shift count to be a compile-time constant

that seems like an odd requirement, but what can you do...

**Comment by jan-wassenberg** [comment]
OK, glad to hear :)

Quick clarification, currently all overloaded operators including < and + do not work on SVE/RVV and we use Lt/Add etc. instead.

**Comment by kfjahnke** [comment]
I see (at least some of) them working on armv8-a clang (trunk) (on godbolt), but on 11.0.1 they don't. Maybe there was a recent improvement.

**Comment by kfjahnke** [comment]
I found an elegant solution which works well with RAII. It requires creating the vectors on the stack, and they must remain in scope while the aggregate is in use, but apart from that, the use of the aggregate feels very natural:

```
#include <hwy/highway.h>
#include <hwy/print-inl.h>

namespace hn = hwy::HWY_NAMESPACE ;

template < typename D , std::size_t N >
class handle_t
{
  typedef hn::Vec < D > vec_t ;

  struct _handle_t
  {
    vec_t & vr ;
    _handle_t ( vec_t & _vr ) : vr ( _vr ) { }
  } ;

  _handle_t hv [N] ;

public:

  template < typename ... Targs >
  handle_t ( Targs & ... Fargs )
  : hv { Fargs ... }
  { }

  vec_t & operator[] ( const std::size_t & i )
  {
    return hv[i].vr ;
  }

  const vec_t & operator[] ( const std::size_t & i ) const
  {
    return hv[i].vr ;
  }
} ;

int main ( int argc , char * argv[] )
{
  typedef hn::ScalableTag<float> D ;
  typedef handle_t < D , 2 > fh2_t ;
  typedef hn::Vec < D > v_t ;
  v_t v1 , v2 ;
  fh2_t fh2 ( v1 , v2 ) ;
  fh2[0] = hn::Set ( D() , 1.23 ) ;
  fh2[1] = hn::Set ( D() , 4.56 ) ;
  Print ( D() , "### " , fh2[1] - fh2[0] ) ;
} 
```

I think this goes to the limit of what's allowed with sizeless types. The handle_t objects don't actually 'contain' any data, they merely hold the information which vectors they refer to. But they are bona file objects and can be passed around, e.g as function arguments. And because there are no proxy objects involved, the implementation is small.

**Comment by jan-wassenberg** [comment]
Sounds good!

> I sawe that clang for arm v8a 64bit trunk seems to support the operators now

Ah, indeed, that was [added in February](https://reviews.llvm.org/D120323), thanks for the pointer! It's limited to a few arithmetic operators for now but a great start!

**Comment by kfjahnke** [comment]
So far I had three ideas how to form aggregates of vectors:

- plain container
- memory-backed objects which mediate write access via a proxy
- aggregates of handles which hold references to vectors

All of these have drawbacks and advantages. Obviously, the plain container approach would be most appealing, so I'd pick that for platforms with sized vectors. The second approach has the advantage that the aggregates can be created in any way (like, stack or heap), but coding the proxy access is laborious, even though I have code handy which can be adapted, it all would need to be tested and maintained. What I'd like with this approach is your opinion: will compilers 'understand' that a vector saved to memory is just a vector in disguise? What I mean is, will a compiler avoid storing to memory and reloading if the memory is not touched in the meantime? And will it hold on to a vector in a register to avoid reloading it when another part of the code accesses the same object? 'Normal' data would be treated like that (copy elision, common subexpressions, const propagation), but since the vector and the backing memory are not 'obviously' the same, I'm not sure if these mechanisms will apply. With the third approach - which I favour less even though it's so elegant - I have fears that building up a set of explicit vectors on the stack might mess with the compiler's handling of available registers, but that's only gut feeling. And the need to set up the vectors on the stack in an outer scope is awkward, to say the least.
There is another aspect to my attempts at finding a solution for this problem: highway does not offer vectors - or an equivalent - which hold more than a register's worth of T. I find that the solution to run half-full vectors of half-sized T to interoperate with full vectors of full-sized T unsatisfactory. Vc has Vc::SimdArray, which allows to code the other way: you use same-sized SimdArrays for both, the object with full-sized T will span two hardware vectors, and the library takes care of interoperation. This does not only avoid using half-sized vectors (at least they don't become apparent) but also makes it natural to use vector widths larger than the hardware size. This may sound funny, but I found with my application that using twice the hardware size is noticeably faster. Whether this happens does of course depend on the code at hand, but it's definitely a good idea to have the option. Now Vc's SimdArray is a very sophisticated construct, with a recursive type definition defining a SimdArray as a combination of two smaller SimdArrays unless the size agrees with the hardware vector size. This design allows for arbitrarily sized SimdArrays which is, in my opinion, overkill - we're talking horizontal vectorization after all, so I think the size could be limited to a multiple of the hardware vector size, if not a power of two. With a fully-fleged definition of a small aggregate of vectors as an arithmetic type I think one might get a good equivalent of Vc::SimdArray, limited to 'reasonable' sizes, but coding interoperation with equally-sized but differently-typed objects might be laborious if one wants to make it fast.
This object - let's call it a chunk - might then be used to store a vectorized channel of a vectorized 'xel' data type. And then, of course, the next step would be to code more general de/interleaving to interface with nD arrays of xel data. What I'd like to see in this regard - apart from the obvious case - is access to strided memory. I use the pair of functions ['bunch' and 'fluff'](https://kfj.bitbucket.io/structwielding_1_1aggregator__base.html) for the purpose, which, when tweaked appropriately, make another noticeable speed difference. But I think this should go into another item and it's probably outside the scope you intend for highway.

**Comment by jan-wassenberg** [comment]
> will compilers 'understand' that a vector saved to memory is just a vector in disguise

Yes, there's a good chance this will work. I've see clang avoid repeated loads, and even rename memory (as in: realize that memory locations map to different regs, and just use those instead).

But it seems prudent to prototype it to see if it actually works (also on other compilers if you care about them).

> highway does not offer vectors - or an equivalent - which hold more than a register's worth of T

Actually on RVV we do support LMUL>1, where single instructions and "vectors" operate on up to 8 HW vectors. And yes, it's to be expected that unrolling helps - even on SVE. We could consider supporting an equivalent of LMUL>1 in Highway to avoid manual unrolling in user code, but not by implementing it via a struct or array of vectors, which once again hits the compiler limitation that those aren't allowed for SVE/RVV.
I suppose your handle idea might work, but that seems less ergonomic than manually unrolling in user code, and accepting that mixed-precision code might involve partial vectors except on RVV?

I agree it's generally a good idea to have the chunk concept (chosen as upper bound of HW vector sizes) in your code, and loop over that with the current HW vector stride.

**Comment by kfjahnke** [comment]
> other compilers if you care about them

I do if I can get hold of them without too much hassle... my resources are limited. I try to write standard-compliant code, but of course mileage differs on different compilers. I'm glad you stuck with C++11 (as do I for now) which is well-trodden by now.

> on RVV we do support LMUL>1, where single instructions and "vectors" operate on up to 8 HW vectors.

Such an option would be great for all targets, and it would save having to code the chunk as an aggregate of vectors - the broadcasting would be automatic. With your impression that a memory-backed type would not introduce too much of a run-time penalty I think a struct/array of vectors using a block of memory for persistent storage and a proxy object for write access might be a more general solution to implement a chunk of N register-sized Vectors, but it's a lot of work and hard to get spot on right.
I do wonder why the standard library hasn't come up with a fixed-size arithmetic container type template. [vigra::TinyVector](http://ukoethe.github.io/vigra/doc-release/vigra/classvigra_1_1TinyVector.html) is excellent, but not in the standard library.
BTW - thanks for ExtractLane and InsertLane, they seem to work here as intended!

**Comment by jan-wassenberg** [comment]
I understand about compiler availability, it's pretty easy with apt-get install clang-9 etc.

> I'm glad you stuck with C++11 (as do I for now) which is well-trodden

:)

> a struct/array of vectors using a block of memory for persistent storage and a proxy object for write access might be a more general solution to implement a chunk of N register-sized Vectors, but it's a lot of work and hard to get spot on right.

Yes :/ Big change to the API too.

Glad to hear Insert/Extract works for you!

**Comment by kfjahnke** [comment]
I think it's all right to close this issue now - I've settled on the memory-backed approach, and it seems to perform well enough.
Just for reference, here's a link to my [hwy_simd_type implementation](https://bitbucket.org/kfj/pv/src/master/vspline/hwy_simd_type.h)
