### ISSUE TITLE
Print requires gtest/gtest.h

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#614]
using hwy::Print ( ... ) I get this error message:
```
In file included from /usr/local/include/hwy/tests/test_util-inl.h:22:
/usr/local/include/hwy/tests/hwy_gtest.h:27:10: fatal error: 'gtest/gtest.h' file not found
#include "gtest/gtest.h"
         ^~~~~~~~~~~~~~~
1 error generated.


```
I'd rather not have additional external dependencies. Also, it would be nice to have a more 'C++' printing function using streams, à la
```
  friend std::ostream & operator<< ( std::ostream & osr , const vector & xv ) ;

```

**Comment by jan-wassenberg** [comment]
Makes sense, we can split that into a separate header.
I would prefer to avoid streams if possible?

**Comment by kfjahnke** [comment]
I think you may have forgotten to have the relevant header installed - if I do a 'make install' from master, it is not copied.

**Comment by kfjahnke** [comment]
And even if I copy that header manually, I get
`minimal.cc:(.text._ZN3hwy8N_SCALAR5PrintINS0_4SimdIfLm1ELi0EEENS0_4Vec1IfEEEEvT_PKcT0_mm[_ZN3hwy8N_SCALAR5PrintINS0_4SimdIfLm1ELi0EEENS0_4Vec1IfEEEEvT_PKcT0_mm]+0xe6): undefined reference to `hwy::detail::PrintArray(hwy::detail::TypeInfo const&, char const*, void const*, unsigned long, unsigned long, unsigned long)'
`

**Comment by jan-wassenberg** [comment]
@kfjahnke oops, my mistake. I didn't add the header to the CMake build. Fixing..

**Comment by kfjahnke** [comment]
Looks like Print is one element short:
```
i32x8 ***  [0+ ->]:
  5,5,5,5,5,5,5,
```

**Comment by jan-wassenberg** [comment]
By default it chooses to print up to 7 lanes to prevent clutter, but you can change that by passing 0 and Lanes(d) for the last 2 parameters.
