### ISSUE TITLE
Question about HwyTargetsTest.DisabledTargetsTest

### ISSUE THREAD

**Issue by novomesk** [google/highway#617]
Hello,

Gentoo Linux developers run tests for highway-0.16.0 and on one CPU there was one failed test:
```
        Start 113: HwyTargetsTest.DisabledTargetsTest
113/541 Test #113: HwyTargetsTest.DisabledTargetsTest ......................................................................Subprocess aborted***Exception:   0.07 sec
```
Details in https://bugs.gentoo.org/836373

Is it something to worry about? Especially when highway is used by libjxl?

**Comment by jan-wassenberg** [comment]
Hi @novomesk, thanks for reaching out. Yes, this points to a potential problem. The compiler flags promise the compiler that AVX-512 is available, but our CPU detection concludes that it is not available.
There are two possibilities:
1) our detection is pessimistic, AVX2/AVX-512 should in fact be available. The only consequence is that this test will fail.
2) the CPU actually does not support one of the features that the compiler is being promised. In the unlikely case that the compiler manages to generate such an instruction (via autovectorization), the code could crash on this CPU.

I'd like to understand what's going on and am happy to help investigate. The CPU-detect code looks at several other features in addition to AVX2/AVX-512; if one of them is missing, then the HWY_AVX2 and/or HWY_AVX3 targets are also considered unavailable. LZCNT is one such feature and I do not see it listed in [datasheets](https://ark.intel.com/content/www/us/en/ark/products/196603/intel-core-i51035g1-processor-6m-cache-up-to-3-60-ghz.html) nor https://en.wikichip.org/wiki/intel/microarchitectures/ice_lake_(client).

Can you share the cpuid and/or x86info output on this CPU?

--

Independently, I'm not sure we want to set CPU_FLAGS_X86 like this. Highway/JPEG XL use whatever is available at runtime, and promising the availability of features can run into trouble (number 2 above) if it's more than the CPU actually supports. Can we simply avoid specifying -mavx2 etc.? That would also avoid this problem (though I'd still like to understand the cause.)

**Comment by PPed72** [comment]
I'm the OP of the original Gentoo bug. I'm attaching the cpuid output for my CPU:
[cpuid_icelakeclient.txt](https://github.com/google/highway/files/8378872/cpuid_icelakeclient.txt)

**Comment by jan-wassenberg** [comment]
@PPed72 Thanks for sharing the cpuid output. I've cross-checked all the features we test and
they are listed in your output. We detect AVX2 but not AVX3 nor AVX3_DL. 

I've again checked the four AVX512* are present in your output, and per
https://en.wikipedia.org/wiki/CPUID#EAX=7,_ECX=0:_Extended_Features
we're indeed supposed to be checking CPUID 7 EBX 16,17,30,31.

Ah, the problem seems to have been incorrect bit indices of XCR0, and your
CPU/OS seems to be the first one that sets BNDCSR.
Would you please confirm the patch fixes this?

**Comment by PPed72** [comment]
Yes, it works fine, now. Thank you very much!

**Comment by jan-wassenberg** [comment]
Thank you for sharing the information that enabled the fix and for confirming!
