### ISSUE TITLE
GetLane/SetLane, operator[]

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#622]
Browsing the code base, I found sporadic occurence of GetLane, and no SetLane. I'm also missing operator[], which is a common way to mediate access to individual lanes. While such operations may not be efficient (as you suggest in g3doc/design_philosophy.md), my code relies on their presence, and having to rewrite code using operator[] would make the port harder. Am I missing something, or is there really no way to access individual lanes?

**Comment by jan-wassenberg** [comment]
That's right, we used to have a SetLane but it's often as efficient to broadcast to all lanes (Set) instead. Do you have a use case where SetLane would be noticeably faster?

operator[] falls into the usual trap of "cannot overload operators on SVE/RVV". However, RVV does have an instruction for that and SVE can still WHILELO + LASTA, which isn't too bad. For x86 to prevent storing to stack the index should be constexpr (and a template arg) - is that OK? We can add such an op, any preference for the name?

**Comment by kfjahnke** [comment]
This is not about speed, but to help with generic coding.
What I'm looking for is a way to code vector manipulations as loops, to provide implementations of vector operations where nothing better can be had. I have fallback implementations for some vector operations which do just that - it's often inefficient (unless the compiler figures out that it can autovectorize the loop), but it's better than having nothing at all, and a quick fix if there is e.g. a bug in the 'proper' vector code. Having operator[] or a GetLane/SetLane function makes this easy, and it can use my extant 'goading' code which has everything implemented as loops. Without it, I have to code stuff like Store-modify memory-Load for every Lane to get the interface I want - or I have to modify my extant code to store the vector, then loop over the memory and then Load back. And I think that constexpr indices would not work for me - how would I code a loop then?

**Comment by jan-wassenberg** [comment]
Right, I understand this isn't time-critical, but my experience is that when ops are added, they will be used. Hence some caution is required.

Thanks for sharing the context. Looks like constexpr won't work.

How about an op SlowIndex(v, size_t i)? Or something other than Index, perhaps Get? (Not sure yet if a d argument will also be required.)

**Comment by kfjahnke** [comment]
> Right, I understand this isn't time-critical, but my experience is that when ops are added, they will be used. Hence some caution is required.

Wise words. It's just that single-element access is a common operation in other vector libraries, so if you want to lure people into the highway camp, it's probably also wise to help them port. My modus operandi is: get the thing up and running no matter how, then tweak it until it' fast.
I have my use of vector code neatly factored out - in a nutshell, there is a template class which offers the functionality I use in lux/vspline which inherits privately from some vector type like Vc::SimdArray or std::simd, and I can override where I must and add what isn't there already. When I try and port to a new vector library, I change the base class and do what's necessary to provide the functionality. Some things, then, are easier, and some are harder, but I'd much rather suffer a small performance penalty at first than change my code, which has already turned out to work well.
The most difficult problem I see for this port is dealing with sizeless vectors, because all my code relies on explicitly, but arbitrarily sized vectors. So porting to highway's fixed-size code should not be too hard, but I struggle with the sizeless types, as you can see from my recent posts. But, hey, it's a challenge.

> How about an op SlowIndex(v, size_t i)?

How about a namespace 'byway' for operations which are not up to highway speed standards ;)
What's wrong with GetLane/SetLane? It would say precisely what it does (rather than the extant GetLane, which seems to only get lane zero unconditionally). I don't think that any SIMD programmer will expect that a series of Lane(d) calls to SetLane in a Loop will perform as well as a Store operation.

**Comment by jan-wassenberg** [comment]
:) Sounds reasonable.

The byway is a funny name :) We previously discussed internally whether to have a slow:: or ext:: namespace and concluded it's safer to avoid extra namespaces, in part because behavior already differs due to ADL (class wrappers vs builtin types).

A historical note, GetLane used to not even guarantee we get lane 0 - this was with an eye towards POWER, where it's cheapest to insert into the *top* lane. But now it's indeed always lane 0.

I understand that `using byway::Lane` would shorten your code. It's important to remain backward compatible, so GetLane(v) should continue to work. GetLane(v, i) seems like a very subtle difference, hard to spot in code reviews, that could have a substantial cost.
Are you strongly opposed to the Slow prefix of SlowLane? Is there any other alternative?

**Comment by kfjahnke** [comment]
It's of course up to you as the library designer to pick any name you feel is adequate. I see that re-using an extant name within a new context is asking for trouble, even with an extra argument. How about GetSingleLane and SetSingleLane - or ExtractLane and InsertLane? The prefix 'Slow' implies that this operation is slow, but this is not necessarily the case: you might use a loop over the Lanes which can be autovectorized by the compiler (these things are clever), and end up with proper SIMD assembly. Best to state what the operation does rather than what you suspect about it's performance.

**Comment by jan-wassenberg** [comment]
Good point that the op might not always be slow. I like Extract/Insert, let's go with that, thanks! Implementation is in progress.

**Comment by jan-wassenberg** [comment]
The Insert change should be ready to go today. These ops are sufficient for your use-case, right?

**Comment by kfjahnke** [comment]
Am 08.04.22 um 09:21 schrieb Jan Wassenberg:

> The Insert change should be ready to go today. These ops are sufficient 
> for your use-case, right?

You mean Insert and Extract? Yes, that should be enough, then I can have 
operator[] in my wrapper object.
