### ISSUE TITLE
Command line parameter selection on Windows / MSVC

### ISSUE THREAD

**Issue by schoppmp** [google/highway#644]
I'm trying to compile Highway on Windows using Bazel and MSVC, but I get the following error:
~~~
PS C:\tmp\highway> bazel build ...
DEBUG: Rule 'bazel_skylib' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0"
DEBUG: Repository bazel_skylib instantiated at:
  C:/tmp/highway/WORKSPACE:21:13: in <toplevel>
Repository rule http_archive defined at:
  C:/tmp/5nvpln35/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed 43 targets (0 packages loaded, 0 targets configured).
INFO: Found 43 targets...
ERROR: C:/tmp/highway/BUILD:116:11: Compiling hwy/targets.cc failed: (Exit 2): cl.exe failed: error executing command C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 41 arguments skipped)
cl : Command line error D8021 : invalid numeric argument '/Wunused-parameter'
INFO: Elapsed time: 0.387s, Critical Path: 0.13s
INFO: 17 processes: 17 internal.
FAILED: Build did NOT complete successfully
~~~

Looking at the definition of [COPTS in BUILD](https://github.com/google/highway/blob/master/BUILD#L90), it seems that the default condition is chosen with CLI arguments for Clang, instead of `:compiler_msvc`. Any idea how to debug this?

**Comment by jan-wassenberg** [comment]
Is there some way you can deduce the value of `flag_values = {"//tools/cpp:compiler"`?
Looks like it is none of the following:  "lexan", "msvc", "gcc", "compiler".

**Comment by jan-wassenberg** [comment]
Ah, it seems there is a bazel config command described in the section "Why doesn’t my select() choose what I expect?" of https://docs.bazel.build/versions/3.5.0/configurable-attributes.html.
It is able to print config values such as "cpu". Is there something unique for your build environment that we could use to detect MSVC?

**Comment by jan-wassenberg** [comment]
Glad to hear that. I'll add a select as you suggest.

Looks like we're missing some HWY_DLLEXPORT in .cc files, that's unfortunately required by some but not all compilers. Will add those as well, thanks for sharing the list.
