### ISSUE TITLE
IsNaN support for NEON?

### ISSUE THREAD

**Issue by LostVector** [google/highway#655]
Doesn't seem to be in arm_neon-inl.h, but no restrictions on architecture mentioned in the quick reference.

**Comment by jan-wassenberg** [comment]
Hi @LostVector, thanks for reaching out. Highway ops are indeed available on all platforms.
I see it at https://github.com/google/highway/blob/master/hwy/ops/arm_neon-inl.h#L3164 - is it perhaps possible your git working copy got garbled somehow?

**Comment by LostVector** [comment]
My mistake ... I pulled HEAD several days ago and it looks like you implemented the operation just afterwards, so the docs confused me.  I'll re-pull and test.  Thanks!

**Comment by jan-wassenberg** [comment]
YW :) Happy to advise if you run into any issues.
