### ISSUE TITLE
64 bit Mul is missing for AVX2

### ISSUE THREAD

**Issue by kfjahnke** [google/highway#698]
I stumbled upon this error:
```
/usr/local/include/hwy/ops/x86_128-inl.h:6741:12: error: invalid operands to binary expression ('hwy::N_AVX2::Vec256<long>' and 'hwy::N_AVX2::Vec256<long>')
  return a * b;
         ~ ^ ~
./vspline/hwy_simd_type.h:1422:30: note: in instantiation of function template specialization 'hwy::N_AVX2::Mul<hwy::N_AVX2::Vec256<long> >' requested here
    OPEQ_FUNC(operator*=,hn::Mul,)
```
AVX2 does not provide the function which would be needed (_mm256_mullo_epi64, I think that's AVX512 only) but maybe you could work around this? My problem is this: The index type needed for double gather/scatter is a vector of long, and my code tries to manipulate the vector (like, multiply it with a constant and add an offset) to get g/s indexes for de/interleaving. Without the long multipliciation, I can't do that - I have to go 'via the backing memory' in my hwy_simd_type, which is slow.

**Comment by jan-wassenberg** [comment]
That's right, 64x64-bit mul are not included because they aren't performance-portable and we didn't yet have a compelling use case. Would MulEven's 32x32=64 mul be enough for this use case? (And does it have to be a mul rather than a shift?)

**Comment by kfjahnke** [comment]
That should do the trick for my indexes, which aren't very large after all. But special-casing is annoying in generic software. Maybe my demand is silly anyway - is there a 64bit gather/scatter in AVX2 at all? Just that my type inference coughs up a vector of long doesn't mean I can use it as intended.

**Comment by jan-wassenberg** [comment]
AVX2 does indeed have 64-bit gather. Yes, it's a bit inconvenient to special-case Mul for int64 (casting to u32 and then calling MulEven). The only caveat is that it will silently assume both operands are < 2^32, but that does seem to be the most reasonable cross-platform thing to do.

**Comment by kfjahnke** [comment]
Thanks for your suggestion. I've opted to work around the issue 'one level up' because the code is not performance-critical, but I reckon the fallback to 32bit would also be feasible. I'll close this issue.
