### ISSUE TITLE
Feature Request: Macro to override SSSE3 or SSE4 support on MSVC

### ISSUE THREAD

**Issue by drewcassidy** [google/highway#704]
As seen [here](https://stackoverflow.com/questions/18563978/detect-the-availability-of-sse-sse2-instruction-set-in-visual-studio), MSVC doesn't set any macros for SSSE3 or SSE4 support being available. This means that there's no way to enable those instruction sets in MSVC short of allowing all of AVX. A macro could be added to bypass the check seen below

```C++
#if defined(__AVX__)
#define HWY_CHECK_SSSE3 1
#define HWY_CHECK_SSE4 1
#else
#define HWY_CHECK_SSSE3 0
#define HWY_CHECK_SSE4 0
#endif
```
and manually set SSSE3 or SSE4 as supported

Unfortunately Im writing a python module, and python extension modules on windows need to be compiled with MSVC for binary compatibility. Otherwise I would have just switched to Clang

**Comment by jan-wassenberg** [comment]
@drewcassidy makes sense. Sure, happy to add such macros.

**Comment by drewcassidy** [comment]
Thanks! that was fast!
