### ISSUE TITLE
uninitialized warnings on GCC 12

### ISSUE THREAD

**Issue by boxerab** [google/highway#710]
I get a number of these warnings on Fedora 36 system with GCC 12

```
In function ‘__m512i _mm512_andnot_si512(__m512i, __m512i)’,
    inlined from ‘hwy::N_AVX3::Vec512<T> hwy::N_AVX3::AndNot(Vec512<T>, Vec512<T>) [with T = int]’ at /home/src/grok/src/lib/jp2/highway/hwy/ops/x86_512-inl.h:279:39,
    inlined from ‘hwy::N_AVX3::VFromD<DI> hwy::N_AVX3::detail::FixConversionOverflow(DI, hwy::N_AVX3::VFromD<DW>, decltype (hwy::N_AVX3::Zero(di).raw)) [with DI = hwy::N_AVX3::Simd<int, 16, 0>; DF = hwy::N_AVX3::Simd<float, 16, 0>]’ at /home/src/grok/src/lib/jp2/highway/hwy/ops/x86_128-inl.h:5391:33,
    inlined from ‘hwy::N_AVX3::Vec512<int> hwy::N_AVX3::NearestInt(Vec512<float>)’ at /home/src/grok/src/lib/jp2/highway/hwy/ops/x86_512-inl.h:3335:39,
    inlined from ‘void grk::N_AVX3::DecompressIrrev::transform(grk::ScheduleInfo)’ at /home/src/grok/src/lib/jp2/point_transform/mct.cpp:214:10,
    inlined from ‘grk::N_AVX3::vscheduler<DecompressIrrev>(grk::ScheduleInfo)::<lambda()>’ at /home/src/grok/src/lib/jp2/point_transform/mct.cpp:348:25,
    inlined from ‘grk::N_AVX3::vscheduler<DecompressIrrev>(grk::ScheduleInfo)::<lambda()>’ at /home/src/grok/src/lib/jp2/point_transform/mct.cpp:352:59:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:7845:50: warning: ‘__Y’ may be used uninitialized [-Wmaybe-uninitialized]
 7845 |   return (__m512i) __builtin_ia32_pandnd512_mask ((__v16si) __A,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
 7846 |                                                   (__v16si) __B,
      |                                                   ~~~~~~~~~~~~~~
 7847 |                                                   (__v16si)
      |                                                   ~~~~~~~~~
 7848 |                                                   _mm512_undefined_epi32 (),
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
 7849 |                                                   (__mmask16) -1);
      |                                                   ~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h: In lambda function:
/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:206:11: note: ‘__Y’ was declared here
  206 |   __m512i __Y = __Y;
```

**Comment by jan-wassenberg** [comment]
hm, this seems to be a shortcoming of GCC's avx512fintrin.h. The line at the bottom of the compile output is indeed using an uninitialized value to implement _mm512_undefined_epi32. That makes sense, but they should be suppressing the warning. I suppose we could wrap our include of the system headers with

HWY_DIAGNOSTICS(push)
HWY_DIAGNOSTICS_OFF(disable : 4703 6001 26494, ignored "-Wmaybe-uninitialized")
// include
HWY_DIAGNOSTICS(pop)

Would you like to see if that solves the problem?

**Comment by boxerab** [comment]
Thanks, this is the fix for the following header:
`highway/hwy/ops/x86_512-inl.h`

```
HWY_DIAGNOSTICS(push)
HWY_DIAGNOSTICS_OFF(disable : 4703 6001 26494, ignored "-Wmaybe-uninitialized")
HWY_DIAGNOSTICS_OFF(disable : 4701, ignored "-Wuninitialized")
#include <immintrin.h>  // AVX2+
```

at the very beginning of the file, and

```
HWY_AFTER_NAMESPACE();

HWY_DIAGNOSTICS(pop)
```

at the very end of the file.

**Comment by jan-wassenberg** [comment]
Thanks for testing, I'm happy to add such a patch but would prefer to push that down into x86_512 and have it wrap only the system headers, to ensure we still notice warnings in the rest of x86_512. Please let me know if the upcoming patch is sufficient :)

**Comment by boxerab** [comment]
@jan-wassenberg thanks for the patch. Unfortunately, this doesn't suppress the warnings on my system....

**Comment by jan-wassenberg** [comment]
Bummer, thanks for letting me know. I see that many `*undefined*` functions are called, so there's little hope of wrapping the call site (AndNot) in the warning disable, and we'll indeed have to cover the entire file.
Can you confirm it's OK to remove the line `HWY_DIAGNOSTICS_OFF(disable : 4701, ignored "-Wuninitialized")`, and then move `HWY_DIAGNOSTICS(pop)` to the end of the file?

**Comment by boxerab** [comment]
Moving the pop works, but not removing the `HWY_DIAGNOSTICS_OFF` line.

**Comment by jan-wassenberg** [comment]
OK, thanks, I'll move it under the `#if GCC` then.
