### ISSUE TITLE
Compile failed in current master

### ISSUE THREAD

**Issue by zhongfly** [google/highway#731]
After https://github.com/google/highway/commit/5e5cf8d7f2905932af3a1136eadad3113da4cf4b ,complie failed.
```
CMake Error at CMakeLists.txt:259 (add_library):
  Cannot find source file:

    hwy/per_targets.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:259 (add_library):
  No SOURCES given to target: hwy


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
Maybe comitter forget to add `hwy/per_targets.cc` `hwy/per_targets.h` ?

**Comment by aous72** [comment]
I was just looking at this.

You need to modify ```highway/CMakeLists.txt``` lines 124 and 125 from
```
    hwy/per_targets.cc
    hwy/per_targets.h
```
to 
```
    hwy/per_target.cc
    hwy/per_target.h
``` 
Perhaps, someone need to submit a pull request.  It is also possible that we need to get the release version.
Cheers,
Aous.

**Comment by ericye16** [comment]
I encountered the same issue and was going to put up a PR, but looks like someone has already put up a PR for this: https://github.com/google/highway/pull/732

**Comment by jan-wassenberg** [comment]
Apologies for the breakage, this is now fixed.
Yes, we recommend (in the README Versioning section) using releases instead of the Git HEAD, as @aous72 was suggesting, especially because our CI/CD only covers the Bazel (not CMake) build system.
