### ISSUE TITLE
How to benchmark hwy/conrtib/sort

### ISSUE THREAD

**Issue by QuarticCat** [google/highway#737]
Any instructions?

I can't find such a target in the generated ninja file with default cmake options.

**Comment by jan-wassenberg** [comment]
Hi @QuarticCat , there is a separate Bazel BUILD file in hwy/contrib/sort. I've drafted a readme with instructions; does that work for you? Using Bazel with Clang is closest to what we're doing internally. It would also be an option to add targets to the main CMakeLists.txt if that's helpful?

**Comment by QuarticCat** [comment]
@jan-wassenberg That works pretty well for me. Thanks!
