### ISSUE TITLE
ideal parameters for clang compiler (sort)

### ISSUE THREAD

**Issue by gus-maurizio** [google/highway#745]
It would be nice to have a summary of the best parameters to compile the vqsort for familiar architectures, like Apple M1/M2, Apple Intel, AWS intel instances, AWS graviton2 and 3 instances... (the -march specific parameters to use).

**Comment by gus-maurizio** [comment]
Absolutely!!! Thanks so so much. Great work guys. We are taking a lot of ideas from this.

**Comment by jan-wassenberg** [comment]
Thanks! I'm curious what you are working on, if you are able to share?

**Comment by jan-wassenberg** [comment]
Interesting, thanks for sharing :)
