### ISSUE TITLE
incorrectly nested #if's and dead code

### ISSUE THREAD

**Issue by guoshimin** [google/highway#774]
Looks like the `#if HWY_TARGET <= HWY_AVX3 ... #else ... #endif` block of https://github.com/google/highway/blob/b2f01e40a916f2064a613e716c2198bf53337ca4/hwy/ops/x86_256-inl.h#L4508-L4561 is nested inside another `#if HWY_TARGET <= HWY_AVX3` starting from https://github.com/google/highway/blob/b2f01e40a916f2064a613e716c2198bf53337ca4/hwy/ops/x86_256-inl.h#L4227, which means the `#else` branch of https://github.com/google/highway/blob/b2f01e40a916f2064a613e716c2198bf53337ca4/hwy/ops/x86_256-inl.h#L4534 is never activated.

It was first introduced in https://github.com/google/highway/commit/1384bc87e644d9202bf548dc28195e3ae37de33e#diff-b2cd99ddd84de4327dfcbd82e9f0a761a1e5eb0bdce81b65a25abb3ca0485298R4006

**Comment by jan-wassenberg** [comment]
Thank you for letting us know! I've removed the extra #if and merged the implementations of CompressBlendedStore.
