### ISSUE TITLE
Problem building 0.17.0 on aarch64 with GCC

### ISSUE THREAD

**Issue by eclipseo** [google/highway#776]
Hello again,

While building highway 0.17.0 with gcc 12.1.1 on aarch64, the build gets stuck at 98%. For a whole night. See for example https://koji.fedoraproject.org/koji/taskinfo?taskID=88443347 (check build.log), which is stuck since yesterday evening.

Building 0.16.0 with the same configuration works with no issue.  Building with Clang also works.

I'm sorry I can't provide more information than that, there is no error displayed anywhere, nothing showing up on the logs.

Did your release build with no problem on aarch64 on Qemu?

**Comment by eclipseo** [comment]
I don't really have contact with GCC folks, you might be more adequate to explain why highway should be included in their battery of tests.

**Comment by jan-wassenberg** [comment]
:) FYI filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106041.

**Comment by stefson** [comment]
@malaterre the gcc folks need a preprocessed source file, not an object file. You get those by adding `-save-temps` to your compiler flags.

**Comment by malaterre** [comment]
@stefson the file is 100k lines, I suspect they need something much much smaller (IMHO).

**Comment by stefson** [comment]
Not sure what file size your refere to by 100k lines, but those preprocessed sources are easily a tenfold bigger than the object files. Just xz them and see if its small enough to allow an upload to the gcc bug tracker. 

You can of course also attach it here as a zip archive, but I'm not an compiler expert at all :-)

**Comment by jan-wassenberg** [comment]
FYI the investigation in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106187 seems indeed to point to a compiler issue.

**Comment by jan-wassenberg** [comment]
I believe this will be fixed in the next GCC release. Big thanks to @malaterre for frequent followups and providing information that helped the compiler devs :)

**Comment by stefson** [comment]
hmm, I believe the armhf issue has been fixed, but the original issue was against aarch64 and that one is not yet fixed, at least if you consider the gcc bugtracker, right?

**Comment by ggardet** [comment]
Tried just now on openSUSE Tumbleweed aarch64, with GCC 12.2.1+git416 and the build still hangs.

**Comment by jan-wassenberg** [comment]
I see this has been fixed 2 weeks ago in GCC ([tracker](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108681)). Per the comments there, GCC 12 is affected.
I'm tempted to disable the LoadInterleaved3/4 test on GCC with a todo to re-enable them after the next GCC release. Please let us know if you prefer a different approach.
