### ISSUE TITLE
conversion warnings

### ISSUE THREAD

**Issue by boxerab** [google/highway#78]
Hello!
I have begun integrating highway into my image codec.
As conversions can hide errors, I like to turn on conversion warnings, and I see
the following when linking to highway:

https://my.cdash.org/viewBuildError.php?type=1&buildid=1974624

Is there any chance of casting those warnings away ?

Thanks,
Aaron

**Comment by jan-wassenberg** [comment]
Hi @boxerab , I agree it's nice to fix warnings and just made that change, thanks for reporting them.

**Comment by boxerab** [comment]
Great, thank you! Really looking forward to using the library.

**Comment by jan-wassenberg** [comment]
@boxerab great :) I am curious how it goes for you, feel free to reach out (janwas at Google) if you hit any snags or would like to share your experience.

**Comment by boxerab** [comment]
@jan-wassenberg thanks! I will definitely take you up on your offer.
