### ISSUE TITLE
The inline assembly instructions in the LoadDup128 functions are incorrect in the x86_512-inl.h header

### ISSUE THREAD

**Issue by johnplatts** [google/highway#797]
https://github.com/google/highway/blob/97ca1888a30b61084b112d1aa79457a1dc134666/hwy/ops/x86_512-inl.h#L1892-L1931

Here are the corrected version of the LoadDup128 functions in the x86_512-inl.h header:
``` // Loads 128 bit and duplicates into both 128-bit halves. This avoids the 
 // 3-cycle cost of moving data between 128-bit halves and avoids port 5. 
 template <typename T> 
 HWY_API Vec512<T> LoadDup128(Full512<T> /* tag */, 
                              const T* const HWY_RESTRICT p) { 
   // Clang 3.9 generates VINSERTF128 which is slower, but inline assembly leads 
   // to "invalid output size for constraint" without -mavx512: 
   // https://gcc.godbolt.org/z/-Jt_-F 
 #if HWY_LOADDUP_ASM 
   __m512i out; 
   asm("vbroadcasti32x4 %1, %[reg]" : [reg] "=x"(out) : "m"(p[0])); 
   return Vec512<T>{out}; 
 #else 
   const auto x4 = LoadU(Full128<T>(), p); 
   return Vec512<T>{_mm512_broadcast_i32x4(x4.raw)}; 
 #endif 
 } 
 HWY_API Vec512<float> LoadDup128(Full512<float> /* tag */, 
                                  const float* const HWY_RESTRICT p) { 
 #if HWY_LOADDUP_ASM 
   __m512 out; 
   asm("vbroadcastf32x4 %1, %[reg]" : [reg] "=x"(out) : "m"(p[0])); 
   return Vec512<float>{out}; 
 #else 
   const __m128 x4 = _mm_loadu_ps(p); 
   return Vec512<float>{_mm512_broadcast_f32x4(x4)}; 
 #endif 
 } 
  
 HWY_API Vec512<double> LoadDup128(Full512<double> /* tag */, 
                                   const double* const HWY_RESTRICT p) { 
 #if HWY_LOADDUP_ASM 
   __m512d out; 
   asm("vbroadcastf32x4 %1, %[reg]" : [reg] "=x"(out) : "m"(p[0])); 
   return Vec512<double>{out}; 
 #else 
   const __m128d x2 = _mm_loadu_pd(p); 
   return Vec512<double>{_mm512_broadcast_f64x2(x2)}; 
 #endif 
 }
```

In the x86_512-inl.h header, the vbroadcasti128 needs to be replaced with the vbroadcasti32x4 instruction and the vbroadcastf128 instruction needs to be replaced with the vbroadcastf32x4 instruction.

The vbroadcasti128 instruction available on AVX2 only supports broadcasting 128-bit vectors to a 256-bit vector, and the vbroadcastf128 instruction available on AVX only supports broadcasting 128-bit vectors to a 256 vector.

The vbroadcasti32x4 instruction needs to be used instead of the vbroadcasti128 instruction to broadcast a 128-bit integer vector to a 512-bit integer vector.

The vbroadcastf32x4 instruction needs to be used instead of the vbroadcastf128 instruction to broadcast a 128-bit integer vector to a 512-bit integer vector.

Including the x86_512-inl.h header with HWY_LOADDUP_ASM equal to 1 will give compiler errors due to the use of the incorrect instructions in the inline assembly statements of the x86_512-inl.h.

The above changes should not be made to the x86_256-inl.h header since targets that support AVX2 but not AVX512F do not have support for the vbroadcasti32x4 and vbroadcastf32x4 instructions.

**Comment by jan-wassenberg** [comment]
Hi @johnplatts , thanks for pointing this out. Last I saw, clang has gotten better about actually generating vbroadcastf32x4 since v3.9, so perhaps the best solution is to entirely remove this (anyway disabled) inline assembly?
