### ISSUE TITLE
hwy::ChosenTarget::Update() removed but LIBRARY_SOVERSION unchanged

### ISSUE THREAD

**Issue by malaterre** [google/highway#824]
In commit 5e5cf8d7f2905932af3a1136eadad3113da4cf4b the symbol `_ZN3hwy12ChosenTarget6UpdateEv` was removed. This means that ABI has changed. 

Please update LIBRARY_SOVERSION accordingly, thanks.

Technically SupportedTargetsCalledForTest was also removed from the ABI.

**Comment by jan-wassenberg** [comment]
Right, we plan to do so in the next (1.0) release, which will bump the major version and thus LIBRARY_SOVERSION. Would that work for you?
(FYI we have one other ABI change in the pipeline: re-numbering targets and expanding them to 64-bit)
