### ISSUE TITLE
convert_test.cc:370:11: error: 'VFromD' does not name a type; did you mean 'TFromD'?

### ISSUE THREAD

**Issue by malaterre** [google/highway#831]
For some reason I can no longer compile git/master on armhf. It fails with:

```
[ 67%] Building CXX object CMakeFiles/convert_test.dir/hwy/tests/convert_test.cc.o
In file included from /home/malat/highway/hwy/foreach_target.h:70,
                 from /home/malat/highway/hwy/tests/convert_test.cc:23:
/home/malat/highway/hwy/tests/convert_test.cc: In member function 'void hwy::N_SCALAR::TestTruncateTo::testTo(From, To, D)':
/home/malat/highway/hwy/tests/convert_test.cc:370:11: error: 'VFromD' does not name a type; did you mean 'TFromD'?
  370 |     const VFromD<decltype(dTo)> actual = TruncateTo(dTo, src);
      |           ^~~~~~
      |           TFromD
In file included from /home/malat/highway/hwy/tests/convert_test.cc:26,
                 from /home/malat/highway/hwy/foreach_target.h:70,
                 from /home/malat/highway/hwy/tests/convert_test.cc:23:
/home/malat/highway/hwy/tests/convert_test.cc:371:38: error: 'actual' was not declared in this scope
  371 |     HWY_ASSERT_VEC_EQ(dTo, expected, actual);
      |                                      ^~~~~~
/home/malat/highway/hwy/tests/test_util-inl.h:151:31: note: in definition of macro 'HWY_ASSERT_VEC_EQ'
  151 |   AssertVecEqual(d, expected, actual, __FILE__, __LINE__)
      |                               ^~~~~~
make[2]: *** [CMakeFiles/convert_test.dir/build.make:76: CMakeFiles/convert_test.dir/hwy/tests/convert_test.cc.o] Error 1
```

**Comment by jan-wassenberg** [comment]
Apologies, we are fixing this momentarily.

**Comment by jan-wassenberg** [comment]
:)
I think it's because of HWY_BROKEN_EMU128? That was intentional, no? (because scalar is less broken on that compiler+platform)

**Comment by malaterre** [comment]
I'll change setup to  `-DHWY_BROKEN_EMU128=0 -DHWY_COMPILE_ONLY_EMU128` on armel (softfp). But I output of list_targets seems to be a bit confusing (`HWY_BROKEN_TARGETS `should list `HWY_BROKEN_EMU128 `right ?) :

```
Config: emu128:1 scalar0 static0 all_attain0 is_test0
Compiled HWY_TARGETS:   Scalar
HWY_ATTAINABLE_TARGETS: Neon Scalar
HWY_BASELINE_TARGETS:   Scalar
HWY_STATIC_TARGET:      Scalar
HWY_BROKEN_TARGETS:    
HWY_DISABLED_TARGETS:  
Current CPU supports:   Neon Scalar
```

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armel&ver=0.17.1%7Egit20220707.b0108ff-1&stamp=1657187198&raw=0

**Comment by jan-wassenberg** [comment]
> HWY_BROKEN_TARGETS should list HWY_BROKEN_EMU128

They are actually separate - it's fine to add 'normal' targets to HWY_BROKEN_TARGETS, but EMU128 cannot simply be disabled without first ensuring that we enable SCALAR. If you think it makes sense, we could also printf HWY_BROKEN_EMU128 but it's set under well-defined circumstances (Arm7, GCC < 11.4) so maybe not necessary?

**Comment by malaterre** [comment]
I think what cause my actual confusion (`V7` suffix) are these lines:

```
#if defined(__arm__) || defined(_M_ARM)
#define HWY_ARCH_ARM_V7 1
#else
#define HWY_ARCH_ARM_V7 0
#endif
```

In my mind `armel` is softfp + arm_arch=5.

Typically on my gcc I can see:

```
armel $ % echo | gcc -dM -E - | grep ARM_ARCH
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_5TE__ 1
#define __ARM_ARCH_ISA_THUMB 1
#define __ARM_ARCH 5
```

while:

```
armhf % echo | gcc -dM -E - | grep ARM_ARCH
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_PROFILE 65
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 7
#define __ARM_ARCH_7A__ 1
```

Do you believe `__ARM_ARCH` is portable ?

**Comment by jan-wassenberg** [comment]
Oh! Thank you for clarifying. I was under the misguided belief that armel was v7 without hardfp. We do not support anything before v7 for SIMD. I'm changing our V7 to exclude armel then, so BROKEN_EMU128 will no longer trigger in that case. Hopefully __ARM_ARCH is indeed enough, it's documented and I see GCC also switched to that.

**Comment by malaterre** [comment]
Closing since 9c775721c1531fd1cf11cf52bbfde4d076691628 is in master
