### ISSUE TITLE
base.h:249:19: error: _Float16 is not supported on this target

### ISSUE THREAD

**Issue by malaterre** [google/highway#846]
It seems I can no longer build on s390x:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=s390x&ver=0.17.1%7Egit20220708.70d2be7-1&stamp=1657291435&raw=0

```
[1/103] /usr/bin/g++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o -MF CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o.d -o CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o -c '/<<PKGBUILDDIR>>/hwy/aligned_allocator.cc'
FAILED: CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o 
/usr/bin/g++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -MD -MT CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o -MF CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o.d -o CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.o -c '/<<PKGBUILDDIR>>/hwy/aligned_allocator.cc'
In file included from /<<PKGBUILDDIR>>/hwy/aligned_allocator.cc:26:
/<<PKGBUILDDIR>>/hwy/base.h:249:19: error: ‘_Float16’ does not name a type; did you mean ‘_Float64’?
  249 | using float16_t = _Float16;
      |                   ^~~~~~~~
      |                   _Float64
/<<PKGBUILDDIR>>/hwy/base.h:443:18: error: ‘float16_t’ was not declared in this scope; did you mean ‘bfloat16_t’?
  443 | struct Relations<float16_t> {
      |                  ^~~~~~~~~
      |                  bfloat16_t
/<<PKGBUILDDIR>>/hwy/base.h:443:27: error: template argument 1 is invalid
  443 | struct Relations<float16_t> {
      |                           ^
/<<PKGBUILDDIR>>/hwy/base.h:461:18: error: ‘float16_t’ does not name a type; did you mean ‘bfloat16_t’?
  461 |   using Narrow = float16_t;
      |                  ^~~~~~~~~
      |                  bfloat16_t
/<<PKGBUILDDIR>>/hwy/base.h:539:25: error: ‘float16_t’ was not declared in this scope; did you mean ‘bfloat16_t’?
  539 | constexpr bool IsSigned<float16_t>() {
      |                         ^~~~~~~~~
      |                         bfloat16_t
/<<PKGBUILDDIR>>/hwy/base.h:539:16: error: template-id ‘IsSigned<<expression error> >’ for ‘constexpr bool hwy::IsSigned()’ does not match any template declaration
  539 | constexpr bool IsSigned<float16_t>() {
      |                ^~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/hwy/base.h:535:24: note: candidate is: ‘template<class T> constexpr bool hwy::IsSigned()’
  535 | HWY_API constexpr bool IsSigned() {
      |                        ^~~~~~~~
```

**Comment by 1480c1** [comment]
I can confirm that this affects mingw-w64 gcc and clang for windows

```c
In file included from <hwy_root>/hwy/aligned_allocator.cc:26:
<hwy_root>/hwy/base.h:249:19: error: _Float16 is not supported on this target
using float16_t = _Float16;
                  ^
1 error generated.
```

so this doesn't seem to be restricted to certain compilers or platforms

**Comment by jan-wassenberg** [comment]
During code review we decided to default to the "standardized" _Float16. This was a mistake, as could have been visible from the 7 opt-outs required to make our CI pass. Sorry about the regression. We'll be switching to opt-in, using it only where required by the platform's intrinsics.

BTW I am disappointed by the yawning gap between documentation and practical support of this feature,
[added to clang](https://reviews.llvm.org/D33719) 5 years ago with no obvious mention of "only for certain targets", and GCC going so far as to [say](https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html) "It is recommended that portable code use the _Float16 type defined by ISO/IEC TS 18661-3:2015."
Apparently the only way to reliably detect support is just to [try using it](https://stackoverflow.com/questions/69977196/how-to-correctly-determine-at-compile-time-that-float16-is-supported), which isn't an option for our Bazel build.

**Comment by malaterre** [comment]
> GCC going so far as to [say](https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html) "It is recommended that portable code use the _Float16 type defined by ISO/IEC TS 18661-3:2015."

Do you want to keep this issue open so that we incrementally work toward this "portable" solution? I volunteer to do the testing on Debian supported arches.

**Comment by jan-wassenberg** [comment]
Thank you :) I think it's fine to continue using a struct with u16 member here - we just want something to load from memory and convert to f32, and there's no need to engage with new/poorly supported compiler extensions for this.
We'll only use them (__fp16 and _Float16) where required by the intrinsics.

**Comment by malaterre** [comment]
> GCC going so far as to [say](https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html) "It is recommended that portable code use the _Float16 type defined by ISO/IEC TS 18661-3:2015."

This should be available now apparently:

* https://sourceware.org/git/?p=glibc.git;a=commit;h=3e5760fcb48528d48deeb60cb885a97bb731160c

**Comment by malaterre** [comment]
> I suppose we can add an `#if` for the next GCC release

Yes. I see that GCC 13 requires those new glibc header:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107128#c4
