### ISSUE TITLE
ISPC Evaluation?

### ISSUE THREAD

**Issue by pbrubaker** [google/highway#857]
(disclaimer I work at INTC, and I am an ISPC fan/advocate)

Hey all, I have been experimenting with Highway for a few weeks now.  Did you evaluate ISPC (https://ispc.github.io/) prior to developing Highway?  If so what were the reasons you ended up choosing this path over ISPC?

One obvious potential reason is that ISPC doesn't support RISC-V.  But given that it's an OSS project, and using LLVM back end that should be relatively simple to add.

I'm looking forward to hearing your thoughts so hopefully we can make ISPC better in the future.

**Comment by jan-wassenberg** [comment]
Hi @pbrubaker, thanks for reaching out. Yes, we were aware of ISPC, I found Matt Pharr's blog series very interesting.

In our context, it's helpful to avoid an external build step, integrate nicely with C++ templates, and have access to what Vulkan calls subgroups (things like ballot which integrate awkwardly into the SPMD/SIMT abstraction). On the flip side, it's great that ISPC is automatically vector-length agnostic.

Have you encountered any limitations or surprises in Highway?

**Comment by jan-wassenberg** [comment]
Closing, please feel free to reopen if you'd like to discuss further :)
