### ISSUE TITLE
emscripten compile linked to pthreads

### ISSUE THREAD

**Issue by boxerab** [google/highway#873]
For a program using threads and linking to libwhy, I had to add the following line into the cmake file
in order to get it to compile:

```
if (HWY_EMSCRIPTEN)
    target_compile_options(hwy PUBLIC -matomics)
endif()
```

compile error:

`wasm-ld: error: --shared-memory is disallowed by targets.cc.o because it was not compiled with 'atomics' or 'bulk-memory' features.`

@jan-wassenberg how do you feel about adding this line to the file ?

**Comment by jan-wassenberg** [comment]
Hi @boxerab, searching for the error messages shows some mention of compiling and linking with -pthread being the preferred fix. Does that work for you?

**Comment by boxerab** [comment]
Thanks, `-pthread` only seems to be needed when the binary that is linked to `hwy` is linked, but `hwy` itself just needs to be
compiled with `-matomics`. At least, this is what I am seeing when compiling examples on my project.

**Comment by jan-wassenberg** [comment]
OK, sending a change that uses HWY_FLAGS 👍

**Comment by boxerab** [comment]
Thanks!
