### ISSUE TITLE
Mention fast math library in documentaion

### ISSUE THREAD

**Issue by castigli** [google/highway#88]
Hi @jan-wassenberg, perhaps it would be worth mentioning the fast math library that is in the `contribute/math` folder either in the `README.md` or in the `quick_reference.md`. If I am not mistaken it is not mentioned in either docs and being outside the `hwy` folder it is easy to miss!

**Comment by jan-wassenberg** [comment]
Hi @castigli, thanks for suggesting this, I've added it to the readme. The math library is work by @rhettstucki and we are adding functions periodically/as needed.

I'm curious how your benchmarking is going? BTW if you hit any snags or would like to share your experience, please feel free to reach out to janwas at Google.

**Comment by jan-wassenberg** [comment]
@castigli Glad to hear it has been going well for you, thanks for sharing.

I believe code size was a concern. Perhaps we could provide noinline wrapper functions and allow the user to choose?
Wrappers might also be helpful for corner case handling, which are not always needed - @rhettstucki , what do you think?

> The only other thing that I needed was to implement a ScatterIndex method. My understanding is that you prefer to not implement it directly in hwy since it is not uniformly supported.

Yes, we prefer to avoid defining things which are both expensive(even on SKX) and nonessential, but there is some leeway. Can you help me understand why it is helpful? (I understand it simplifies translating/autovectorizing scalar code, but a lot of SSE2..AVX2 code has been written despite its absence.) Adding it to contrib could be a good compromise.

> I am also interested in benchmarking a SVE implementation. I am willing to start myself the implementation (time permitting!), but I was wondering what it would be the best starting point (i.e. RVV implementation?) and if you or someone else already started some work on it.

Very interesting! I had considered starting already but haven't gotten to it; would be very happy to collaborate - what might be helpful?
Yes, copying RVV is a good starting point (but beware argument order, I think it is reversed).
They are quite similar, it could be as little as a few days of work. Clang 11 should work as the compiler but to test I think you'd need `armie`?

**Comment by rhettstucki** [comment]
@castigli <https://github.com/castigli> I am explicitly choosing to ignore
Nans and Infinities and as far as inlining, you need a non-inlined version
in order to do dynamic dispatch. Doesn't mean we couldn't have both, but
that was the reasoning behind it.

Depending on your use case, you can also just do the following if an
approximation is okay:

inline double exp(double x) {
  x = 1.0 + x / 256.0;
  x *= x;
  x *= x;
  x *= x;
  x *= x;
  x *= x;
  x *= x;
  x *= x;
  x *= x;
  return x;
}

**Comment by rhettstucki** [comment]
Okay the default math functions are now all inlined and if you want
outlined versions you just use Call<whatever> like CallSin, CallExp, and so
on. Hope this helps.

**Comment by castigli** [comment]
> Can you help me understand why it is helpful?

@Jan thanks for the explanation, we have few kernels that uses indirect indexing, something like `output[index[i]] += res[i]`. I am not sure how I could avoid that, but I would be happy to hear suggestions.

> Very interesting! I had considered starting already but haven't gotten to it; would be very happy to collaborate - what might be helpful?
Yes, copying RVV is a good starting point (but beware argument order, I think it is reversed).
They are quite similar, it could be as little as a few days of work. Clang 11 should work as the compiler but to test I think you'd need `armie`?

Great, as soon as I have some time, I will start a fork and work on it. I will let you know if I get stuck!
I set up `armie` on an single board computer at home, that should be enough to get started.
Once things are more or less working I should be able to get access to a A64FX machine.

> @castigli <https://github.com/castigli> I am explicitly choosing to ignore
Nans and Infinities and as far as inlining, you need a non-inlined version
in order to do dynamic dispatch.

@rhet thanks for the clarifications, for now I am mainly interested in static dispatch so that wasn't on my radar.

> Depending on your use case, you can also just do the following if an
approximation is okay:

Thanks for the suggestion, unfortunately I cannot get away with an approximation.


> Okay the default math functions are now all inlined and if you want
outlined versions you just use Call<whatever> like CallSin, CallExp, and so
on. Hope this helps.

Great, thank you, that is very helpful!

**Comment by jan-wassenberg** [comment]
> output[index[i]] += res[i]. I am not sure how I could avoid that, but I would be happy to hear suggestions.

Thanks for sharing the example. For concreteness, let there be (with first element = index 0)
output = [100, 200, 300, 400],
index = [1, 0, 3, 2],
res = [20, 40, 60, 80].

Then output = [140, 220, 380, 460].
Assuming this fits within one register, we can achieve the same effect with output += TableLookupLanes(res, index).
More generally, it is often possible (and beneficial to speed) to replace scatter on the output side with gather on the input side.
Do you think that would work?

> Great, as soon as I have some time, I will start a fork and work on it. I will let you know if I get stuck! I set up armie on an single board computer at home, that should be enough to get started. Once things are more or less working I should be able to get access to a A64FX machine.

Sounds great!

> Great, thank you, that is very helpful!

Thanks, Rhett!
@castigli I am curious whether that closes the performance gap or whether you have any tricks we could incorporate into exp?

**Comment by castigli** [comment]
> Thanks for sharing the example. For concreteness, let there be (with first element = index 0)
output = [100, 200, 300, 400],
index = [1, 0, 3, 2],
res = [20, 40, 60, 80].

> Then output = [140, 220, 380, 460].
Assuming this fits within one register, we can achieve the same effect with output += TableLookupLanes(res, index).
More generally, it is often possible (and beneficial to speed) to replace scatter on the output side with gather on the input side.
Do you think that would work?

Sorry for not being sufficiently clear in my example, the problem in our application is that typically the shift due indirect indexing is much larger than the SIMD width. Typically `output` is a pointer to a large array and the `index` elements are unique but arbitrary (or at least not easily predictable) and can cover the whole array span.  It is possible that with a large refactorization of the code this could be avoided, but I don't think I am in the position of doing that!

> @castigli I am curious whether that closes the performance gap or whether you have any tricks we could incorporate into exp?

I think the rest of the gap (which is not large less than 10% measured from the kernels) boils down to the order of the polynomial and the evaluation method. I was using a  6th order rational poly with a Horner's method for the evaluation. It is a bit faster, but the error is in the order of 4 ULP (I haven't checked myself, but you seem to be able to get 1 ULP). I am curious as well, I will look into this in a bit more detail.

**Comment by jan-wassenberg** [comment]
Ah, got it, thanks for explaining. Yes, with large arrays we'd need to add Scatter. If there is an actual and unavoidable use case, I don't mind putting it in the core library. Do you think it should only be available on targets where it's efficient, i.e. users must check HWY_SCATTER_LANES>1 to prevent compile error? Or should we emulate it using scalar stores?

> It is a bit faster, but the error is in the order of 4 ULP (I haven't checked myself, but you seem to be able to get 1 ULP). I am curious as well, I will look into this in a bit more detail.

Thanks for checking. I would think both 1 and 4 ulp versions could be useful.

**Comment by jan-wassenberg** [comment]
@castigli Scatter is now implemented for all targets in hwy/.

To simplify user code, it's probably helpful to emulate Gather where not supported and remove the requirement to check/use HWY_GATHER_LANES, right?

**Comment by castigli** [comment]
Hi @jan-wassenberg , sorry for the slow reply!

>@castigli Scatter is now implemented for all targets in hwy/.

great news, thank you!

> To simplify user code, it's probably helpful to emulate Gather where not supported and remove the requirement to check/use HWY_GATHER_LANES, right?

I am doubled minded about this, but probably it is better to favor portability and emulate gather/scatter when not available. 
It is after all an expensive operation anyway and something that should be avoided if possible.

**Comment by jan-wassenberg** [comment]
@castigli You're welcome :)
Makes sense, we will emulate gather soon.

**Comment by jan-wassenberg** [comment]
Hi @castigli , any update on your SVE experiment? I'd be happy to discuss/pair-program via video call if you are interested.

**Comment by jan-wassenberg** [comment]
Thanks for reaching out, looking forward to the call. Let's close this (already resolved) issue.
