### ISSUE TITLE
Extend support of Ge/Le comparison for integer type

### ISSUE THREAD

**Issue by hellishfire** [google/highway#885]
Currently highway only supports Ge/Le comparison for float type. I suppose it's not difficult to extend this support for integer type. For hardware where no native instruction is available, simply implement them on top of existing Gt/Lt and invert the result?

**Comment by jan-wassenberg** [comment]
Hi @hellishfire, sounds good, that would indeed be useful. Would you like to send a pull request for this?

**Comment by jan-wassenberg** [comment]
Thank you @johnplatts for implementing these!
