### ISSUE TITLE
hwy/ops/rvv-inl.h:19:10: fatal error: riscv_vector.h: No such file or directory

### ISSUE THREAD

**Issue by malaterre** [google/highway#888]
Looks like `riscv_vector.h` is now included without any sentinel, and it is failing a default gcc built:

```
[1/107] /usr/bin/c++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I/<<PKGBUILDDIR>> -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=1 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -march=rv64gcv1p0 -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c /<<PKGBUILDDIR>>/hwy/per_target.cc
FAILED: CMakeFiles/hwy.dir/hwy/per_target.cc.o 
/usr/bin/c++ -DHWY_SHARED_DEFINE -Dhwy_EXPORTS -I/<<PKGBUILDDIR>> -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=1 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -march=rv64gcv1p0 -MD -MT CMakeFiles/hwy.dir/hwy/per_target.cc.o -MF CMakeFiles/hwy.dir/hwy/per_target.cc.o.d -o CMakeFiles/hwy.dir/hwy/per_target.cc.o -c /<<PKGBUILDDIR>>/hwy/per_target.cc
In file included from /<<PKGBUILDDIR>>/hwy/highway.h:367,
                 from /<<PKGBUILDDIR>>/hwy/per_target.cc:21:
/<<PKGBUILDDIR>>/hwy/ops/rvv-inl.h:19:10: fatal error: riscv_vector.h: No such file or directory
   19 | #include <riscv_vector.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=1.0.0-1&stamp=1659388148&raw=0

**Comment by jan-wassenberg** [comment]
HWY_RVV is only used if the compiler flags request it - that is what -march=rv64gcv1p0 does. The simplest solution would be to remove that flag (or change to just rv64gc) on compilers that do not actually support vectors.

One interesting question is why the compiler accepts/does not complain about the arch/vector extension, but then doesn't provide the riscv_vector.h.

**Comment by malaterre** [comment]
> One interesting question is why the compiler accepts/does not complain about the arch/vector extension, but then doesn't provide the riscv_vector.h.

The above is a default gcc build. clang is not even installed on the buildd machine, see full log at:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=1.0.0-1&stamp=1659388148&raw=0

**Comment by malaterre** [comment]
Testing currently:

* https://salsa.debian.org/debian-phototools-team/highway/-/blob/debian/1.0.0-3/debian/patches/riscv64.patch

**Comment by malaterre** [comment]
> (or change to just rv64gc)

nope, this is still too high for Debian/riscv64 baseline:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=riscv64&ver=1.0.0-3&stamp=1659431269&raw=0

```
    Path: '/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/tests/transform_test'
    Result: Illegal instruction
    Output:
```

will work toward a patch

**Comment by jan-wassenberg** [comment]
Oh, I suppose we should only be setting whatever -march the system actually supports. It's possible that it does not support c (compressed instructions). My suggestion was basically to remove the v1p0, but I'm sure sure what is the minimum baseline (even g might be too much?)

**Comment by malaterre** [comment]
There is a graceful logic for arm5 (aka armel) which would be nice to implement for riscv64 with no V-extension...

Anyway I've fixed my Debian/riscv64 buildd using `-DHWY_COMPILE_ONLY_EMU128`. Closing since really #838 is the actual issue here.
