### ISSUE TITLE
HWY_CMAKE_ARM7:BOOL=ON regression

### ISSUE THREAD

**Issue by malaterre** [google/highway#891]
I am seeing a regression on armhf (arm7) on Debian buildd machine:

Before:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=0.17.1%7Egit20220711.f0a396a-1&stamp=1657558394&raw=0

After:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=1.0.1%7Egit20220802.5810c58-1&stamp=1659436928&raw=0

will try to dig into this at some point

**Comment by malaterre** [comment]
nevermind, it seems that using a different buildd machine makes the compilation go all the way:

* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=armhf&ver=1.0.1%7Egit20220802.5810c58-1&stamp=1659439971&raw=0

it seems to indicate that neon instructions are actually used but runtime dispatch is not working as it should during compilation ...

**Comment by jan-wassenberg** [comment]
hm, looks like a false positive for the static analysis: operator<(void*, void*) doesn't actually have to look at the memory, it just compares the pointers. But it's easy to fix (just move the free after removing from std::set), so I've done that :)

What's the issue with runtime dispatch?

**Comment by malaterre** [comment]
> What's the issue with runtime dispatch?

I fail to understand why I see this `Illegal instruction` in the log:

```
[30/107] : && /usr/bin/g++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DHWY_BROKEN_EMU128=0 -Wno-psabi -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now     -fPIE -pie CMakeFiles/hwy_list_targets.dir/hwy/tests/list_targets.cc.o -o hwy_list_targets  -Wl,-rpath,"/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf"  libhwy.so.1.0.1  -latomic && cd "/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf" && "/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf/hwy_list_targets" || ( exit 0 )
Illegal instruction
```

I am assuming some kind of neon-instructions is being called... but I fail to understand why such instructions would be required just to run `hwy_list_targets`...

**Comment by jan-wassenberg** [comment]
hm, that's indeed strange. hwy_list_targets is mostly just fprintfs. It is generally possible that the compiler could be generating some other special instructions, but I don't see any such flags in your invocation.

Given this happens with one builder but not the other, I wonder whether it's a cross-compile and not correctly being re-routed to QEMU? (e.g. running arm7 instructions on an x86 host)
