### ISSUE TITLE
What are the supported architectures?

### ISSUE THREAD

**Issue by eclipseo** [google/highway#9]
I'mtrying to package this library for Fedora but I'm encountering some issue on aarch64, ppc64le, s390x. Build works on armv7hl and x86 platforms. Could you tell me if this is normal  and what are the supported arches?

You can see the build.log following this link: https://koji.fedoraproject.org/koji/taskinfo?taskID=57335109

**Comment by jan-wassenberg** [comment]
Hi, thanks for reaching out! ppc64le and s390x are currently not supported.
aarch64 should work and does in our test environment (with clang).
I am on leave until Monday and will look into this afterwards. Looks like we have a problem stringizing "GCC target", plus some missing casts. Thanks for letting us know!

**Comment by jan-wassenberg** [comment]
The casts are fixed in c3654c2. Am investigating the pragma.
