### ISSUE TITLE
incorrect result for MinOfLanes

### ISSUE THREAD

**Issue by hellishfire** [google/highway#910]
Tested under AVX2 with highway 1.0.0 release

reproducible code:

void test() {
    std::vector<int16_t> input = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,-1,15 };
    ScalableTag<int16_t> d;
    int16_t expected = *std::min_element(input.begin(), input.end());
    auto vec = LoadU(d, input.data());
    auto ret = MinOfLanes(d, vec);
    int16_t min_val = GetLane(ret);
    assert(expected == min_val);
}

The expected result should be -1, while the returned result is 1

**Comment by jan-wassenberg** [comment]
@hellishfire Sorry about the incorrect behavior and inconvenience, thanks for letting us know.
I can repro with int32 also, on clang - is that what you're compiling with? Investigating..

**Comment by jan-wassenberg** [comment]
The int32 issue is fixed by changing the test, and I've found and fixed the int16 issue: we were not sign-extending correctly. Adding PromoteEven/Odd ops would help for that.

Thanks again for raising the issue!

**Comment by hellishfire** [comment]
I tested MinOfLanes with multiple data types (int16/32/64, float, double), and it only breaks with int16. The same goes for MaxOfLanes.

**Comment by jan-wassenberg** [comment]
Thanks :) Yes, the int32 issue I initially saw in addition to that was due to my adaptation of your test.
