### ISSUE TITLE
Missing data type promotion

### ISSUE THREAD

**Issue by hellishfire** [google/highway#915]
According to the manual of PromoteTo:

V,D: (u8,u16), (u16,u32), (u8,u32), (u32,u64), (u8,i16),
(u8,i32), (u16,i32), (i8,i16), (i8,i32), (i16,i32), (i32,i64) Vec<D> PromoteTo(D, V part): returns part[i] zero- or sign-extended to the integer type MakeWide<T>.

Why are some data type promotion missing? e.g, int8->int64, int16->int64

**Comment by jan-wassenberg** [comment]
The initial design philosophy was to only provide ops which are efficient on all platforms. Since then, we have evolved to a more inclusive "any anything useful which doesn't have major performance cliffs, and applications cannot do any better themselves using other ops".
The short answer is: no one has asked for them yet :) Do you have a use case that requires them?

**Comment by hellishfire** [comment]
I'm writing codes which involve calculating the sum of an input array (of InputType), and return the sum (of OutputType, where InputType is no wider than OutputType) . Something like the following snippet:

template<typename InputType, typename OutputType>
OutputType sum(const InputType* input, int num) {
  static_assert(std::is_integral_v<InputType> && std::is_integral_v<OutputType>);
  static_assert(sizeof(OutputType) >= sizeof(InputType));
  static_assert(std::is_signed_v<InputType> == std::is_signed_v<OutputType>);

  const ScalableTag<OutputType> d_output;
  const Rebind<InputType, decltype(d_output)> d_input;
  const size_t N = Lanes(d_output);
  auto vec_sum = Zero(d_output);
  int i = 0;
  for (; i + N <= num; i += N) {
    auto vec = LoadU(d_input, input);
    vec_sum = Add(vec_sum, PromoteTo(d_output, vec));
    input += N;
  }
  vec_sum = SumOfLanes(d_output, vec_sum);
  OutputType ret = GetLane(vec_sum);
  // ... handle trailing elements
  return ret;
}

Both InputType and OutputType range from int8 to int64. SumOfLanes only works with int32/64, but I can do without it. However, PromoteTo doesn't handle every type promotion combinations and fails to compile.

**Comment by hellishfire** [comment]
Thanks for taking note of this issue. Unfortunately I've been on a tight schedule recently:(
Can't say I'm familiar with simd instructions, but I did skim through the x86 implementation of PromoteTo. Shouldn't be too hard to expand it, I guess, though some workaround is needed for sse3.

**Comment by jan-wassenberg** [comment]
:) Right, it's definitely doable. In the meantime, to unblock your use case you might consider implementing in your code placeholder overloads, to be deleted when we add the native ops? Something like
```
template <class FromV, class ToD>
HWY_API Vec<ToD> PromoteTo(ToD dto,
                                 FromV vfrom) {
  static_assert(sizeof(TFromD<ToD>) > sizeof(TFromV<FromV>), "Not promoting");
  HWY_ALIGN TFromD<ToD> lanes[MaxLanes(dto)];
  HWY_ALIGN TFromV<FromV> from[MaxLanes(dto)];
  Store(vfrom, DFromV<FromV>(), from);
  for (size_t i = 0; i < Lanes(dto); ++i) {
    // For bits Y > X, floatX->floatY and intX->intY are always representable.
    lanes[i] = static_cast<ToT>(from[i]);
  }
  return Load(dto, lanes);
}
```

FYI I will be out of office until the end of the week.

**Comment by hellishfire** [comment]
Ok, thanks for the advice

**Comment by jan-wassenberg** [comment]
Thanks @johnplatts for implementing these, we now have the full set for unsigned -> unsigned/signed and signed -> signed.
