### ISSUE TITLE
Add equivalent of `_mm_madd_epi16`?

### ISSUE THREAD

**Issue by kleisauke** [google/highway#928]
I'm experimenting with highway integration in libvips (see [this work-in-progress branch](https://github.com/kleisauke/libvips/tree/simd-highway)), and noticed that this operation was missing.

I had a quick attempt to add this operation in highway, named `MulAddAdjacent`, see work-in-progress diff:
https://github.com/google/highway/compare/master...kleisauke:highway:MulAddAdjacent (currently missing tests and documentation)

Would the highway project be interested in this? For Neon, it's not 1:1, and I'm not sure if RISC-V or ARM SVE offers an equivalent.

**Comment by jan-wassenberg** [comment]
Hi @kleisauke , thanks for reaching out.
This is indeed very interesting. We've previously had a use case for the similar bf16 x bf16 + f32 operation, it's called ReorderWidenMulAccumulate. The trick is that we allow the op to compute the sums in any order. This should allow both x86 madd16 and NEON vmlal_s16 to be used without any penalty.

The only guarantee is that the sum of the int32 accumulators is then the dot product. This would be sufficient for all uses of madd16 I've seen. Does that work for you as well?

Example:
```
V32 sum1 = Zero(d32);
V32 sum2 = Zero(d32);
V16 in1, in2;
sum1 = ReorderWidenMulAccumulate(in1, in2, sum1, /*byref*/sum2);
dot_product = GetLane(SumOfLanes(Add(sum1, sum2)));
```

**Comment by kleisauke** [comment]
Hi @jan-wassenberg,

Great! I hadn't noticed `ReorderWidenMulAccumulate`, I think an i16 x i16 + i32 variant would work for us, we're just computing the dot product.

**Comment by jan-wassenberg** [comment]
@kleisauke glad to hear, thanks for confirming. I've made a note to add this after the upcoming 1.0.1 release.

**Comment by jan-wassenberg** [comment]
@kleisauke Please let us know if this implementation works for you :)

**Comment by kleisauke** [comment]
@jan-wassenberg I confirm that this works for me, thanks! I just opened PR #981 to implement the missing i16-based versions of the `ReorderWidenMulAccumulate` and `ReorderDemote2To` operations for Wasm.

**Comment by jan-wassenberg** [comment]
Wonderful, thanks for confirming and implementing the wasm version :D
