### ISSUE TITLE
benchmark SIMD with highway

### ISSUE THREAD

**Issue by laoshaw** [google/highway#964]
SIMD benchmark is hard to find if there is any, as each arch needs some hand crafting for the best result.

can we make a highway-based SIMD benchmark that runs on AVX|SVE|RVV to compare their performance apple to apple?

**Comment by jan-wassenberg** [comment]
Hi @laoshaw , thanks for reaching out. This is a very interesting topic. We do have such a benchmark for vectorized quicksort, see hwy/contrib/sort/bench_*. We've tested this on x86, NEON and SVE, with interesting results (https://onlinelibrary.wiley.com/doi/abs/10.1002/spe.3142).

We'd welcome pull requests for benchmarks of other algorithms and I'm happy to help or advise on that if you would like to develop one.

**Comment by jan-wassenberg** [comment]
Closing, feel free to reopen if you'd like to continue the discussion.
