### ISSUE TITLE
Build for ARM Neon/Apple M1

### ISSUE THREAD

**Issue by loretoparisi** [google/highway#987]
Hello in the new docs for Vectorized QuickSort [here](https://github.com/google/highway/blob/master/hwy/contrib/sort/README.md) you mention instructions to build for ARM NEON/Apple M1, but I only find details for Linux x86 and AWS Graviton.

Thank you!

**Comment by jan-wassenberg** [comment]
Hi @loretoparisi , I believe the Linux x86 instructions are also appropriate for NEON. Thanks for raising this, we'll update the readme :)
