### ISSUE TITLE
Having `highway` installed makes `pkg-config` segfault when trying to parse `libhwy-test.pc`

### ISSUE THREAD

**Issue by AliSoftware** [google/highway#999]
While trying to install a Ruby gem (namely, `rmagic`) that required `imagemagick`, which in turn required `highway`… I kept running into a SegFault on `pkg-config` apparently because the `libhwy-test.pc` file has what I'd guess would be some invalid content.

## Environment

 - MacOS 12.6
 - Tested on both M1 and Intel Macs
 - `pkg-config` version 0.29.2
 - `highway` version 1.0.1

## How To Reproduce

 - `brew install pkg-config`
 - `brew install highway`
 - `pkg-config --debug --list-all` — which leads to the following logs, ending with a SegFault

```
… (Long list of logs about parsing other packages; omitted for brievety here) …

Looking for package '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
Considering '/opt/homebrew/lib/pkgconfig/libhwy-test.pc' to be a filename rather than a package name
Reading '/opt/homebrew/lib/pkgconfig/libhwy-test.pc' from file '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
Parsing package file '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
  line>prefix=/opt/homebrew/Cellar/highway/1.0.1
 Variable declaration, 'prefix' has value '/opt/homebrew/Cellar/highway/1.0.1'
  line>libdir=${exec_prefix}/lib
[1]    20848 segmentation fault  pkg-config --debug --list-all
```

 - `brew uninstall highway`
 - `pkg-config --debug --list-all` — which leads to successful end, without any SegFault

**Comment by AliSoftware** [comment]
Side note: From a quick Google search I found similar issues happening with other projects's `.pc` files in the past, like https://github.com/OSGeo/PROJ/issues/2064. Maybe that could lead to some pointers on how to fix `libhwy-test.pc` in a similar way? 🤔  (Just my two cents, as I have no idea about how `.pc` files work)

**Comment by jan-wassenberg** [comment]
Thanks @AliSoftware . I see that this file is missing exec_prefix. Would you please confirm that inserting the following as the second line fixes this? `exec_prefix=${prefix}`

So the first four lines would be:
```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```

**Comment by jan-wassenberg** [comment]
(FYI this fix was made in https://github.com/google/highway/commit/357e21beabb1af037f20130b4195fa5d0e6bbbfb; you can also test it by using Git head instead of 1.0.1)

**Comment by AliSoftware** [comment]
Hello @jan-wassenberg and thanks for the quick reply and fix!

I was out of office last week but could finally test your fix today, and I can confirm it works! 🎉 

```
# Repro with 1.0.1

$ brew install highway
…

$ pkg-config --list-all
[1]    17942 segmentation fault  pkg-config --debug --list-all

# After (head)

$ brew uninstall --ignore-dependencies highway
$ brew install --head highway
…
==> Installing highway --HEAD
==> cmake -S . -B builddir -DBUILD_SHARED_LIBS=ON -DHWY_ENABLE_TESTS=OFF -DHWY_ENABLE_EXAMPLES=OFF -DCMAKE_INSTALL_RPATH=@loader_path/../lib
==> cmake --build builddir
==> cmake --install builddir
🍺  /opt/homebrew/Cellar/highway/HEAD-7398607: 60 files, 2.2MB, built in 7 seconds
…

$ pkg-config --list-all
… lists all packages as expected ==> no segfault anymore!
```

**Comment by jan-wassenberg** [comment]
Excellent, thanks @AliSoftware for confirming, and @lipidity for authoring the fix :)
